Fixes in rc after test runs for forestry and default settings
magpiemodel/magpie pull request #214
Opened 2020-08-21 14:36 UTC by abhimishr

## Purpose of this PR

Purpose of this PR is to apply some fixes for forestry implementation and to also update the module embedding issues in module 38 Factor Costs

## Performance loss/gain from current default behavior

magpie default baseline: 0.58
magpie default policy    : 0.85
magpie forestry baseline: 0.9 (performance loss = 60%)

![Untitled](https://user-images.githubusercontent.com/16802976/93084186-f9375580-f693-11ea-998b-4d7706e3b264.png)

## Type of change

- [x] Bug fix (Change which fixes an issue).
- [x] New feature (Change which adds functionality).
- [x] Minor change (Change which does not modify core model code i.e., in /modules).
- [ ] Major change (fix or feature that would change current model behaviour).

## How Has This Been Tested?

- [x] Runs using starting script which tests current defaults (using `test_runs.R`).
- [x] Runs using starting script which successfully runs the same scenarios as in `test_runs.R` but with the changes from PR.
Note - No CO2 price runs
- [ ] (If applicable) Runs using different scenarios/mappings which are not the default (12 regions/c200 clusters).

## *Additions* or *Changes* to default configuration (default.cfg):
Additions are the introduction of new model components in default config

Changes are deletion or updates to the existing model components in default config

- [ ] Realizations:
- [x] Scenario switches: See `changelog`
- [x] Scalars/Constants: See `changelog`
- [ ] Model interfaces: 
- [ ] Others:

## Checklist:

- [x] Self-review of my own code.
- [x] Added changes to `CHANGELOG.md`
- [x] No hard coded numbers and cluster/country/region names.
- [x] The code doesn't contain declared but unused parameters or variables.
- [x] In-code comments added including documentation comments.
- [x] Compiled and checked resulting documentation with `goxygen::goxygen()` for the new/updated parts.
- [x] Changes to `magpie4` R library for post processing of model output (ideally backward compatible).

## Special comments/warnings

None. This is a fix in rc branch which will be made master and remerged with develop so the changes are made directly to the release candidate.

2020-09-08 17:43 UTC, abhimishr commented on core/sets.gms
> +                    ac150,ac155,acx /
Added new age-classes for making sure than carbonstock reporting is not buggy in case MAgPIE is run till 2150

2020-09-08 17:43 UTC, abhimishr commented on modules/20_processing/off/sets.gms
> +   res_nonfibrous,scp,wood,woodfuel/
Added for clarity - We don't model processing of initial wood products

2020-09-08 17:43 UTC, abhimishr commented on modules/20_processing/substitution_dec18/sets.gms
> +   res_nonfibrous,scp,wood,woodfuel/
Added for clarity - We don't model processing of initial wood products

2020-09-08 17:43 UTC, abhimishr commented on modules/21_trade/selfsuff_reduced/input.gms
> +$setglobal c21_trade_liberalization  l909090r808080
This is the value from default config. Not sure why this was set to `l908080r807070` by default

2020-09-11 11:32 UTC, tscheypidi requested changes

2020-09-11 11:32 UTC, tscheypidi commented on config/default.cfg
> +cfg$gms$s32_fix_plant <- 0                          # def = 0
I don't understand how that switch works. What means 0? No fixing? What would be alternative values to put here? And what would they mean? Does it have a unit? How is that all related to 2020? What happens before 2020? Does it mean that this number only affects the behavior after 2020?

2020-09-11 11:32 UTC, tscheypidi commented on config/default.cfg
> +cfg$gms$s32_plant_share <- 0.25                     # def = 0.25
Again the description is not clear to me. The beginning of the sentence suggests that via the switch I am able to switch betweena constant share and another scenario, but looking at the value my guess is that we are always talking about a constant share scenario and I just define the share here. Is that correct? If so, please describe it that way in the comment. If my interpretation is correct you could for instance write: "Share of overall timber production from plantations which is hold constant over time."

2020-09-11 11:32 UTC, tscheypidi commented on config/default.cfg
> +cfg$gms$c32_interest_rate <- "regional"             # def = regional
Here I guess you have some predefined options what the switch could be set to. Please mention all options here! (Have a look at other switches as an example how to do so)

2020-09-11 11:32 UTC, tscheypidi commented on config/default.cfg
> +cfg$gms$s32_forestry_int_rate   <- 0.05              # def = 0.05
Why is that decoupled from our interest rate module?

2020-09-11 11:32 UTC, tscheypidi commented on config/default.cfg
> +cfg$gms$s32_investment_cost     <- 200              # def = 1000
values should be set to the default value in default.cfg

2020-09-11 11:32 UTC, tscheypidi commented on config/default.cfg
> +
What is the unit here? Please set value to its default value!

2020-09-11 11:32 UTC, tscheypidi commented on modules/73_timber/biomass_mar20/equations.gms
> +                    + sum((cell(i2,j2),ac,kforestry), v73_prod_forestry(j2,ac,kforestry) * s73_timber_harvest_cost * 0)
multiplication by 0? Is that intended? If so, delete the whole line instead of multiplying it with 0!

2020-09-11 11:32 UTC, tscheypidi commented on modules/73_timber/biomass_mar20/equations.gms
> +                  + sum((ct,cell(i2,j2),ac_sub), vm_hvarea_secdforest(j2,ac_sub) * s73_timber_harvest_cost * s73_cost_multiplier * 0.75)
what does the 0.75 mean here? Where does it come from. Better: Use a scalar containing that value and explain in the description of the scalar what it means and what unit it has.

2020-09-11 11:32 UTC, tscheypidi commented on modules/73_timber/biomass_mar20/equations.gms
> +                  + sum((ct,cell(i2,j2),ac_sub), vm_hvarea_other(j2, ac_sub)     * s73_timber_harvest_cost * s73_cost_multiplier * 0.75)
same as comment before

2020-09-14 12:05 UTC, abhimishr commented on CHANGELOG.md
> + - **switch** Allowing for constant or increasing area of timber plantations area after 2020, allowing to fix a static portion of overall timber production coming from plantations, added for allowing
Done

2020-09-14 12:05 UTC, abhimishr commented on CHANGELOG.md
> + - **scalars** Global interest rate for timber plantation's rotation length calculation, additional investment needed to setup timber plantations in unproductive cells.
Done. Affected modules are mentioned trailing the mentioning of scalars/switches

2020-09-15 10:36 UTC, tscheypidi approved these changes

2020-09-15 10:37 UTC, merged