Implemented option to include alcohol consumption in EAT-Lancet diets
magpiemodel/magpie pull request #218
Opened 2020-09-08 15:15 UTC by weindl

## Purpose of this PR

Purpose of this PR is to update the implementation of the EAT-Lancet diet by the option to select a scenario-specific allowance for calories from alcohol consumption via a new scalar in the configuration file (default.cfg).

## Performance loss/gain from current default behavior

Not applicable since the update only affects specific scenarios in the 15_food module

## Type of change

- [x] New feature (Change which adds functionality).
- [x] Minor change (Change which does not modify core model code i.e., in /modules).

## How Has This Been Tested?

- [x] Runs using starting script which tests current defaults.
- [x] Runs using different scenarios in the 15_food module (exogenous diet scenarios with different values for the new scalar).

## *Additions* or *Changes* to default configuration (default.cfg):
Additions are the introduction of new model components in default config

Changes are deletion or updates to the existing model components in default config

- [ ] Realizations:
- [ ] Scenario switches:
- [x] Scalars/Constants: 
Scalar defining the scenario target for the inclusion of alcohol consumption in the EAT-Lancet diet

- [ ] Model interfaces:
- [ ] Others:

## Checklist:

- [x] Self-review of my own code.
- [x] Added changes to `CHANGELOG.md`
- [x] No hard coded numbers and cluster/country/region names.
- [x] The code doesn't contain declared but unused parameters or variables.
- [x] In-code comments added including documentation comments.

## Special comments/warnings

None. This is an update in the rc branch which will be made master and, after the publication of the release, re-merged with the develop-branch.

2020-09-08 17:22 UTC, abhimishr commented on config/default.cfg
> +         "rev4.51_h12_validation.tgz",
@tscheypidi I spoke to Isabelle and looks like indeed we'd have to skip 4 versions. Is that okay or are we allowed to ask the creator of rev 4.48 for removal of their prepossessed data?

2020-09-08 17:24 UTC, abhimishr approved these changes
Good to go after version increment is approved by RSE. 

Changes seem fine to me.

#214 will go on top of this.

2020-09-08 19:35 UTC, tscheypidi commented on config/default.cfg
> +         "rev4.51_h12_validation.tgz",
skipping versions is not an issue

2020-09-08 19:40 UTC, tscheypidi requested changes
Please clarify whether the comments are done as intended and whether the goxygen documentation of the realization looks like it should look. Otherwise, no further requests from my side. Rest looks fine to me (as far as I can judge)

2020-09-08 19:40 UTC, tscheypidi commented on modules/15_food/anthropometrics_jan18/intersolve.gms
> +* Food-specific calorie intake of the model-internal diet projections is
Is it intended, that some comments are goxygen-comments while others are not? For me the comments read like they all would be goxygen comments, but the ' after the * at the beginning of the line is missing quite often.

2020-09-09 12:04 UTC, weindl commented on modules/15_food/anthropometrics_jan18/intersolve.gms
> +* Food-specific calorie intake of the model-internal diet projections is
This was intended. My perspective here was to avoid to produce too much text for the documentation, but still provide additional information within the code to make it easier to understand specific calculations. However, if preferred, I could also transform some of the "code-only" comments into goxygen-readable comments.

2020-09-09 14:53 UTC, weindl commented on modules/15_food/anthropometrics_jan18/intersolve.gms
> +* Food-specific calorie intake of the model-internal diet projections is
I now compiled and checked resulting documentation with `goxygen::goxygen()` for the new/updated parts in the 15_food module. The text is created as intended. However, if more text would be preferred, I could include more comments into the documentation (see reply above).

2020-09-09 15:32 UTC, flohump approved these changes
The changes look fine to me.

2020-09-10 19:38 UTC, tscheypidi commented on modules/15_food/anthropometrics_jan18/intersolve.gms
> +* Food-specific calorie intake of the model-internal diet projections is
this is fine with me. Just wanted to check whether this was intended or not.

2020-09-10 19:38 UTC, tscheypidi approved these changes

2020-09-10 19:38 UTC, merged