Modifications for AgMIP GWP* study
magpiemodel/magpie pull request #233
Opened 2020-11-19 11:57 UTC by flohump

Please fill following information
(Add additional info if you think its important and not covered by this Pull Request (PR)):

## Purpose of this PR

- Modifications for AgMIP GWP* study

## Performance loss/gain from current default behavior

![Unknown-36](https://user-images.githubusercontent.com/16921122/99662760-faa34680-2a65-11eb-87c1-3cd135604e33.png)

- %performance loss/gain = No change because the default config is unchanged.

## Type of change

- [ ] Bug fix (Change which fixes an issue).
- [x] New feature (Change which adds functionality).
- [x] Minor change (Change which does not modify core model code i.e., in /modules).
- [ ] Major change (fix or feature that would change current model behavior).

## How Has This Been Tested?
SSP2_RCPREF_C0000_REFDIET is equivalent to a default MAgPIE SSP2-NPI run.
- [ ] Runs using starting script which tests current defaults (using `test_runs.R`).
- [ ] Runs using starting script which successfully runs the same scenarios as in `test_runs.R` but with the changes from PR.
- [x] (If applicable) Runs using different scenarios/mappings which are not the default (12 regions/c200 clusters).

## *Additions* or *Changes* to default configuration (default.cfg):
Additions are the introduction of new model components in default config

Changes are deletion or updates to the existing model components in default config

- [ ] Realizations:
- [ ] Scenario switches:
- [ ] Scalars/Constants:
- [ ] Model interfaces:
- [ ] Others:

## Checklist:

- [x] Self-review of my own code.
- [x] Compilation check (model starts without compilation errors).
- [x] Added changes to `CHANGELOG.md`
- [x] No hard coded numbers and cluster/country/region names.
- [x] The code doesn't contain declared but unused parameters or variables.
- [x] In-code comments added including documentation comments.
- [ ] Compiled and checked resulting documentation with `goxygen::goxygen()` for the new/updated parts.
- [ ] Changes to `magpie4` R library for post processing of model output (ideally backward compatible).

## Special comments/warnings

- Notes

2020-11-19 12:23 UTC, tscheypidi commented
@flohump is one of the runs in the performance figure a default run? If so, which one? If not, how long does a default run currently take?

2020-11-19 12:36 UTC, flohump commented
SSP2_RCPREF_C0000_REFDIET is equivalent to a default MAgPIE SSP2-NPI run.

2020-11-19 12:49 UTC, tscheypidi requested changes

2020-11-19 12:49 UTC, tscheypidi commented on modules/56_ghg_policy/price_jan20/equations.gms
> +                     -3.75 * pc56_emissions_reg_before(i2,emis_reg_yr56,pollutants_short)) * s56_gwpstar) *
In contrast to what you have said in your PR you actually do have a hard-coded number here. Please fix.

2020-11-19 12:49 UTC, tscheypidi commented on modules/15_food/anthropometrics_jan18/presolve.gms
> +*' if original intake > 430 kcal/cap/day
please run goxygen and check your documentation. I don't think that all parts of the documentation will show up as intended (also true for older parts in presolve.gms, as the @stop command is used frequently stopping code from being shown which is actually referenced in the documentation comments. Please check/fix

2020-11-19 12:49 UTC, tscheypidi commented on modules/56_ghg_policy/price_jan20/equations.gms
> +                     -3.75 * pc56_emissions_reg_before(i2,emis_reg_yr56,pollutants_short)) * s56_gwpstar) *
this formulation suggests that this equation holds true for any kind of shortlived pollutant, but my understanding was that this is a specific equation for CH4. If my assumption is correct, than write CH4 explicitly instead of using pollutants_short.

2020-11-19 12:49 UTC, tscheypidi commented on modules/56_ghg_policy/price_jan20/equations.gms
> +                     im_pollutant_prices(ct,i2,pollutants_short)));
you are repeating lines 45-47 in lines 49,52 and 53. This can lead to errors and misinterpretations. Please try to avoid these repetitions. 
you could solve it via a dynamic set pollutants_xtra and sum the first part over all pollutants which are not in pollutants_xtra and sum the second part about pollutants_extra depending on the setting of s56_gwpstar pollutants_extra is either empty or containing CH4 (I suggest a different naming than pollutants_short in case that the equation does not hold for any shortlived polluter...if it holds for any shortlived, you could stay with the current naming convention)

2020-11-19 12:49 UTC, tscheypidi commented on modules/56_ghg_policy/price_jan20/equations.gms
> +                     im_pollutant_prices(ct,i2,pollutants_short)));
forgot to mention: if you go via a set you could use this set directly as the switch in the config and could get rid of s56_gwpstar

2020-11-19 12:49 UTC, tscheypidi commented on modules/56_ghg_policy/price_jan20/presolve.gms
> +pc56_emissions_reg_before(i,emis_source,pollutants) = sum(t20, p56_emissions_reg(t20,i,emis_source,pollutants));
I would recommend to use p56_emissions_reg_before and to let it run over t (in the equations you can use `sum(ct,p56_emissions_reg_before(ct,i,emis_source,pollutants))`) to have the emissions_before information also available in the gdx

2020-11-19 12:49 UTC, tscheypidi commented on modules/56_ghg_policy/price_jan20/presolve.gms
> +display t20;
please avoid display statements in the code

2020-11-19 13:39 UTC, flohump commented on modules/56_ghg_policy/price_jan20/equations.gms
> +                     im_pollutant_prices(ct,i2,pollutants_short)));
Thanks for this suggestion. I will give it a try. If it works, its much cleaner. 
But how can I use a set in the config as switch? Do we have an example for that?

2020-11-19 13:39 UTC, flohump commented on modules/56_ghg_policy/price_jan20/equations.gms
> +                     -3.75 * pc56_emissions_reg_before(i2,emis_reg_yr56,pollutants_short)) * s56_gwpstar) *
short-lived is correct, but will equal to CH4 in our case.
https://iopscience.iop.org/article/10.1088/1748-9326/ab6d7e
https://www.nature.com/articles/s41612-019-0086-4

2020-11-19 13:40 UTC, flohump commented on modules/56_ghg_policy/price_jan20/equations.gms
> +                     -3.75 * pc56_emissions_reg_before(i2,emis_reg_yr56,pollutants_short)) * s56_gwpstar) *
Fair enough. But this equation is directly taken from https://iopscience.iop.org/article/10.1088/1748-9326/ab6d7e#erlab6d7es2 Equation 3. 
These numbers are hard-coded because they should not be changed. 
And I don't think that two additional scalars (s15_gwp*) would improve the readability of the code.

2020-11-19 14:28 UTC, tscheypidi commented on modules/56_ghg_policy/price_jan20/equations.gms
> +                     im_pollutant_prices(ct,i2,pollutants_short)));
`cfg$gms$select_countries12` is an example

2020-11-19 14:29 UTC, tscheypidi commented on modules/56_ghg_policy/price_jan20/equations.gms
> +                     -3.75 * pc56_emissions_reg_before(i2,emis_reg_yr56,pollutants_short)) * s56_gwpstar) *
so that means that equation holds true for any kind of short-lived pollutant? always with the exact same factors? I would have guessed that the time horizon and so on vary dependening on the gas you are looking at

2020-11-19 14:32 UTC, tscheypidi commented on modules/56_ghg_policy/price_jan20/equations.gms
> +                     -3.75 * pc56_emissions_reg_before(i2,emis_reg_yr56,pollutants_short)) * s56_gwpstar) *
sorry, but I am still skeptic here. Are you saying that the number does not change no matter what gas one is looking at? Something like a fundamental constant?

2020-11-22 17:00 UTC, flohump commented on modules/15_food/anthropometrics_jan18/presolve.gms
> +*' if original intake > 430 kcal/cap/day
Fixed. In agreement with @weindl I converted the doc text to code comments.

2020-11-22 17:02 UTC, flohump commented on modules/56_ghg_policy/price_jan20/equations.gms
> +                     im_pollutant_prices(ct,i2,pollutants_short)));
Done. It was a bit tricky because my case is different from `cfg$gms$select_countries12`. But once implemented, it is a really nice solution.

2020-11-22 17:02 UTC, flohump commented on modules/56_ghg_policy/price_jan20/presolve.gms
> +display t20;
Done.

2020-11-22 17:02 UTC, flohump commented on modules/56_ghg_policy/price_jan20/presolve.gms
> +pc56_emissions_reg_before(i,emis_source,pollutants) = sum(t20, p56_emissions_reg(t20,i,emis_source,pollutants));
Done.

2020-11-22 17:06 UTC, flohump commented on modules/56_ghg_policy/price_jan20/equations.gms
> +                     -3.75 * pc56_emissions_reg_before(i2,emis_reg_yr56,pollutants_short)) * s56_gwpstar) *
That's what Lynch et al say, although they highlight that they focus on CH4. 
I added more explantation to the default.cfg
# * Selection of pollutants that should be taxed based on the GWPstar-metric instead of GWP100
# * The GWPstar-metric should only be applied to short-lived pollutants.
# * Meaningful options: "ch4"
cfg$gms$poll_gwpstar <- "" 		# def = ""

2020-11-22 17:13 UTC, flohump commented
I made substantial changes in preloop.gms and equations.gms, including documentation. 
Please review thoroughly. I also request feedback from @bodirsky .
I might make sense to read the documentation before. 

https://github.com/magpiemodel/magpie/pull/233/files#diff-889aab35b22532c1f56f78d3cee5024cf15bb4ad2f3dc54de7012f3f268e2077

https://github.com/magpiemodel/magpie/pull/233/files#diff-00a21482f0d0699543d51dad5f39ec22594d28b831d3928308baea2fa0a57a45L39

2020-11-23 10:42 UTC, bodirsky submitted a review, later dismissed
- Do I understand the factor 4 as something that actually increases the emission price (e.g. on the stock market ) by factor 4? Interesting... But then on the other hand, dont you need to "discount" future effects? In the way that in the future, these emissions are substracted again with 3.75.... it seems strange to me that the model would suddenly adopt 4 times more expesnive mitigation measures, independent of the longelivity of the GHG
- rather than commenting a warning for "emis_cell_yr56 is an empty set. The equation below needs to be adjusted to gwpstar if emis_cell_yr56 is no longer empty." please directly include the new equation here
- make sure that magpie4-library can handle the new outputs and if checked, than also check the box in the PR
- * if original intake > 430 kcal/cap/day --> comment should not be dependent on hard-coded number, but rather on the scalar s15_kcal_pc_livestock_intake_target 
- check with Jan, but I guess it would be better to have a conditional constraint rather than this formulation:  sum(poll_gwp100,
                     vm_emissions_reg(i2,emis_reg_yr56,poll_gwp100) *
                     sum(ct, p56_emis_policy(ct,i2,poll_gwp100,emis_reg_yr56) *
                     im_pollutant_prices(ct,i2,poll_gwp100)))
               + sum(poll_gwpstar,
                     (1 * vm_emissions_reg(i2,emis_reg_yr56,poll_gwpstar) 
                     - 3.75/4 * sum(ct, p56_emissions_reg_before(ct,i2,emis_reg_yr56,poll_gwpstar))) *
                     sum(ct, p56_emis_policy(ct,i2,poll_gwpstar,emis_reg_yr56) *
                     im_pollutant_prices(ct,i2,poll_gwpstar)));
Alternatively, you could also write this as one equation, with the GWP*-specific paramters becoming 1 in case that GWP* is not activated.

a general comment (but not sure you can solve this here) is that the ex-post diet scenarios in the food demand module become quite lengthy and complex. Maybe at one point we need to think about a generalizable simple approach.

2020-11-23 11:57 UTC, flohump commented
> * Do I understand the factor 4 as something that actually increases the emission price (e.g. on the stock market ) by factor 4? Interesting... 
Given the formuation of emission cost in the GWPstar case `(4 * emis(t) - 3.75 * emis(t-20)) * CO2_price * GWP100`, the marginal costs are `4 * CO2_price * GWP100`. And these marginal costs should be seen be the MACCs module, no? The interface between the modules `56_ghg_policy` and `57_maccs` is `im_pollutant_prices`. Therefore, I adjust the `im_pollutant_prices` based on the set `poll_gwpstar`. If `poll_gwpstar` is empty, which is the default `im_pollutant_prices` remains unchannged.

> * But then on the other hand, dont you need to "discount" future effects? In the way that in the future, these emissions are substracted again with 3.75.... 
Well, this would be much more complex implementation. I think that the current implemention is in line with the myopic nature of MAgPIE.

> * it seems strange to me that the model would suddenly adopt 4 times more expesnive mitigation measures, independent of the longelivity of the GHG
Maybe this is a misunderstanding, the GWPstar metric should only be applied to short-lived climate pollutants. In MAgPIE, only "ch4" falls into this category. 
Under constant CH4 emissions, the emissions costs of GWPstar are 25% of the GWP100 emissions costs, i.e. it is cheaper to emit CH4. But at the same time, the marginal costs are 4 times higher. 

> * rather than commenting a warning for "emis_cell_yr56 is an empty set. The equation below needs to be adjusted to gwpstar if emis_cell_yr56 is no longer empty." please directly include the new equation here
Ok, this will done. 

> * make sure that magpie4-library can handle the new outputs and if checked, than also check the box in the PR
Done.

> * * if original intake > 430 kcal/cap/day --> comment should not be dependent on hard-coded number, but rather on the scalar s15_kcal_pc_livestock_intake_target
Will do.

> * check with Jan, but I guess it would be better to have a conditional constraint rather than this formulation:  sum(poll_gwp100,
>   vm_emissions_reg(i2,emis_reg_yr56,poll_gwp100) *
>   sum(ct, p56_emis_policy(ct,i2,poll_gwp100,emis_reg_yr56) *
>   im_pollutant_prices(ct,i2,poll_gwp100)))
>   + sum(poll_gwpstar,
>   (1 * vm_emissions_reg(i2,emis_reg_yr56,poll_gwpstar)
>   - 3.75/4 * sum(ct, p56_emissions_reg_before(ct,i2,emis_reg_yr56,poll_gwpstar))) *
>   sum(ct, p56_emis_policy(ct,i2,poll_gwpstar,emis_reg_yr56) *
>   im_pollutant_prices(ct,i2,poll_gwpstar)));
>   Alternatively, you could also write this as one equation, with the GWP*-specific paramters becoming 1 in case that GWP* is not activated.
You mean two constraints, depending on the dynamics sets `poll_gwp100` and `poll_gwpstar `?
Re-writting as one equation, would counter the idea of dynamics sets. 

> 
> a general comment (but not sure you can solve this here) is that the ex-post diet scenarios in the food demand module become quite lengthy and complex. Maybe at one point we need to think about a generalizable simple approach.

2020-11-30 09:39 UTC, flohump commented on modules/56_ghg_policy/price_jan20/equations.gms
> +                     -3.75 * pc56_emissions_reg_before(i2,emis_reg_yr56,pollutants_short)) * s56_gwpstar) *
reverted back to develop

2020-11-30 09:39 UTC, flohump commented on modules/56_ghg_policy/price_jan20/equations.gms
> +                     -3.75 * pc56_emissions_reg_before(i2,emis_reg_yr56,pollutants_short)) * s56_gwpstar) *
reverted back to develop

2020-11-30 09:40 UTC, flohump commented
I reverted back all changes in the 56_ghg_policy module. The GWP*-based pricing comes in via the external input file for polluntant prices.

2020-12-07 14:58 UTC, tscheypidi approved these changes

2020-12-07 19:46 UTC, merged