Bugfixes in 32_forestry
magpiemodel/magpie pull request #238
Opened 2020-12-21 07:39 UTC by flohump

Please fill following information
(Add additional info if you think its important and not covered by this Pull Request (PR)):

## Purpose of this PR

- ac0 was used instead of ac_est in some case
- minimum carbon treshold for afforesation was overwritten (code moved to end of presolve.gms)
- Removed plantations from vm_cdr_aff because p32_cdr_ac can be changed to plantations with s32_aff_plantation.

## Performance loss/gain from current default behavior

- no test runs. No expected impact on performance. Just bugfixes

## Type of change

- [x] Bug fix (Change which fixes an issue).
- [ ] New feature (Change which adds functionality).
- [x] Minor change (Change which does not modify core model code i.e., in /modules).
- [ ] Major change (fix or feature that would change current model behavior).

## How Has This Been Tested?

- GAMS Compilation works fine "gams main.gms action=C"

## *Additions* or *Changes* to default configuration (default.cfg):
Additions are the introduction of new model components in default config

Changes are deletion or updates to the existing model components in default config

- [ ] Realizations:
- [ ] Scenario switches:
- [ ] Scalars/Constants:
- [ ] Model interfaces:
- [ ] Others:

## Checklist:

- [x] Self-review of my own code.
- [x] Compilation check (model starts without compilation errors).
- [x] Added changes to `CHANGELOG.md`
- [x] No hard coded numbers and cluster/country/region names.
- [x] The code doesn't contain declared but unused parameters or variables.
- [x] In-code comments added including documentation comments.
- [x] Compiled and checked resulting documentation with `goxygen::goxygen()` for the new/updated parts.
- [x] Changes to `magpie4` R library for post processing of model output (ideally backward compatible).

## Special comments/warnings

- Notes

2020-12-21 08:47 UTC, tscheypidi reviewed
Fix itself looks from the basics good to me (did not check the equations in detail as I expect that someone else will do that).

However, I noticed two unrelated issues in the modified parts of the code which need some fixing. Perhaps @abhimishr can have a look at that?

1. The goxygen documentation bits are not sufficient. Please have a look at the resulting documentation (e.g. here: https://rse.pik-potsdam.de/doc/magpie/4.3/32_forestry.htm) This part of the documentation of the dynamic afforestation realization is hardly readable as sentences are incomplete (no real sentences) and not explaining the overall ideas of the code. Comments should be changed so that text reads like a real documentation.
2. the "DON'T USE TYPE32 SET HERE" is unclear to me. Please explain better (if still required) what it means so that I am also able to understand its reasoning and meaning.

2020-12-21 09:06 UTC, flohump commented
Thanks for your feedback.
> 1. The goxygen documentation bits are not sufficient. Please have a look at the resulting documentation (e.g. here: https://rse.pik-potsdam.de/doc/magpie/4.3/32_forestry.htm) This part of the documentation of the dynamic afforestation realization is hardly readable as sentences are incomplete (no real sentences) and not explaining the overall ideas of the code. Comments should be changed so that text reads like a real documentation.
Can you be more specific here? Which parts of the forestry dynamic documentation are diffcult to read?

2020-12-21 09:45 UTC, tscheypidi commented
I was referring to the documentation snippets in presolve.gms. If you look there at the goxygen comments you will see that hardly any of these is a complete sentence and they do not add overall context to the code, but rather repeat the code in other words.

2020-12-21 10:59 UTC, flohump commented
The doc snippets in presolve.gms are very technical. I suggest to convert these snippets to code comments. @abhimishr What do you think?

2020-12-21 17:42 UTC, abhimishr commented
> The doc snippets in presolve.gms are very technical. I suggest to convert these snippets to code comments. @abhimishr What do you think?

Looks fine to me. I agree that we can convert them to code comments instead.

2020-12-21 17:42 UTC, abhimishr approved these changes

2020-12-21 17:47 UTC, abhimishr requested changes
While we are at this, can you make an additional commit? `f32_bph_effect.cs3` is requested but not used in the model. We should remove it if the file is not needed. Looks like we use `f32_bph_effect_noTCRE.cs3` and `f32_localTCRE.cs3` now and `f32_bph_effect.cs3` is not being read in by any input file parameter.

2020-12-29 15:03 UTC, abhimishr commented on modules/32_forestry/dynamic_may20/presolve.gms
> -= (p32_carbon_density_ac(t,j,"plant",ac,"vegc") - p32_carbon_density_ac(t,j,"plant",ac-1,"vegc")) * s32_plant_carbon_foresight;
If s32_plant_carbon_foresight is removed here then it should also be removed form default.cfg and input.gms in forestry module. Its still used in the forestry runs and defaults to 1, why is this removed here?

2020-12-30 07:52 UTC, mikewin-climsci commented
> 
> 
> While we are at this, can you make an additional commit? `f32_bph_effect.cs3` is requested but not used in the model. We should remove it if the file is not needed. Looks like we use `f32_bph_effect_noTCRE.cs3` and `f32_localTCRE.cs3` now and `f32_bph_effect.cs3` is not being read in by any input file parameter.

Indeed, thanks for catching this. "f32_bph_effect.cs3" is deprecated and replaced by the other two datasets.

2021-01-05 15:44 UTC, flohump commented on modules/32_forestry/dynamic_may20/presolve.gms
> -= (p32_carbon_density_ac(t,j,"plant",ac,"vegc") - p32_carbon_density_ac(t,j,"plant",ac-1,"vegc")) * s32_plant_carbon_foresight;
s32_plant_carbon_foresight does not exist in default.cfg

2021-01-05 15:45 UTC, flohump commented on modules/32_forestry/dynamic_may20/presolve.gms
> -= (p32_carbon_density_ac(t,j,"plant",ac,"vegc") - p32_carbon_density_ac(t,j,"plant",ac-1,"vegc")) * s32_plant_carbon_foresight;
But I removed it from a start script.

2021-01-05 15:54 UTC, flohump commented
@tscheypidi Travis check failed: 
The command "Rscript -e "if(!requireNamespace('gms')) devtools::install_github('pik-piam/gms')"" failed and exited with 1 during .
Can you do something about this?
Or what can I do?

2021-01-05 16:43 UTC, abhimishr approved these changes
Seems good to go except for the travis checks!

2021-01-05 17:07 UTC, tscheypidi commented
not sure what happened there, but something seems to have changed on Travis side. REMIND ran into a similar issue a few days ago.

@flohump can you please replace the .travis.yml in your branch with the one remind is currently using? https://github.com/remindmodel/remind/blob/develop/.travis.yml

2021-01-06 08:45 UTC, merged