Develop
magpiemodel/magpie pull request #244
Opened 2021-01-22 14:29 UTC by bodirsky

Please fill following information
(Add additional info if you think its important and not covered by this Pull Request (PR)):

## Purpose of this PR

- Better representation of nitrogen-related emissions via a new emission module realiztaion

## Performance loss/gain from current default behavior

- Runtime slightly improved

![image](https://user-images.githubusercontent.com/14294086/105502989-54bec300-5cc6-11eb-8ccd-0d33efacaf52.png)
runs on the right are old version, on the left its the new PR.

- %performance loss/gain = 100*Runtime from PR/Runtime from current default from develop branch.

## Type of change

- [ ] Bug fix (Change which fixes an issue).
- [ X ] New feature (Change which adds functionality).
- [ X ] Minor change (Change which does not modify core model code i.e., in /modules).
- [ ] Major change (fix or feature that would change current model behavior).

## How Has This Been Tested?

- [ X ] Runs using starting script which tests current defaults (using `test_runs.R`).
- [ X ] Runs using starting script which successfully runs the same scenarios as in `test_runs.R` but with the changes from PR.
- [ X ] (If applicable) Runs using different scenarios/mappings which are not the default (12 regions/c200 clusters).

## *Additions* or *Changes* to default configuration (default.cfg):
Additions are the introduction of new model components in default config

Changes are deletion or updates to the existing model components in default config

- [ X ] Realizations: nitrogen module, "rescaled_jan21"
- [ ] Scenario switches:
- [ ] Scalars/Constants:
- [ X ] Model interfaces: v50_nr_nue_eff and v50_nr_nue_eff_pasture are now interfaces
- [ ] Others:

## Checklist:

- [ X ] Self-review of my own code.
- [ X ] Compilation check (model starts without compilation errors).
- [ X ] Added changes to `CHANGELOG.md`
- [ X ] No hard coded numbers and cluster/country/region names.
- [ X ] The code doesn't contain declared but unused parameters or variables.
- [ X ] In-code comments added including documentation comments.
- [ X ] Compiled and checked resulting documentation with `goxygen::goxygen()` for the new/updated parts.
- [ X ] Changes to `magpie4` R library for post processing of model output (ideally backward compatible).

## Special comments/warnings

- Notes

2021-01-22 18:24 UTC, tscheypidi requested changes

2021-01-22 18:24 UTC, tscheypidi commented on config/default.cfg
> +# *          neff70_75_starty2010,neff75_80_starty2010,neff80_85_starty2010
these names are rather cryptic. Some explanation of what these different settings are or how the names can be interpreted (there seems to be a pattern in it, right?) might be helpful

2021-01-22 18:24 UTC, tscheypidi commented on modules/15_food/anthropometrics_jan18/equations.gms
> +         *(i15_prices_initial_kcal(iso,kfo)-sum((ct,current_iter15), p15_prices_kcal(ct,iso,kfo,current_iter15))))
would it be possible to use set name "citer15" instead of current_iter15 to be consistent to the t -> ct logic?

2021-01-22 18:24 UTC, tscheypidi commented on modules/15_food/anthropometrics_jan18/intersolve.gms
> +last_iter15(iter15)$(ord(iter15)=p15_iteration_counter(t)-1) = yes;
from the name I was assuming that you would refer to the very last iteration (the one when the iterating finishes). Perhaps use "previous / piter15" instead?

2021-01-22 18:24 UTC, tscheypidi commented on modules/15_food/anthropometrics_jan18/sets.gms
> +
as mentioned earlier: call it "previous" instead of "last"

2021-01-22 18:24 UTC, tscheypidi commented on modules/50_nr_soil_budget/exoeff_aug16/equations.gms
> +*' For cropland the equation `q50_nr_bal_crp` balances the withdrawls of nitrogen with the share of all
typo: "withdrawls"

2021-01-22 18:24 UTC, tscheypidi commented on modules/50_nr_soil_budget/off/not_used.txt
> +vm_nr_eff_pasture,input,not needed
this is not true! The module is providing that information to other modules. Hence every realization (including the off realization) must provide it!

2021-01-22 18:24 UTC, tscheypidi commented on modules/51_nitrogen/rescaled_jan21/not_used.txt
> +name,type,reason
please delete all files which come without content

2021-01-25 07:16 UTC, bodirsky commented on modules/15_food/anthropometrics_jan18/equations.gms
> +         *(i15_prices_initial_kcal(iso,kfo)-sum((ct,current_iter15), p15_prices_kcal(ct,iso,kfo,current_iter15))))
I find "citer" a bit cryptic. With citer i dont think of current iteration, but of a person that cites papers.

2021-01-25 07:17 UTC, bodirsky commented on modules/15_food/anthropometrics_jan18/intersolve.gms
> +last_iter15(iter15)$(ord(iter15)=p15_iteration_counter(t)-1) = yes;
good point. I name it prev_iter15

2021-01-25 07:19 UTC, bodirsky commented on modules/15_food/anthropometrics_jan18/equations.gms
> +         *(i15_prices_initial_kcal(iso,kfo)-sum((ct,current_iter15), p15_prices_kcal(ct,iso,kfo,current_iter15))))
shortened to curr_iter15

2021-01-25 07:20 UTC, bodirsky commented on modules/50_nr_soil_budget/exoeff_aug16/equations.gms
> +*' For cropland the equation `q50_nr_bal_crp` balances the withdrawls of nitrogen with the share of all
changed

2021-01-25 07:21 UTC, bodirsky commented on modules/50_nr_soil_budget/off/not_used.txt
> +vm_nr_eff_pasture,input,not needed
good point.

2021-01-25 07:26 UTC, bodirsky commented on modules/51_nitrogen/rescaled_jan21/not_used.txt
> +name,type,reason
done

2021-01-25 07:26 UTC, bodirsky commented on modules/51_nitrogen/rescaled_jan21/not_used.txt
> +name,type,reason
thanks for the review!

2021-01-25 07:28 UTC, bodirsky commented on config/default.cfg
> +# *          neff70_75_starty2010,neff75_80_starty2010,neff80_85_starty2010
not changed by this PR, but I now included a description of the scenario names.

2021-01-25 11:14 UTC, tscheypidi requested changes

2021-01-25 11:14 UTC, tscheypidi commented on modules/51_nitrogen/rescaled_jan21/not_used.txt
> +name,type,reason
it seems that you forgot to delete this not_used.txt file

2021-01-25 11:14 UTC, tscheypidi commented on config/default.cfg
> +# *          neff70_75_starty2010,neff75_80_starty2010,neff80_85_starty2010
sorry, I do not understand. Where do I find the description now?

2021-01-26 09:09 UTC, tscheypidi approved these changes

2021-01-26 09:35 UTC, merged