Single Cell Protein as Food and Feed replacement (exogenous assumptions)
magpiemodel/magpie pull request #246
Opened 2021-01-29 17:19 UTC by flohump

Please fill following information
(Add additional info if you think its important and not covered by this Pull Request (PR)):

## Purpose of this PR

- Changes needed for running scenarios with exogenous assumptions for the replacement of food (ruminant meat and dairy) and feed (crops and forage) by Single Cell Protein.

## Performance loss/gain from current default behavior

![Unknown-42](https://user-images.githubusercontent.com/16921122/106306276-1a24cf80-625e-11eb-9ea6-341b3d2c3155.png)

## Type of change

- [ ] Bug fix (Change which fixes an issue).
- [ ] New feature (Change which adds functionality).
- [ ] Minor change (Change which does not modify core model code i.e., in /modules).
- [ ] Major change (fix or feature that would change current model behavior).

## How Has This Been Tested?

- [ ] Start script paper_scp.R. SSP2_Ref_SCPoff is a run with default settings.

## *Additions* or *Changes* to default configuration (default.cfg):
Additions are the introduction of new model components in default config

Changes are deletion or updates to the existing model components in default config

- [ ] Realizations:
- [ ] Scenario switches:
- [ ] Scalars/Constants:
- [ ] Model interfaces:
- [ ] Others:

## Checklist:

- [ ] Self-review of my own code.
- [ ] Compilation check (model starts without compilation errors).
- [ ] Added changes to `CHANGELOG.md`
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The code doesn't contain declared but unused parameters or variables.
- [ ] In-code comments added including documentation comments.
- [ ] Compiled and checked resulting documentation with `goxygen::goxygen()` for the new/updated parts.
- [ ] Changes to `magpie4` R library for post processing of model output (ideally backward compatible).

## Special comments/warnings

- Notes

2021-01-29 20:32 UTC, tscheypidi commented
@flohump In the figure I am not able to tell which run is what. in appResults you can choose what color code should be used for the different dots. Choosing the title would probably help to see what it is.
You don't need to redo the figure, but can you please tell me which dot is what?

2021-01-29 21:44 UTC, flohump commented
> @flohump In the figure I am not able to tell which run is what. in appResults you can choose what color code should be used for the different dots. Choosing the title would probably help to see what it is.
> You don't need to redo the figure, but can you please tell me which dot is what?

I updated the figure.

2021-01-29 21:52 UTC, tscheypidi commented
thx

2021-01-29 21:53 UTC, tscheypidi approved these changes

2021-02-01 09:26 UTC, bodirsky requested changes
did not review the startscript

2021-02-01 09:26 UTC, bodirsky commented on modules/70_livestock/fbask_jan16/preloop.gms
> +im_feed_baskets(t_all,i,kap,kcer70) = im_feed_baskets(t_all,i,kap,kcer70)*fm_attributes("nr",kcer70);
same here, can be simplfied into 2 lines of code

2021-02-01 09:26 UTC, bodirsky commented on modules/70_livestock/fbask_jan16/preloop.gms
> +*convert from DM to Nr
also here

2021-02-01 10:38 UTC, flohump commented on modules/20_processing/substitution_dec18/equations.gms
> +         ;
SCP is also based on inputs. There are 4 cases:
scp_methane,861
scp_sugar,789
scp_cellulose,841
scp_hydrogen,1444
scp_methane, scp_sugar and scp_cellulose are part of f20_processing_unitcosts.
But scp_hydrogen does not exist in "kpr". Therefore, I added this extra calculation. On the other hand, the model dynamics will not be affected by the costs of scp_hydrogen because the scp mix and substition is exogenous. I think it makes sense to remove the extra calculation for scp. It just means that scp_hydrogen, which is landless has no costs in MAgPIE.

2021-02-01 10:39 UTC, flohump commented on modules/20_processing/substitution_dec18/declarations.gms
> +     q20_processing(i,kpr,ksd)                        	Processing equation (mio. tDM per yr)
Just formatting

2021-02-01 10:40 UTC, flohump commented on modules/15_food/anthropometrics_jan18/presolve.gms
> +p15_kcal_pc_calibrated(t,i,kfo_rd) = p15_kcal_pc_calibrated(t,i,kfo_rd) * i15_kcal_pc_to_protein_pc(t,kfo_rd);
Thanks! This is much cleaner. I will change the code accordingly.

2021-02-01 12:10 UTC, flohump commented on modules/31_past/endo_jun13/input.gms
> +  s31_unequal  switch for unequal (1) and equal (0) pasture production (binary)   / 1 /
I removed this switch. I only used this for testing. Probably it would be cleaner to add a new realization with =e= in q31_prod.

2021-02-01 12:10 UTC, flohump commented on modules/31_past/endo_jun13/equations.gms
> -q31_prod(j2) ..
Removed see above.

2021-02-01 12:23 UTC, flohump commented on config/default.cfg
> +cfg$gms$c70_cereal_scen <- "constant"                         # def = constant
Done

2021-02-01 17:19 UTC, bodirsky approved these changes

2021-02-01 17:19 UTC, merged