Reshuffling of forestry, natveg and timber module code : Better routine for timber production inclusing performance updates
magpiemodel/magpie pull request #249
Opened 2021-02-17 14:03 UTC by abhimishr

## :bird: Purpose of this PR :bird:

This PR add major re-writing of current roundwood production routine. Production equations have now moved to respective forestry and natveg modules and then sent back to timber module. The module contracts have also now changed. Forestry and natveg module now handle land movements along with harvesting decisions, age-class shifting decisions and new plantation establishment decisions. Forestry module now handles mainly the demand calculations and residue accounting from industrial roundwood production. This PR also improves the current default branch's runtime so we also introduce performance improvements.

## :wrench: Type of change :wrench:

Label your pull request accordingly [from the label list](https://github.com/magpiemodel/magpie/labels).

- [ ] Low risk
  - [ ] Simple bugfixes (missing files, updated documentation, typos) or
  - [ ] Start/output scripts
- [ ] Medium risk  
  - [ ] New realization
  - [ ] Changes to existing realization
  - [ ] Other changes which don't modify default.cfg
- [ ] High risk
  - [ ] New input files (if cfg$input is changed in default.cfg)
  - [ ] Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.)
  - [ ] Other changes in default.cfg

## :key: Model run prerequisites :key:

- [ ] Low risk : No new model run needed.
- [ ] Medium risk : Default run based on the current version of the fork from which PR is made
- [ ] High risk
  - [ ] Default run from the current develop branch
  - [ ] Default run based on the current version of the fork from which PR is made

## :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:

- For high risk PR's : Comparison of run time between current develop and PR runs.

## :rotating_light: Checklist :rotating_light:

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The code doesn't contain declared but unused parameters or variables.
- [ ] In-code comments added including documentation comments.
- [ ] Compiled and checked resulting documentation with [`goxygen`](https://github.com/pik-piam/goxygen) for the new/updated parts (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.

## :warning: Special comments/warnings :warning:

Run time comparison:
Current develop branch default : 29 mins
This PR's default :  25 mins
This PR's Forestry run : 35 mins

2021-02-18 10:08 UTC, abhimishr commented
I added an addition file to our internal cloud with main results
1. Land-use plots (Cropland, Pasture, Primary forest, Secondary forest, Plantations, Other land)
2. Land-use change emissions (additional validation from Gasser et al. 2020 paper)
3. Tau
All values are reported GLO+REG

2021-02-18 14:20 UTC, tscheypidi requested changes

2021-02-18 14:20 UTC, tscheypidi commented on CHANGELOG.md
> +- **73_timber** Additive calibration with FAO data for roundwood demand. New switches: `c73_wood_scen`
A few lines up you say that `c32_dev_scen` is renamed `c73_wood_scen` which would mean that the latter does not exist anymore, but here you say that it is newly introduced? 
I suggest to check again all infos in CHANGELOG.md and (where possible) streamline it (remove intermediate solution if they did not make it to the final version in PR and shorten where possible)

2021-02-18 14:20 UTC, tscheypidi commented on CHANGELOG.md
> +- **deafult.cfg** New `forestry` scenario which simulates timber production in MAgPIE
typo

2021-02-18 14:20 UTC, tscheypidi commented on modules/21_trade/selfsuff_reduced/equations.gms
Why do deviate from standard setup for timber?

2021-02-18 14:20 UTC, tscheypidi commented on modules/21_trade/selfsuff_reduced/input.gms
> +  s21_trade_bal_damper Fraction to ease self sufficiency pool trade for roundwood /0.75/
why is that needed?

2021-02-18 14:20 UTC, tscheypidi commented on modules/21_trade/selfsuff_reduced/sets.gms
> +
we need a discussion on why that is needed

2021-02-18 14:25 UTC, abhimishr commented on modules/21_trade/selfsuff_reduced/equations.gms
Tagging @flohump here for responding

2021-02-18 14:25 UTC, abhimishr commented on modules/21_trade/selfsuff_reduced/sets.gms
> +
Tagging @flohump here for responding

2021-02-18 14:27 UTC, abhimishr commented on modules/21_trade/selfsuff_reduced/input.gms
> +  s21_trade_bal_damper Fraction to ease self sufficiency pool trade for roundwood /0.75/
I added this because current trade balance reduction numbers are too restrictive for wood and wood fuel in the inelastic trade pool

2021-02-18 14:35 UTC, abhimishr commented on CHANGELOG.md
> +- **deafult.cfg** New `forestry` scenario which simulates timber production in MAgPIE
Fixed

2021-02-18 14:36 UTC, abhimishr commented on CHANGELOG.md
> +- **73_timber** Additive calibration with FAO data for roundwood demand. New switches: `c73_wood_scen`
sorry. my mistake. fixed now

2021-02-18 15:19 UTC, flohump commented on modules/21_trade/selfsuff_reduced/equations.gms
The standard setup was developed in the absence of timber production.
The upper bound on agricultural production was introduced to avoid overproduction. 
In the case of exogenous wood harvesting scenarios, this constraint is infeasible. 
Moreover, the harvesting of timber plantations is fixed based on the rotation length, which can also cause some overproduction. This is not in line with this special constraint for avoiding overproduction of agricultural products.
Therefore, the upper bound on production has been removed for timber production.

2021-02-19 10:52 UTC, tscheypidi approved these changes

2021-02-19 11:08 UTC, abhimishr reviewed
I'll wait until @flohump also approves to merge from MAgPIE side. Thanks @tscheypidi !

2021-02-28 17:20 UTC, flohump approved these changes
Good to go!

2021-02-28 19:34 UTC, merged