Release v4.3.2
magpiemodel/magpie pull request #262
Opened 2021-03-17 19:59 UTC by tscheypidi

Please fill following information
(Add additional info if you think its important and not covered by this Pull Request (PR)):

## Purpose of this PR

Release of MAgPIE v4.3.2

2021-03-17 20:15 UTC, abhimishr submitted a review, later dismissed
🚀 Good to go 💎 🙌🏽 📈

2021-03-18 14:58 UTC, FelicitasBeier requested changes
Minor code cleanup changes requested.

2021-03-18 14:58 UTC, FelicitasBeier commented on modules/35_natveg/static/declarations.gms
> +  vm_cost_hvarea_natveg(i)						blub
Please add a variable description here

2021-03-18 14:58 UTC, FelicitasBeier commented on modules/39_landconversion/global_static_aug18/not_used.txt
> +name,type,reason
empty file. I think this doesn't have to be included, right?

2021-03-18 14:58 UTC, FelicitasBeier commented on modules/50_nr_soil_budget/exoeff_aug16/declarations.gms
>  *** |  authors, and contributors see CITATION.cff file. This file is part
Just wondering: Does this already include Benni's latest bugfix?

2021-03-18 14:58 UTC, FelicitasBeier commented on modules/52_carbon/normal_dec17/preloop.gms
> +*** |  (C) 2008-2021 Potsdam Institute for Climate Impact Research (PIK)
This file is now empty. I think should be deleted

2021-03-18 16:55 UTC, abhimishr commented
@tscheypidi what would be the best way to address the requested changes? Branch out from my commits at https://github.com/magpiemodel/magpie/pull/249, call it rc in my fork, make a PR for my fork's rc with main model's rc?

2021-03-18 17:03 UTC, abhimishr commented on modules/10_land/landmatrix_dec18/start.gms
> +*due to some rounding errors the input data currently may contain in some cases
True. Maybe we keep it for next data iteration of data preparation?

2021-03-18 17:03 UTC, abhimishr commented on modules/15_food/anthropometrics_jan18/intersolve.gms
> +* Now we also define a set for the last iteration
@bodirsky please check

2021-03-18 17:03 UTC, abhimishr commented on modules/15_food/anthropometrics_jan18/presolve.gms
> +* activating the first iteration
@bodirsky please check

2021-03-18 17:09 UTC, abhimishr commented on modules/50_nr_soil_budget/exoeff_aug16/declarations.gms
>  *** |  authors, and contributors see CITATION.cff file. This file is part
Not sure. Can you check @bodirsky ? Seems to be related to https://github.com/magpiemodel/magpie/pull/244 which was already part of https://github.com/magpiemodel/magpie/pull/249 so yes

2021-03-18 17:19 UTC, abhimishr commented on modules/52_carbon/normal_dec17/preloop.gms
> +*** |  (C) 2008-2021 Potsdam Institute for Climate Impact Research (PIK)
Fixed via 65bd3d4

2021-03-18 17:19 UTC, abhimishr commented on modules/39_landconversion/global_static_aug18/not_used.txt
> +name,type,reason
Fixed via 65bd3d4

2021-03-18 17:19 UTC, abhimishr commented on modules/35_natveg/static/declarations.gms
> +  vm_cost_hvarea_natveg(i)						blub
Fixed via 65bd3d4

2021-03-18 17:20 UTC, abhimishr commented on modules/50_nr_soil_budget/exoeff_aug16/declarations.gms
>  *** |  authors, and contributors see CITATION.cff file. This file is part
If this is another bugfix which came after https://github.com/magpiemodel/magpie/pull/249 then it won't be part of this planned release

2021-03-18 20:23 UTC, flohump commented on modules/15_food/anthropometrics_jan18/presolve.gms
> +* activating the first iteration
Yes. This is needed for the food demand model.

2021-03-19 08:04 UTC, bodirsky commented on modules/15_food/anthropometrics_jan18/intersolve.gms
> +* Now we also define a set for the last iteration
"previous" seems indeed better wording to me!
How do i change this in the RC?

2021-03-19 08:05 UTC, bodirsky commented on modules/50_nr_soil_budget/exoeff_aug16/declarations.gms
>  *** |  authors, and contributors see CITATION.cff file. This file is part
Which bugfix do you refer to?

2021-03-19 10:04 UTC, abhimishr commented on modules/15_food/anthropometrics_jan18/intersolve.gms
> +* Now we also define a set for the last iteration
i can pass this edit as a commit as I already have a cloned rc locally

2021-03-19 10:06 UTC, abhimishr commented on modules/15_food/anthropometrics_jan18/intersolve.gms
> +* Now we also define a set for the last iteration
Fixed with https://github.com/magpiemodel/magpie/pull/262/commits/14228c4cb3aff3313251ae2e1122ee8bbbdcc104

2021-03-19 10:07 UTC, abhimishr commented
I marked most of the requests resolved. @FelicitasBeier can you also check if https://github.com/magpiemodel/magpie/pull/262#discussion_r596869827 is okay? (Also if you'd like to re-open the changes I marked resolved)

2021-03-19 14:00 UTC, FelicitasBeier approved these changes
seems fine

2021-03-19 14:44 UTC, abhimishr approved these changes
🚀 ready to go

2021-03-19 20:23 UTC, merged