F bii update dev
magpiemodel/magpie pull request #264
Opened 2021-03-23 10:33 UTC by pvjeetze

## Purpose of this PR

Added biodiversity module. In the biodiversity module _biodiversity values_ (BV) are computed for each land cover type. The calculations are based on the Biodiversity Intactness Index (BII). BII values for each land cover type are multiplied by the respective land area and are weighted by cluster-specific range-rarity. The module also allows to introduce costs on the loss of the total biodiversity value.

## Performance loss/gain from current default behavior

Run times:
Current develop branch default : 30 mins
This PR's default : 32 mins

## Type of change

- [ ] Bug fix (Change which fixes an issue).
- [x] New feature (Change which adds functionality).
- [ ] Minor change (Change which does not modify core model code i.e., in /modules).
- [ ] Major change (fix or feature that would change current model behavior).

## How Has This Been Tested?

- [x] Runs using starting script which tests current defaults (using `test_runs.R`).
- [ ] Runs using starting script which successfully runs the same scenarios as in `test_runs.R` but with the changes from PR.
- [ ] (If applicable) Runs using different scenarios/mappings which are not the default (12 regions/c200 clusters).

## *Additions* or *Changes* to default configuration (default.cfg):

- Included section 44_biodiversity

- [x] Realizations: cfg$gms$biodiversity <- "bv_btc_mar21"
- [x] Scenario switches: Switch for different price scenarios cfg$gms$c44_price_bv_loss <- "p0"		# def = "p0"
- [ ] Scalars/Constants:
- [ ] Model interfaces:
- [ ] Others:

## Checklist:

- [x] Self-review of my own code.
- [x] Compilation check (model starts without compilation errors).
- [x] Added changes to `CHANGELOG.md`
- [x] No hard coded numbers and cluster/country/region names.
- [x] The code doesn't contain declared but unused parameters or variables.
- [x] In-code comments added including documentation comments.
- [x] Compiled and checked resulting documentation with `goxygen::goxygen()` for the new/updated parts.
- [x] Changes to `magpie4` R library for post processing of model output (ideally backward compatible).

## Special comments/warnings

2021-03-23 11:15 UTC, abhimishr commented
Hey @pvjeetze sorry I would not have good idea on what to look for in this review. Additional request - Can you make forestry runs with this if possible? Also it would be nice to old current default run from existing develop and a default run from your branch for comparison.

2021-03-23 11:25 UTC, abhimishr requested changes

2021-03-23 11:25 UTC, abhimishr commented on config/default.cfg
> +# * unit: $ per ha of biodiversity loss
US instead of $ maybe?

2021-03-23 11:25 UTC, abhimishr commented on config/default.cfg
> +# * (Pattern: p<year 2020>_p<year 2100> in USD)
Would need better explanation of pXX_pXX, Is this a sliding scale of costs, or does the price stay constant over time?

2021-03-23 11:25 UTC, abhimishr commented on main.gms
> +$setglobal c_title  bv_p0
Default title should not be changed

2021-03-23 11:25 UTC, abhimishr commented on modules/10_land/feb15/input.gms
> +table fm_luh2_side_layers(j,luh2_side_layers10) luh2 side layers (grid cell share)
Does this file come from existing cellular input (rev 52)? If not, this has to be changed in default.cfg

2021-03-23 11:25 UTC, abhimishr commented on modules/35_natveg/dynamic_feb21/declarations.gms
> +<<<<<<< HEAD
Merge errors. Should not exist

2021-03-23 11:25 UTC, abhimishr commented on modules/44_biodiversity/bv_btc_mar21/input.gms
> +*** (C) 2008-2021 Potsdam Institute for Climate Impact Research (PIK),
Is the new data already in existing cfg$input files? if not the default.cfg needs to be updated

2021-03-23 11:25 UTC, abhimishr commented on scripts/start/projects/bv_price.R
> +# |  (C) 2008-2020 Potsdam Institute for Climate Impact Research (PIK)
2021

2021-03-23 14:11 UTC, flohump requested changes
Overall fine. I have some specific request and sugestions, on top of @abhimishr

2021-03-23 14:11 UTC, flohump commented on modules/44_biodiversity/bv_btc_mar21/sets.gms
> +		/ crop_ann, crop_per, manpast, rangeland, urban, ndc, aff, primary, secondary, plant /
The naming of some set items could be improved for more intuitve interpretation. 
ndc -> aff_ndc
aff -> aff_co2p
plant -> timber_plant

In addtion, I suggest to include "other" as extra category. This also requires a change in the equations in 35_natveg
primforest, secdforest, other

2021-03-24 19:44 UTC, tscheypidi requested changes
In addition to Abhis and Florians remarks I had mainly some remarks about the model documentation.

2021-03-24 19:44 UTC, tscheypidi commented on main.gms
> +$setglobal c_title  bv_p0
ideally, you revert all changes in main.gms as they all were created automatically and there is no need to have them committed

2021-03-24 19:44 UTC, tscheypidi commented on modules/35_natveg/dynamic_feb21/declarations.gms
> +<<<<<<< HEAD
did you really test whether the model compiles?

2021-03-24 19:44 UTC, tscheypidi commented on modules/44_biodiversity/bv_btc_mar21/realization.gms
> +
It looks like a description of the realization for the documentation is missing here.

2021-03-24 19:44 UTC, tscheypidi commented on modules/44_biodiversity/module.gms
> +*'
Please make sure that the module description reflects the overall purpose of the module without making statements about the specific implementation. The description for each realization is then explaining how the general purpose of module is achieved in the respective realization. 
Things where I am not completely sure but got the feeling that they don't belong here, are the BII methodology (one could imagine to have another realization based on a different methodology, right?) and the specific description of how it is calculated here.

2021-03-25 09:13 UTC, pvjeetze commented on config/default.cfg
> +# * (Pattern: p<year 2020>_p<year 2100> in USD)
Updated the module description in default.cfg

2021-03-25 09:13 UTC, pvjeetze commented on modules/10_land/feb15/input.gms
> +table fm_luh2_side_layers(j,luh2_side_layers10) luh2 side layers (grid cell share)
The file is already included in the input data (additional data)

2021-03-25 09:16 UTC, pvjeetze commented on modules/35_natveg/dynamic_feb21/declarations.gms
> +<<<<<<< HEAD
Resolved this issue. The model compiles without errors.

2021-03-25 09:19 UTC, pvjeetze commented on main.gms
> +$setglobal c_title  bv_p0
reverted the change to default

2021-03-25 09:20 UTC, pvjeetze commented on modules/44_biodiversity/bv_btc_mar21/input.gms
> +*** (C) 2008-2021 Potsdam Institute for Climate Impact Research (PIK),
no update needed for cfg$input in this case

2021-03-25 09:23 UTC, pvjeetze commented on core/sets.gms
> +* ac_intermediate(ac) age classes intermediate
ac_intermediate deleted

2021-03-25 09:27 UTC, pvjeetze commented on modules/44_biodiversity/bv_btc_mar21/declarations.gms
> +equations
units added to equations

2021-03-25 10:34 UTC, flohump commented on modules/44_biodiversity/bv_btc_mar21/input.gms
> +table fm_bii_coeff(bii_class44,potnatveg) bii coeff
Units are still missing here.

2021-03-25 11:33 UTC, pvjeetze commented on modules/44_biodiversity/module.gms
> +*'
I update both the module & realisation descriptions

2021-03-25 12:45 UTC, tscheypidi approved these changes
all good from my side

2021-03-25 15:14 UTC, pvjeetze commented on modules/44_biodiversity/bv_btc_mar21/input.gms
> +table fm_bii_coeff(bii_class44,potnatveg) bii coeff
Units have been added in this [commit ](https://github.com/magpiemodel/magpie/pull/264/commits/c82a3363de473c582d4d6d5eda65c6a15d3b46e4)

2021-03-25 16:40 UTC, abhimishr commented on scripts/start/projects/bv_price.R
> +# |  (C) 2008-2020 Potsdam Institute for Climate Impact Research (PIK)
opening this again as the comment was marked resolved without resolving the requested change. 2008-2020 should be changed to 2008-2021 (we updated the headers recently so this should also be changed)

2021-03-25 16:41 UTC, abhimishr commented on config/default.cfg
> +# * unit: $ per ha of biodiversity loss
Marking unresolved. Sorry I meant USD not US. USD is our default naming convention

2021-03-25 16:44 UTC, abhimishr commented
@tscheypidi might be a good time to also look into our new PR template? (maybe after this PR) I see that the current PR template includes information which is not needed/outdated. Ideally I'd like to see this PRs default vs existing default run (I think they are exactly the same but @pvjeetze can confirm).

2021-03-25 16:44 UTC, pvjeetze commented on scripts/start/projects/bv_price.R
> +# |  (C) 2008-2020 Potsdam Institute for Climate Impact Research (PIK)
weird, same happened with my changes to the units suggested by @flohump, the also didn't appear. but check out this [commit](https://github.com/magpiemodel/magpie/pull/264/commits/71089e9cbea39cfcb285756461e63cb517fc223d)

2021-03-25 16:47 UTC, pvjeetze commented on config/default.cfg
> +# * unit: $ per ha of biodiversity loss
check out this [https://github.com/magpiemodel/magpie/pull/264/commits/170ad4c0e2dc75b2a0192bc3c4333ff65f43a851]

2021-03-25 16:55 UTC, abhimishr commented
Also good to go from my side but I would propose to wait for Florian's approval (not marking approved from my side)

2021-03-25 17:00 UTC, weindl requested changes
Some small comments on top of previous reviews.

2021-03-25 17:00 UTC, weindl commented on config/default.cfg
> +cfg$gms$biodiversity <- "bv_btc_mar21"    # def = bv_btc_mar21
Shortly explain the acronym btc

2021-03-25 17:00 UTC, weindl commented on modules/30_crop/endo_jun13/declarations.gms
> + q30_bv_per(j,potnatveg)       Biodiversity value of perennial cropland
add units to the declaration of equations

2021-03-25 17:00 UTC, weindl commented on modules/30_crop/module.gms
> +*' the biodiversity value of the existing cropland.
"and the biodiversity value"

2021-03-25 17:00 UTC, weindl commented on modules/31_past/endo_jun13/declarations.gms
> + q31_bv_manpast(j,potnatveg)    Biodiversity value for managed pastures
add units

2021-03-25 17:00 UTC, weindl commented on modules/32_forestry/static_sep16/presolve.gms
> +
all occurrences of v32_land (lines 24-33): suffix .l seems to be missing

2021-03-25 17:00 UTC, weindl commented on modules/35_natveg/dynamic_feb21/equations.gms
> +        + sum(ac_mature, v35_secdforest(j2,ac_mature) + v35_other(j2,ac_mature)) * fm_bii_coeff("secd_young",potnatveg) * fm_luh2_side_layers(j2,potnatveg);
line 42: I think it should be "sum(ac_young, v35_secdforest(j2,ac_young) + v35_other(j2,ac_young)) * ... 
                         instead of " sum(ac_mature, v35_secdforest(j2,ac_mature) + v35_other(j2,ac_mature)) * ..."

2021-03-25 17:00 UTC, weindl commented on modules/35_natveg/static/presolve.gms
> +          sum(ac_mature, v35_secdforest(j,ac_mature) + v35_other(j,ac_mature)) * fm_bii_coeff("secd_mature",potnatveg) * fm_luh2_side_layers(j,potnatveg)
suffix .l needed for variables v35_secdforest and v35_other

2021-03-25 17:00 UTC, weindl commented on modules/35_natveg/static/presolve.gms
> +        + sum(ac_mature, v35_secdforest(j,ac_mature) + v35_other(j,ac_mature)) * fm_bii_coeff("secd_young",potnatveg) * fm_luh2_side_layers(j,potnatveg);
see above: ac_young instead of ac_mature (line 28)

2021-03-25 17:22 UTC, pvjeetze commented on config/default.cfg
> +cfg$gms$biodiversity <- "bv_btc_mar21"    # def = bv_btc_mar21
added reference to the Bending the Curve initiative

2021-03-25 17:22 UTC, pvjeetze commented on modules/30_crop/endo_jun13/declarations.gms
> + q30_bv_per(j,potnatveg)       Biodiversity value of perennial cropland
units added

2021-03-25 17:22 UTC, pvjeetze commented on modules/30_crop/module.gms
> +*' the biodiversity value of the existing cropland.
was corrected

2021-03-25 17:22 UTC, pvjeetze commented on modules/31_past/endo_jun13/declarations.gms
> + q31_bv_manpast(j,potnatveg)    Biodiversity value for managed pastures
units added

2021-03-25 17:23 UTC, pvjeetze commented on modules/32_forestry/static_sep16/presolve.gms
> +
level added to v32_land

2021-03-25 17:23 UTC, pvjeetze commented on modules/35_natveg/dynamic_feb21/equations.gms
> +        + sum(ac_mature, v35_secdforest(j2,ac_mature) + v35_other(j2,ac_mature)) * fm_bii_coeff("secd_young",potnatveg) * fm_luh2_side_layers(j2,potnatveg);
this bug has been fixed

2021-03-25 17:30 UTC, pvjeetze commented on modules/35_natveg/static/presolve.gms
> +          sum(ac_mature, v35_secdforest(j,ac_mature) + v35_other(j,ac_mature)) * fm_bii_coeff("secd_mature",potnatveg) * fm_luh2_side_layers(j,potnatveg)
suffix added

2021-03-25 17:31 UTC, pvjeetze commented on modules/35_natveg/static/presolve.gms
> +        + sum(ac_mature, v35_secdforest(j,ac_mature) + v35_other(j,ac_mature)) * fm_bii_coeff("secd_young",potnatveg) * fm_luh2_side_layers(j,potnatveg);
the bug was fixed

2021-03-25 17:41 UTC, pvjeetze commented
Thanks @abhimishr, @tscheypidi, @flohump and @weindl for reviewing the code. I have tried to address all comments in today's commits.

2021-03-25 19:18 UTC, flohump approved these changes

2021-03-26 08:49 UTC, abhimishr approved these changes

2021-03-26 09:08 UTC, weindl approved these changes

2021-03-26 09:13 UTC, merged