Release of version 4.3.3
magpiemodel/magpie pull request #266
Opened 2021-03-30 13:03 UTC by tscheypidi

updated version information

2021-03-30 13:21 UTC, abhimishr requested changes
Seems fine in general. Some comments about whitespaces and the commits should be avoided if possible with those whitespeace changes. An additional question to @flohump based on https://github.com/magpiemodel/magpie/commit/158661e37292db77c85f83a348331bee5e78cebd

2021-03-30 13:21 UTC, abhimishr commented on core/sets.gms
> +   i all economic regions /
unnecessary whitespace can be removed

2021-03-30 13:21 UTC, abhimishr commented on core/sets.gms
> +       USA_191*USA_200 /
same as above

2021-03-30 13:21 UTC, abhimishr commented on core/sets.gms
> +   cell(i,j) number of LPJ cells per region i /
avoid whitespace changes

2021-03-30 13:21 UTC, abhimishr commented on core/sets.gms
> +       USA . USA_191*USA_200 /
avoid whitespace changes

2021-03-30 13:21 UTC, abhimishr commented on core/sets.gms
> +   i_to_iso(i,iso) mapping regions to iso countries /
avoid whitespace changes

2021-03-30 13:21 UTC, abhimishr commented on core/sets.gms
> +       USA . (USA) /
avoid whitespace changes

2021-03-30 13:21 UTC, abhimishr commented on modules/20_processing/substitution_dec18/preloop.gms
> +
avoid whitespace changes

2021-03-30 13:21 UTC, abhimishr commented on modules/44_biodiversity/bv_btc_mar21/declarations.gms
> + p44_price_bv_loss(t)			                biodiversity value loss price factor (US$ per ha of bv loss)
Can you check again if we allow only USD or US$? I could not find instances of US$ except for one place in sticky implementation. USD is recognized correctly by goxygen for documentation

2021-03-30 13:21 UTC, abhimishr commented on modules/44_biodiversity/bv_btc_mar21/declarations.gms
> + p44_price_bv_loss(t)			                biodiversity value loss price factor (US$ per ha of bv loss)
If you decide on USD i'd suggest changing all instances of US$ to USD (even in sticky)

2021-03-30 13:21 UTC, abhimishr commented on modules/56_ghg_policy/price_jan20/sets.gms
> +*###############################################################################
It comes from https://github.com/magpiemodel/magpie/commit/158661e37292db77c85f83a348331bee5e78cebd but why this special set writing to this file @flohump ?

2021-03-30 13:23 UTC, tscheypidi commented on core/sets.gms
> +   i all economic regions /
This part is created automatically

2021-03-30 13:23 UTC, tscheypidi commented on core/sets.gms
> +       USA_191*USA_200 /
see above

2021-03-30 13:24 UTC, tscheypidi commented on core/sets.gms
> +   cell(i,j) number of LPJ cells per region i /
see above

2021-03-30 20:41 UTC, flohump commented on modules/56_ghg_policy/price_jan20/sets.gms
> +*###############################################################################
These are automatic sets, which are generated based on the content of the file.

2021-03-30 20:42 UTC, flohump commented on modules/44_biodiversity/bv_btc_mar21/declarations.gms
> + p44_price_bv_loss(t)			                biodiversity value loss price factor (US$ per ha of bv loss)
@pvjeetze Could you check on this?

2021-03-30 20:44 UTC, flohump commented on modules/44_biodiversity/bv_btc_mar21/declarations.gms
> + p44_price_bv_loss(t)			                biodiversity value loss price factor (US$ per ha of bv loss)
@tscheypidi Changes should be made directly in the rc branch?

2021-03-30 20:52 UTC, tscheypidi commented on modules/44_biodiversity/bv_btc_mar21/declarations.gms
> + p44_price_bv_loss(t)			                biodiversity value loss price factor (US$ per ha of bv loss)
yes

2021-03-31 06:48 UTC, pvjeetze commented on modules/44_biodiversity/bv_btc_mar21/declarations.gms
> + p44_price_bv_loss(t)			                biodiversity value loss price factor (US$ per ha of bv loss)
I've changed the units to USD in https://github.com/magpiemodel/magpie/pull/266/commits/ec099f61dfd757623df34537a8429c88f317885b

2021-03-31 07:19 UTC, flohump commented on core/sets.gms
> +   i_to_iso(i,iso) mapping regions to iso countries /
These sets are created automatically. The function that writes these sets has been changed slightly.

2021-03-31 07:20 UTC, flohump commented on core/sets.gms
> +       USA . (USA) /
These sets are created automatically. The function that writes these sets has been changed slightly.

2021-03-31 07:21 UTC, flohump commented on modules/20_processing/substitution_dec18/preloop.gms
> +
One additional line at the end is not critical.

2021-03-31 07:22 UTC, flohump commented on core/sets.gms
> +       USA . USA_191*USA_200 /
These sets are created automatically. The function that writes these sets has been changed slightly.

2021-03-31 07:22 UTC, flohump commented on core/sets.gms
> +   cell(i,j) number of LPJ cells per region i /
These sets are created automatically. The function that writes these sets has been changed slightly.

2021-03-31 07:22 UTC, flohump commented on core/sets.gms
> +       USA_191*USA_200 /
These sets are created automatically. The function that writes these sets has been changed slightly.

2021-03-31 07:22 UTC, flohump commented on core/sets.gms
> +   i all economic regions /
These sets are created automatically. The function that writes these sets has been changed slightly.

2021-03-31 07:26 UTC, flohump approved these changes
Seems all fine to me.

2021-03-31 10:19 UTC, abhimishr approved these changes
🚀 Seems fine!
I noticed a typo I introduced. Can you maybe fix this in the commits here 
`*' @title Age class` in module 29 `module.gms`. I committed it as "production" but it should be Age class

2021-04-02 04:37 UTC, merged