Incorporating agricultural residue burning emissions
magpiemodel/magpie pull request #268
Opened 2021-04-08 12:33 UTC by mscrawford

## Purpose of this PR

Incorporate the emissions calculations from agricultural residue burning (N2O, NO2). Changes to 18_residues and 51_nitrogen. 

## Performance loss/gain from current default behavior

![newplot](https://user-images.githubusercontent.com/3107098/114024543-761a5e80-9874-11eb-97ab-225a0d6a75d9.png)

~ 7% performance loss

## Type of change

- [ ] Bug fix (Change which fixes an issue).
- [ ] New feature (Change which adds functionality).
- [X] Minor change (Change which does not modify core model code i.e., in /modules).
- [ ] Major change (fix or feature that would change current model behavior).

## How Has This Been Tested?

The new calculations are present in the .GDX. The following plot shows the correspondence between MAgPIE's calculations and the historical FAO data for N2O.

![image](https://user-images.githubusercontent.com/3107098/114024853-d0b3ba80-9874-11eb-96fe-9913bc1b3528.png)

## *Additions* or *Changes* to default configuration (default.cfg):

One new file was added, incorporating the emissions factors taken from the IPCC 2019 revision, f51_ef_resid_burn.cs4

## Checklist:

- [X] Self-review of my own code.
- [X] Compilation check (model starts without compilation errors).
- [X] Added changes to `CHANGELOG.md`
- [X] No hard coded numbers and cluster/country/region names.
- [X] The code doesn't contain declared but unused parameters or variables.
- [X] In-code comments added including documentation comments.
- [X] Compiled and checked resulting documentation with `goxygen::goxygen()` for the new/updated parts.
- [X] Changes to `magpie4` R library for post processing of model output (ideally backward compatible).

## Special comments/warnings

The additions don't add anything to the optimization, but do increase the total number of calculations.

2021-04-09 07:20 UTC, tscheypidi requested changes
As you have introduced a new interface, please update the module contracts of the corresponding modules. You find the contracts as part of the goxygen documentation in the module.gms files of the corresponding modules.

The module contract should describe what the purpose of the module is, what outputs it is promising to provide and what inputs it is expecting to get in order to compute the outputs.

In addition I saw that in one off-realization you just set the value of that new interface to zero. The description of that realization should make very clear what scenario this module is representing. In your case, if no residue burning is happening, what is happening instead?

2021-04-12 09:04 UTC, mscrawford commented
Within the module contract, it is already stipulated that 18_residues is connected to 51_nitrogen:

`
*' @description
*' The nitrogen module calculates nitrogeneous emissions before technical
*' mitigation, including N2O, NOx, NH3, NO3- and N2.
*' The model receives information on nitrogen flows from [50_nr_soil_budget],
*' [55_awms], [18_residues], [59_som], and it provides the emissions to the
*' module [56_ghg_policy].
*' Emissions factors estimates are largely based on the IPCC 2006 Guidelines for
*' National Greenhouse Gas Inventories (@ipcc_2006_2006.),
*' as described in (@bodirsky_current_2012.).
`

And the `off` realization is perhaps a tad vague but is nonetheless still true with my changes:

`
*' @description
*' Emissions are set to zero.
*'
*' @authors Benjamin Leon Bodirsky
`

Should I change these documentations to be more specific? I could also add myself to the authors, or the IPCC 2019 Refinement to the literature description, specifically for agricultural residue burning.

2021-04-12 13:39 UTC, mscrawford commented
I have now amended the module contracts for both 18_residues and 51_nitrogen to be more specific.

2021-04-13 09:47 UTC, mscrawford commented
I've now amended the documentation to better fit Jan's specifications.

2021-04-13 10:18 UTC, tscheypidi approved these changes
looks good

2021-04-26 19:24 UTC, tscheypidi commented
@mscrawford what is the status here? Still needs @bodirsky to review, right? Should probably happen rather soon as PR are currently piling up

2021-04-27 04:08 UTC, mscrawford commented
Yes, I am waiting for Benni on this one!

On Mon, Apr 26, 2021 at 21:24 Jan Dietrich ***@***.***> wrote:

> @mscrawford <https://github.com/mscrawford> what is the status here?
> Still needs @bodirsky <https://github.com/bodirsky> to review, right?
> Should probably happen rather soon as PR are currently piling up
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/magpiemodel/magpie/pull/268#issuecomment-827086137>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXWSGR4NCGZWXDGVKMZ3I3TKW4YFANCNFSM42SZQ3MA>
> .
>

2021-04-28 10:36 UTC, bodirsky approved these changes
all fine!

2021-04-28 10:37 UTC, merged