Bugfix SCP "mixed" scenario + "kfo_rd" set added to config file
magpiemodel/magpie pull request #270
Opened 2021-04-25 13:17 UTC by flohump

Please fill following information
(Add additional info if you think its important and not covered by this Pull Request (PR)):

## Purpose of this PR

- The "mixed" scenario for single-cell protein production (c20_scp_type) was not working as expected. The corresponding code in 20_processing has been updated. Review needed from @bodirsky 
- The set "kfo_rd" (livst_rum, livst_milk), which is used in the food substitution scenarios c15_rumdairy_scp_scen and c15_rumdairyscen, has been added to the default.cfg file. This allows for sensitivity scenarios (e.g. only livst_milk or only livst_rum). Review needed from @weindl 

## Performance loss/gain from current default behavior

- Add an image using plot from `shinyresults::appResults()` and annotate accordingly.

- %performance loss/gain = 100*Runtime from PR/Runtime from current default from develop branch.

## Type of change

- [ ] Bug fix (Change which fixes an issue).
- [ ] New feature (Change which adds functionality).
- [ ] Minor change (Change which does not modify core model code i.e., in /modules).
- [ ] Major change (fix or feature that would change current model behavior).

## How Has This Been Tested?

- [ ] Runs using starting script which tests current defaults (using `test_runs.R`).
- [ ] Runs using starting script which successfully runs the same scenarios as in `test_runs.R` but with the changes from PR.
- [ ] (If applicable) Runs using different scenarios/mappings which are not the default (12 regions/c200 clusters).

## *Additions* or *Changes* to default configuration (default.cfg):
Additions are the introduction of new model components in default config

Changes are deletion or updates to the existing model components in default config

- [ ] Realizations:
- [ ] Scenario switches:
- [ ] Scalars/Constants:
- [ ] Model interfaces:
- [ ] Others:

## Checklist:

- [ ] Self-review of my own code.
- [ ] Compilation check (model starts without compilation errors).
- [ ] Added changes to `CHANGELOG.md`
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The code doesn't contain declared but unused parameters or variables.
- [ ] In-code comments added including documentation comments.
- [ ] Compiled and checked resulting documentation with `goxygen::goxygen()` for the new/updated parts.
- [ ] Changes to `magpie4` R library for post processing of model output (ideally backward compatible).

## Special comments/warnings

- Notes

2021-04-26 19:22 UTC, tscheypidi commented on modules/15_food/anthropometrics_jan18/input.gms
> +$onMultiR
why do you need $onMultiR here?

2021-04-26 19:44 UTC, flohump commented on modules/15_food/anthropometrics_jan18/input.gms
> +$onMultiR
Because the set kfo_rd needs to be defined in sets.gms (some declarations depend on kfo_rd) and then overwritten in input.gms.

2021-04-28 11:33 UTC, flohump commented
@bodirsky @weindl @tscheypidi I need your feedback on this PR.

2021-04-28 13:10 UTC, tscheypidi approved these changes
looks good to me, but could you please pull the recent version of develop into your branch as there was recently another PR accepted (I don't see these changes in your diff view at the moment for some reason)

2021-04-28 13:27 UTC, flohump commented
> looks good to me, but could you please pull the recent version of develop into your branch as there was recently another PR accepted (I don't see these changes in your diff view at the moment for some reason)

Done!

2021-04-28 20:10 UTC, weindl approved these changes

2021-04-28 20:10 UTC, weindl commented on config/default.cfg
> +cfg$gms$kfo_rd <- "livst_rum,livst_milk"				#def = livst_rum,livst_milk
maybe add possible options ("livst_rum,livst_milk", "livst_rum" and "livst_milk")

2021-04-29 13:52 UTC, bodirsky requested changes
a few tiny changes (see comments above)

2021-04-29 13:52 UTC, bodirsky commented on modules/20_processing/substitution_dec18/equations.gms
>  sum((ksd,processing20,kpr), v20_dem_processing(i2,processing20,kpr)
line 113: f20_scp_conversionmatrix doesnt exist anymore

2021-04-29 14:25 UTC, flohump commented on modules/20_processing/substitution_dec18/equations.gms
>  sum((ksd,processing20,kpr), v20_dem_processing(i2,processing20,kpr)
removed

2021-04-29 14:25 UTC, flohump commented on config/default.cfg
> +cfg$gms$c20_scp_type <- "sugar"                         # def = sugar
This woudl require quite some renaming in input files. I added a comment in the config file.

2021-04-29 14:35 UTC, flohump commented on config/default.cfg
> +cfg$gms$kfo_rd <- "livst_rum,livst_milk"				#def = livst_rum,livst_milk
This holds true for many other sets in module 15. Maybe this is needed for the food demand model?

2021-04-30 05:58 UTC, bodirsky approved these changes

2021-04-30 05:59 UTC, merged