PR for merging new yield realization and input data preprocessing via mrmagpie
magpiemodel/magpie pull request #273
Opened 2021-04-26 17:58 UTC by k4rst3ns

## :bird: Purpose of this PR :bird:

:warning: **PLEASE DO NOT MERGE** at the current state!!! 

This pull request will update the yield module by adding a new realization, which is able to process input data coming from cellular preprocessing by mrmagpie (especially new LPJmL data). In the best case the model will be able to run with old and new data. 

## :wrench: Checklist for PR creator :wrench:

- [x] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The new code doesn't contain declared but unused parameters or variables.
- [ ] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau. 

## :warning: Additional notes or warnings :warning:
**PLEASE DO NOT MERGE**!!! This pull request is active and will be worked on the upcoming weeks.

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2021-05-03 11:40 UTC, vartika271987 commented on main.gms
> +$setglobal c_title  default_lpjml5
I guess this needs to be removed when the PR is merged into develop

2021-05-03 11:41 UTC, vartika271987 commented on main.gms
> +$setglobal yields  managementcalib_aug19
In the default.cfg, the value used is "dynamic_aug18"

2021-05-03 14:34 UTC, FelicitasBeier reviewed
I still need to check preloop of managementcalib...

2021-05-03 21:23 UTC, k4rst3ns commented on main.gms
> +$setglobal c_title  default_lpjml5
The main.gms is normally updated automatically, but having a main.gms in default settings is probably better in any case.

2021-05-03 21:24 UTC, k4rst3ns commented on main.gms
> +$setglobal yields  managementcalib_aug19
Same as above (will be changed, once al test runs have been made).

2021-05-03 21:25 UTC, k4rst3ns commented on config/default.cfg
> +cfg$crop_calib_max <- 100            # def= 1
For the old default, there was never a upper bound in place, so I just set it to 100 to reproduce old behaviour.
For the new yield realization it should be 1 (or close to- this is up for discussion at the moment).

2021-05-03 21:26 UTC, k4rst3ns commented on config/default.cfg
> +cfg$force_download <- TRUE
Will be removed (just ended up there during test runs ^^').

2021-05-03 21:28 UTC, k4rst3ns commented on config/default.cfg
> +# *                          pasture yields as in dynamic_aug18 (new LPJmL4/5)
I have the feeling there is missing some port of the suggestion? (now it would be identical to the dynamic_aug18 description).

2021-05-03 21:31 UTC, k4rst3ns commented on config/default.cfg
> +cfg$gms$c41_initial_irrigation_area  <- "Siebert"          # def = LUH2v2
The default script should reproduce old settings. As new LUH2v2 data was introduced with the new realization, the old default is still Siebert and will be changed when ever managementcalib_aug19 becomes new default.

2021-05-03 21:33 UTC, k4rst3ns commented on modules/59_som/cellpool_aug16/input.gms
> +$include "./modules/59_som/input/lpj_carbon_topsoil.cs2b"
Yes - it has been introduced newly, see ?magclass::write.magpie()

2021-05-03 21:36 UTC, k4rst3ns commented on scripts/start_functions.R
> +                      spamfile = Sys.glob("input/0.5-to-*_sum.spam")) {
this will be only executed if the rds is missing (see https://github.com/k4rst3ns/magpie/blob/ef7dbb791e72117b443faeeb37d264a927b9ae37/scripts/start_functions.R#L231).
This ensures backwards compatibility, for old preprocessing data.
I will add comments to clarify this. Thanks for spotting.

2021-05-03 21:38 UTC, k4rst3ns commented on modules/14_yields/managementcalib_aug19/input.gms
> +table f14_yields(t_all,j,kve,w) LPJmL potential yields per cell (rainfed and irrigated) (tDM per ha per yr)
normally in the magpie code a cell is what we call cluster in the preprocessing.
I think this is confusing too, but consistent with the rest of the magpie code.
Maybe you can check again, for usage of cluster or cell in the code?

2021-05-03 21:42 UTC, k4rst3ns commented on scripts/calibration/calc_calib.R
> +    for (i in getCells(calib_best)){
Not sure if I understand (this would just change the runtime of the calibration run, which is normally not an indicator of runtime we look on).
The best calib approach was added by Edna as an improvement and the loop goes over regions (which re normally just a few), so I guess the performance gain would be rather small.

2021-05-03 21:43 UTC, k4rst3ns commented on scripts/output/extra/disaggregation.R
> +  warning(paste0("Negative values in inital high resolution dataset ",
Yes, this function was to be updated in any case.
The intermediate version seem to be buggy a bit ^^'

2021-05-03 21:44 UTC, k4rst3ns commented on modules/14_yields/managementcalib_aug19/declarations.gms
> + i14_croparea_total(t_all,j)                            Cellular water type specific cropareas (mio. ha)
good catch!

2021-05-03 21:45 UTC, k4rst3ns commented on modules/14_yields/managementcalib_aug19/equations.gms
> + * (1 + s14_yld_past_switch*(sum(cell(i2,j2),pc13_tau(i2)/fm_tau1995(i2)) - 1));
yes, will changes that.

2021-05-04 04:25 UTC, vartika271987 commented on config/default.cfg
> +cfg$force_download <- TRUE
Shouldn't it be true in the first default for everyone to  be able to download the NEW data?

2021-05-04 06:58 UTC, FelicitasBeier commented on modules/14_yields/managementcalib_aug19/input.gms
> +table f14_yields(t_all,j,kve,w) LPJmL potential yields per cell (rainfed and irrigated) (tDM per ha per yr)
I know it is used everywhere in the MAgPIE code, still doesn't make it good. I think cluster cell everywhere in the code would be clearer. 
Especially here in the case of calibration I would specify it clearly by saying cluster cell or 0.5 degree cell because both would make logical sense in a calibration.

2021-05-04 07:02 UTC, FelicitasBeier commented on config/default.cfg
> +# *                          pasture yields as in dynamic_aug18 (new LPJmL4/5)
From the description I understand that the pasture yields part is identical to dynamic_aug18. My point is just that it's risky to refer to a different realization in a description because it may be deleted in the future.
Therefore: "calibrate potential LPJmL-yields to FAO regional numbers,
                         pasture yields increase based on exogenous demand-side proxy for growth rate of cattle stocks"

2021-05-04 07:02 UTC, FelicitasBeier commented on config/default.cfg
> +# *                          pasture yields as in dynamic_aug18 (new LPJmL4/5)
Also: Typo in (dynamic_aug18): exogenuous -> exogenous

2021-05-04 07:44 UTC, k4rst3ns commented on modules/14_yields/managementcalib_aug19/input.gms
> +table f14_yields(t_all,j,kve,w) LPJmL potential yields per cell (rainfed and irrigated) (tDM per ha per yr)
As the is no such thing as half degree in magpie code, I don't think this is nessessary. I would want to be in line with naming conventions in magpie, but I do not know what the are. Is cluster used anywhere else in the magpie code.
If yes, I would change it, if not I would stick to the naming convention as also in the magpie4 library, where cell=clustered data, grid=0.5degree data.

2021-05-04 20:28 UTC, k4rst3ns commented on config/default.cfg
> +cfg$force_download <- TRUE
if needed it is download - it means that it is just not forced to download, if already available.

2021-05-05 06:31 UTC, k4rst3ns commented on modules/14_yields/managementcalib_aug19/equations.gms
> + vm_yld(j2,kcr,w) =e= sum(ct,i14_yields_calib(ct,j2,kcr,w) *
changed!

2021-05-07 16:07 UTC, flohump commented on scripts/start/lpjml5.R
> +cfg$input <- c("rev4.59irrig_is_rainf_h12_magpie_debug.tgz",
The input files + settings used here need to be included into the default.cfg

2021-05-20 10:26 UTC, vartika271987 commented on config/default.cfg
> +cfg$gms$c41_initial_irrigation_area <- "Siebert"             # def = "LUH2v2"
default settings in this module are now switched to LUH2v2. Shouldn't it be the same here?

2021-05-21 12:52 UTC, caviddhen commented on config/default.cfg
> +cfg$best_calib <- FALSE
is best calib default FALSE?

2021-05-21 12:59 UTC, caviddhen commented on config/default.cfg
> +cfg$best_calib <- FALSE
nvm saw the conversation later on defaults regarding Siebert vs LUH2v2

2021-05-21 20:55 UTC, FelicitasBeier commented on modules/30_crop/endo_apr21/realization.gms
> +*' module [14_yields] and the rotational as well as suitability constrains
typo: constrains -> constraints

2021-05-21 20:55 UTC, FelicitasBeier commented on modules/32_forestry/dynamic_feb21/declarations.gms
> + p32_bii_coeff(type32,bii_class_secd,potnatveg)     bii coeff (unitless)
I think usually we use (1) instead of unitless

2021-05-24 08:31 UTC, vartika271987 commented on config/default.cfg
> +# * (c30_rotation_constrains): switch for rotational constrains: on, off
Should the spelling be `c30_rotation_constraints` overall?

2021-05-24 08:39 UTC, vartika271987 commented on config/default.cfg
> +# * (dynamic): capital shares depend on each regions GDP in each time step
We should add in the description here that this is only applicable is `sticky` realization is selected.

2021-05-24 08:50 UTC, vartika271987 commented on main.gms
> +* Repository: scp://cluster.pik-potsdam.de/p/projects/landuse/data/input/archive
This will be changed when the develop version is merged into master, right?

2021-05-24 09:10 UTC, vartika271987 commented on modules/14_yields/managementcalib_aug19/preloop.gms
> +*' to which the baseline (FAO) is under or over estimated and therefor controls,
No `,` after controls (?)

2021-05-24 09:30 UTC, vartika271987 commented on modules/14_yields/managementcalib_aug19/preloop.gms
> +*' on the setting 's14_limit_calib' and than hold constant for all other time steps.
typo -> and is then `held` constant

2021-05-24 09:55 UTC, vartika271987 commented on modules/14_yields/managementcalib_aug19/preloop.gms
> +** Natveg yields are unchanged and doesn't depend on plantation yield switch
typo: and doesn't <- and do not

2021-05-24 09:56 UTC, vartika271987 commented on modules/14_yields/managementcalib_aug19/presolve.gms
> +*' aboveground `f14_aboveground_fraction`. Additionally, we divide aboveground
typo: aboveground <- above ground

2021-05-24 09:57 UTC, vartika271987 commented on modules/14_yields/managementcalib_aug19/presolve.gms
> +** If the plantation yield switch is on, forestry yields are treated are plantation yields
typo: treated area >- treated as

2021-05-24 09:58 UTC, vartika271987 commented on modules/14_yields/managementcalib_aug19/realization.gms
> +*' Pasture yields are calulcated based on pasture demand to account for
*calculated

2021-05-25 00:32 UTC, k4rst3ns commented on modules/20_processing/substitution_may21/presolve.gms
> +vm_secondary_overproduction.fx(i2,kall,kpr)=0;
I don't know. Sorry this was not changed and might be clarified with author of the module.

2021-05-25 00:33 UTC, k4rst3ns commented on modules/20_processing/substitution_may21/presolve.gms
> +vm_dem_processing.fx(i,knpr)=0;
i2 is used only in equations.

2021-05-25 00:34 UTC, k4rst3ns commented on modules/20_processing/substitution_may21/realization.gms
> +*' The realization substitution_may21 excludes the calibration factors that are used in substitution_dec18 in order to reduce the substitution of oils by other oils.
I was asking Benni for this and he ony added this :(. As in the default case only one realization is there the module file contains quite some information.

Tagging @bodirsky to clarify this

2021-05-25 06:51 UTC, FelicitasBeier commented on modules/20_processing/substitution_may21/presolve.gms
> +vm_dem_processing.fx(i,knpr)=0;
I'm asking because all others below (here in the presolve) use i2. Maybe they should be referred to as i then?

2021-05-25 06:57 UTC, vartika271987 reviewed
Looks good to me overall, aside from minor typos.

2021-06-01 09:14 UTC, k4rst3ns commented on modules/14_yields/managementcalib_aug19/nl_fix.gms
> +
original nl_fix did had any comment as well - I will leave this as it was for all other realizations.

2021-06-01 09:25 UTC, k4rst3ns commented on modules/41_area_equipped_for_irrigation/endo_apr13/sets.gms
> +sets
also added for static. was not updated there. thanks!

2021-06-01 09:34 UTC, k4rst3ns commented on modules/20_processing/substitution_dec18/realization.gms
> +*' The realization substitution_dec18 includes the calibration factors that are used to reduce the substitution of oils by other oils.
As the original realization, this development is based on, was not documented; thi was is neither. Since this is minor change to the over pull request. I wil mark this as resolved for now, but will bring the general issue of documenting this realization to the meeting.

2021-06-01 09:44 UTC, k4rst3ns commented on modules/14_yields/managementcalib_aug19/preloop.gms
> +*' However, when FAO yields are significantly higher than given by the cellular yield inputs,
done!

2021-06-01 09:52 UTC, k4rst3ns commented on modules/14_yields/managementcalib_aug19/preloop.gms
> +*' on the setting 's14_limit_calib' and than hold constant for all other time steps.
thanks!

2021-06-01 10:33 UTC, k4rst3ns commented on modules/14_yields/managementcalib_aug19/preloop.gms
> +*' cellular yields comming from crop models like LPJmL ('f14_yields').
changed to i14_modeled_yields_hist and i14_fao_yields_hist

2021-06-01 10:45 UTC, k4rst3ns commented on config/default.cfg
> +# * (c30_rotation_constrains): switch for rotational constrains: on, off
yes!!!

2021-06-01 12:18 UTC, tscheypidi requested changes

2021-06-01 12:18 UTC, tscheypidi commented on modules/14_yields/managementcalib_aug19/not_used.txt
> +name,type,reason
please do not add empty not_used.txt files

2021-06-01 12:18 UTC, tscheypidi commented on modules/20_processing/substitution_may21/not_used.txt
> +name,type,reason
pleas remove empty not_used.txt

2021-06-01 12:18 UTC, tscheypidi commented on modules/20_processing/substitution_may21/realization.gms
> +*' The realization substitution_may21 excludes the calibration factors that are used in substitution_dec18 in order to reduce the substitution of oils by other oils.
besides the lack of detail on should always avoid to have the name of the realization in the text as it is on one hand redundand and on the other hand might change over time...renaming the realization without renaming it here would lead to an inconsistent documentation. "This realization [...]" should work here.

2021-06-01 12:18 UTC, tscheypidi commented on modules/30_crop/endo_apr21/preloop.gms
> +pm_croparea_start(j,kcr) = sum(w, fm_croparea("y1995",j,w,kcr));
as you use fm_croparea now as interface please convert pm_croparea_start to an internal parameter and use fm_croparea instead in all instances where it is used, otherwise it will be too confusing to have two separate interfaces for more or less the same information

2021-06-01 12:18 UTC, tscheypidi commented on scripts/calibration/calc_calib.R
> +  y_ini <- prep(readGDX(gdx_file,"i14_yields","i14_yields_calib"))
do you mean `readGDX(...., format = "first_found", react = "silent")` here? I guess how it is written it would return a list of magclass objects, if both parameters exist and otherwise send warnings if one of them is missing

2021-06-01 12:25 UTC, k4rst3ns commented on scripts/calibration/calc_calib.R
> +  y_ini <- prep(readGDX(gdx_file,"i14_yields","i14_yields_calib"))
only the one or the other should exists, but we can change this to your request as well, I guess.

2021-06-01 19:14 UTC, k4rst3ns commented on .github/workflows/test-code.yaml
> -
Sorry somebody deleted inbetween and it was not restored during the merge :(
Should be back now.

2021-06-01 19:16 UTC, k4rst3ns commented on modules/14_yields/managementcalib_aug19/not_used.txt
> +name,type,reason
seems they were added while updating the header ???

2021-06-01 19:18 UTC, k4rst3ns commented on modules/14_yields/managementcalib_aug19/not_used.txt
> +name,type,reason
Could be that there are more empty not_used (just found another in the other processing realization).
Maybe the insert_header function need a fix.

2021-06-01 19:21 UTC, k4rst3ns commented on modules/14_yields/module.gms
> +*' Anne Biewald, Kristine Karstens
seems fine. Only issue at  cluster was, that ö could not be displayed correctly.

2021-06-01 19:49 UTC, k4rst3ns commented on scripts/calibration/calc_calib.R
> +  y_ini <- prep(readGDX(gdx_file,"i14_yields","i14_yields_calib"))
changed!

2021-06-01 20:43 UTC, k4rst3ns commented on modules/30_crop/endo_apr21/preloop.gms
> +pm_croparea_start(j,kcr) = sum(w, fm_croparea("y1995",j,w,kcr));
Was some work, hopefully I did not introduced any bugs.

2021-06-01 22:05 UTC, tscheypidi approved these changes
good to go from my side

2021-06-02 09:04 UTC, merged