Remove lower bound on TC in historic time steps + lower land conversion costs for forestry + Bugfix BII
magpiemodel/magpie pull request #276
Opened 2021-05-10 07:42 UTC by flohump

## :bird: Purpose of this PR :bird:

- Remove lower bound on TC in historic time steps for improved near-term cropland, TAU and CO2 emission trends
- lower land conversion costs for forestry (1000 $/ha). High land conversion costs (8000 $/ha) are only needed for cropland and pasture to maintain a balance between expansion and intensification. High land conversion costs for forestry land prohibit afforestation. Lower land conversion costs for forestry increase afforestation in Policy runs but do not change timber plantation establishment.
- Bugfix BII: "ac0" added to set ac_young, which is needed in the biodiversity module for pricing biodiversity loss and BII coefficients now correspond to the choice of growth curve
Results: https://1drv.ms/p/s!AlN2Seu8OCz8hJRPNljEb1sVbRPBeA
Additional results can be added on request.

## :wrench: Checklist for PR creator :wrench:

- [ ] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : 0.48 h
  * This PR's default :  0.44 h

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The new code doesn't contain declared but unused parameters or variables.
- [ ] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2021-05-10 09:13 UTC, tscheypidi requested changes
- Please rename/reformulate your TC modifications as the current name and description is a bit misleading
- please also add the new switch to the config file
- if you plan to change the default behavior and abandon the historic tau development this probably requires more discussions and would make it a "high risk" PR

2021-05-10 09:13 UTC, tscheypidi commented on modules/13_tc/endo_jun18/input.gms
> + s13_tau_hist_lower_bound	logical switch for setting a lower bound on TAU in historic time steps (0=off 1=on) / 0 /
In addition, this switch should also show up in the config then. Do you plan to change the default here (not taking historical values in to account anymore)?

2021-05-10 09:13 UTC, tscheypidi commented on modules/32_forestry/dynamic_feb21/equations.gms
> +          (fm_bii_coeff("secd_young",potnatveg)*(1-s32_aff_plantation) + fm_bii_coeff("timber",potnatveg)*(s32_aff_plantation));
This is quite some repetitive writing. Isn't there a better formulation possible, e.g. via a mapping set rather than writing 2 times the same for ac_mature and ac_young?

2021-05-10 09:13 UTC, tscheypidi commented on modules/32_forestry/dynamic_feb21/equations.gms
> +
same as above....are the repeated terms the same as above? Perhaps calculate them first in a separate equations and use them afterwards in these two equations?

2021-05-10 09:13 UTC, tscheypidi commented on modules/39_landconversion/global_static_aug18/input.gms
>  ;
I believe this change in settings requires the PR to be tagged as "medium risk" as it will have probably some visible effects on the dynamics

2021-05-10 15:09 UTC, flohump commented on modules/13_tc/endo_jun18/input.gms
> + s13_tau_hist_lower_bound	logical switch for setting a lower bound on TAU in historic time steps (0=off 1=on) / 0 /
renamed to s13_ignore_tau_historical
Do we really need this switch in the config? It can be changed in a start script, if needed by expericend users.

2021-05-10 15:09 UTC, flohump commented on modules/32_forestry/dynamic_feb21/equations.gms
> +          (fm_bii_coeff("secd_young",potnatveg)*(1-s32_aff_plantation) + fm_bii_coeff("timber",potnatveg)*(s32_aff_plantation));
I revised these equations. Please check.

2021-05-10 15:09 UTC, flohump commented on modules/32_forestry/dynamic_feb21/equations.gms
> +
I revised these equations. Please check.

2021-05-10 15:52 UTC, pvjeetze reviewed
Overall fine, thanks for fixing the biodiversity module!

2021-05-10 15:52 UTC, pvjeetze commented on modules/44_biodiversity/bv_btc_mar21/sets.gms
> +	bii_secd(bii_class44) bii coefficent land cover classes secondary vegetation
First impression is that it becomes a little harder to read initially, with this additional set. But this may be very personal and the code may get pretty long otherwise. Just to highlight this. Maybe clearer (but longer names) could help?

2021-05-10 16:51 UTC, tscheypidi commented on modules/13_tc/endo_jun18/input.gms
> + s13_tau_hist_lower_bound	logical switch for setting a lower bound on TAU in historic time steps (0=off 1=on) / 0 /
my understanding was that you introduced that scalar to be able to change the setting...if that was the intention than it should be part of the config.
If your intention was just to ignore historic tau values in all future simulations the historic values should be removed from the realization alltogether...however, in the latter case this is a significant modification and should be discussed as for all other values we fix the model to historic values. Excluding tau values from that rule would mean a paradigm shift

2021-05-11 16:59 UTC, flohump commented on modules/44_biodiversity/bv_btc_mar21/sets.gms
> +	bii_secd(bii_class44) bii coefficent land cover classes secondary vegetation
I could rename "bii_secd" to "bii_class44_secd". But this would imply renaming "ac_to_bii_secd(ac,bii_secd)" to "ac_to_ bii_class44_secd(ac, bii_class44_secd)", which would also increase the length of the code in equations.gms. Maybe we just call it "bii_ac"?

2021-05-11 17:14 UTC, flohump commented on modules/13_tc/endo_jun18/input.gms
> + s13_tau_hist_lower_bound	logical switch for setting a lower bound on TAU in historic time steps (0=off 1=on) / 0 /
I disagree here. First, we have other examples of switches which exist in an input.gms file but are not part of the config file. My understanding is that this serves the gaol of not overloading the default.cfg file with too many switches. However, I'm fine with adding s13_ignore_tau_historical to the default.cfg.
Second, and this is more important, we don't fix or impose a lower bound on cropland in the historic period. Having a lower bound only for TAU is somewhat unbalanced from my perspective, and partly explains why our near-term dynamics of cropland and CO2 emissions slightly mismatch with observed data. Setting a lower bound or fixing a variable for historic time steps is rather an exception so far. We fix many parameter values to make sure that scenarios don't diverge before 2020. 
I now created additional runs based on the current develop and the branch to be merged to facilitate a structured, efficient and transparent discussion.
Results can be found here: https://1drv.ms/p/s!AlN2Seu8OCz8hJRPNljEb1sVbRPBeA

2021-05-11 17:37 UTC, pvjeetze commented on modules/44_biodiversity/bv_btc_mar21/sets.gms
> +	bii_secd(bii_class44) bii coefficent land cover classes secondary vegetation
Looks good, I think. For the second one maybe the other way around `ac_bii`?

2021-05-11 17:54 UTC, pvjeetze commented on modules/44_biodiversity/bv_btc_mar21/sets.gms
> +	bii_secd(bii_class44) bii coefficent land cover classes secondary vegetation
no excuse me. `bii_secd` -> `bii_class44_secd` and `ac_to_bii_secd` -> `ac_bii`

2021-05-13 12:19 UTC, pvjeetze approved these changes
Thanks Florian for the updates! I've looked at them once more and all is fine.

2021-05-13 13:54 UTC, weindl approved these changes
Technically, the modifications look good. The comments on NPI/NDC afforestation are suggestions, and do not preclude a merge of the PR.

2021-05-13 13:54 UTC, weindl commented on modules/32_forestry/dynamic_feb21/preloop.gms
> +** Update c-density for timber plantations based on calibration factor to match FAO growing stocks
Just to be sure:
While timber plantation uses the FAO-calibrated carbon density (pm_carbon_density_ac_forestry(t_all,j,ac,"vegc") ), carbon-price induced afforestation uses the uncalibrated carbon density (p32_c_density_ac_fast_forestry(t_all,j,ac) ), right?

This allows afforestation to follow the growth curves towards LPJmL natural vegetation carbon density, without being inconsistent with the LPJmL estimates at the mature level.

2021-05-13 13:54 UTC, weindl commented on modules/32_forestry/dynamic_feb21/preloop.gms
> +p32_bii_coeff("ndc",bii_class_secd,potnatveg) = fm_bii_coeff(bii_class_secd,potnatveg);
Would it make sense to also allow for the application of the switch "s32_aff_bii_coeff" onto NPI/NDC afforestation? Also here, afforestation policies could be implemented in different ways, either in a more plantation like manner with fast growing species or using only native species, with different implications for biodiversity and thus the choice of bii coefficient.

2021-05-13 13:54 UTC, weindl commented on modules/32_forestry/dynamic_feb21/presolve.gms
>  *' NDC carbon densities are natveg carbon densities.
see comment on bii coefficient in the NPI/NDC context above: maybe consider also here the possibility to select between plantation and natveg growth curves?

2021-05-13 13:54 UTC, weindl commented on modules/32_forestry/dynamic_feb21/preloop.gms
> +** Update c-density for timber plantations based on calibration factor to match FAO growing stocks
I checked in modules/32_forestry/dynamic_feb21/presolve.gms the application of the carbon density parameters. All looks fine.

2021-05-13 19:13 UTC, abhimishr commented
Also seems fine to me. As we need to finish the checklist part, @pvjeetze or @weindl would you like to do it? if not I can also do it. Just indicate this here. MAgPIE side of review seems good to go and @tscheypidi will handle the RSE side of review.

2021-05-13 19:15 UTC, abhimishr commented
Also tagging @mishkos here. The cost validation taskforce indicated about timber production costs in non-rimber production runs for historical period. Would it be okay if I fix it in the post-processing side?

2021-05-14 05:40 UTC, flohump commented on modules/32_forestry/dynamic_feb21/preloop.gms
> +** Update c-density for timber plantations based on calibration factor to match FAO growing stocks
> Just to be sure:
> While timber plantation uses the FAO-calibrated carbon density (pm_carbon_density_ac_forestry(t_all,j,ac,"vegc") ), carbon-price induced afforestation uses the uncalibrated carbon density (p32_c_density_ac_fast_forestry(t_all,j,ac) ), right?
Yes, I confirm. That's how it is intended. I discussed this @abhimish 
> 
> This allows afforestation to follow the growth curves towards LPJmL natural vegetation carbon density, without being inconsistent with the LPJmL estimates at the mature level.

2021-05-14 05:46 UTC, flohump commented on modules/32_forestry/dynamic_feb21/preloop.gms
> +p32_bii_coeff("ndc",bii_class_secd,potnatveg) = fm_bii_coeff(bii_class_secd,potnatveg);
Sure, this could be added. We would need 2 more switches for that like s32_ndc_growth_curve and  s32_ndc_bii_coeff to allow for different assumptions with respect to ndc and co2 price driven afforestation. @mishkos What do you think?Does it make sense to have these additional switches?

2021-05-14 05:48 UTC, flohump commented on modules/32_forestry/dynamic_feb21/presolve.gms
>  *' NDC carbon densities are natveg carbon densities.
This I discussed with @abhimishr . We agreed that it does not make sense to assume natveg growth curves for timber plantations.

2021-05-14 07:39 UTC, mishkos approved these changes
Approving the changes that are correcting the cases of NPI/NDC afforestation infeasibility

2021-05-14 07:39 UTC, mishkos commented on modules/32_forestry/dynamic_feb21/presolve.gms
> +** END ndc **
This looks good to me. The change doesn't affect the way how npi/ndc aff policy is established in each cell. The code is simplified.

2021-05-14 07:39 UTC, mishkos commented on modules/32_forestry/dynamic_feb21/preloop.gms
> +p32_bii_coeff("ndc",bii_class_secd,potnatveg) = fm_bii_coeff(bii_class_secd,potnatveg);
While it does make sense to differentiate what kind of forests are established under npi/ndc policies, the national documents don't specify this at all. Therefore I suggest for the time being to stick to the natveg growth curves for npi/ndc aff pol.

2021-05-14 07:39 UTC, mishkos commented on modules/32_forestry/dynamic_feb21/presolve.gms
>  *' NDC carbon densities are natveg carbon densities.
as answered above, I suggest to keep natveg growth curves for the npi/ndc aff policy.

2021-05-14 08:22 UTC, abhimishr commented on modules/32_forestry/dynamic_feb21/preloop.gms
> +p32_bii_coeff("ndc",bii_class_secd,potnatveg) = fm_bii_coeff(bii_class_secd,potnatveg);
NPI/NDC afforestation still uses natveg growth. We only now provide a possibility where CO2 price induced afforestation can be selected to grow with a plantation growth curved. We have three forestry categories, `plant` which is timber production plantations, `aff` which are co2 priced afforestation and `ndc` which are prescribed afforestation according to NPI/NDC policy. My understanding was that prescribed `NPI/NDC` policy does not merge back into `aff`. 
@flohump this is the correct way to put it right?

2021-05-17 15:15 UTC, pvjeetze commented on CHANGELOG.md
>  - **32_foresty** BII coefficients for CO2 price driven afforestation
Please briefly highlight new switch for choosing the BII coefficient

2021-05-21 08:10 UTC, abhimishr commented
@tscheypidi would you like to request more changes? I'll re-request your review here. MAgPIE side of review seems good to go.

2021-05-21 09:03 UTC, tscheypidi commented
@abhimishr If i remember correctly, we postponed in our last MAgPIE meeting the decision how to deal with the suggested modification of historic tau treatment and wanted to discuss it again in the next meeting. That is why I haven't given green light yet

2021-05-21 12:46 UTC, flohump commented
> @abhimishr If i remember correctly, we postponed in our last MAgPIE meeting the decision how to deal with the suggested modification of historic tau treatment and wanted to discuss it again in the next meeting. That is why I haven't given green light yet

In cooperation with @k4rst3ns I included additiontal results based on #273 in the results document.
https://1drv.ms/p/s!AlN2Seu8OCz8hJRPNljEb1sVbRPBeA

Ignoring historic TAU patterns has mostly effects on cropland dynamics and CO2 emissions in REF. I would argue that Ignoring historic TAU patterns results in more plausible near-term cropland dynamics and CO2 emissions in REF.

[Resources_Land_Cover_Cropland-20.pdf](https://github.com/magpiemodel/magpie/files/6522537/Resources_Land_Cover_Cropland-20.pdf)

[Emissions_CO2_Land_Land_use_Change-32.pdf](https://github.com/magpiemodel/magpie/files/6522538/Emissions_CO2_Land_Land_use_Change-32.pdf)

2021-05-26 11:06 UTC, tscheypidi approved these changes

2021-05-26 11:09 UTC, merged