nocc2020 switch added
magpiemodel/magpie pull request #277
Opened 2021-05-17 14:16 UTC by emolinab

## :bird: Purpose of this PR :bird:

- A new option for the cc/nocc scenarios switch was added. Specifically, nocc2020 uses historical/variable values in parameters affected by climate change up to 2020. After 2020, values stay constant for the rest of the run's time horizon.

## :wrench: Checklist for PR creator :wrench:

- [x] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [x] Providing additional information based on PR label
Minor changes in scenario_config.csv, default.cgf, and several realizations.

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [x] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : 28 mins
  * This PR's default :  29 mins
  
![image](https://user-images.githubusercontent.com/55435245/118500703-4e969b80-b728-11eb-9ab7-2dce51af51ba.png)

- [x] Added changes to `CHANGELOG.md`
- [x] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [x] No hard coded numbers and cluster/country/region names.
- [x] The new code doesn't contain declared but unused parameters or variables.
- [x] Where relevant, In-code comments added including documentation comments.
- [x] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [Not needed] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible). 
- [x] Self-review of my own code.
- [Not needed] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2021-05-17 19:18 UTC, tscheypidi requested changes
Please check whether the solution via dollar condition as suggested would work too.

2021-05-17 19:18 UTC, tscheypidi commented on core/sets.gms
>  ;
I believe this set is not needed and a dollar condition could be used instead.

2021-05-17 19:18 UTC, tscheypidi commented on modules/14_yields/dynamic_aug18/input.gms
> +$if "%c14_yields_scenario%" == "nocc2020" f14_yields(t_nocc2020,j,kve,w) = f14_yields("y2020",j,kve,w);
I believe a dollar condition should be a solution here setting the values as wanted. Haven't tested the suggestion below but something like that should be it:

```suggestion
$if "%c14_yields_scenario%" == "nocc2020" f14_yields(t_all,j,kve,w)$(ord(t_all) > ord("y2020")) = f14_yields("y2020",j,kve,w);
```

2021-05-17 19:19 UTC, tscheypidi commented
is it now low or medium risk? It can't be both as suggested by the labels

2021-05-18 06:09 UTC, emolinab commented on core/sets.gms
>  ;
> is it now low or medium risk? It can't be both as suggested by the labels

> My bad.  I meant low risk.

2021-05-18 06:10 UTC, emolinab commented on modules/14_yields/dynamic_aug18/input.gms
> +$if "%c14_yields_scenario%" == "nocc2020" f14_yields(t_nocc2020,j,kve,w) = f14_yields("y2020",j,kve,w);
Perfect, I'll work in the dollar sign approach.

2021-05-18 09:00 UTC, tscheypidi approved these changes
looks good!

2021-05-18 14:19 UTC, abhimishr requested changes
Seems fine in general. I propose the following change to make it more consistent : 

1. Florian introduced a scalar `sm_fix_ssp2` to keep our historical behavior consistent, maybe you can use the same switch here? By replacing your hard-coded 2020 instances with `sm_fix_SSP2`. It helps in two ways:
* Everytime we  update `sm_fix_SSP2` the same is reflected in in you "holding constant after xx year" philosophy
* Avoids hard-coding a number in `$` checks 

2. Additionally, you can rename `nocc2020` to `histcc` instead

2021-05-19 12:01 UTC, abhimishr approved these changes
good to go 🚀

2021-05-19 12:52 UTC, merged