F duallayer
magpiemodel/magpie pull request #282
Opened 2021-06-02 13:07 UTC by tscheypidi

## :bird: Purpose of this PR :bird:

**DRAFT** This PR add two region-layer support to MAgPIE

## :wrench: Checklist for PR creator :wrench:

- [ ] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The new code doesn't contain declared but unused parameters or variables.
- [ ] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2021-07-06 12:06 UTC, FelicitasBeier reviewed
Generally looks good to me.

One thing I did not see (maybe I overlooked it?): where are the supra-regions set? Is this manually done by the user in the default config? If yes, I think this has to be added. Or are they hard-set somewhere.

Minor comment: Maybe in the comments of the changed variables etc. write "(supra-)regions" rather than "regions"?

2021-07-06 12:06 UTC, FelicitasBeier commented on modules/21_trade/exo/equations.gms
> + q21_cost_trade(h2).. sum(supreg(h2,i2),vm_cost_trade(i2)) =e=
I feel that there should be a warning somewhere in postprocessing / output scripts if this value does take a value that is not 0

2021-07-06 12:08 UTC, FelicitasBeier commented
You only provided results for the comparison of default run with and the equivalent where i=h. Do you also have a sample run where the regions were set separately for i and h? (to see if this also gives the expected model behavior)

2021-07-06 12:40 UTC, mishkos commented
> You only provided results for the comparison of default run with and the equivalent where i=h. Do you also have a sample run where the regions were set separately for i and h? (to see if this also gives the expected model behavior)

We thought that for this PR if would suffice to test for the default regional definition that has 1-1 mapping with superregional level. Like this, the concept of a duallayer would be invariant to the standard usage and development of the model. I do have runs with non-1-1 mapping, that operates on the EU as a super region for five different regions, but this is something that is still in the development and the results need further analysis. If you still think it's relevant for this PR, I can include some plots to demonstrate.

2021-07-06 14:26 UTC, tscheypidi commented
FYI: I just removed the start_scripts-function `start_reportrun`. This is not related to the other changes but I just found out in another context that this function is not in use anymore for quite a while it would probably not work anymore in its current form

2021-07-06 15:10 UTC, k4rst3ns requested changes
I just had a first look on things and guess the most important would be checking if you changed everything correctly (especially preloop of managementcalib). 
The second request would be for additional runs:
* (a) once the calibration run (just to see that the impacts is also low there)
* (b) also for a lpjml_addon version (as this will be default super soon) and we lately had issues solving this in a reasonable time as we might reach some critical *size* of the model. As this changes also increase complexity, just checking once would be very nice.

2021-07-06 15:10 UTC, k4rst3ns commented on scripts/start_functions.R
> -}
It seems gms version would have to be updated for running locally (since gms::writeSets was freshly moved there?
You might want to add this to the changelog (like the new dependency to the gms package version).

2021-07-06 17:48 UTC, tscheypidi commented on modules/13_tc/endo_jun18/declarations.gms
> + i13_tc_factor(t)            Regression factor (USD05PPP per ha)
this is intended. the regional differentiation of `i13_tc_factor` was exclusively used in a non-working scenario setup which I removed

2021-07-06 17:52 UTC, tscheypidi commented on modules/21_trade/exo/equations.gms
> + q21_cost_trade(h2).. sum(supreg(h2,i2),vm_cost_trade(i2)) =e=
Conceptually, I agree. But I have no clue where to put it so that it will be seen.

2021-07-06 17:54 UTC, tscheypidi commented on modules/60_bioenergy/1stgen_priced_dec18/sets.gms
> -*THERE YOU CAN ALSO FIND ADDITIONAL INFORMATION
I had to update/generalize the R-script creating this part. As the generalized script is now used broader I could not be that specific anymore in the comment

2021-07-06 17:55 UTC, tscheypidi commented on modules/80_optimization/nlp_par/solve.gms
> +      display h2;
@flohump could have a look at it as he is the mastermind behind the parallel realization

2021-07-06 20:27 UTC, flohump commented on modules/80_optimization/nlp_par/solve.gms
> +      display h2;
Makes sense to me. We are in a loop over h. h2 is the current superregion. Then all regions i2 and cells j2 that belong to the superregion are activated in the dynamic sets.

2021-07-07 08:52 UTC, tscheypidi commented on main.gms
>  *'  * Always try to access model outputs through the corresponding magpie package instead of accessing them directly with readGDX. It cannot be guaranteed that your script will work in the future if
Good point. I reverted the changes in main.gms

2021-07-07 10:44 UTC, tscheypidi commented on modules/21_trade/exo/declarations.gms
> + v21_manna_from_heaven(h,kall)                  Last resort resource for otherwise infeasble trade balance constraints (mio. tDM per yr)
fixed

2021-07-07 10:46 UTC, tscheypidi commented on modules/21_trade/free_apr16/input.gms
> +table f21_self_suff(t_all,h,kall) Regional self-sufficiency rates (1)
done

2021-07-07 10:47 UTC, tscheypidi commented on modules/21_trade/off/declarations.gms
> + q21_notrade(h,kall)        Regional production constraint of non-tradable commodities (mio. tDM per yr)
done

2021-07-07 10:47 UTC, tscheypidi commented on modules/21_trade/exo/equations.gms
> + q21_cost_trade(h2).. sum(supreg(h2,i2),vm_cost_trade(i2)) =e=
created function `magpie4::outputCheck` and added an output check script to the output scripts checking for these problems

2021-07-07 10:51 UTC, tscheypidi commented on scripts/start_functions.R
> -}
good point...I added now version requirement information as comments to the README.md

2021-07-07 11:57 UTC, tscheypidi commented on modules/14_yields/dynamic_aug18/preloop.gms
> +i14_yields(t,j,"betr",w) = i14_yields(t,j,"betr",w)*sum((supreg(h,i),cell(i,j)),fm_tau1995(h))/smax(h,fm_tau1995(h));
good catch. I fixed that in management calib and biocorrect.

2021-07-07 11:57 UTC, tscheypidi commented on modules/13_tc/exo/presolve.gms
>                       * (1+pm_interest(t,i))**15;
done

2021-07-07 13:04 UTC, FelicitasBeier reviewed
seems good overall

Please decide whether to use "superregional" everywhere in the description where h is used now instead of i.
I'm aware these are quite some places where the description needs to be adjusted, but right now it's only in two places and I would prefer for it to be consistent.

2021-07-07 13:16 UTC, tscheypidi commented on modules/21_trade/selfsuff_reduced/declarations.gms
> + v21_excess_prod(h,k_trade)              Regional excess production (mio. tDM per yr)
done. Actually, only a few spots were missing as most of the variables/parameters do not specify in their description on which level they act (which also makes sense as it is otherwise clearly visible from the declaration itself). 
I hope that I got now all locations where it was not changed yet

2021-07-07 20:15 UTC, k4rst3ns approved these changes

2021-07-07 20:17 UTC, k4rst3ns commented
I approved now the PR as in my opinion no changes to the code are needed anymore. Still I strongly suggesting once checking feasibility of calib run and lpjml_addon.R.

2021-07-07 20:54 UTC, merged