Peatland from 1995 onwards + country switches for land protection and cropland set aside share
magpiemodel/magpie pull request #283
Opened 2021-06-04 19:14 UTC by flohump

## :bird: Purpose of this PR :bird:

- Peatland from 1995 onwards, was active so far only from 2020 onwards.
- country switches for land protection and cropland set aside share

## :wrench: Checklist for PR creator :wrench:

- [ ] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The new code doesn't contain declared but unused parameters or variables.
- [ ] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2021-06-07 07:28 UTC, FelicitasBeier commented on modules/30_crop/endo_apr21/input.gms
> +  policy_countries30(iso) countries to be affected by ghg policy / ABW,AFG,AGO,AIA,ALA,ALB,AND,ARE,ARG,ARM,
affect by land protection or set-aside land policy, no? (not: ghg policy)

2021-06-07 07:28 UTC, FelicitasBeier commented on modules/30_crop/endo_apr21/preloop.gms
> +p30_region_setaside_shr(t_all,i) = sum(i_to_iso(i,iso), p30_country_dummy(iso) * im_pop_iso(t_all,iso)) / sum(i_to_iso(i,iso), im_pop_iso(t_all,iso));
Does population weight make sense here or would weight by country-area or something like that be better?

2021-06-07 07:28 UTC, FelicitasBeier commented on modules/35_natveg/dynamic_feb21/preloop.gms
> +p35_region_prot_shr(t_all,i) = sum(i_to_iso(i,iso), p35_country_dummy(iso) * im_pop_iso(t_all,iso)) / sum(i_to_iso(i,iso), im_pop_iso(t_all,iso));
same question as above. population weight or better area weight?

2021-06-07 08:01 UTC, tscheypidi requested changes

2021-06-07 08:01 UTC, tscheypidi commented on modules/58_peatland/on/presolve.gms
> +	v58_peatland_man.fx(j,"rewet",land58) = 0;
also here my doubts that this distinction based on sm_fix_SSP2 makes sense

2021-06-07 08:01 UTC, tscheypidi commented on scripts/start/projects/project_LAMACLIMA.R
> +cfg$gms$policy_countries56  <- oecd_countries#oecd_countries #todo
what is this todo comment here?

2021-06-07 08:01 UTC, tscheypidi commented on scripts/start/projects/project_peatland.R
> +# start_run(cfg,codeCheck=FALSE)
there should not be any commented code remaining in a script...if you use these outputs sometimes, use conditionals...otherwise remove the code

2021-06-07 09:33 UTC, flohump commented on modules/30_crop/endo_apr21/input.gms
> +  policy_countries30(iso) countries to be affected by ghg policy / ABW,AFG,AGO,AIA,ALA,ALB,AND,ARE,ARG,ARM,
Will be corrected.

2021-06-07 09:34 UTC, flohump commented on modules/30_crop/endo_apr21/preloop.gms
> +p30_region_setaside_shr(t_all,i) = sum(i_to_iso(i,iso), p30_country_dummy(iso) * im_pop_iso(t_all,iso)) / sum(i_to_iso(i,iso), im_pop_iso(t_all,iso));
True. Makes a lot of sense to me. This holds true both, the country switches for land protection and set a-aside policy. I will change this.

2021-06-07 09:48 UTC, flohump commented on CHANGELOG.md
> +- **35_natveg** Calculation of land protection policies
`Calculation of land protection policies revised and moved from presolve.gms to preloop.gms`

2021-06-07 09:52 UTC, flohump commented on CHANGELOG.md
> +- **58_peatland** Peatland area and GHG emissions are fixed to 2015 levels for the historic period, depending on `sm_fix_SSP2`
Yes. That what is says. "fixed to 2015 levels". The whole point is that in the current develop peatland is only initlized from 2015 onwards, see figures. The improvement of the PR is that peatland area is initlized in 1995, and hold fixed depending on sm_fix_SSP2. I will make this clearer in the changelog.

2021-06-07 09:57 UTC, tscheypidi commented on CHANGELOG.md
> +- **58_peatland** Peatland area and GHG emissions are fixed to 2015 levels for the historic period, depending on `sm_fix_SSP2`
ah sorry..my bad

2021-06-07 09:58 UTC, flohump commented on config/default.cfg
> +# are selected and only s30_set_aside_shr has to be set.
So, you suggest to remove `In default, all countries# are selected and only s30_set_aside_shr has to be set.`?
We have this in other places in the default.cfg as well.

2021-06-07 10:06 UTC, flohump commented on modules/58_peatland/on/preloop.gms
> +
It's quite technical and not necessarily needed to understand the equations, therefore I excluded it.

2021-06-07 10:07 UTC, flohump commented on config/default.cfg
> +# * One-time and recurring costs for peatland degradation (USD05MER per ha)
Will be improved

2021-06-07 10:10 UTC, flohump commented on modules/58_peatland/on/equations.gms
> +	+ ((vm_land(j2,land58)-pcm_land(j2,land58))*p58_scaling_factor(j2))$(sum(ct, m_year(ct))>sm_fix_SSP2);
I use `sm_fix_SSP2` to fix peatland area to 2015 levels until the year provided by `sm_fix_SSP2 `. Do you instead suggest to add a specific switch for this, like `s58_peatland_fix`?

2021-06-07 10:11 UTC, flohump commented on modules/35_natveg/dynamic_feb21/presolve.gms
> +p35_save_other(t,j) = p35_save_natveg(t,j,"other");
I moved the revised calcuation from presolve.gms to preloop.gms (I will add this to the changelog).

2021-06-07 10:14 UTC, flohump commented on modules/35_natveg/dynamic_feb21/presolve.gms
> +p35_save_other(t,j) = p35_save_natveg(t,j,"other");
On p35_save_primforest, p35_save_secdforest and p35_save_other. I was thinking the same. But we use these 3 parameters in the magpie4 R library. Therefore, I kept them.

2021-06-07 10:17 UTC, flohump commented on modules/35_natveg/dynamic_feb21/sets.gms
> +
Sure.

2021-06-07 10:29 UTC, tscheypidi commented on config/default.cfg
> +# are selected and only s30_set_aside_shr has to be set.
yes, my suggestion is to remove it.

2021-06-07 10:33 UTC, flohump commented on scripts/start/projects/project_LAMACLIMA.R
> +cfg$gms$policy_countries56  <- oecd_countries#oecd_countries #todo
Already done ;-)

2021-06-07 10:33 UTC, flohump commented on scripts/start/projects/project_peatland.R
> +# start_run(cfg,codeCheck=FALSE)
Removed

2021-06-07 10:36 UTC, pvjeetze requested changes

2021-06-07 10:36 UTC, pvjeetze commented on modules/41_area_equipped_for_irrigation/endo_apr13/input.gms
> +$setglobal c41_initial_irrigation_area  Siebert
Please revert back to default

2021-06-07 10:36 UTC, pvjeetze commented on modules/42_water_demand/agr_sector_aug13/input.gms
> +$setglobal c42_watdem_scenario  nocc
same as above (and below)

2021-06-07 10:46 UTC, flohump commented on modules/41_area_equipped_for_irrigation/endo_apr13/input.gms
> +$setglobal c41_initial_irrigation_area  Siebert
According to the default.cfg `Siebert` is the default.

2021-06-07 10:47 UTC, flohump commented on modules/14_yields/biocorrect/input.gms
> +$setglobal c14_yields_scenario  nocc
The default for for c14_yields_scenario is `nook`

2021-06-07 10:52 UTC, flohump commented on main.gms
`s58_rewet_cost_onetime` and `s58_rewet_cost_recur` are not new. I would like to keep them for consistency.

2021-06-07 10:52 UTC, flohump commented on modules/30_crop/endo_apr21/input.gms
> +s30_set_aside_shr   		Share of available cropland that is witheld for other land cover types (unitless) / 0 /
I will handle that

2021-06-07 10:55 UTC, flohump commented on modules/41_area_equipped_for_irrigation/endo_apr13/input.gms
> +$setglobal c41_initial_irrigation_area  Siebert
For the work in the preprocessing (iso version of avl_cropland_0.5.mz), I need some support.

2021-06-07 10:55 UTC, flohump commented on modules/42_water_demand/agr_sector_aug13/input.gms
> +$setglobal c42_watdem_scenario  nocc
`nocc` is the default

2021-06-07 11:01 UTC, tscheypidi commented on modules/30_crop/endo_apr21/preloop.gms
> +p30_region_setaside_shr(t_all,i) = sum(i_to_iso(i,iso), p30_country_dummy(iso) * im_pop_iso(t_all,iso)) / sum(i_to_iso(i,iso), im_pop_iso(t_all,iso));
sounds good

2021-06-07 11:03 UTC, tscheypidi commented on modules/35_natveg/dynamic_feb21/presolve.gms
> +p35_save_other(t,j) = p35_save_natveg(t,j,"other");
please simplify and modify magpie4 accordingly

2021-06-07 11:04 UTC, tscheypidi commented on modules/58_peatland/on/equations.gms
> +	+ ((vm_land(j2,land58)-pcm_land(j2,land58))*p58_scaling_factor(j2))$(sum(ct, m_year(ct))>sm_fix_SSP2);
if it is not related to fixing the scenario to SSP2, then yes, definitely

2021-06-10 08:21 UTC, flohump commented on modules/58_peatland/on/equations.gms
> +	+ ((vm_land(j2,land58)-pcm_land(j2,land58))*p58_scaling_factor(j2))$(sum(ct, m_year(ct))>sm_fix_SSP2);
I added `s58_fix_peatland` as replacement for `sm_fix_SSP2`

2021-06-10 08:21 UTC, flohump commented on modules/35_natveg/dynamic_feb21/presolve.gms
> +p35_save_other(t,j) = p35_save_natveg(t,j,"other");
Done in GAMS + magpie4 R

2021-06-10 08:23 UTC, flohump commented on modules/58_peatland/on/postsolve.gms
>  pc58_peatland_intact(j) = v58_peatland_intact.l(j);
`s58_fix_peatland`

2021-06-10 08:23 UTC, flohump commented on modules/58_peatland/on/presolve.gms
> +	v58_peatland_man.fx(j,"rewet",land58) = 0;
`s58_fix_peatland`

2021-06-10 09:40 UTC, tscheypidi commented on CHANGELOG.md
> +- **58_peatland** Peatland area and GHG emissions are fixed to 2015 levels for the historic period, depending on `sm_fix_SSP2`
`sm_fix_SSP2` needs to be replaced here with `s58_fix_peatland` right?

2021-06-10 09:40 UTC, tscheypidi commented on modules/58_peatland/on/postsolve.gms
>  pc58_peatland_intact(j) = v58_peatland_intact.l(j);
please also add `s58_fix_peatland` to the default.cfg so that it can be set

2021-06-10 11:05 UTC, tscheypidi approved these changes
all my remarks have been addressed

2021-06-10 14:02 UTC, flohump commented on modules/30_crop/endo_apr21/preloop.gms
> +p30_region_setaside_shr(t_all,i) = sum(i_to_iso(i,iso), p30_country_dummy(iso) * im_pop_iso(t_all,iso)) / sum(i_to_iso(i,iso), im_pop_iso(t_all,iso));
iso level area is now used as weight for aggregation

2021-06-10 14:02 UTC, flohump commented on modules/35_natveg/dynamic_feb21/preloop.gms
> +p35_region_prot_shr(t_all,i) = sum(i_to_iso(i,iso), p35_country_dummy(iso) * im_pop_iso(t_all,iso)) / sum(i_to_iso(i,iso), im_pop_iso(t_all,iso));
iso level area is now used as weight for aggregation

2021-06-10 14:03 UTC, flohump commented on modules/41_area_equipped_for_irrigation/endo_apr13/input.gms
> +$setglobal c41_initial_irrigation_area  Siebert
Big thanks to @pvjeetze for preparing the iso level data!

2021-06-11 07:32 UTC, pvjeetze approved these changes
Overall fine. Just hinting at another aspect/limitation that should be addressed at a later stage: Right now, if a country set aside policy is chosen, results are only meaningful when analysed at the cluster level. Further work will be needed to also adjust the disaggregation procedure so that set aside shares are correctly distributed spatially at the 0.5 degree level.

2021-06-11 07:32 UTC, pvjeetze commented on modules/35_natveg/dynamic_feb21/preloop.gms
>  * Countries are weighted by their population size.
total land area

2021-06-11 07:44 UTC, k4rst3ns commented on config/default.cfg
> +         "patch_land_iso.tgz")
How this will be solved for the lpjml_addon script?
Please also update input data for it (increase revision number or also adding this patch).

2021-06-11 07:46 UTC, FelicitasBeier reviewed
some minor adjustments in comments necessary

2021-06-11 07:46 UTC, FelicitasBeier commented on modules/30_crop/endo_apr21/preloop.gms
> +* Countries are weighted by their population size.
comment needs to be changed: they are weighted by cropland area

2021-06-11 07:46 UTC, FelicitasBeier commented on modules/35_natveg/dynamic_feb21/declarations.gms
> + i35_secdforest(j,ac)							  Inital secdforest (mio. ha)
typo: inital -> initial

2021-06-11 07:46 UTC, FelicitasBeier commented on modules/35_natveg/dynamic_feb21/input.gms
> +  policy_countries35(iso) countries to be affected by ghg policy / ABW,AFG,AGO,AIA,ALA,ALB,AND,ARE,ARG,ARM,
typo: not ghg but land policy, right?

2021-06-11 07:46 UTC, FelicitasBeier commented on modules/35_natveg/dynamic_feb21/preloop.gms
> +* Countries are weighted by their population size.
adjust comment: no longer population size weight but land weight

2021-06-11 08:09 UTC, flohump commented on config/default.cfg
> +         "patch_land_iso.tgz")
https://github.com/flohump/magpie/blob/f_peatland5/scripts/start/extra/lpjml_addon.R
The patch is not needed for 4.61 because 4.61 includes the 2 addtional files, which are in patch_land_iso.tgz.

2021-06-11 08:12 UTC, flohump commented on config/default.cfg
> +         "patch_land_iso.tgz")
I also did sucessful test susing the script
https://github.com/flohump/magpie/blob/f_peatland5/scripts/start/projects/project_LAMACLIMA.R
which uses lpjml_addon.

2021-06-11 08:13 UTC, k4rst3ns commented on config/default.cfg
> +         "patch_land_iso.tgz")
ahh sorry, I didn't found the changes in the lpjml_addon script at first. thanks and all good (I just have to hurry up using my old preprocessing for testing before your PR enters the develop).

2021-06-11 08:14 UTC, FelicitasBeier approved these changes
seems good to me

2021-06-11 08:58 UTC, k4rst3ns approved these changes

2021-06-11 09:03 UTC, merged