Addition of depreciation rate in irrigation area expansion (41_area_equipped_for_irrigation)
magpiemodel/magpie pull request #288
Opened 2021-07-01 05:47 UTC by vartika271987

## :bird: Purpose of this PR :bird:

- This PR adds a switch for a depreciation rate to be accounted for in 41_area_equipped_for_irrigation. A default rate of 0.05 is set. 

## :wrench: Checklist for PR creator :wrench:

- [ X] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

Equation changed in 41_area_equipped_for_irrigation, switch added in default.cfg, equation change in post_solve

![image](https://user-images.githubusercontent.com/51452385/124071643-4b980600-da5d-11eb-8990-7d2005d39408.png)

- [X ] Providing additional information based on PR label

* High risk
  * Default run from the current develop branch -Yes
  * Default run based on the current version of the fork from which PR is made - Yes

- [X ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default: 32.85 mins
  * This PR's default:  35.77 mins

- [x ] Added changes to `CHANGELOG.md`
- [ x] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [x ] No hard coded numbers and cluster/country/region names.
- [ x] The new code doesn't contain declared but unused parameters or variables.
- [ x] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post-processing of model output (ideally backward compatible).
- [ x] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2021-07-01 07:57 UTC, tscheypidi commented
Please add labels to your PR and update the in-code documentation for the equation you modified.
Are we sure that the new implementation is superior to the current one? Just judging on the validation figure I got the impression that the current model setup behaves slightly better...

2021-07-01 09:30 UTC, tscheypidi approved these changes
good to go from RSE side, but a content reviewer from landuse side should please review whether the new model behavior is acceptable/preferable

2021-07-01 10:07 UTC, bodirsky requested changes

2021-07-01 10:07 UTC, bodirsky commented on modules/41_area_equipped_for_irrigation/endo_apr13/input.gms
> +s41_AEI_depreciation Depreciation rate in capital value of irrigation infrastructure / 0.1 /
different depreciation rate than in the config.cfg. maybe harmonize (and rather use 0.05)

2021-07-01 10:07 UTC, bodirsky commented on modules/41_area_equipped_for_irrigation/endo_apr13/postsolve.gms
> +pc41_AEI_start(j)=v41_AEI.l(j) * (1 - s41_AEI_depreciation);
timestep length is not included here, but should. The longer a timestep, the larger the depreciation. What you included here is in fact a 1% depreciation for a 5 year timestep, and a 0.5% depreciation rate for a 10yr timestep. right?

I would probably also use a parameter with time-dimension (not pc_) so that you can see and check the changes in postprocessing

2021-07-01 10:17 UTC, vartika271987 commented on modules/41_area_equipped_for_irrigation/endo_apr13/input.gms
> +s41_AEI_depreciation Depreciation rate in capital value of irrigation infrastructure / 0.1 /
This got replaced in the test runs. Default is 0.05 and will be set to that.

2021-07-01 10:19 UTC, vartika271987 commented on modules/41_area_equipped_for_irrigation/endo_apr13/postsolve.gms
> +pc41_AEI_start(j)=v41_AEI.l(j) * (1 - s41_AEI_depreciation);
Right - I had added it in previous versions but missed here. Added now.

2021-07-01 12:28 UTC, vartika271987 commented
Revised results after adding timestep-length- not much change.
![image](https://user-images.githubusercontent.com/51452385/124124340-f0363a00-da95-11eb-9dbe-837914071fcd.png)

2021-07-02 07:24 UTC, FelicitasBeier commented on config/default.cfg
> +cfg$gms$s41_AEI_depreciation <- 0.05                       # def = 0.05
Maybe we should discuss whether we want the depreciation rate activated by default. This is what everybody will use for their runs and I'm not sure that the patterns we see for the future are realistic. Maybe we can do some more testing before (i.e. already merge the functionality, but leave the default at 0)

2021-07-02 07:24 UTC, FelicitasBeier commented on modules/41_area_equipped_for_irrigation/endo_apr13/equations.gms
> +	sum(ct,pm_interest(ct,i2)/(1+pm_interest(ct,i2)))
In postsolve, depreciated part of AEI investment is "(1 - s41_AEI_depreciation)**(m_timestep_length)". Shouldn't this also be the part that is considered here in the cost section?

2021-07-02 09:28 UTC, abhimishr commented
1. As this is tagged as high risk maybe we need a whole array of general model behavior indicators - all land uses, food prices etc. - also seen in the checklist - to avoid a review going through even without all checks have been completed.

At the moment we have quite many changes happening around the model and the result requirements for the PR template were put in place to avoid situations where we see a strange model behavior at some point but due to a lot many changes happening around the same time it gets buried in the details and a possible bug difficult to diagnose.

2. There appears to be space between the `x` and `]` which is not parsed as a check mark and will also not appear in the PR checklist count. Getting rid of the space will solve this.

2021-07-02 09:42 UTC, vartika271987 commented on modules/41_area_equipped_for_irrigation/endo_apr13/equations.gms
> +	sum(ct,pm_interest(ct,i2)/(1+pm_interest(ct,i2)))
Valid point. Tagging @emolinab here as this would affect the equations here and in sticky

2021-07-02 09:43 UTC, vartika271987 commented on config/default.cfg
> +cfg$gms$s41_AEI_depreciation <- 0.05                       # def = 0.05
I agree. Keeping the default to 0 for now and continuing testing is a good idea.

2021-07-02 09:56 UTC, emolinab commented on modules/41_area_equipped_for_irrigation/endo_apr13/equations.gms
> +	sum(ct,pm_interest(ct,i2)/(1+pm_interest(ct,i2)))
Hey! The costs of the depreciated capital (in sticky) are assumed in the next time step in:  investment =needed capital -existing capital.

2021-07-02 10:00 UTC, vartika271987 commented
> 1. As this is tagged as high risk maybe we need a whole array of general model behavior indicators - all land uses, food prices etc. - also seen in the checklist - to avoid a review going through even without all checks have been completed.
> 
**Agree, but if we follow Feli's suggestion for now, the default remains 0 and it does not change anything in the model. Only when we use it for some analysis in our projects, it will become relevant**

> At the moment we have quite many changes happening around the model and the result requirements for the PR template were put in place to avoid situations where we see a strange model behavior at some point but due to a lot many changes happening around the same time it gets buried in the details and a possible bug difficult to diagnose.
> 
> 1. There appears to be space between the `x` and `]` which is not parsed as a check mark and will also not appear in the PR checklist count. Getting rid of the space will solve this.
**Perfect-will do**

2021-07-08 10:03 UTC, mishkos commented on modules/41_area_equipped_for_irrigation/endo_apr13/equations.gms
> +	sum(ct,pm_interest(ct,i2)/(1+pm_interest(ct,i2)))
We don't need to multiply with the time step length here cause the optimizer needs to see the annual costs of the current time step. These costs are the flows of capital in the current step. In the postsolve, one multiplies the stocks of capital with the time step length, to make sure that the starting point of available capital is correct for the next time step which optimized.

2021-07-08 11:21 UTC, vartika271987 commented on modules/41_area_equipped_for_irrigation/endo_apr13/postsolve.gms
> +pc41_AEI_start(j)=v41_AEI.l(j) * (1 - s41_AEI_depreciation);
@bodirsky I fixed the timestep_length issue here and removed the calculation from post-solve to pre-solve to ensure there is consistency between this realization and sticky. 
A parameter `p41_AEI_start(j)` has already been defined in the pre-solve so this parameter includes the time-dimension.

2021-07-19 05:20 UTC, vartika271987 commented on modules/41_area_equipped_for_irrigation/endo_apr13/postsolve.gms
> +pc41_AEI_start(j)=v41_AEI.l(j) * (1 - s41_AEI_depreciation);
@bodirsky can you confirm if the updated changes are good to go?

2021-07-19 05:21 UTC, vartika271987 commented on modules/41_area_equipped_for_irrigation/endo_apr13/postsolve.gms
> +pc41_AEI_start(j)=v41_AEI.l(j) * (1 - s41_AEI_depreciation);
@bodirsky can you please review if the updated changes are good to go?

2021-07-19 06:50 UTC, FelicitasBeier requested changes

2021-07-19 06:50 UTC, FelicitasBeier commented on config/default.cfg
> +cfg$gms$s41_AEI_depreciation <- 0.05                       # def = 0.05
Still needs to be set to 0 though.

2021-08-19 12:44 UTC, bodirsky approved these changes
my issues have been addressed.

2021-08-19 17:47 UTC, FelicitasBeier approved these changes

2021-08-20 03:15 UTC, merged