Bug fix in the variable costs of sticky
magpiemodel/magpie pull request #304
Opened 2021-08-12 16:05 UTC by emolinab

## :bird: Purpose of this PR :bird:

The variable costs in the sticky realization (dynamic) need to be updated in each time step based on the capital share. Before, it was done only in the first time step so that bug is fixed in this PR. Also, the sticky start script was updated.

## :wrench: Checklist for PR creator :wrench:

- [x] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [x] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : 35 mins
  * This PR's default :  1hour 38 mins
 Note: magpie4 was updated during the run so rds_report failed, and results could not be loaded to the repository. 

- [x] Added changes to `CHANGELOG.md`
- [x] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [x] No hard coded numbers and cluster/country/region names.
- [x] The new code doesn't contain declared but unused parameters or variables.
- [N.A.] Where relevant, In-code comments added including documentation comments.
- [x] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [N.A.] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [x] Self-review of my own code.
- [N.A.] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2021-08-13 07:17 UTC, tscheypidi requested changes
In addition to the two code specific comments two additional requests:

- You indicated that you labelled the PR correctly, but I could not see any labels. Can you please check what went wrong here.
- Can you please elaborate on where this 3 fold increase in runtime comes from? This is quite dramatic and in contrast to it the code changes look rather minimalistic. I don't understand what is happening here.

2021-08-13 07:17 UTC, tscheypidi commented on modules/38_factor_costs/sticky_feb18/declarations.gms
> + p38_capital_need(i,kcr,mobil38)     Capital requirements for farming with tau equal 1 (mio USD05MER)
please make these parameters time depending as they vary over time (instead of overwriting it for each time step). That makes the code more readable and simplifies postprocessing as used values do not need to be recalculated.

2021-08-13 07:17 UTC, tscheypidi commented on modules/38_factor_costs/sticky_feb18/presolve.gms
> +p38_variable_costs(i2,kcr) = f38_fac_req(kcr)  * (1-p38_capital_cost_share(i2)) ;
does `p38_capital_cost_share` vary over time? If so, then please add the time dimension here and for `p38_variable_costs`. If not, then you can probably move that calculation to preloop and call it `i38_variable_costs`

2021-08-13 12:04 UTC, emolinab commented on modules/38_factor_costs/sticky_feb18/presolve.gms
> +p38_variable_costs(i2,kcr) = f38_fac_req(kcr)  * (1-p38_capital_cost_share(i2)) ;
You are right, both change over time, I'll make the modifications.

2021-08-13 12:53 UTC, flohump requested changes
Looks good in general. I have one question for clarification and one small request for code changes.

2021-08-13 12:53 UTC, flohump commented on modules/38_factor_costs/sticky_feb18/equations.gms
> -                              =e= vm_prod_reg(i2,kcr) * i38_variable_costs(i2,kcr) / (1-s38_mi_start)
Why is `s38_mi_start ` no longer needed?

2021-08-13 12:53 UTC, flohump commented on modules/38_factor_costs/sticky_feb18/presolve.gms
> +p38_variable_costs(i2,kcr) = f38_fac_req(kcr)  * (1-p38_capital_cost_share(i2)) ;
please use `i` instead of `i2` in presolve

2021-08-13 12:53 UTC, flohump commented on modules/38_factor_costs/sticky_feb18/presolve.gms
> +p38_variable_costs(i2,t,kcr) = f38_fac_req(kcr)  * (1-p38_capital_cost_share(i2)) ;
please use `i` instead of `i2` in presolve

2021-08-13 14:01 UTC, emolinab commented on modules/38_factor_costs/sticky_feb18/equations.gms
> -                              =e= vm_prod_reg(i2,kcr) * i38_variable_costs(i2,kcr) / (1-s38_mi_start)
This s38_mi_start was initially conceived to be associated with Patrick's work at some point. However, in the meantime, it was not being used, as in the presolve it was a multiplying factor in the calculation of i38_variable_costs(i2,kcr).

2021-08-14 17:17 UTC, emolinab commented on modules/38_factor_costs/sticky_feb18/presolve.gms
> +p38_variable_costs(i2,kcr) = f38_fac_req(kcr)  * (1-p38_capital_cost_share(i2)) ;
* Regarding the labels, I apologize, I thought I made it but probably didn't save it. 
* I had compared the run time with the default develop branch. Now, I updated the run time comparing the develop branch using the sticky realization. As you can see, the difference was only 6 minutes.
* Also, I the CHANGELOG changes have been pushed.

2021-08-14 17:19 UTC, emolinab commented on modules/38_factor_costs/sticky_feb18/presolve.gms
> +p38_variable_costs(i2,t,kcr) = f38_fac_req(kcr)  * (1-p38_capital_cost_share(i2)) ;
Done :)

2021-08-16 06:52 UTC, tscheypidi reviewed
typos

2021-08-16 06:52 UTC, tscheypidi commented on CHANGELOG.md
> +- **38_factor_costs** Realization `sticky_feb18` extended to differentiate capital requirements between regions and their specific development status (GDP) in each time step of the magpie run. The ch
```suggestion
- **38_factor_costs** Realization `sticky_feb18` extended to differentiate capital requirements between regions and their specific development status (GDP) in each time step of the magpie run. The changes in the `sticky` realization also include an additional switch so it can be operated as `dynamic` (change of each region capital share at each time step) or `free` (capital shares equal to zero and equivalent to the `fixed_per_ton_mar18` realization). Bugfix in the yearly update of the variable input requirements. Addition of the time dimension and clean up of names of parameters used in the realization. Removal of the management factor (this factor was not being used, it was being cancelled out in the calculations). Correction of the costs that are given in 05USDppp.
```

2021-08-16 07:28 UTC, tscheypidi approved these changes

2021-08-16 07:47 UTC, flohump approved these changes

2021-08-16 11:23 UTC, mishkos commented on modules/38_factor_costs/sticky_feb18/equations.gms
> -                              =e= vm_prod_reg(i2,kcr) * i38_variable_costs(i2,kcr) / (1-s38_mi_start)
We can also re-introduce this parameter once there is a link to management intensity developed in the model

2021-08-16 11:31 UTC, mishkos requested changes

2021-08-16 11:31 UTC, mishkos commented on modules/38_factor_costs/sticky_feb18/declarations.gms
> + p38_variable_costs(i,t,kcr)           Variable input costs (mio USD05ppp per input unit)
In the model we declare parameter, equations and variables over sets starting with the time dimension first. It's usually var(t,i,data). I suggest to stick to this convention further.

2021-08-17 07:50 UTC, mishkos approved these changes

2021-08-17 07:50 UTC, merged