Develop
magpiemodel/magpie pull request #310
Opened 2021-08-30 15:30 UTC by bodirsky

## :bird: Purpose of this PR :bird:

- Includes an update of parameters in non-default realisation of 51_nitrogen rescaled_jan21
- Includes an exogenous pathway for N released by soil organic matter loss in case the SOM module is switched off
- Includes a number of updates in runscripts

## :wrench: Checklist for PR creator :wrench:

- [ X] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [X ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

- [ X] Added changes to `CHANGELOG.md`
- [ X] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ X] No hard coded numbers and cluster/country/region names.
- [ X] The new code doesn't contain declared but unused parameters or variables.
- [ X] Where relevant, In-code comments added including documentation comments.
- [ X] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ X] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [X ] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2021-08-31 18:50 UTC, tscheypidi requested changes
some units are missing in scalar/parameter descriptions. Besides that, it looks good to me.

2021-08-31 18:50 UTC, tscheypidi commented on modules/41_area_equipped_for_irrigation/endo_apr13/input.gms
> +s41_AEI_depreciation Depreciation rate in capital value of irrigation infrastructure / 0 /
```suggestion
s41_AEI_depreciation Depreciation rate in capital value of irrigation infrastructure (1) / 0 /
```

2021-08-31 18:50 UTC, tscheypidi commented on modules/51_nitrogen/rescaled_jan21/declarations.gms
> +  i51_ef_n_soil(t,i,n_pollutants_direct,emis_source_n_cropsoils51) emission factors for nitrogen emissions from cropland soils
```suggestion
  i51_ef_n_soil(t,i,n_pollutants_direct,emis_source_n_cropsoils51) emission factors for nitrogen emissions from cropland soils (1)
```

2021-09-01 07:08 UTC, bodirsky commented on modules/41_area_equipped_for_irrigation/endo_apr13/input.gms
> +s41_AEI_depreciation Depreciation rate in capital value of irrigation infrastructure / 0 /
not introduced but my commit (just because i ran a default run), but happy to add unit.
Rather than unity, I prefer to preserve original units. Mathematically the same, it makes a difference; for example, the DM/DM share of a process can be a different one than the GE/GE share.

2021-09-01 07:51 UTC, vartika271987 reviewed
This value is a percentage (or rather share). Should I correct it?

2021-09-01 12:06 UTC, mishkos commented on modules/41_area_equipped_for_irrigation/endo_apr13/input.gms
> +s41_AEI_depreciation Depreciation rate in capital value of irrigation infrastructure (USD05PPP per USD05PPP) / 0 /
Perhaps putting 1 instead of USD05PPP per USD05PPP for unit? In the other parts of the code we have rates of shares with unit 1.

2021-09-01 13:41 UTC, bodirsky commented on modules/41_area_equipped_for_irrigation/endo_apr13/input.gms
> +s41_AEI_depreciation Depreciation rate in capital value of irrigation infrastructure (USD05PPP per USD05PPP) / 0 /
just mentioned above, i prefer not cancelling out the unit, even though mathematically the same. It still helps to understand which unit it should be applied to. 
And it sometimes makes a difference. E.g. processing conversion factors are different when expressed as DM/DM or as N/N, even though the unit would cancel out, you should not combine a DM flow with the N/N ratio

2021-09-01 14:15 UTC, mishkos requested changes
Looks good methodologically and content-wise. 

You also added a bunch of C-price and bioenergy demand scenarios. I wonder if this should be documented in the changelog. But it should be included in the list of option in the `default.cfg`.

2021-09-02 19:49 UTC, tscheypidi commented
There are conflicts due to the release of magpie 4.3.5. Especially the CHANGELOG.md needs to be modified with care (modifications which comes with this release must be listed under "Unreleased". Please make sure that they don't accidentally end under 4.3.5)

2021-09-03 17:45 UTC, tscheypidi approved these changes
Looks good..I have just one additional request: 

Could you please replace line 34 in `scripts/npi_ndc/start_npi_ndc.R` which is currently looking like this:

`getRegions(land_stock) <- paste(pol_mapping,1:59199,sep=".")`

with this: 

` getItems(land_stock, dim = 1, raw = TRUE) <- paste(pol_mapping,1:59199,sep=".")`

This will remove a deprecation warning. Thanks!

2021-09-04 13:20 UTC, k4rst3ns commented
Adressed @tscheypidi requested changes.

@flohump: You changed this PR to 'major' and 'high risk', which would in a way mean we would have to do additional test runs and document them here in this PR, right? Unsure about this re-labeling and would to do now ^^'

2021-09-06 09:05 UTC, mishkos approved these changes
All good. I added the update of the config file wrt new coupled scenarios that are available.

2021-09-06 09:44 UTC, flohump commented
> Adressed @tscheypidi requested changes.
> 
> @flohump: You changed this PR to 'major' and 'high risk', which would in a way mean we would have to do additional test runs and document them here in this PR, right? Unsure about this re-labeling and would to do now ^^'

I did so because according to our classification this PR is now major and high risk since many default settings in the default.cfg are changed and the input data is changed. However, we all know that the settings from the previous "lpjml_addon" script, which now become default, have been vetted in detail already. Therefore, my intention is not to request additional validation but instead to make it clear to the outside that with this PR major changes are made to the model.

2021-09-06 10:11 UTC, merged