Contruction wood dev and new release needed for forestry paper
magpiemodel/magpie pull request #311
Opened 2021-08-31 11:19 UTC by abhimishr

## :bird: Purpose of this PR :bird:

- Briefly explain the purpose of this pull request

## :wrench: Checklist for PR creator :wrench:

- [ ] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The new code doesn't contain declared but unused parameters or variables.
- [ ] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2021-09-01 07:31 UTC, tscheypidi approved these changes
just the minor comment to please not commit out-commented code. Besides that it looks ok from RSE side

2021-09-01 07:31 UTC, tscheypidi commented on scripts/start/projects/forestry.R
> +#for(i in names(all_configs)){
please avoid committing out-commented code. Include it with a switch instead if it should be optional

2021-09-01 07:31 UTC, tscheypidi commented on scripts/start/projects/forestry_lpjml_addon.R
> +#for(i in names(all_configs)){
please avoid committing out-commented code. Include it with a switch instead if it should be optional

2021-09-01 11:56 UTC, abhimishr commented on scripts/start/projects/forestry_lpjml_addon.R
> +#for(i in names(all_configs)){
Removed unused code

2021-09-02 08:26 UTC, flohump requested changes
Overall fine. Some minor changes are needed, which do not affect the model outcome.

2021-09-02 08:26 UTC, flohump commented on config/default.cfg
> +# * ("max_marginal_increment")      = Harvesting when the average annual increment is maximum
This is confusing. Change to "mean_annual_increment" ?

2021-09-02 08:26 UTC, flohump commented on modules/32_forestry/dynamic_feb21/preloop.gms
> +  display "Rotation lengths are calculated based on maximizing increment in this run.";
maximizing MAI

2021-09-02 08:26 UTC, flohump commented on modules/32_forestry/dynamic_feb21/preloop.gms
> +  display "Rotation lengths are calculated based on maximizing NPV.";
Is NPV correct? Or instantaneous growth rate equated to interest rate?

2021-09-02 08:26 UTC, flohump commented on modules/73_timber/default/preloop.gms
> +p73_fraction(t_all) = s73_expansion/80;
80 = 2100 - 2020
You can use m_year(t) for this, this works in preloop
m_year("y2100") - m_year("y2020")
Maybe calculate it once and save it in scalar?

2021-09-02 08:26 UTC, flohump commented on scripts/start/projects/forestry_lpjml_addon.R
> +# |  (C) 2008-2021 Potsdam Institute for Climate Impact Research (PIK)
Can be deleted?

2021-09-02 08:26 UTC, flohump commented on scripts/start/projects/forestry_lpjml_addon.R
> +# |  (C) 2008-2021 Potsdam Institute for Climate Impact Research (PIK)
Is this start script needed for your release?

2021-09-02 11:52 UTC, abhimishr commented on config/default.cfg
> +# * ("max_marginal_increment")      = Harvesting when the average annual increment is maximum
Changed via 2fdde79

2021-09-02 11:52 UTC, abhimishr commented on modules/32_forestry/dynamic_feb21/preloop.gms
> +  display "Rotation lengths are calculated based on maximizing increment in this run.";
Changed via 2fdde79

2021-09-02 11:52 UTC, abhimishr commented on modules/32_forestry/dynamic_feb21/preloop.gms
> +  display "Rotation lengths are calculated based on maximizing NPV.";
Edited for clarity. Changed via 2fdde79

2021-09-02 11:52 UTC, abhimishr commented on modules/73_timber/default/preloop.gms
> +p73_fraction(t_all) = s73_expansion/80;
Redid the calculation for clean steps. Changed via 2fdde79

2021-09-02 11:53 UTC, abhimishr commented on scripts/start/projects/forestry_lpjml_addon.R
> +# |  (C) 2008-2021 Potsdam Institute for Climate Impact Research (PIK)
I'll keep it (but not needed for release). It stays in the project folder

2021-09-02 14:22 UTC, flohump approved these changes

2021-09-02 16:52 UTC, merged