Peatland Module on by default
magpiemodel/magpie pull request #317
Opened 2021-09-06 19:44 UTC by flohump

## :bird: Purpose of this PR :bird:

- Briefly explain the purpose of this pull request

## :wrench: Checklist for PR creator :wrench:

- [ ] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The new code doesn't contain declared but unused parameters or variables.
- [ ] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2021-09-07 08:46 UTC, tscheypidi requested changes
comments need an update in default.cfg (see my suggested changes)

2021-09-07 08:46 UTC, tscheypidi commented on config/default.cfg
> +cfg$gms$s56_peatland_policy <- 1			# def = 0
```suggestion
cfg$gms$s56_peatland_policy <- 1			# def = 1
```

2021-09-07 08:46 UTC, tscheypidi commented on config/default.cfg
> +cfg$gms$peatland  <- "on"                     # def = off
```suggestion
cfg$gms$peatland  <- "on"                     # def = on
```

2021-09-07 12:42 UTC, tscheypidi approved these changes

2021-09-23 09:51 UTC, k4rst3ns approved these changes

2021-09-23 09:54 UTC, k4rst3ns approved these changes
Looks all good to me. EU is a bit strange with this high emissions now, but as our emissions are anyway not very stable and correct I guess this is a minor thing
.

2021-09-23 10:04 UTC, k4rst3ns commented
Maybe than we should clarify, if the peatland emission factors for EU are too high* or
the validation data is lacking detailed peatland emissions.

* Could be as especially in EUR some peatland conversion happened very long ago (more than 100 years), the emission factors we use overestimate emissions from very old degraded peatlands (?)

2021-09-23 11:05 UTC, mishkos commented
> Maybe than we should clarify, if the peatland emission factors for EU are too high* or
> the validation data is lacking detailed peatland emissions.
> 
> (*) Could be as especially in EUR some peatland conversion happened very long ago (more than 100 years), the emission factors we use overestimate emissions from very old degraded peatlands (?)

Good point with overestimation. Where are our peatland emissions factors from, IPCC? We might need to revise those. The emissions in EU are very high now, and with the coupling with REMIND I think we will have issues to justify those levels.

2021-09-23 11:56 UTC, flohump commented
> > Maybe than we should clarify, if the peatland emission factors for EU are too high* or
> > the validation data is lacking detailed peatland emissions.
> > (*) Could be as especially in EUR some peatland conversion happened very long ago (more than 100 years), the emission factors we use overestimate emissions from very old degraded peatlands (?)
> 
> Good point with overestimation. Where are our peatland emissions factors from, IPCC? We might need to revise those. The emissions in EU are very high now, and with the coupling with REMIND I think we will have issues to justify those levels.

GHG emissions from peatlands in the EU are about 220 Mt CO2eq/yr 
https://onlinelibrary.wiley.com/doi/10.1002/adsu.202000146

The estimate in MAgPIE for EUR is very close. This is CO2 only, but that's the most important gas here.
![Emissions_CO2_Land_Land_use_Change_Peatland](https://user-images.githubusercontent.com/16921122/134501798-4e639075-7bc3-4e18-9b1a-a29a72506efc.png)

Global CO2 emissions from peatlands compare well to Joosten 2010
https://www.wetlands.org/publications/the-global-peatland-co2-picture/

Reporting of wetland GHG emissions is fragmentented and incomplete.
https://greifswaldmoor.de/files/dokumente/GMC%20Schriften/18-02_Barthelmes_GMC.pdf

2021-09-23 12:22 UTC, k4rst3ns commented
Ok, thanks @flohump.

I guess than either we were right for the wrong reasons before or our validation data does not include this peatland emissions.
Do you know more about in what regard the validation data includes peatland emissions?

2021-09-23 12:30 UTC, mishkos commented
I'm a bit confused by this level of ~220 MtCO2 per year in the given reference. I checked in the European Environment Agency and the value presently is ~15MtCO2 per yer. The discrepancy is considerable. 

I was generally surprised that peatlands are such a huge source of emissions in the EU, like 25% of total GHG in AFOLU. Do they indeed contribute that much? 

Here is the snapshot from the [EEA data](https://www.eea.europa.eu/data-and-maps/data/data-viewers/greenhouse-gases-viewer) 
![image](https://user-images.githubusercontent.com/32301623/134506896-d7a8caf9-c854-41ac-9a6e-c644ed22ebeb.png)

2021-09-23 16:20 UTC, flohump commented
> I'm a bit confused by this level of ~220 MtCO2 per year in the given reference. I checked in the European Environment Agency and the value presently is ~15MtCO2 per yer. The discrepancy is considerable.
> 
> I was generally surprised that peatlands are such a huge source of emissions in the EU, like 25% of total GHG in AFOLU. Do they indeed contribute that much?
> 
> Here is the snapshot from the [EEA data](https://www.eea.europa.eu/data-and-maps/data/data-viewers/greenhouse-gases-viewer)
> ![image](https://user-images.githubusercontent.com/32301623/134506896-d7a8caf9-c854-41ac-9a6e-c644ed22ebeb.png)

Degraded peatlands in Germany alone already emit about 53 Mio ton CO2eq/yr.
https://www.umweltbundesamt.de/daten/klima/treibhausgas-emissionen-in-deutschland/emissionen-der-landnutzung-aenderung#nachhaltige-landnutzung-und-forstwirtschaft-

I think the category in the EEA DB in your screenshot includes only emissions from intact wetlands.

2021-09-24 09:32 UTC, merged