Bugfix for exo trade runs incomaptible with dynamic forestry realization and trade module
magpiemodel/magpie pull request #321
Opened 2021-09-09 09:20 UTC by abhimishr

## :bird: Purpose of this PR :bird:

- Briefly explain the purpose of this pull request

## :wrench: Checklist for PR creator :wrench:

- [ ] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The new code doesn't contain declared but unused parameters or variables.
- [ ] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2021-09-09 09:39 UTC, emolinab approved these changes
Looks okay to me :)

2021-09-09 10:00 UTC, flohump requested changes
The two variables added in the static realizations need to be fixed to 0, otherwise these are free variables.

2021-09-09 11:54 UTC, abhimishr commented on modules/32_forestry/static_sep16/declarations.gms
> + vm_prod_forestry(j,kforestry)    Production of woody biomass from commercial plantations (mio. tDM per yr)
I thought this will be taken care by `vm_prod` being 0 (because `vm_supply`) is zero. Fixing `vm_prod_forestry` to zero would cause issue with trade module specification as it still asks to produce ``f21_trade_balance` in historical period.

2021-09-09 11:54 UTC, abhimishr commented on modules/35_natveg/static/declarations.gms
> +  vm_prod_natveg(j,land_natveg,kforestry)       Production of woody biomass from natural vegetation (mio. tDM per yr)
same as above

2021-09-10 12:09 UTC, flohump approved these changes
Looks fine to me.

2021-09-10 20:59 UTC, tscheypidi commented on main.gms
>  *##################### R SECTION START (VERSION INFO) ##########################
please revert the changes in this file as they are of no relevance and would otherwise only cause merge conflicts in other PRs

2021-09-10 21:01 UTC, tscheypidi requested changes
one file to be deleted and changes in main.gms to be reverted. Rest looks good.

2021-09-10 21:01 UTC, tscheypidi commented on modules/21_trade/exo/not_used.txt
>  # |  Contact: magpie@pik-potsdam.de
This file is now empty and can (should) be removed

2021-09-13 11:37 UTC, abhimishr commented on main.gms
>  *##################### R SECTION START (VERSION INFO) ##########################
Fixed in 849be75

2021-09-13 11:37 UTC, abhimishr commented on modules/21_trade/exo/not_used.txt
>  # |  Contact: magpie@pik-potsdam.de
Fixed in 849be75

2021-09-13 11:39 UTC, abhimishr commented on main.gms
>  *##################### R SECTION START (VERSION INFO) ##########################
there are some whitespaces diff but I have copy pasted how the main gms looks like in develop branch 🤷🏽

2021-09-13 11:44 UTC, tscheypidi approved these changes

2021-09-13 12:02 UTC, merged