Performance Improvements
magpiemodel/magpie pull request #337
Opened 2021-11-01 06:05 UTC by flohump

## :bird: Purpose of this PR :bird:

- Briefly explain the purpose of this pull request

## :wrench: Checklist for PR creator :wrench:

- [ ] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The new code doesn't contain declared but unused parameters or variables.
- [ ] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2021-11-01 09:32 UTC, mishkos approved these changes
All looks good to me, but maybe wait for Edna's review on the optimization module.

2021-11-01 09:44 UTC, abhimishr requested changes
minor comments

2021-11-01 09:44 UTC, abhimishr commented on modules/58_peatland/off/not_used.txt
> +vm_land_timber, input, not used
In general, it should be good to go. Except here where we should ideally not include variables in `not_used.txt` (I see why it is included as the codeCheck will complain) but from past discussions with @tscheypidi I understood that it is generally not a good idea to include variables in this file.

2021-11-01 09:44 UTC, abhimishr commented on modules/32_forestry/dynamic_feb21/equations.gms
> +			pc32_yield_forestry_future_reg(i2) * (sum(cell(i2,j2), sum(ac_est, v32_land(j2,"plant",ac_est))+v32_land_missing(j2)));
No changes needed here - just for me - why was this moved to RHS?

2021-11-01 09:44 UTC, abhimishr commented on modules/38_factor_costs/sticky_labor/input.gms
> +$setglobal c38_sticky_mode  free
In the line below we should specify which settings can be used like
`* options dynamic, free` (basically what default config tells us anyways)

2021-11-01 12:50 UTC, emolinab commented on modules/58_peatland/off/not_used.txt
> +vm_land_timber, input, not used
I am curious about the follow-up of this comment. It usually not only complains but stops the run. In the factor costs realization, we have a few variables in the not_used.txt

2021-11-01 12:50 UTC, emolinab commented on modules/58_peatland/on/declarations.gms
> + q58_land(j,land58)								Managed land (mio. ha)
Should these changes be added to the changelog?

2021-11-01 13:12 UTC, flohump commented on modules/32_forestry/dynamic_feb21/equations.gms
> +			pc32_yield_forestry_future_reg(i2) * (sum(cell(i2,j2), sum(ac_est, v32_land(j2,"plant",ac_est))+v32_land_missing(j2)));
I moved it to the RHS to avoid division by zero. Division by zero happens if a region has not plantation establishment. It does not happen with the current data, but it could in principal.

2021-11-01 13:13 UTC, flohump commented on modules/38_factor_costs/sticky_labor/input.gms
> +$setglobal c38_sticky_mode  free
added.

2021-11-01 13:42 UTC, tscheypidi requested changes

2021-11-01 13:42 UTC, tscheypidi commented on modules/58_peatland/off/not_used.txt
> +vm_land_timber, input, not used
@abhimishr @emolinab One has to be more careful in the decision whether an interface can get ignored when it is a variable. In case of a variable there is always the risk that by not adressing it the model might start to show unusual behavior (e.g. when a constrained variable suddenly becomes a free variables).

In this particular case `vm_land_timber` is just another reporting variable from the forestry module which is already sufficiently constrained in its dynamic by other constraints. So, no risk here.

2021-11-01 13:45 UTC, abhimishr approved these changes
my comments have been resolved! Good to go from MAgPIE side (pending Edna's question)

2021-11-02 05:49 UTC, emolinab approved these changes

2021-11-02 17:16 UTC, tscheypidi approved these changes
looks good

2021-11-02 17:24 UTC, merged