Added script for land conversion cost calibration
magpiemodel/magpie pull request #339
Opened 2021-11-04 20:33 UTC by flohump

## :bird: Purpose of this PR :bird:

- Briefly explain the purpose of this pull request

## :wrench: Checklist for PR creator :wrench:

- [ ] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The new code doesn't contain declared but unused parameters or variables.
- [ ] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2021-11-15 10:08 UTC, abhimishr approved these changes
Looks fine to me!

2021-11-15 11:35 UTC, tscheypidi requested changes
additional to my specific remarks: you changed to variable names: did you make sure that  all functions in the magpie4 package which are using these variables can now also handle the new names (and still the old ones?)

2021-11-15 11:35 UTC, tscheypidi commented on modules/39_landconversion/calib/presolve.gms
> +i39_reward_reduction(t,i,"crop") = s39_cost_establish_crop * s39_reward_shr * i39_calib(t,i,"reward");
is it possible to get rid of `s39_reward_shr`? Why not just multiply with the calibration factor?

2021-11-15 11:35 UTC, tscheypidi commented on modules/39_landconversion/calib/realization.gms
> +*' Global cost for cropland expansion (10000 USD/ha as default) are scaled with a regional and time-dependent calibration factor
avoid putting these numbers here as the documentation most likely will not be updated when you change that numbers elsewhere and an outdated documentation should be avoided!

2021-11-15 11:35 UTC, tscheypidi commented on modules/39_landconversion/calib/realization.gms
>  *'
same here...avoid mentioning the numbers...if you want to have the numbers in the text, add the corresponding code snippets into the documentation via @code. By doing so you can be sure that the numbers are correct

2021-11-15 11:35 UTC, tscheypidi commented on scripts/calibration/calc_calib.R
> +    old_calib<-new.magpie(cells_and_regions = getCells(calib_divergence),names = getNames(calib_divergence),fill = 1)
```suggestion
    old_calib <- new.magpie(cells_and_regions = getCells(calib_divergence), names = getNames(calib_divergence), fill = 1)
```

2021-11-15 11:35 UTC, tscheypidi commented on scripts/calibration/calc_calib.R
> +
why did you change that?

2021-11-15 11:35 UTC, tscheypidi commented on scripts/calibration/landconversion_cost.R
> +  data <- superAggregate(readGDX(gdx_file,"f10_land"),level="reg",aggr_type = "sum")[,y,"crop"]
```suggestion
  data <- dimSums(readGDX(gdx_file, "f10_land")[, y, "crop"], dim = 1.2)
```

2021-11-15 11:35 UTC, tscheypidi commented on scripts/calibration/landconversion_cost.R
> +  require(luscale)
```suggestion
```

2021-11-15 11:35 UTC, tscheypidi commented on scripts/calibration/landconversion_cost.R
> +  magpie <- land(gdx_file)[,,c("crop")][,y,]
```suggestion
  magpie <- land(gdx_file)[, y, "crop"]
```

2021-11-15 11:35 UTC, tscheypidi commented on scripts/calibration/landconversion_cost.R
> +  out2 <- mbind(new.magpie(getRegions(calib_factor),years = c(1995,2015),fill=1),new.magpie(getRegions(calib_factor),years = seq(2050,2150,by=5),fill=1))
```suggestion
  out2 <- new.magpie(getRegions(calib_factor), years = c(1995, 2015, seq(2050, 2150, by=5)), fill = 1) 
```

2021-11-15 11:35 UTC, tscheypidi commented on scripts/calibration/landconversion_cost.R
> +  require(luscale)
```suggestion
```

2021-11-15 11:35 UTC, tscheypidi commented on scripts/calibration/landconversion_cost.R
> +  data <- superAggregate(readGDX(gdx_file,"f10_land"),level="reg",aggr_type = "sum")[,,"crop"]
```suggestion
    data <- dimSums(readGDX(gdx_file, "f10_land")[, , "crop"], dim = 1.2)
```

2021-11-15 12:28 UTC, emolinab commented on scripts/start/extra/recalibrate.R
> -cfg$input<- cfg$input[names(cfg$input)!="calibration"]
We had agreed a few weeks back when we pushed the update that led to the rc branch, that we would start calibrations without previous values. This line takes care of it, it reads default inputs and removes the calibration one. Why was this removed?

2021-11-15 12:28 UTC, emolinab commented on scripts/start/extra/recalibrate_realizations.R
> -      cfg$input<- cfg$input[names(cfg$input)!="calibration"]
same question as before :)

2021-11-15 12:28 UTC, emolinab commented on scripts/start/extra/recalibrate.R
> +cfg$recalibrate_landconversion_cost <- TRUE
Personally, I find the name of the scripts a bit misleading. Here, you are calibrating yields and land conversion costs (both are TRUE). But in recalibrate_all.R, costs are only "ifneeded".

2021-11-15 12:28 UTC, emolinab commented on scripts/calibration/calc_calib.R
> +
+1

2021-11-15 12:44 UTC, flohump commented on scripts/start/extra/recalibrate.R
> -cfg$input<- cfg$input[names(cfg$input)!="calibration"]
I removed this line because the calibration tgz now includes both `f14_yld_calib.csv` and `f39_calib.csv`. If `f39_calib.csv` exists, only the yield calibration is executed. But I also changed the way `f14_yld_calib.csv` is read-in in MAgPIE. MAgPIE can now start without this file. This allow to delete `f14_yld_calib.csv` in case of `cfg$recalibrate <- TRUE`. I added corresponding lines in the yield calibration script.

2021-11-15 12:44 UTC, flohump commented on scripts/start/extra/recalibrate_realizations.R
> -      cfg$input<- cfg$input[names(cfg$input)!="calibration"]
see above

2021-11-15 12:46 UTC, flohump commented on scripts/start/extra/recalibrate.R
> +cfg$recalibrate_landconversion_cost <- TRUE
This is a mistake. It should be the other way around. I changed it now.

2021-11-15 12:49 UTC, emolinab commented on scripts/start/extra/recalibrate.R
> -cfg$input<- cfg$input[names(cfg$input)!="calibration"]
Just to confirm I understood correctly if cfg$recalibrate<-TRUE, the file is deleted and yield calibration will always start with ones.

2021-11-15 12:55 UTC, flohump commented on scripts/start/extra/recalibrate.R
> -cfg$input<- cfg$input[names(cfg$input)!="calibration"]
Exactly.

2021-11-15 12:56 UTC, flohump commented on scripts/start/extra/recalibrate.R
> -cfg$input<- cfg$input[names(cfg$input)!="calibration"]
For `f39_calib.csv `is works in the way.

2021-11-15 14:34 UTC, flohump commented on scripts/calibration/calc_calib.R
> +
Because the calibration factors are not independent from each other. Choosing the best calibration factor for each region from different iterations can result in unexpected outcomes. E.g. a factor of 0.95 for EUR might result in different croland area in 1995 depending on the calibration factor used for USA. In the updated version, calibration factors from the iteration with the lowest standard deviation in divergence are used.

2021-11-15 15:57 UTC, flohump commented on modules/39_landconversion/calib/presolve.gms
> +i39_reward_reduction(t,i,"crop") = s39_cost_establish_crop * s39_reward_shr * i39_calib(t,i,"reward");
The alternative would be a scalar like `s39_reward_cropland_reduction <- 6600`. `s39_cost_establish_crop` can not be used directly as this would result in too much cropland reduction. I would like to keep s39_reward_shr as the calibration routine works best with this ratio.

2021-11-15 15:57 UTC, flohump commented on modules/39_landconversion/calib/equations.gms
> +*' Reward for land reduction is only used for cropland, and only for those regions with a decline of cropland between 1995 and 2015 in historic data.
Moved to realizations.gms

2021-11-15 15:58 UTC, flohump commented on modules/39_landconversion/calib/equations.gms
> +*' Land establishment costs apply on expansion of cropland, pasture, forestry and urban land.
Moved to realizations.gms

2021-11-15 16:00 UTC, flohump commented
> additional to my specific remarks: you changed to variable names: did you make sure that all functions in the magpie4 package which are using these variables can now also handle the new names (and still the old ones?)

`v10_landreduction` and `vm_carbon_stock_change`are not used in the magpie4 R library.

2021-11-15 16:57 UTC, emolinab approved these changes
The calibration part is clear to me now.

2021-11-16 09:29 UTC, tscheypidi approved these changes

2021-11-16 12:48 UTC, mishkos approved these changes
All good!

2021-11-16 14:24 UTC, merged