34_urban exo_nov21 Realisation PR
magpiemodel/magpie pull request #340
Opened 2021-11-06 10:28 UTC by caviddhen

## :bird: Purpose of this PR :bird:

- Briefly explain the purpose of this pull request

## :wrench: Checklist for PR creator :wrench:

- [ ] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The new code doesn't contain declared but unused parameters or variables.
- [ ] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2021-11-08 14:42 UTC, tscheypidi commented
@caviddhen  codeCheck failed....please fix the issue first

2021-11-08 15:10 UTC, caviddhen commented
> 
> 
> @caviddhen codeCheck failed....please fix the issue first

Ah sorry, Fixed now

2021-11-09 11:40 UTC, tscheypidi requested changes

2021-11-09 11:40 UTC, tscheypidi commented on modules/10_land/landmatrix_dec18/presolve.gms
> +*' v10_lu_transitions.fx(j,"urban","urban") = pcm_land(j,"urban");
two issues/questions:

- using `*'` will make your comment a goxygen comment and it will show up in the document. Is that intended?
- As this was fixed before but is not fixed anymore: This realization will still work with static urban?

2021-11-09 11:40 UTC, tscheypidi commented on modules/34_urban/exo_nov21/equations.gms
> +            v34_cost1(j2) =g= sum(ct, i34_urban_area(ct, j2)) - vm_land(j2,"urban");
Why is that required? why not just use `vm_land.fx(j2,"urban") = i34_urban_area(ct,j2)`?

2021-11-09 11:40 UTC, tscheypidi commented on modules/34_urban/exo_nov21/not_used.txt
> +name,type,reason
please do not add empty not_used files. Remove it, if everything is being used.

2021-11-09 11:41 UTC, tscheypidi commented on CHANGELOG.md
> +- **34_urban** New exo_nov21 exogenous realization of urban land expansion
This needs to put under the sub-category "added"

2021-11-09 11:56 UTC, caviddhen commented on modules/10_land/landmatrix_dec18/presolve.gms
> +*' v10_lu_transitions.fx(j,"urban","urban") = pcm_land(j,"urban");
Ah, I can just delete it instead?

Static urban still static. I believe this line in static realization already constrains it, the results also maintain static urban land: 
https://github.com/magpiemodel/magpie/blob/rc/modules/34_urban/static/presolve.gms#L9

2021-11-09 11:57 UTC, caviddhen commented on modules/34_urban/exo_nov21/equations.gms
> +            v34_cost1(j2) =g= sum(ct, i34_urban_area(ct, j2)) - vm_land(j2,"urban");
We thought that safeguards against infeasible outcomes. Where urban land should expand but can not due to NPI or other protected land constraints. In this case it can have high costs and shift it elsewhere in the region.

2021-11-11 09:01 UTC, bodirsky requested changes
once the runtime issue is clarified and my minor comments were corrected, ready to merge!

2021-11-11 09:01 UTC, bodirsky commented on modules/34_urban/module.gms
> +*' @authors Jan Philipp Dietrich, Florian Humpenöder, David Chen
i want to be part here too at the end...

2021-11-11 09:08 UTC, caviddhen commented on modules/10_land/landmatrix_dec18/input.gms
> +  s10_cost_balance Artificial cost for balance variable (USD05MER per ha) / 1e+06 /
This is not one of my changes. It is just a renaming of the unit, I think it comes from Florian's branch when i cloned it.

2021-11-11 09:30 UTC, flohump commented on modules/34_urban/exo_nov21/equations.gms
> +            vm_cost_urban(j2) =e= (v34_cost1(j2) + v34_cost2(j2)) * 1000000;
1000000 should be added as scalar like s34_cost_urban_deviation

2021-11-12 12:39 UTC, tscheypidi approved these changes

2021-11-15 09:41 UTC, bodirsky approved these changes

2021-11-15 09:46 UTC, flohump commented on modules/34_urban/exo_nov21/presolve.gms
> +vm_bv.fx(j,"urban", potnatveg) = pcm_land(j,"urban") * fm_bii_coeff("urban",potnatveg) * fm_luh2_side_layers(j,potnatveg);
I agree, there is room for improvement. Also the "Bending the curve" paper should be added as reference. But this should be done as part of a dedicated PR, not as part of this PR.

2021-11-15 09:47 UTC, merged