Rc
magpiemodel/magpie pull request #350
Opened 2021-11-30 14:23 UTC by dklein-pik

## :bird: Purpose of this PR :bird:

- All related to REMIND coupling
- Remove elements from the parameter list of start_run(), instead include them as regular settings in the default.cfg.
- Add new option to take ghg prices from different file than the regular reporting file (used in the REMIND coupling).

## :wrench: Checklist for PR creator :wrench:

- [x] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

- [x] Added changes to `CHANGELOG.md`
- [x] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [x] No hard coded numbers and cluster/country/region names.
- [x] The new code doesn't contain declared but unused parameters or variables.
- [x] Where relevant, In-code comments added including documentation comments.
- [x] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [x] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2021-12-01 09:35 UTC, dklein-pik commented
Please DO NOT merge after reviewing. The merge needs to be synchronous to a corresponding merge in REMIND. Thank you!

2021-12-06 12:02 UTC, flohump requested changes
In general the proposed changes look fine to me. However, I have some suggestions for improving the handling of external input files for bioenergy demand and GHG prices. But I don't know if my suggested changes would be in line with the changes made in REMIND.

2021-12-07 08:27 UTC, dklein-pik commented on scripts/start_functions.R
> -  cfg <- gms::check_config(cfg, extras = "info")
Good point. Only wanted to delete the first line. Will re-introduce the check_config.

2021-12-07 09:23 UTC, dklein-pik commented on config/default.cfg
Thanks! Renamed the `cfg$path_to_report` to `cfg$path_to_report_bioenergy` and moved the new settings to the respective topic sections in the default.cfg

2021-12-07 09:24 UTC, dklein-pik commented on scripts/start_functions.R
> +    getReportData(cfg$path_to_report, cfg$mute_ghgprices_until, cfg$path_to_report_ghgprices)
Done

2021-12-07 09:27 UTC, dklein-pik commented on scripts/start_functions.R
> +    getReportData(cfg$path_to_report, cfg$mute_ghgprices_until, cfg$path_to_report_ghgprices)
I suggest to do without `cfg$mute_bioenergy_until` and add it later if needed.

2021-12-07 09:36 UTC, dklein-pik commented on config/default.cfg
> +cfg$mute_ghgprices_until <- "y2010"
Done

2021-12-07 10:52 UTC, tscheypidi commented on scripts/start_functions.R
> +start_run <- function(cfg, codeCheck=TRUE, lock_model=TRUE) {
I would not remove the scenario argument as it is on another level of abstraction compared to the other, very specific settings. From my perspective it makes conceptually sense to provide a cfg along with a scenario....this can be understood as "Please take this configuration, but make it consistent to the chosen scenario".

2021-12-07 11:32 UTC, dklein-pik commented on scripts/start_functions.R
> +start_run <- function(cfg, codeCheck=TRUE, lock_model=TRUE) {
I agree. For some reason I thought it was only realted to the REMIND coupling, but I was wrong. I re-introduced the scenario.

2021-12-08 08:30 UTC, tscheypidi requested changes

2021-12-08 08:30 UTC, tscheypidi commented on scripts/start_functions.R
> +    y_zeroprices <- getYears(mag) <= mute_ghgprices_until
it looks like `mute_ghgprices_until` is not being passed to `.emission_prices` but instead read from its parent environment. For more transparency I would recommend to add it as another argument to `.emission_prices` and to avoid direct access of the parent environment.

2021-12-08 08:30 UTC, tscheypidi commented on scripts/start_functions.R
> +    cat("Reading ghg prices from",path_to_report_ghgprices,"\n")
```suggestion
    message("Reading ghg prices from ",path_to_report_ghgprices)
```

2021-12-08 08:30 UTC, tscheypidi commented on scripts/start_functions.R
> +      empty95<-ghgmag[,1,];empty95[,,]<-0;dimnames(empty95)[[2]] <- "y1995"
```suggestion
      empty95 <- ghgmag[,1,]
      empty95[,,] <- 0
      dimnames(empty95)[[2]] <- "y1995"
```

2021-12-08 09:04 UTC, dklein-pik commented on scripts/start_functions.R
> +    y_zeroprices <- getYears(mag) <= mute_ghgprices_until
Done

2021-12-08 09:58 UTC, flohump approved these changes
All my points have been adressed.

2021-12-08 13:05 UTC, tscheypidi approved these changes
looks good

2021-12-08 13:08 UTC, merged