Grassland management implementation
magpiemodel/magpie pull request #379
Opened 2022-03-02 15:25 UTC by mppalves

## :bird: Purpose of this PR :bird:

This pull request implements a new realization of module 31_past that allows the separation of grass biomass production into areas of managed pastures and rangelands. It also updates module 13_tc adding a new set that distinguishes tau that is applied to managed pastures vs tau applied to crops.

## :wrench: Checklist for PR creator :wrench:

- [x] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [x] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
     default_dev_mar22
  * Default run based on the current version of the fork from which PR is made
    default_new_mar22 - New default
    IPSL-CM6A-LR-SSP2-set18 - New Realization ON
- [x] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : 30.7 mins
  * This PR's default :  32.0  mins

- [x] Added changes to `CHANGELOG.md`
- [x] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [x] No hard coded numbers and cluster/country/region names.
- [x] The new code doesn't contain declared but unused parameters or variables.
- [x] Where relevant, In-code comments added including documentation comments.
- [x] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [x] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [x] Self-review of my own code.
- [x] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau. 

=======================================================================

**Below find the results comparing the current default and the new implementation: **

The **blue** line is the current develop (old TC module and old pasture module)
The **red** line is the new proposed default (new TC module and old pasture module)
The **green** line is the new implementation (new TC and new pasture modules)

![Resources_Land_Cover_Pastures_and_Rangelands](https://user-images.githubusercontent.com/37006832/161244434-e80845a6-a649-49d8-9199-3aabf5993383.png)
![Resources_Land_Cover_Cropland](https://user-images.githubusercontent.com/37006832/161244425-be706daa-d230-4dbb-b65d-a9d007932959.png)
![Productivity_Landuse_Intensity_Indicator_Tau](https://user-images.githubusercontent.com/37006832/161245108-5e605e8b-b115-4ae5-b4b5-67ddb3df101f.png)
![Resources_Land_Cover_Managed_Pastures](https://user-images.githubusercontent.com/37006832/161244431-496dc8c6-937c-4a2b-bdbc-cc089e0aefed.png)
![Resources_Land_Cover_Rangelands](https://user-images.githubusercontent.com/37006832/161244419-47d8252a-f79c-45ee-b74e-4bc55e3774f5.png)

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [x] PR is labeled correctly.
- [x] `CHANGELOG` is updated correctly
- [x] No hard coded numbers and cluster/country/region names.
- [x] No unnecessary increase in module interfaces
- [x] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [x] In-code comments and documentation comments are satisfactory.
- [x] model behavior/performance is satisfactory.
- [x] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [x] PR is labeled correctly.
- [x] `CHANGELOG` is updated correctly
- [x] No hard coded numbers and cluster/country/region names.
- [x] Changes to the model are scientifically sound
- [x] In-code comments and documentation comments are satisfactory.
- [x] model behavior/performance is satisfactory.
- [x] Requested changes (if any) were applied correctly

2022-03-03 15:04 UTC, tscheypidi reviewed
I just reviewed the first part (tc and yield module). My comments should now be visible. I will continue tomorrow to review the rest

2022-03-03 15:04 UTC, tscheypidi commented on modules/13_tc/exo/sets.gms
>  	scen13 tc cost scenario
have you tested, whether the exo realization is working as well?

2022-03-03 15:04 UTC, tscheypidi commented on modules/15_food/anthropometrics_jan18/input.gms
> +set    kfo_rd(kfo) Ruminant meat and dairy food products / livst_rum /;
what happened here and why?

2022-03-04 15:10 UTC, tscheypidi requested changes

2022-03-04 15:10 UTC, tscheypidi commented on modules/31_past/grasslands_feb22/equations.gms
> +  vm_prod(j2,"pasture") =e= sum(grassland, v31_grass_area(j2,grassland,"rainfed")
in the equation above you have rainfed and irrigated pasture and rangelands but you only consider rainfed production!?

If you only consider rainfed, then you should also remove the irrigated cases above!

2022-03-04 15:10 UTC, tscheypidi commented on modules/31_past/grasslands_feb22/equations.gms
> +*' into managed pastures and rangelands, an extension of the land matrix implemented
is this land matrix really needed here? I thought you made tests which showed that simple land expansion constraints would work equally well?

2022-03-04 15:10 UTC, tscheypidi commented on modules/31_past/grasslands_feb22/equations.gms
> +
where is the code which is described here?

2022-03-04 15:10 UTC, tscheypidi commented on modules/31_past/grasslands_feb22/not_used.txt
> +pcm_land, input, not needed
which realization needs `pcm_land` and why?

2022-03-04 15:10 UTC, tscheypidi commented on modules/31_past/grasslands_feb22/not_used.txt
> +vm_prod_reg, variable, not needed
must not the pasture production be fed back into this variable?

2022-03-04 15:10 UTC, tscheypidi commented on modules/31_past/grasslands_feb22/preloop.gms
> +*' @code
why not have the code-flag in front of all comments but instead have it here somewhere in the middle of the description?

2022-03-04 15:10 UTC, tscheypidi commented on scripts/start/projects/paper_grassland.R
> +# description:
description is missing

2022-03-04 15:10 UTC, tscheypidi commented on modules/31_past/grasslands_feb22/preloop.gms
> +
you need to explain me at some point what is happening here

2022-03-04 17:27 UTC, mppalves commented on config/default.cfg
> +cfg$gms$c13_tccost_mpastr <- "medium"		# def = medium
I thought it could be interesting to check the effects of decoupling pasture and crop tau scenarios. From my tests, I do not change the outcomes significantly. So, I can remove it if you don't see an added value for future developments.

2022-03-04 17:34 UTC, mppalves commented on config/default.cfg
> +cfg$gms$s31_limit_calib <- 1       # def = 1
This switch determines how the lambda factor is calculated in the preloop calibration. It essentially allows to turn on/off the mechanism that defines if the calibration will be purely a relative (multiplicative) or an absolute (additive) calibration.
The description is the same as in the yield module for the equivalent switch. I can change it but, I would suggest to keep it the same in the two places where it is used. I can ask Kristines help (I think she wrote this description) to improve it if necessary.

2022-03-04 17:35 UTC, mppalves commented on modules/13_tc/exo/sets.gms
>  	scen13 tc cost scenario
Yes. I tested all possible combinations of the modules in the two realizations I have changed. I will add some new images showing the outputs in the PR.

2022-03-04 18:08 UTC, mppalves commented on modules/15_food/anthropometrics_jan18/input.gms
> +set    kfo_rd(kfo) Ruminant meat and dairy food products / livst_rum /;
Automatically overridden by:

`cfg$gms$kfo_rd <- "livst_rum"                             #def = livst_rum`

in the config file.

2022-03-05 11:10 UTC, mppalves commented on modules/31_past/grasslands_feb22/equations.gms
> +q31_yield_grassl_range(j2,grassland,w)..
Didn't know that! Corrected now.

2022-03-05 11:12 UTC, mppalves commented on modules/31_past/grasslands_feb22/equations.gms
> +  vm_prod(j2,"pasture") =e= sum(grassland, v31_grass_area(j2,grassland,"rainfed")
Agreed!

2022-03-05 11:19 UTC, mppalves commented on modules/31_past/grasslands_feb22/equations.gms
> +*' into managed pastures and rangelands, an extension of the land matrix implemented
Yes, but unfortunatelly the good results looked like a coincidence at that particular run. After I merged the new develop with my branch I noticed the model consistently underestimating grassland areas in the first time step. So, I tested with the land use matrix and the results improved. I think for my next paper it would be better to have this implementation for the sake of the results.

2022-03-08 10:56 UTC, mppalves commented on modules/31_past/grasslands_feb22/preloop.gms
> +*' @code
That slipped! Fixed already.

2022-03-08 10:57 UTC, mppalves commented on modules/31_past/grasslands_feb22/preloop.gms
> +
Mattermost!

2022-03-08 11:04 UTC, mppalves commented on modules/31_past/grasslands_feb22/equations.gms
> +q31_yield_grassl_pastr(j2,grassland,w)..
Fixed

2022-03-08 14:43 UTC, tscheypidi commented on config/default.cfg
> +cfg$gms$c13_tccost_mpastr <- "medium"		# def = medium
Yeah, I would suggest to remove it. Try to keep complexity as low as possible

2022-03-08 14:45 UTC, tscheypidi commented on config/default.cfg
> +cfg$gms$s31_limit_calib <- 1       # def = 1
I agree that it should be the same. Would be good if you could contact Kristine and discuss with here whether there might be an easier way to describe it.

2022-03-08 14:45 UTC, tscheypidi commented on modules/13_tc/exo/sets.gms
>  	scen13 tc cost scenario
for me was only important that this realization was tested and still runs. No need from my side to add further images

2022-03-08 14:50 UTC, tscheypidi commented on modules/31_past/grasslands_feb22/equations.gms
> +*' into managed pastures and rangelands, an extension of the land matrix implemented
and the underestimation cannot be fixed by adjusting corresponding costs for conversion?

2022-03-08 14:53 UTC, tscheypidi commented on modules/31_past/grasslands_feb22/not_used.txt
> +vm_prod_reg, variable, not needed
sounds good

2022-03-08 16:02 UTC, mppalves commented on modules/31_past/grasslands_feb22/equations.gms
> +*' into managed pastures and rangelands, an extension of the land matrix implemented
It doesn't seem so because with the land transition matrix I'm not penalizing the expansion of grasslands but the conversion between rangelands to managed pastures and vice versa. With the expansion costs, I'm charging the expansion of managed pastures and rangelands regardless of the origin.

2022-03-08 16:50 UTC, mppalves commented on config/default.cfg
> +cfg$gms$s31_limit_calib <- 1       # def = 1
How does this version, sound?

Switch that allows selecting how yield calibration factors will be calculated.
If 0, grassland/crop yields calibration will be calculated as multiplicative relative values.
If 1, calibration values will be limited to additive absolute values when modeled yields strongly underestimate historical values. For more information, read the description on the 'preloop' of module X

2022-03-09 07:10 UTC, mppalves commented on config/default.cfg
> +cfg$gms$c13_tccost_mpastr <- "medium"		# def = medium
Done!

2022-03-09 07:10 UTC, mppalves commented on modules/13_tc/exo/sets.gms
>  	scen13 tc cost scenario
Done!

2022-03-09 07:10 UTC, mppalves commented on modules/31_past/grasslands_feb22/equations.gms
> +q31_yield_grassl_range(j2,grassland,w)..
Done

2022-03-09 07:11 UTC, mppalves commented on modules/31_past/grasslands_feb22/equations.gms
> +  vm_prod(j2,"pasture") =e= sum(grassland, v31_grass_area(j2,grassland,"rainfed")
done

2022-03-09 07:11 UTC, mppalves commented on modules/31_past/grasslands_feb22/equations.gms
> +
Done

2022-03-09 07:11 UTC, mppalves commented on modules/31_past/grasslands_feb22/not_used.txt
> +pcm_land, input, not needed
done

2022-03-09 07:12 UTC, mppalves commented on modules/31_past/grasslands_feb22/not_used.txt
> +vm_prod_reg, variable, not needed
done... one less interface in module 31_past

2022-03-09 07:13 UTC, mppalves commented on modules/31_past/grasslands_feb22/preloop.gms
> +*' @code
Done

2022-03-09 07:13 UTC, mppalves commented on modules/31_past/grasslands_feb22/preloop.gms
> +
Done?

2022-03-09 07:13 UTC, mppalves commented on scripts/start/projects/paper_grassland.R
> +# description:
Done

2022-03-09 07:32 UTC, mppalves commented on CHANGELOG.md
> + - **literature** Added new .bib reference for KleinGoldewijk.2017
done

2022-03-09 07:34 UTC, mppalves reviewed
All comments are addressed

2022-03-09 13:41 UTC, tscheypidi commented on config/default.cfg
> +cfg$gms$s31_limit_calib <- 1       # def = 1
sounds good

2022-03-09 13:44 UTC, tscheypidi commented on modules/31_past/grasslands_feb22/equations.gms
> +*' into managed pastures and rangelands, an extension of the land matrix implemented
my idea was that only the expansion of managed pastures should be penalized as it involves some costs and for these costs the origin should not play a role. I would not put any costs on the expansion of rangelands.

2022-03-09 15:09 UTC, weindl commented
Question regarding the first set of comparison plots: does the run "default_new_mar22" include already the new endo_ja22 realization of the 13_tc module?

2022-03-09 15:22 UTC, mppalves commented
> Question regarding the first set of comparison plots: does the run "default_new_mar22" include already the new endo_ja22 realization of the 13_tc module?

Yes Isabelle, the realization endo_jun18 is not compatible anymore with this implementation and was replaced by the endo_jan22. So, all the runs flagged as new are using the realization endo_jan22.

2022-03-09 19:02 UTC, weindl requested changes

2022-03-09 19:02 UTC, weindl commented on config/default.cfg
> +cfg$gms$c31_past_suit_scen  <- "ssp126"   # def = "ssp126"
However, it could be an option to add a row c31_past_suit_scen earlier in the scenario_config.csv, and select there the respective switches for the different SSP scenarios.

2022-03-10 16:31 UTC, mppalves commented on config/default.cfg
> +               validation  = "rev4.68_h12_validation.tgz",
Good point. I'm running the preprocessing for all scenarios to be added in the scenario_config.csv!

2022-03-10 16:37 UTC, mppalves commented on config/default.cfg
>                 calibration = "calibration_H12_sticky_feb18_free_18Jan22.tgz")
The results from  IPSL-CM6A-LR-SSP2-set18 were not calibrated. The results below show the results with the new realization ON after calibration:

![image](https://user-images.githubusercontent.com/37006832/157710876-744ff0a2-5187-4d3e-a53e-4224b9ce6468.png)

![image](https://user-images.githubusercontent.com/37006832/157710554-7675a0ac-aa2b-4b9f-b3ba-041f6ef2d4bb.png)

2022-03-10 16:44 UTC, mppalves commented on config/default.cfg
> +cfg$gms$c31_past_suit_scen  <- "ssp126"   # def = "ssp126"
I consider adding c31_past_suit_scen to the scenario_config.csv a very good option! I will do it. Also, I think ssp245 is a better scenario to be left as default.

2022-03-10 16:54 UTC, mppalves commented on modules/31_past/grasslands_feb22/equations.gms
> +*' Grassland yileds are estimated separetely for rangelands and managed pastures
Thanks for spotting that!

2022-03-10 16:54 UTC, mppalves commented on modules/31_past/grasslands_feb22/equations.gms
> +*' yields of manged pastures through 'vm_tau', whereas rangeland yields are kept
Thanks for spotting that!

2022-03-10 17:08 UTC, mppalves commented on modules/31_past/grasslands_feb22/equations.gms
> +*' following equations. 'v31_grass_transitions' stores the all the conversion between
Thanks for spoting that!

2022-03-10 17:40 UTC, mppalves commented on modules/31_past/grasslands_feb22/input.gms
> +table f31_pastr_suitability(t_all,j,ssp_past) LPJmL potential yields per cell (rainfed and irrigated) (tDM per ha per yr)
Thanks!

2022-03-10 17:47 UTC, mppalves commented on modules/31_past/grasslands_feb22/preloop.gms
> +i31_grass_hist_yld(t_past,i,grassland) = (f31_grass_bio(t_past,i, grassland) /
"f31_grass_bio" is grazed biomass from 1965 to 2010. You're correct, the description should be (tDM per yr) or just (tDM) as the year is already a set... (?)

2022-03-10 17:49 UTC, mppalves commented on modules/31_past/grasslands_feb22/realization.gms
> +*' related degradation of pastures.
Good point

2022-03-10 17:52 UTC, mppalves commented on modules/31_past/grasslands_mar22/equations.gms
> +*' Grassland yileds are calculated separetely for rangelands and managed pastures.
yes!

2022-03-10 18:20 UTC, mppalves commented on scripts/start/projects/paper_grassland.R
> +    if(ssp_setting == "SSP4") {cfg$gms$c31_past_suit_scen  <- "ssp585"}
Yes, the RCPs have little impact on the output, but for consistency, I will create preprocessing with all possible combinations of SSP and RCPs. I'm also updating the scenario_config with the c31_past_suit_scen switches and the new input files. The new runs should be ready by Monday.

2022-03-17 08:08 UTC, mppalves commented on modules/14_yields/managementcalib_aug19/realization.gms
> +*' performs a number of calibrations. First, a bioenergy yield correction is performed.
I changed this description as a request from Kristine

2022-03-17 08:08 UTC, mppalves commented on modules/14_yields/managementcalib_aug19/realization.gms
> +
I changed this description as a request from Kristine

2022-03-17 20:47 UTC, tscheypidi requested changes

2022-03-17 20:47 UTC, tscheypidi commented on modules/13_tc/endo_jan22/preloop.gms
> +  i13_tc_factor(t, tautype) = f13_tc_factor(t,"%c13_tccost%");
`i13_tc_factor` does not depend anymore on `tautype`, right? please reduce its dimensionality

2022-03-17 20:47 UTC, tscheypidi commented on modules/13_tc/exo/preloop.gms
> +  i13_tc_exponent(t,tautype) = f13_tc_exponent(t,"%c13_tccost%");
same here as in the oder realization (remove tautype)

2022-03-17 20:47 UTC, tscheypidi commented on modules/13_tc/endo_jan22/preloop.gms
> +  i13_tc_factor(t, tautype) = f13_tc_factor(t,"%c13_tccost%");
btw. what happened with `i13_tc_exponent`? This seems to be missing here, right?

2022-03-17 20:47 UTC, tscheypidi commented on modules/31_past/grasslands_mar22/equations.gms
> + sum(ct,i31_grass_yields(ct,j2,"range","rainfed"));
I think we talked already about this, but you assume that there is only rainfed production, right? In that case none of the variables or parameters should have `w` as dimension. Please remove it everywhere where it is being used

2022-03-17 20:47 UTC, tscheypidi commented on modules/31_past/grasslands_mar22/equations.gms
> +  vm_prod(j2,"pasture") =e= sum(grassland, v31_grass_area(j2,grassland,"rainfed")
I believe it makes more sense to merge the first three equations into one

```suggestion
  vm_prod(j2,"pasture") =e= v31_grass_area(j2,"range")*sum(ct,i31_grass_yields(ct,j2,"range"))
                                              + v31_grass_area(j2,"pastr")*sum(ct,i31_grass_yields(ct,j2,"pastr"))* sum((cell(i2,j2), supreg(h2,i2)), vm_tau(h2, "pastr") / fm_pastr_tau_hist("y1995",h2));                                         
```
Doing so reduces the number of equations as well as variables and in particular avoids creating a variable for rangeland yields while they are actually exogneously prescribed

2022-03-17 20:47 UTC, tscheypidi commented on modules/31_past/grasslands_mar22/equations.gms
> +  sum(cell(i2,j2), v31_grass_area(j2,"pastr","rainfed")) =l= sum((cell(i2,j2),ct),i31_manpast_suit(ct,j2));
not sure whether it makes a difference in overall performance but I would recommend to just introduce an upper bound to the variable in `presolve.gms` instead of introducing an extra equation for that:

```
v31_grass_area.up(j2,"pastr")) = i31_manpast_suit(t,j2));
```

2022-03-17 20:47 UTC, tscheypidi commented on modules/31_past/grasslands_mar22/equations.gms
> +                            sum(grassland, v31_grass_area(j2, grassland, "rainfed") - pc31_grass(j2,grassland));
Units don't add up: left hand side should be in mio. USD, but right hand side seems to be in mio. ha

2022-03-17 20:47 UTC, tscheypidi commented on modules/31_past/grasslands_mar22/equations.gms
> +
This equation does not make any sense to me (units don't add up) . It looks like $ = ton + $, or considering the current calculation above $ = ton + ha.

2022-03-23 13:37 UTC, weindl commented on modules/31_past/grasslands_feb22/equations.gms
> +*' into managed pastures and rangelands, an extension of the land matrix implemented
I see now also Jan's point "expansion of managed pastures should be penalized as it involves some costs and for these costs the origin should not play a role" and am fine with this approach.

One question: why do the starting values differ between the 2 approaches?

2022-03-23 13:55 UTC, weindl commented on config/default.cfg
> +cfg$gms$c31_past_suit_scen  <- "ssp126"   # def = "ssp126"
Just to be sure that did not misunderstand anything: In the comment you wrote "I think ssp245 is a better scenario to be left as default" and in the default.cfg you included:

cfg$gms$c31_past_suit_scen  <- "ssp370"   # def = "ssp370"

Is ssp245 or ssp370 better as default?

2022-03-23 14:07 UTC, weindl commented on scripts/start/projects/paper_grassland.R
> +    if(ssp_setting == "SSP4") {cfg$gms$c31_past_suit_scen  <- "ssp585"}
Great, thanks for including both aspects!

2022-03-27 19:52 UTC, weindl commented on config/default.cfg
> +cfg$gms$c31_past_suit_scen  <- "ssp126"   # def = "ssp126"
Why is c31_past_suit_scen now set to "ssp126" as default, and not to "ssp245"?

2022-04-02 09:48 UTC, tscheypidi requested changes
looks quite good now. Just one additional suggestion for further simplification and two questions concerning some mz-files which are now being copied to the modules

2022-04-02 09:48 UTC, tscheypidi commented on modules/31_past/grasslands_apr22/equations.gms
> +  q31_bv_rangeland(j2,potnatveg) .. vm_bv(j2,"rangeland",potnatveg)
why have you put that in two separate equations? isn't that just:

```
vm_bv(j2,<set>,potnatveg)
  					=e=
					vm_land(j2,"past") * fm_luh2_side_layers(j2,<set>) * fm_bii_coeff(<set>,potnatveg) * fm_luh2_side_layers(j2,potnatveg);
					```
					
where `<set>` is a placeholder for a set containing "manpast" and "rangeland"?

2022-04-02 09:48 UTC, tscheypidi commented on modules/31_past/input/files
> +f31_pastr_suitability.mz
what is the mz-file used for here?

2022-04-02 09:48 UTC, tscheypidi commented on modules/40_transport/input/files
> +transport_distance.mz
same here? what is the mz-file for?

2022-04-04 19:50 UTC, tscheypidi commented on modules/31_past/grasslands_apr22/equations.gms
> +  q31_bv_rangeland(j2,potnatveg) .. vm_bv(j2,"rangeland",potnatveg)
can you quickly react on my suggestion?

2022-04-05 08:10 UTC, tscheypidi approved these changes

2022-04-05 12:10 UTC, weindl approved these changes
Looks good!

2022-04-06 06:19 UTC, merged