FSEC modeling script
magpiemodel/magpie pull request #381
Opened 2022-03-17 15:40 UTC by FelicitasBeier

## :bird: Purpose of this PR :bird:

- added FSEC modeling script for global runs
- updated BII disaggregation output script (outputs written in separate folder for easier project reporting)

## :wrench: Checklist for PR creator :wrench:

- [x] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts

- [x] Providing additional information based on PR label

* Low risk : No new model run needed.

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The new code doesn't contain declared but unused parameters or variables.
- [ ] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2022-03-17 16:49 UTC, tscheypidi requested changes

2022-03-17 16:49 UTC, tscheypidi commented on scripts/start/projects/project_FSEC_Scenarios.R
> +source("scripts/performance_test.R")
what is that used for?

2022-03-17 16:49 UTC, tscheypidi commented on scripts/start/projects/project_FSEC_Scenarios.R
> +  # (cannot be implemented)
one could also define these scenarios in the scenario config and use them via `setScenario(cfg, "scenarioName")`, but you prefer to have them directly defined here in the script?

2022-03-17 16:58 UTC, FelicitasBeier commented on scripts/start/projects/project_FSEC_Scenarios.R
> +source("scripts/performance_test.R")
Not sure, it's copy-pasted from other start scripts, but I thought:
- library(gms) is necessary for the setScenario() function call
- source("scripts/start_functions.R") to load start_run(cfg) function which is needed to start MAgPIE runs
- source("scripts/performance_test.R") maybe some tests that might be useful?

2022-03-17 17:02 UTC, FelicitasBeier commented on scripts/start/projects/project_FSEC_Scenarios.R
> +  # (cannot be implemented)
Yes, because it is an ongoing effort with new developments coming, and I want to avoid to update the scenario and including more and more switches that would then also have to be changed for the existing scenarios

2022-03-17 17:23 UTC, tscheypidi commented on scripts/start/projects/project_FSEC_Scenarios.R
> +source("scripts/performance_test.R")
I was just referring to the last line which is (as far as I can see) not needed in your script

2022-03-17 17:24 UTC, tscheypidi commented on scripts/start/projects/project_FSEC_Scenarios.R
> +  # (cannot be implemented)
makes sense

2022-03-18 19:47 UTC, mishkos requested changes
Just some small comments for you to quickly resolve ;)

2022-03-18 19:47 UTC, mishkos commented on scripts/start/projects/project_FSEC_Scenarios.R
> +
do we want to have the dynamic forestry realization switched on for the general setting?

2022-03-18 19:47 UTC, mishkos commented on scripts/start/projects/project_FSEC_Scenarios.R
> +### (4) Energy and transfport transformation ###
transport

2022-03-18 19:47 UTC, mishkos commented on scripts/start/projects/project_FSEC_Scenarios.R
> +  cfg$gms$c32_aff_policy   <- "ndc"
I would add NDC policies (all types) in general settings, cause they are part of reality already.

2022-03-18 19:47 UTC, mishkos commented on scripts/start/projects/project_FSEC_Scenarios.R
> +
cfg <- gms::setScenario(cfg, "SSP2", "NDC")

2022-03-21 08:49 UTC, FelicitasBeier commented on scripts/start/projects/project_FSEC_Scenarios.R
> +
Dynamic forestry (cfg$gms$forestry  <- "dynamic_feb21") is switched on by default, no? Or do you mean another switch?

2022-03-21 09:09 UTC, mishkos commented on scripts/start/projects/project_FSEC_Scenarios.R
> +
In the scenario_config.csv there is a scenario ForestryEdno that set the switches right.

2022-03-21 09:11 UTC, mishkos approved these changes

2022-03-21 13:20 UTC, FelicitasBeier commented on scripts/start/projects/project_FSEC_Scenarios.R
> +
Endo forestry is now switched on in general_settings(): cfg <- gms::setScenario(cfg, "cc", "SSP2", "NDC", "ForestryEndo")

2022-03-21 13:20 UTC, FelicitasBeier commented on scripts/start/projects/project_FSEC_Scenarios.R
> +  cfg$gms$c32_aff_policy   <- "ndc"
NDC is now added in general_settings: 
cfg <- gms::setScenario(cfg, "cc", "SSP2", "NDC", "ForestryEndo")

2022-03-21 13:21 UTC, FelicitasBeier commented on scripts/start/projects/project_FSEC_Scenarios.R
> +
added to general_settings now

2022-05-02 07:10 UTC, merged

2022-05-02 07:11 UTC, bodirsky approved these changes