land carbon sink adjustment factors added to 52_carbon
magpiemodel/magpie pull request #383
Opened 2022-03-24 13:24 UTC by flohump

## :bird: Purpose of this PR :bird:

- **52_carbon** added land carbon sink adjustment factors, needed in R post-processing

## :wrench: Checklist for PR creator :wrench:

- [ ] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The new code doesn't contain declared but unused parameters or variables.
- [ ] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2022-03-24 14:03 UTC, tscheypidi requested changes
did you test your code before creating this PR? I would expect that the compilation fails due to the syntax error in the config file

2022-03-24 14:03 UTC, tscheypidi commented on config/default.cfg
> +cfg$gms$c52_land_carbon_sink_rcp  RCPBU
I guess you meant:

```suggestion
cfg$gms$c52_land_carbon_sink_rcp  <- "RCPBU"
```

2022-03-24 14:03 UTC, tscheypidi commented on modules/52_carbon/normal_dec17/input.gms
> +i52_land_carbon_sink(t_all,i) = f52_land_carbon_sink(t_all,i,"%c52_land_carbon_sink_rcp%");
will this line of code work if the file is missing (judging from the code before you assume that it might be missing in some cases, right?)?

2022-03-24 16:30 UTC, flohump commented on modules/52_carbon/normal_dec17/input.gms
> +i52_land_carbon_sink(t_all,i) = f52_land_carbon_sink(t_all,i,"%c52_land_carbon_sink_rcp%");
Yes, the code works even if the file is missing. If the file is missing `f52_land_carbon_sink` is filled with zeros.

2022-03-24 16:31 UTC, flohump commented
> did you test your code before creating this PR? I would expect that the compilation fails due to the syntax error in the config file

I tested the code with `gams main.gms`. Therefore I missed the syntax error in the config file.

2022-03-24 20:45 UTC, tscheypidi approved these changes
looks good now...thanks for clarification.

2022-03-25 09:55 UTC, mikewin-climsci approved these changes
Is business as usual "BU" still the designated name for RCP 8.5 within MAgPIE? I don't see it in the scope of this PR to tackle the "BU" issue. However, it might be a necessary discussion in the future as objection to this viewpoint is mounting. E.g. https://www.nature.com/articles/d41586-020-00177-3

2022-03-25 10:17 UTC, flohump commented
> Is business as usual "BU" still the designated name for RCP 8.5 within MAgPIE? I don't see it in the scope of this PR to tackle the "BU" issue. However, it might be a necessary discussion in the future as objection to this viewpoint is mounting. E.g. https://www.nature.com/articles/d41586-020-00177-3

Considering the source of the data, the set element RCPBU can be interpreted as RCP7.0 or RCP8.5.

2022-03-25 10:17 UTC, merged