hypothetical carbon stocks for emission pricing
magpiemodel/magpie pull request #389
Opened 2022-04-19 19:59 UTC by flohump

## :bird: Purpose of this PR :bird:

- PR386 solved one problem under CO2 emission pricing (decline in primary forest) but introduced another problem (large shift from cropland and pasture to other land)
- This PR aims to solve both problems by introducing hypothetical carbon stocks for emission pricing and by reverting the default of cfg$gms$s56_reward_neg_emis to 0.
- By pricing only CO2 emission due to land-use change, based on current land patterns and previous carbon density (previousCarbonDensity), the decline of primary forest area can be avoided under increasing carbon density. At the same time, the overall dynamics under CO2 emission pricing are back to normal.

## :wrench: Checklist for PR creator :wrench:

- [ ] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch: PR_CO2Price_SSP2-Ref
  * Default run based on the current version of the fork from which PR is made: PR_CO2Price_after_SSP2-Ref

**Default runs are unchanged:**

![Resources_Land_Cover_Cropland-64](https://user-images.githubusercontent.com/16921122/164085211-3510b5fe-fc90-4dd3-9362-0d2ad47c6d70.png)

**Runs with CO2 pricing:** 

- Red: old setup
- Blue: current setup (PR386)
- Green: new setup

![Emissions_CO2_Land_Land_use_Change-43](https://user-images.githubusercontent.com/16921122/164085329-b1bb7f86-990c-4d00-9f9f-28e05bd10900.png)
![Productivity_Landuse_Intensity_Indicator_Tau-52](https://user-images.githubusercontent.com/16921122/164085338-b4d5b91b-61d0-4ba4-a75e-cae49afb8025.png)
![Resources_Land_Cover_Change_Forest_Managed_Forest-3](https://user-images.githubusercontent.com/16921122/164085343-7aeb2999-0aa8-4d37-971d-53c1ed50ded2.png)
![Resources_Land_Cover_Change_Forest_Natural_Forest_Primary_Forest-6](https://user-images.githubusercontent.com/16921122/164085348-2e0e0e0a-4170-44fc-8f5f-612d5555c1e7.png)
![Resources_Land_Cover_Change_Pastures_and_Rangelands-3](https://user-images.githubusercontent.com/16921122/164085350-826eec3e-1a9c-4f64-a5ab-309d9413758e.png)
![Resources_Land_Cover_Cropland-63](https://user-images.githubusercontent.com/16921122/164085354-f15229b2-00f3-4fbf-831b-43db8cdbaebc.png)
![Resources_Land_Cover_Other_Land](https://user-images.githubusercontent.com/16921122/164085356-7d5be58e-4c13-40a6-88ab-612f652afe4f.png)

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : 0.6 h
  * This PR's default :  0.46 h (newer GAMS version)

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The new code doesn't contain declared but unused parameters or variables.
- [ ] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2022-04-22 13:34 UTC, tscheypidi requested changes
Looks good overall. A question and an update request:

* You changed some interfaces. Have you checked that the outputs scripts and the functions in `magpie4` are all compatible to these changes (functions in `magpie4` in addition need to remain downwards compatible)

* The code is currently quite repetivite. I would suggest the following: Merge the carbon equations 1,2,3,4 again into one equation using dollar conditions and write a macro which produces this equation for the different land modules.

2022-04-22 13:34 UTC, tscheypidi commented on config/default.cfg
> +# * Please not the choice of s56_reward_neg_emis strongly interacts with the choice of c56_carbon_stock_pricing.
```suggestion
# * Please note the choice of s56_reward_neg_emis strongly interacts with the choice of c56_carbon_stock_pricing.
```

2022-04-22 13:34 UTC, tscheypidi commented on core/calculations.gms
> +      display pt;
please remove this display statement or provide some context as it is done for ct. Otherwise the output will be confusing

2022-04-22 13:34 UTC, tscheypidi commented on modules/31_past/endo_jun13/declarations.gms
> + q31_carbon1(j,ag_pools)  Above ground carbon content calculation for pasture (mio tC)
I thought it should be possible to write `q31_carbon(j, ag_pools, stockType)` instead and then declare this equation separately for each element  of stockType. Have you tested this? If this works, it would improve readability

2022-04-22 13:34 UTC, tscheypidi commented on modules/31_past/endo_jun13/equations.gms
> + vm_carbon_stock(j2,"past",ag_pools,"previousCarbonDensity") =e=
alternatively to my suggestion above one could also write everything in one equation and use dollar conditions to distinguish the 4 different cases

2022-04-22 13:34 UTC, tscheypidi commented on modules/32_forestry/dynamic_feb21/equations.gms
> +
would it make sense to work with a macro here? the formulations look all pretty similar across the different land modules

2022-04-22 13:36 UTC, tscheypidi commented
another question: Did you create the goxygen documentation and check whether the module descriptions now fit the new structure/interfaces of the modules? In the code I saw some documentation updates but overall had the feeling that some additional updates might be required here. In particular, the descriptions in the various `module.gms` files might now be outdated

2022-04-22 13:39 UTC, tscheypidi commented
and another question (sorry): can you show runtime comparison using the same GAMS version. I remember Marcos mentioning that runs are now around 40% faster. If this is the case this PR seems to slow down the model again quite significantly. Would be important to know what the impact of these changes on performance is

2022-04-24 09:07 UTC, flohump commented on core/calculations.gms
> +      display pt;
done.

2022-04-24 09:08 UTC, flohump commented on modules/31_past/endo_jun13/declarations.gms
> + q31_carbon1(j,ag_pools)  Above ground carbon content calculation for pasture (mio tC)
Done.

2022-04-24 09:08 UTC, flohump commented on modules/32_forestry/dynamic_feb21/equations.gms
> +
Yes. I addded 2 macros for the carbon stock calculation.

2022-04-24 09:09 UTC, flohump commented on modules/31_past/endo_jun13/equations.gms
> + vm_carbon_stock(j2,"past",ag_pools,"previousCarbonDensity") =e=
I addded 2 macros for the carbon stock calculation.

2022-04-24 09:09 UTC, flohump commented on config/default.cfg
> +# * Please not the choice of s56_reward_neg_emis strongly interacts with the choice of c56_carbon_stock_pricing.
updated.

2022-04-24 09:10 UTC, flohump commented
> another question: Did you create the goxygen documentation and check whether the module descriptions now fit the new structure/interfaces of the modules? In the code I saw some documentation updates but overall had the feeling that some additional updates might be required here. In particular, the descriptions in the various `module.gms` files might now be outdated

I made some additional revisions in the documentation, espcially in 56_ghg_policy.

2022-04-24 09:11 UTC, flohump commented
> and another question (sorry): can you show runtime comparison using the same GAMS version. I remember Marcos mentioning that runs are now around 40% faster. If this is the case this PR seems to slow down the model again quite significantly. Would be important to know what the impact of these changes on performance is

This PR has only minimal effects on run time. See the additinal figure for run time.

2022-04-24 09:15 UTC, flohump commented
> Looks good overall. A question and an update request:
> 
> * You changed some interfaces. Have you checked that the outputs scripts and the functions in `magpie4` are all compatible to these changes (functions in `magpie4` in addition need to remain downwards compatible)

Yes, I updated the magpie4 carbonstock function (downwards compatible).
https://github.com/pik-piam/magpie4/commit/0e9e90a33409690bdee6a3680a510f2476291e58
The test runs shown here used the updated version. 

> * The code is currently quite repetivite. I would suggest the following: Merge the carbon equations 1,2,3,4 again into one equation using dollar conditions and write a macro which produces this equation for the different land modules.

I added 2 macros for carbon stock calcuatio, which allows to considerably reduced the number of required equaitons.

2022-04-25 12:51 UTC, tscheypidi approved these changes
looks good

2022-04-27 13:55 UTC, tscheypidi requested changes
I put some requests for technical imrpovements. I was focussing on technical aspects, the contenwise changes need to reviewed by someone else.

2022-04-27 13:55 UTC, tscheypidi commented on config/default.cfg
> -cfg$gms$s56_peatland_policy <- 1			# def = 1
so this is not needed anymore?

2022-04-27 13:55 UTC, tscheypidi commented on core/sets.gms
was `beccs` in there before by mistake or why is it now taken out / replaced by `peatland` and `resid_burn`?

2022-04-27 13:55 UTC, tscheypidi commented on modules/35_natveg/dynamic_feb21/scaling.gms
> +v35_secdforest_reduction.scale(j,ac) = 10e-3;
what is the purpose of these various scaling updates?

2022-04-27 13:55 UTC, tscheypidi commented on modules/51_nitrogen/ipcc2006_sep16/presolve.gms
> +*vm_btm_reg.lo(i,"som",n_pollutants) = -Inf;
please don't add commented code
```suggestion
```

2022-04-27 13:55 UTC, tscheypidi commented on modules/56_ghg_policy/price_jan20/preloop.gms
> +***fix to zero be default here. Bounds are released in the respective modules.
why is that fixed to 0?

2022-04-27 13:55 UTC, tscheypidi commented on modules/58_peatland/on/equations.gms
> +
please improve the syntax:

* use a single equation instead of three separate ones
* store the conversion factors in a parameter
* create a mapping between emission types and sum over this mapping

2022-04-28 12:41 UTC, flohump commented on config/default.cfg
> -cfg$gms$s56_peatland_policy <- 1			# def = 1
Yes. This is now covered by `c56_emis_policy`.

2022-04-28 12:43 UTC, flohump commented on core/sets.gms
`beccs` was unused and therefore removed.
`resid_burn` was missing.

2022-04-28 12:47 UTC, flohump commented on modules/35_natveg/dynamic_feb21/scaling.gms
> +v35_secdforest_reduction.scale(j,ac) = 10e-3;
I removed some variables and changed the dimension of other variables. 
Therefore, I used gdx::calc_scaling("fulldata.gdx") for `SSP-Ref` and `SSP-Pk900` to get updated scaling factors. I also noticed that some scaling factors had been declared twice, in the cost module and the module defining the varible. In that case, I kept the later one.

2022-04-28 12:48 UTC, flohump commented on modules/56_ghg_policy/price_jan20/preloop.gms
> +***fix to zero be default here. Bounds are released in the respective modules.
To avoid unbounded variable dimensions.

2022-04-28 13:04 UTC, tscheypidi commented on modules/56_ghg_policy/price_jan20/preloop.gms
> +***fix to zero be default here. Bounds are released in the respective modules.
i think that should be taken care off by the modules filling in the information.

2022-04-29 09:06 UTC, flohump commented on modules/56_ghg_policy/price_jan20/preloop.gms
> +***fix to zero be default here. Bounds are released in the respective modules.
I moved the fixing of variables to the responsible modules.

2022-05-02 07:04 UTC, bodirsky requested changes
a few open questions. Some may need discussion, as I was not always sure whether they need change.

2022-05-02 07:04 UTC, bodirsky commented on modules/59_som/cellpool_aug16/equations.gms
>  q59_carbon_soil(j2,pools59) ..
are always all three calculations done, or are they alternatively selected? Why do you need all three in parallel?

2022-05-05 20:07 UTC, flohump commented on config/default.cfg
> +cfg$gms$s13_max_gdp_shr <- 1 # def = 1
I changed this back to 0.002

2022-05-05 20:19 UTC, flohump commented on config/default.cfg
> +cfg$gms$s70_past_mngmnt_factor_fix <- "2005"	# def = 2005
config added cfg$gms$s70_past_mngmnt_factor_fix with default 2005 (previous default was 2010). The previous setting caused a strong spike in CO2 emissions from pasture expansion in SSA. With 2005, this can be avoided.

2022-05-05 20:20 UTC, flohump commented on core/macros.gms
> +* macro for simple carbon stocks
Carbon stocks for cropland, pasture and urban land are simple to calculate while carbons stocks with age-classes are more difficult.

2022-05-05 20:22 UTC, flohump commented on modules/56_ghg_policy/price_jan20/equations.gms
> +                     sum((ct,cell(i2,j2)), im_pollutant_prices(ct,i2,pollutants,emis_cell_yr56)));
Well, I think you implemented this a couple of years ago. But you are right, it can be done on the regional level. I revised the code accordingly.

2022-05-05 20:29 UTC, flohump commented on config/default.cfg
> +# * 	previousLandPattern: CO2 emissions for pricing are based on carbon stocks with previous land patterns and current carbon density
Yes, there is no endogeneity in this option. This option is only added for completeness.

2022-05-05 20:30 UTC, flohump commented on modules/56_ghg_policy/price_jan20/sets.gms
> +   rice, ent_ferm /
Yes. It was unused for a quite a while.

2022-05-05 21:41 UTC, tscheypidi requested changes

2022-05-05 21:41 UTC, tscheypidi commented on CHANGELOG.md
> + - **config** changed default setting for s56_reward_neg_emis from 0 to -Inf
I think you completely removed that switch, right?

2022-05-05 21:41 UTC, tscheypidi commented on modules/13_tc/endo_jan22/input.gms
> + s13_max_gdp_shr Maximum tech cost as share of regional GDP / 0.002 /
that means all runs work again with a max share of 0.002?

2022-05-05 21:41 UTC, tscheypidi commented on modules/35_natveg/dynamic_feb21/input.gms
> +s35_hvarea_primforest annual primforest harvest rate for s35_hvarea equals 1 (percent per year) / 0 /
why has this been changed now?

2022-05-05 21:41 UTC, tscheypidi commented on modules/44_biodiversity/bv_btc_mar21/input.gms
>  ;
new default value?

2022-05-05 21:41 UTC, tscheypidi commented on modules/56_ghg_policy/price_jan20/equations.gms
> +*' Actual cellular CO2 emissions are calculated based on changes in carbon stocks between timesteps in the interface `vm_carbon_stock`.
why are you talking about cellular emissions if the equation is regional?

2022-05-05 21:41 UTC, tscheypidi commented on modules/56_ghg_policy/price_jan20/equations.gms
> +*' Actual GHG emissions
Please use complete sentences in the documentation

2022-05-05 21:41 UTC, tscheypidi commented on modules/56_ghg_policy/price_jan20/preloop.gms
> +*vm_btm_reg.fx(i,emis_oneoff,pollutants)$(not sameas(pollutants,"co2_c")) = 0;
please delete code, if it is not being used.

2022-05-05 21:41 UTC, tscheypidi commented on scripts/start/extra/carbon_pricing.R
>  }
please delete code if you being used.

2022-05-06 06:10 UTC, flohump commented on CHANGELOG.md
> + - **config** changed default setting for s56_reward_neg_emis from 0 to -Inf
Yes. I changed it in the changelog.

2022-05-06 06:10 UTC, flohump commented on modules/13_tc/endo_jan22/input.gms
> + s13_max_gdp_shr Maximum tech cost as share of regional GDP / 0.002 /
Yes!

2022-05-06 06:11 UTC, flohump commented on modules/35_natveg/dynamic_feb21/input.gms
> +s35_hvarea_primforest annual primforest harvest rate for s35_hvarea equals 1 (percent per year) / 0 /
Default values set by running the model with `scripts/start/default.R`

2022-05-06 06:11 UTC, flohump commented on modules/44_biodiversity/bv_btc_mar21/input.gms
>  ;
Default values set by running the model with `scripts/start/default.R`

2022-05-06 06:11 UTC, flohump commented on modules/56_ghg_policy/price_jan20/equations.gms
> +*' Actual cellular CO2 emissions are calculated based on changes in carbon stocks between timesteps in the interface `vm_carbon_stock`.
I have updated the documentation.

2022-05-06 06:12 UTC, flohump commented on modules/56_ghg_policy/price_jan20/preloop.gms
> +*vm_btm_reg.fx(i,emis_oneoff,pollutants)$(not sameas(pollutants,"co2_c")) = 0;
done.

2022-05-06 06:12 UTC, flohump commented on scripts/start/extra/carbon_pricing.R
>  }
done

2022-05-06 06:12 UTC, flohump commented on modules/56_ghg_policy/price_jan20/equations.gms
> +*' Actual GHG emissions
done.

2022-05-06 06:53 UTC, bodirsky approved these changes
Nice. Reduced code quite a bit.

maybe reconsider the 0.002 as too strict (for low income countries with high ag share).

2022-05-06 06:53 UTC, bodirsky commented on config/default.cfg
> +cfg$gms$s13_max_gdp_shr <- 0.002 # def = 0.002
we could also go for 5% if it caused infeasibilties, 100% of gdp just seemd to much...

2022-05-06 06:53 UTC, bodirsky commented on modules/13_tc/endo_jan22/input.gms
> + s13_max_gdp_shr Maximum tech cost as share of regional GDP / 0.002 /
0.002 may be a bit low in countries where agriculture is 50% of gdp, no?

2022-05-06 06:55 UTC, tscheypidi approved these changes
looks good

2022-05-06 07:47 UTC, merged