[Draft]: Modifications to the factor requirements modules and variables
magpiemodel/magpie pull request #394
Opened 2022-05-03 12:37 UTC by emolinab

## :bird: Purpose of this PR :bird:

- Briefly explain the purpose of this pull request

## :wrench: Checklist for PR creator :wrench:

- [ ] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The new code doesn't contain declared but unused parameters or variables.
- [ ] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2022-05-12 13:31 UTC, tscheypidi requested changes
looks good. My main request is only to stick to snake_case syntax for realization names to stay with our established standard

2022-05-12 13:31 UTC, tscheypidi commented on CHANGELOG.md
> +- **config** Update of regional and grid inputs from 4.68 to rev4.69, and additional files to 4.17. Removed free/dynamic sticky switch, and added scalars used in mixed_regional factor costs realizati
this comment is just meant as a reminder to update the additional data revision to the final version when PR is ready.

2022-05-12 13:31 UTC, tscheypidi commented on CHANGELOG.md
> +- **38_factor_costs** mixed_feb17 and fixed_per_ton_mar18 realzations removed because they are not bein used at the moment.
```suggestion
- **38_factor_costs** mixed_feb17 and fixed_per_ton_mar18 realizations removed because they are not being used at the moment.
```

2022-05-12 13:31 UTC, tscheypidi commented on config/default.cfg
> +# * (perTonFAO)            factor costs fixed per ton
If I am not mistaken this might be so far the only occurrence of camel case writing for a realization name, other realizations primarily use snake case. To avoid mixing styles I would like to ask you to use snake case here as well without capital letters (e.g. `per_ton_fao_may22` or just `per_ton_may22`)

2022-05-12 14:14 UTC, deleip commented on config/default.cfg
> +               additional  = "additional_data_rev4.17.tgz",
4.17 is the correct version, I now removed Edna's comment in the PR (4.17a was an intermediate version used for testing before Florian's PR)

2022-05-12 14:32 UTC, deleip commented on CHANGELOG.md
> +- **config** Update of regional and grid inputs from 4.68 to rev4.69, and additional files to 4.17. Removed free/dynamic sticky switch, and added scalars used in mixed_regional factor costs realizati
you mean to update it to the newest version that has been created in the meantime? or is this related to the confusion between 4.17 and 4.17a?

2022-05-17 09:34 UTC, mishkos requested changes
Some minor comments, mostly regarding the description. Since many variables have change their names, is the magpie4 library updated accordingly?

2022-05-17 09:34 UTC, mishkos commented on modules/31_past/grasslands_apr22/declarations.gms
> +vm_cost_prod_past(i)                                    Factor costs for pasture (mio. USD05MER per yr)
Production costs instead of factor costs

2022-05-17 09:34 UTC, mishkos commented on modules/38_factor_costs/mixed_reg_feb17/declarations.gms
> +q38_cost_prod_crop(i,req)      Regional factor input costs for plant production (mio. USD05MER per yr)
"Regional factor input costs of capital and labor for plant production"

2022-05-17 09:34 UTC, mishkos commented on modules/38_factor_costs/mixed_reg_feb17/declarations.gms
> +vm_cost_prod_crop(i,req)       Crop factor costs (mio. USD05MER per yr)
"Regional factor costs of capital and labor for plant production"

2022-05-17 09:34 UTC, mishkos commented on modules/38_factor_costs/mixed_reg_feb17/declarations.gms
> +p38_cost_share(t,i,req)       Capital anad labor shares  (1)
typo. 
"Capital and labor factor shares in unit cost of plant production"  (correct?)

2022-05-17 09:34 UTC, mishkos commented on modules/38_factor_costs/module.gms
>  $Ifi "%factor_costs%" == "sticky_labor" $include "./modules/38_factor_costs/sticky_labor/realization.gms"
shouldn't there be also the mixed_reg_feb17?

2022-05-17 09:34 UTC, mishkos commented on modules/31_past/static/presolve.gms
> +vm_cost_prod_past.fx(i) = 0;
why is this necessary to initialize with 0?

2022-05-17 09:34 UTC, mishkos commented on modules/18_residues/off/preloop.gms
> +vm_cost_prod_kres.fx(i,kres)           = 0;
is it necessary to initialize it with zero?

2022-05-17 09:34 UTC, mishkos commented on modules/38_factor_costs/per_ton_fao_may22/declarations.gms
> +q38_cost_prod_crop(i,req)      Regional factor input costs for plant production (mio. USD05MER per yr)
update the description as in the previous suggestion.

2022-05-17 09:34 UTC, mishkos commented on modules/38_factor_costs/sticky_feb18/declarations.gms
> + p38_cost_share(t,i,req)               Capital anad labor shares  (1)
update the description as in the previous suggestion.

2022-05-17 09:34 UTC, mishkos commented on modules/38_factor_costs/sticky_labor/declarations.gms
> + p38_cost_share(t,i,req)               Capital anad labor shares  (1)
update the description as in the previous suggestion.

2022-05-17 09:34 UTC, mishkos commented on modules/38_factor_costs/sticky_labor/declarations.gms
> + vm_cost_prod_crop(i,req)                  Factor costs  (mio USD05MER  per yr)
update the description as in the previous suggestion.

2022-05-17 09:34 UTC, mishkos commented on modules/70_livestock/fbask_jan16/declarations.gms
> + p70_cost_share_livst(t,i,req)                    Capital anad labor shares  (1)
update the description as in the previous suggestion.

2022-05-17 14:25 UTC, emolinab commented on modules/31_past/endo_jun13/declarations.gms
> + vm_cost_prod_past(i)                  Factor costs for pasture (mio. USD05MER per yr)
Thanks Misko for pointing to this! We are going to use the description from the equations such as: "Costs for putting animals on grasslands and expanding grassland areas". Would this work?

2022-05-17 14:53 UTC, emolinab commented on modules/38_factor_costs/mixed_reg_feb17/declarations.gms
> +p38_cost_share(t,i,req)       Capital anad labor shares  (1)
What about: Capital and labor shares of the regional factor costs for plant production. Your suggestion sounded to us like these shares are of the overall production costs instead of the factor costs.

2022-05-18 07:22 UTC, mishkos commented on modules/31_past/endo_jun13/declarations.gms
> + vm_cost_prod_past(i)                  Factor costs for pasture (mio. USD05MER per yr)
But these costs don't include grassland expansion costs, do they? Maybe I'm looking in an old equation... I'd still call it pasture production costs, putting animals to grazing is a proxy for it. If not sure, ask Isabelle directly.

2022-05-18 07:22 UTC, mishkos commented on modules/38_factor_costs/mixed_reg_feb17/declarations.gms
> +p38_cost_share(t,i,req)       Capital anad labor shares  (1)
ok

2022-05-18 07:29 UTC, emolinab commented on modules/31_past/endo_jun13/declarations.gms
> + vm_cost_prod_past(i)                  Factor costs for pasture (mio. USD05MER per yr)
I used the definition of the equations (eq) that were before our changes (we didn't modify this definitions): https://github.com/emolinab/magpie/blob/develop/modules/31_past/endo_jun13/declarations.gms#L12
https://github.com/emolinab/magpie/blob/develop/modules/31_past/grasslands_apr22/declarations.gms#L11

2022-05-18 14:16 UTC, emolinab commented on modules/38_factor_costs/module.gms
>  $Ifi "%factor_costs%" == "sticky_labor" $include "./modules/38_factor_costs/sticky_labor/realization.gms"
just updated the automatically defined outputs and definitions

2022-05-18 14:19 UTC, emolinab commented on modules/18_residues/off/preloop.gms
> +vm_cost_prod_kres.fx(i,kres)           = 0;
same as before? this realization is considering residues off

2022-05-18 15:09 UTC, mishkos commented on modules/31_past/static/presolve.gms
> +vm_cost_prod_past.fx(i) = 0;
ok

2022-05-18 15:12 UTC, mishkos approved these changes
thanks!

2022-05-20 07:48 UTC, tscheypidi approved these changes
looks good

2022-05-20 09:59 UTC, merged