New protected area baseline and option for restoration in future land conservation options
magpiemodel/magpie pull request #396
Opened 2022-05-16 14:25 UTC by pvjeetze

## :bird: Purpose of this PR :bird:

- So far MAgPIE only included 351.81 Mha of protected areas (in IUCN Cats. I & II). However, legally protected area in MAgPIE grid cells covered an area of 864.31 Mha in 1995 (IUCN catergories I-VI + not assigned) and 1662.02 in 2020. This implementation closes this gap using data on the protected area in the pasture, primary forest, secondary forest and other land classes estimated based on ESA CCI LULC data and geospatial data on protected areas from https://www.protectedplanet.net/en 
- The new implementation also allows to restore land to natural vegetation classes based on future conservation templates.

## :wrench: Checklist for PR creator :wrench:

- [x] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [x] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [x] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : 37.42 mins
  * This PR's default :  36.25 mins
![runtime](https://user-images.githubusercontent.com/50408549/168615153-50033932-61d8-4222-8e82-564dfe83b50a.png)

- [x] Added changes to `CHANGELOG.md`
- [x] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [x] No hard coded numbers and cluster/country/region names.
- [x] The new code doesn't contain declared but unused parameters or variables.
- [x] Where relevant, In-code comments added including documentation comments.
- [x] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [x] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [x] Self-review of my own code.
- [x] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
New preprocessing has to be set up still

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [x] PR is labeled correctly.
- [x] `CHANGELOG` is updated correctly
- [x] No hard coded numbers and cluster/country/region names.
- [x] No unnecessary increase in module interfaces
- [x] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [x] In-code comments and documentation comments are satisfactory.
- [x] model behavior/performance is satisfactory.
- [x] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [x] PR is labeled correctly.
- [x] `CHANGELOG` is updated correctly
- [x] No hard coded numbers and cluster/country/region names.
- [x] Changes to the model are scientifically sound
- [x] In-code comments and documentation comments are satisfactory.
- [x] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

🔴 lines: default in current develop. 🟢  lines: default of this PR 

![Resources_Land_Cover_Cropland](https://user-images.githubusercontent.com/50408549/168615167-d68ac287-e71e-4f5e-a952-30ffe13894b8.png)
![Resources_Land_Cover_Forest](https://user-images.githubusercontent.com/50408549/168615142-5b251625-f6f1-499a-ab3f-82d4f2fa02f7.png)
![Resources_Land_Cover_Other_Land](https://user-images.githubusercontent.com/50408549/168615146-83c8c7e2-415e-4c18-97cd-b5c48cfe5dbe.png)
![Resources_Land_Cover_Pastures_and_Rangelands](https://user-images.githubusercontent.com/50408549/168615150-5b7bc590-33b8-43fe-b3d0-ac05ace43ab1.png)
![Productivity_Landuse_Intensity_Indicator_Tau](https://user-images.githubusercontent.com/50408549/168615165-2f7bfebe-ae34-4092-9828-b92844b4e50b.png)
![Costs_TC](https://user-images.githubusercontent.com/50408549/168615155-da1b4243-4eee-4303-8ebf-8b1c83ec2746.png)
![Emissions_CO2_Land_Land_use_Change_GLO](https://user-images.githubusercontent.com/50408549/168615160-f937de74-bb5f-44c9-9c28-7b19d0efddcb.png)
![Emissions_CO2_Land_Land_use_Change_reg](https://user-images.githubusercontent.com/50408549/168615163-25fdb80f-0a1a-4bc3-93bc-01b8423c26c6.png)

2022-05-17 09:11 UTC, flohump reviewed
Thanks for including these improvements!
In general looks fine to me. 
I have some smaller comments for clarification. 
We still need to agree on a new value for `cfg$gms$s13_max_gdp_shr`.
Disclaimer: I had several bilateral talks with @pvjeetze regarding the suggested model changes in this PR.

2022-05-17 12:17 UTC, tscheypidi requested changes
nice work! I put some comments/change requests. In addition, please also compile the goxygen document and have a look at it. I think it might require some rework / more details in some parts.

2022-05-17 12:17 UTC, tscheypidi commented on modules/22_land_conservation/area_based_apr22/equations.gms
> +            sum((ct,land_natveg,consv_type), pm_land_conservation(ct,j2,land_natveg,consv_type));
Currently, it seems that you have a mix of constraints, some of which are set here in the land conservation module and others which are set in the corresponding land modules (based on `pm_land_conservation`. Please choose only one of the two options: Either do all constraints here (in which case `pm_land_conservation` is not needed anymore) or do all in the corresponding land modules (in which case you don't need `vm_land` anymore as input).

I don't have a clear preference, could only imagine that in some cases the treatment of land conservations constraints might be land realization specific in which case option two would be preferable.

2022-05-17 12:17 UTC, tscheypidi commented on modules/22_land_conservation/area_based_apr22/presolve.gms
> +if(s22_restore_land = 1 OR m_year(t) <= sm_fix_SSP2,
I think using `sm_fix_SSP2` here is correct as the description of this switch reads " Year until which **all parameters** are fixed to SSP2 values"

2022-05-17 12:17 UTC, tscheypidi commented on modules/22_land_conservation/module.gms
> +*' options for land conservation based on conservation priority areas.
Would be good to become a bit more precise here, not in terms of the specific implementation as this is task of the realization description, but in relation to the general purpose of this module. What inputs from other modules does it take into account for what purpose and what information does it provide to other modules? See this part as some sort of contract which this module signs with the rest of the model. This contract should be rather precise about what it expects from the rest model in order to function and what it promises to deliver to the rest of the model.

2022-05-18 08:38 UTC, pvjeetze commented on config/default.cfg
> +cfg$gms$s22_restore_land <- 0                 # def = 0
Perfect, I also prefer to have this actually activated by default. This also gives support to suggested changes below of simplifying the condition for restoration in the reference period 1995-2020. If `cfg$gms$s22_restore_land <- 1` is the default anyway, we may not need the additional condition of making sure that PAs are restored in the ref period based on the historic data

2022-05-18 08:40 UTC, pvjeetze commented on modules/22_land_conservation/area_based_apr22/input.gms
> +$include "./modules/22_land_conservation/input/wdpa_baseline.cs3"
True, I will still have to set up a new preprocessing.

2022-05-18 08:43 UTC, pvjeetze commented on modules/22_land_conservation/area_based_apr22/presolve.gms
> +if(s22_restore_land = 1 OR m_year(t) <= sm_fix_SSP2,
I formulated the conditions as such, as I thought `cfg$gms$s22_restore_land <- 0` might become the default. I also think, `cfg$gms$s22_restore_land <- 1` would be even better as the default. This would mean I can remove `m_year(t) <= sm_fix_SSP2`, which made sure that land conservation in the reference period followed the WDPA data

2022-05-18 11:55 UTC, pvjeetze commented on config/default.cfg
> +# * if one of the 'future options' (e.g. BH) is chosen.
Yes in the current version WDPA is always  active, changing the option to "none" would entail quite changes to the way it is set up right now. "WDPA" is simply a set item in the the input data, which is set to zero. Making it quite efficient in the code structure. Changing it to "none" would require a own $ifthen section to allow for this option

2022-05-18 11:57 UTC, pvjeetze commented on modules/22_land_conservation/area_based_apr22/equations.gms
> +            sum((ct,land_natveg,consv_type), pm_land_conservation(ct,j2,land_natveg,consv_type));
I can easily move `q22_natveg_conservation(j2)` to the natveg module. Adding NPI/NDC to the land conservation module was also something that I discussed with Florian.. @flohump what would you say? Shall I move the NPI/NDC equation back to the natveg module?

2022-05-18 16:04 UTC, flohump commented on modules/22_land_conservation/area_based_apr22/equations.gms
> +            sum((ct,land_natveg,consv_type), pm_land_conservation(ct,j2,land_natveg,consv_type));
Indeed, we discussed this previously. But looking at the code again, I see Jan's point. It's better to have the constraints in one module, i.e. moving q22_natveg_conservation back to the natveg module. With NPI/NDC I'm a bit torn because content-wise it fits to the new 22_land_conservation module. But reading-in the NPI data in 22_land_conservation module and protecting the area in 35_natveg would require another interface. Therefore, we could also move back the NPI/NDC code to 35_natveg. That means the new module 22 would only provide the interface pm_land_conservation without having any constraints.

2022-05-23 10:39 UTC, pvjeetze commented on modules/22_land_conservation/area_based_apr22/input.gms
> +$include "./modules/22_land_conservation/input/wdpa_baseline.cs3"
I will set up a revision `4.71` today afternoon

2022-05-23 10:41 UTC, pvjeetze commented
I've updated the code, please see whether, I have addressed all requests. The updated preprocessing will follow this afternoon.

2022-05-30 06:25 UTC, pvjeetze commented on config/default.cfg
> +# * if one of the 'future options' (e.g. BH) is chosen.
I've now done some rework of the input data mainly for easier use during postprocessing, but also to make clearer the difference between the WDPA baseline and future options for conservation in conservation priority areas. `protect_area.cs3` is now replaced with `consv_prio_areas.cs3` created with the new function `calcConservationPriority` in `mrland`. This also allowed me to simplify/rework the code a bit. Please check again.

2022-05-30 11:35 UTC, tscheypidi requested changes
Changes look good to me. Just some additional questions / change requests.

2022-05-30 11:35 UTC, tscheypidi commented on modules/22_land_conservation/area_based_apr22/preloop.gms
> +p22_add_consv(t,j,"HalfEarth",land) = f22_consv_prio(j,"HalfEarth",land)*p22_conservation_fader(t);
is it possible to merge the lines above to a single line?

2022-05-30 11:35 UTC, tscheypidi commented on modules/22_land_conservation/area_based_apr22/presolve.gms
> +
is merging here possible as well? This would improve readability as one does not have to check line by line whether the code is more or less the same or not.

2022-05-30 11:35 UTC, tscheypidi commented on modules/22_land_conservation/module.gms
> +*' options for land conservation based on conservation priority areas.
the extended description looks now good to me. Thanks!

2022-05-30 11:35 UTC, tscheypidi commented on modules/35_natveg/dynamic_feb21/declarations.gms
> + p35_min_other(t,j)      		                      Minimum other land stock [land conservation for climate change mitigation] (Mha)
not sure whether the brackets might introduce problems somewhere in our various scripts. Can you write the description without the use of a bracket? Perhaps something like "Minimum forest/other stock land conservation target" (if that is what you mean)?

2022-05-30 11:35 UTC, tscheypidi commented on modules/35_natveg/dynamic_feb21/equations.gms
> +
why do you sum here over `land_natveg` on both sides? Shouldn`t this constraint hold for each landtype separately?

2022-05-30 12:18 UTC, pvjeetze commented on modules/22_land_conservation/area_based_apr22/preloop.gms
> +p22_add_consv(t,j,"HalfEarth",land) = f22_consv_prio(j,"HalfEarth",land)*p22_conservation_fader(t);
Thanks for spotting this, done!

2022-05-30 12:19 UTC, pvjeetze commented on modules/22_land_conservation/area_based_apr22/presolve.gms
> +
Here, it bit more tricky as each option needs its own specification. I don't see an easy way out here, at the moment.

2022-05-30 12:19 UTC, pvjeetze commented on modules/35_natveg/dynamic_feb21/declarations.gms
> + p35_min_other(t,j)      		                      Minimum other land stock [land conservation for climate change mitigation] (Mha)
done

2022-05-30 12:29 UTC, pvjeetze commented on modules/35_natveg/dynamic_feb21/equations.gms
> +
Each landtype has its own lower bound formulated in the land modules based on the conservation target. This constraint is there to make land restoration more flexible. E.g. the model is allowed to use other natural land types to fulfill the overall conservation target, if e.g. there's not enough other land, magpie can additionally use secondary forest to meet the target. This also takes care of potential mismatches between the land classification in the input data for the land pools and the conservation data. In simple terms: each land type is protected based on the reference data, but if the model needs to restore land, it can fulfill requirements with any natural land that is still remaining before enlarging natural land.

2022-05-30 14:29 UTC, flohump approved these changes
I looked again through all changes and did not find any inconsistencies.

2022-05-31 08:46 UTC, tscheypidi approved these changes
looks good

2022-05-31 08:58 UTC, merged