New module realizations of 30_crop that introduce fallow land and incentive-based crop rotations
magpiemodel/magpie pull request #398
Opened 2022-05-26 05:11 UTC by bodirsky

## :bird: Purpose of this PR :bird:

- New module realizations of 30_crop that introduce fallow land and incentive-based crop rotations

## :wrench: Checklist for PR creator :wrench:

- [ x] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Medium risk : New realization 

- [ ] Providing additional information based on PR label

* Medium risk : Default run based on the current version of the fork from which PR is made
(still needs to be repeated with merge from PR in between)

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:

how can I add a picture here?
  * Current develop branch default : **42 mins
  * This PR's default :  **42 mins 
  * This PR's new module realization: **41 mins

- [ x] Added changes to `CHANGELOG.md`
- [ x] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ x] No hard coded numbers and cluster/country/region names.
- [ x] The new code doesn't contain declared but unused parameters or variables.
- [ x] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing). 
- [ X] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ X] Self-review of my own code.

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2022-05-26 09:22 UTC, FelicitasBeier reviewed
Cool implementation.
Some clarification needed in description

2022-05-26 09:22 UTC, FelicitasBeier commented on modules/30_crop/rotation_apr22/equations.gms
> +* we also include the max constraint irrigated systems so that they cannot
see comment above

2022-05-26 09:22 UTC, FelicitasBeier commented on modules/30_crop/rotation_apr22/realization.gms
> +*' constraints which are implemented as fixed limits. Rotational constraints
, which are implemented as fixed limits
or:
. These are implemented as fixed limits

2022-05-26 09:22 UTC, FelicitasBeier commented on modules/30_crop/rotation_apr22/realization.gms
> +*' are defined for total land as well as for irrigated areas only to avoid
I don't get the only in this sentence.

They are defined for total land and then there is an additional constraint (max) for irrigated land, right?

2022-05-27 01:29 UTC, bodirsky commented on config/default.cfg
> +# * (rotation_apr22): new rotational constraints with different scenarios
fixed, thanks!

2022-05-27 01:29 UTC, bodirsky commented on config/default.cfg
> +# * In realization rotation_apr22: min, default,good,good_20div,setaside,legumes,agroforestry,sixfoldrotation,agroecology
fixed, thanks!

2022-05-27 01:30 UTC, bodirsky commented on config/default.cfg
> +# * (c30_rotation_scenario): scenarios for stricter constraints.
fixed, thanks!

2022-05-27 01:30 UTC, bodirsky commented on modules/30_crop/penalty_apr22/sets.gms
> +* legumes need longer rotations, only soybean can and is cultivated all 2 years
fixed, thanks!

2022-05-27 01:30 UTC, bodirsky commented on modules/30_crop/rotation_apr22/realization.gms
> +*' constraints which are implemented as fixed limits. Rotational constraints
fixed, thanks!

2022-05-27 01:30 UTC, bodirsky commented on modules/30_crop/rotation_apr22/realization.gms
> +*' are defined for total land as well as for irrigated areas only to avoid
fixed, thanks!

2022-06-02 14:09 UTC, tscheypidi requested changes

2022-06-02 14:09 UTC, tscheypidi commented on modules/30_crop/rotation_apr22/equations.gms
> +   sum((kcr,w), vm_area(j2,kcr,w)) =e= vm_land(j2,"crop")+  vm_fallow(j2);
```suggestion
   sum((kcr,w), vm_area(j2,kcr,w)) =e= vm_land(j2,"crop") +  vm_fallow(j2);
```

2022-06-02 14:09 UTC, tscheypidi commented on modules/50_nr_soil_budget/exoeff_aug16/equations.gms
> +                  + sum(cell(i2,j2),vm_fallow(j2) * 0.005)
perhaps introduce that number as scalar as hardcoded numbers should not show up in the code, in particular not in equations

2022-06-02 14:09 UTC, tscheypidi commented on scripts/output/extra/disaggregation.R
> +  fallow <- Fallow(gdx, level="cell")
why does this function start with a capital "F"? please convert if possible to a lower-case letter to be consistent to (most) of our other functions

2022-06-02 14:09 UTC, tscheypidi commented on scripts/output/extra/disaggregation.R
> +          comment="unit: croparea fractions of total grid-cell",
odd unit. Isn't it either 1 or 1/100 instead?

2022-06-02 14:09 UTC, tscheypidi commented on scripts/output/projects/fsdp_reporting_reg.R
> +wdbefore=getwd()
pro-tip, you can also use `withr::local_dir("wdbefore")` which will take care of setting the folder but also returning back after calculation is finished

2022-06-03 13:04 UTC, pvjeetze commented on modules/30_crop/penalty_apr22/declarations.gms
> + v30_penalty(j,rota30) Penalty for violating rotational constraints (USD05MER)
(mio. ha) right? This is the crop area above rotational constraints, right?

2022-06-03 13:09 UTC, pvjeetze commented on modules/30_crop/penalty_apr22/declarations.gms
> + i30_rotation_incentives(t_all,rota30) penalty for violating constraints (USD05MER per ha)
per ha. or per mio ha.?

2022-06-03 13:21 UTC, pvjeetze commented on modules/30_crop/penalty_apr22/equations.gms
> + 					(vm_land(j2,"crop") * fm_bii_coeff("crop_per",potnatveg)
Not sure whether the equations is right here. I think it should be
```suggestion
 					(vm_land(j2,"crop") - sum((crop_ann30,w), vm_area(j2,crop_ann30,w)) * fm_bii_coeff("crop_per",potnatveg) * fm_luh2_side_layers(j2,potnatveg);
```

2022-06-03 13:21 UTC, pvjeetze commented on modules/30_crop/penalty_apr22/equations.gms
> +          - sum((crop_ann30,w), vm_area(j2,crop_ann30,w)) * fm_bii_coeff("crop_ann",potnatveg))
```suggestion

```

2022-06-03 13:21 UTC, pvjeetze commented on modules/30_crop/penalty_apr22/equations.gms
> +          * fm_luh2_side_layers(j2,potnatveg);
```suggestion

```

2022-06-03 13:23 UTC, pvjeetze commented on modules/30_crop/penalty_apr22/presolve.gms
> +*' Set aside cropland policy is fading in after 2020
'set aside' terminology

2022-06-03 13:23 UTC, pvjeetze commented on modules/30_crop/penalty_apr22/realization.gms
> +*' This realisation also includes the option to set aside a given share of
"set aside" terminology

2022-06-03 13:32 UTC, pvjeetze commented on modules/30_crop/rotation_apr22/equations.gms
> + 					(vm_land(j2,"crop") * fm_bii_coeff("crop_per",potnatveg)
See suggestion above regarding the equation. I think it is not quite right.

2022-06-03 13:33 UTC, pvjeetze commented on modules/30_crop/rotation_apr22/input.gms
> +s30_set_aside_shr   		Share of available cropland that is witheld for other land cover types (1) / 0 /
"set aside" terminology

2022-06-03 13:36 UTC, pvjeetze commented on modules/30_crop/rotation_apr22/input/files
> +f30_set_aside_fader.csv
Florian has introduced a macro for replacing all the fader files in the modules. Optionally this could be done here as well. Here's an example how this macro is used: https://github.com/magpiemodel/magpie/blob/develop/modules/22_land_conservation/area_based_apr22/preloop.gms#L29

2022-06-03 13:37 UTC, pvjeetze commented on modules/30_crop/rotation_apr22/preloop.gms
> +****** Regional share of Set aside cropland policy in selective countries:
"set aside" terminology

2022-06-03 13:37 UTC, pvjeetze commented on modules/30_crop/rotation_apr22/presolve.gms
> +*' Set aside cropland policy is fading in after 2020
"set aside" terminology

2022-06-03 13:58 UTC, pvjeetze commented
Please also add some comparison figures to this PR for easier tracking of changes.

2022-06-05 00:04 UTC, bodirsky commented on modules/15_food/anthropometrics_jan18/preloop.gms
> +*** |  Contact: c15_livescenmagpie@pik-potsdam.de
very strange

2022-06-05 09:07 UTC, bodirsky reviewed
Can we maybe do the set-aside renaming in a separate pull request? 
Its not directly connected to this one...

2022-06-05 09:07 UTC, bodirsky commented on modules/30_crop/rotation_apr22/input/files
> +f30_set_aside_fader.csv
ah, cool! 
but i think i will use it next time. 
syntax is interesting, as it is not a=fucntion(b), but just b(a,...)

2022-06-17 07:25 UTC, pvjeetze commented on config/default.cfg
> +               validation  = "rev4.73_h12_validation.tgz",
Does the new revision 4.73 include all RCPs too?

2022-06-17 07:38 UTC, pvjeetze approved these changes

2022-06-17 07:38 UTC, pvjeetze commented on config/default.cfg
> +# * a share of 0.2 corresponds to a share of 20 % of SNV in terms of the available cropland.
```suggestion
# * a share of 0.2 corresponds to 20 % of SNV in terms of the available cropland.
```

2022-06-21 08:08 UTC, merged