Added primary and secondary other land adjustment to BII disaggregattion
magpiemodel/magpie pull request #415
Opened 2022-07-08 18:50 UTC by pvjeetze

## :bird: Purpose of this PR :bird:

- New BII disaggregation with primary and secondary other land specification.
- Also includes changes/rewrite of `magpie4::PrimSecdOtherLand`

## :wrench: Checklist for PR creator :wrench:

- [ ] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [x] No hard coded numbers and cluster/country/region names.
- [x] The new code doesn't contain declared but unused parameters or variables.
- [x] Where relevant, In-code comments added including documentation comments.
- [x] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [x] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [x] Self-review of my own code.
- [ ] In case of updated cellular input tgz file in default.cfg: scenario_config.csv has been updated accordingly (rcp1p9, rcp2p6 etc)

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2022-07-11 13:33 UTC, tscheypidi requested changes
can you check whether the dependency on `mrcommons` is really needed?

2022-07-11 13:33 UTC, tscheypidi commented on scripts/output/extra/disaggregation_BII_adjusted.R
> +library(mrcommons)
what is madrat and mrcommons being used for here? Output scripts should not use any mr-packages as this would limit their use to machines with a full madrat installation including all relevant sources, which is currently only available on the PIK cluster.

2022-07-11 13:33 UTC, tscheypidi commented on scripts/output/extra/disaggregation_BII_adjusted.R
> +library(mrcommons)
(`toolAggregate` can be used, but no calc-, read- or download- functions)

2022-07-11 14:03 UTC, pvjeetze commented on scripts/output/extra/disaggregation_BII_adjusted.R
> +library(mrcommons)
This was inherited from the original [script](https://github.com/magpiemodel/magpie/blob/develop/scripts/output/extra/disaggregation_BII.R). It also e.g. occurs in the [LUH disaggregation script](https://github.com/magpiemodel/magpie/blob/develop/scripts/output/extra/disaggregation_LUH2.R). While this is, of course, not a justification, maybe we can fix this in a different PR? It might require some rework of the package structure. In this particular case `mrcommons::toolCell2isoCell` is used in line 64

2022-07-12 12:24 UTC, tscheypidi commented on scripts/output/extra/disaggregation_BII_adjusted.R
> +library(mrcommons)
ok, we can fix this later as the use of a tool-function (while not optimal) is not that of an issue like the use of a read- or calc- function would be

2022-07-26 14:49 UTC, flohump approved these changes
Looks good

2022-07-26 15:10 UTC, FelicitasBeier reviewed
Since this is an improvement of the existing BII script, why don't you replace the old script but introduce a new one? 
I would suggest to replace the existing one rather than introducing a parallel BII_adjusted.

2022-07-27 08:53 UTC, pvjeetze commented on scripts/output/extra/disaggregation_BII.R
> +# Save disaggregated BII data
```suggestion
# Save BII data as .nc and .mz file, the first for better transferabiltiy, the second one for faster processing
```

2022-07-27 08:54 UTC, pvjeetze commented on scripts/start/projects/project_FSEC_Scenarios.R
> +                       #"projects/FSEC_dietaryIndicators",
```suggestion
                       "projects/FSEC_dietaryIndicators",
```

2022-07-27 08:55 UTC, pvjeetze commented on scripts/start/projects/project_FSEC_Scenarios.R
>                         "extra/disaggregation_BII"
```suggestion
                       "extra/disaggregation_BII",
```

2022-07-27 10:33 UTC, merged