FSEC modeling script for global runs
magpiemodel/magpie pull request #426
Opened 2022-08-09 13:00 UTC by FelicitasBeier

## :bird: Purpose of this PR :bird:

- Updated and improved script for FSEC
- relaxed upper limit for tau for feasibility of land Sparing runs

## :wrench: Checklist for PR creator :wrench:

- [x] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels): Low risk (start script and output script update) to medium risk (upper limit of tau relaxed)

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [x] No hard coded numbers and cluster/country/region names.
- [x] The new code doesn't contain declared but unused parameters or variables.
- [x] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [x] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [x] Self-review of my own code.
- [x] In case of updated cellular input tgz file in default.cfg: scenario_config.csv has been updated accordingly (rcp1p9, rcp2p6 etc)

## :warning: Additional notes or warnings :warning:
- relaxed upper limit for tau

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2022-08-09 13:30 UTC, mscrawford reviewed
Good from my side. Does the change in Tau require a test run of the develop branch?

2022-08-09 14:17 UTC, FelicitasBeier commented
> Good from my side. Does the change in Tau require a test run of the develop branch?

I have done a default run test now (see updated text above)

2022-08-10 07:35 UTC, tscheypidi requested changes

2022-08-10 07:35 UTC, tscheypidi commented on config/default.cfg
> +cfg$magicc_emis_scen <- "bjoernAR6_C_SSP2-NDC.mif"
How do I do that? Is there this mif-file in the main folder? Unclear to me how to use this setting and what options are there.

2022-08-10 07:35 UTC, tscheypidi commented on modules/13_tc/endo_jan22/presolve.gms
> +	vm_tau.up(h,tautype) =  3 * pcm_tau(h,tautype);
this is odd that this is being required to find feasible solutions. This is really far off a realistic solution

2022-08-10 07:35 UTC, tscheypidi commented on scripts/output/rds_report.R
> +write.report2(report, file = mif)
```suggestion
write.report(report, file = mif)
```
not directly related to your changes, but `write.report2` had recently been deprecated and is now just a redirect to `write.report`. So using the latter function directly is recommended

2022-08-10 07:35 UTC, tscheypidi commented on scripts/start/extra/recalibrate_FSEC.R
> +codeCheck <- FALSE
why do you introduce this variable here? If I see correctly it is only used once down below, right? Why not set it directly in the corresponding `start_run` call as it was before?

2022-08-10 08:17 UTC, FelicitasBeier commented on scripts/start/extra/recalibrate_FSEC.R
> +codeCheck <- FALSE
I think it's easier to find when it's on top (in case one wants to set it to TRUE), but don't have a strong preference can also put it in the start_run call.

2022-08-10 08:27 UTC, FelicitasBeier commented on config/default.cfg
> +cfg$magicc_emis_scen <- "bjoernAR6_C_SSP2-NDC.mif"
It's done in the post-processing, but the information is required in the gdx. 
Maybe @mscrawford can explain in more detail where/how it's used?
I have added the options now.

2022-08-10 08:28 UTC, FelicitasBeier commented on scripts/output/rds_report.R
> +write.report2(report, file = mif)
Done. Also updated all other instances where this occurs.

2022-08-10 08:36 UTC, FelicitasBeier commented on modules/13_tc/endo_jan22/presolve.gms
> +	vm_tau.up(h,tautype) =  3 * pcm_tau(h,tautype);
It's only required when we use the combination of the new pasture realization (gms$past <- "grasslands_apr22", gms$c31_past_suit_scen <- "ssp245") and a very strict land conservation and restoration scenario (cfg$gms$c22_protect_scenario <- "HalfEarth").
Maybe @mppalves @alexkoberle or @bodirsky want to add to the discussion, so that we can decide whether this change is justified for this PR or whether we need to refrain from using this combination right now?

2022-08-10 09:53 UTC, mscrawford commented on config/default.cfg
> +cfg$magicc_emis_scen <- "bjoernAR6_C_SSP2-NDC.mif"
Blackmagicc reads the scenario setting as either an input parameter or (if that parameter is NULL) the config.yml. If one of these parameters has a value, then it grabs the relevant scenario from either the blackmagicc .tgz (which is unpacked from a .tgz stored on /p/projects/magpie) or the scenario's output directory. These are the REMIND scenarios stored in the .tgz:

bjoernAR6_C_RemSDP-900-MagSSP1.mif
bjoernAR6_C_RemSSP1-1000-MagSDP.mif
bjoernAR6_C_SDP-NPi.mif
bjoernAR6_C_SDP-PkBudg1000.mif
bjoernAR6_C_SSP1-Base.mif
bjoernAR6_C_SSP1-NDC.mif
bjoernAR6_C_SSP1-NPi.mif
bjoernAR6_C_SSP1-PkBudg900.mif
bjoernAR6_C_SSP2-Base.mif
bjoernAR6_C_SSP2-NDC.mif
bjoernAR6_C_SSP2-NPi.mif
bjoernAR6_C_SSP2-PkBudg900.mif

I think that the default for this should be NULL, because it takes a lot of forethought to know which REMIND scenario is appropriate. Maybe having this list with a link to Björn's paper could be an intermediate solution. Over the medium term I need to better describe these scenarios so that people can make a wise selection, esp. in terms of the coupled variables (i.e. bioenergy).

2022-08-10 12:03 UTC, FelicitasBeier commented on config/default.cfg
> +cfg$magicc_emis_scen <- "bjoernAR6_C_SSP2-NDC.mif"
I did set it to NULL by default now.

2022-08-16 11:51 UTC, mscrawford approved these changes
👍

2022-08-16 12:07 UTC, tscheypidi approved these changes
it should be `cfg$magicc_emis_scen <- NULL`  not `"NULL"`. Otherwise the PR looks ok now for me. I still don't understand why the higher upper limit for tau might be needed but also don't see a good alternative for it if you say that some runs get infeasible otherwise.

2022-08-16 12:07 UTC, tscheypidi commented on config/default.cfg
> +cfg$magicc_emis_scen <- "NULL"
```suggestion
cfg$magicc_emis_scen <- NULL
```

2022-08-16 15:05 UTC, FelicitasBeier commented on config/default.cfg
> +cfg$magicc_emis_scen <- "bjoernAR6_C_SSP2-NDC.mif"
I reverted to the SSP2 default setting after consulting Mike because NULL throws an error.

2022-08-16 15:08 UTC, FelicitasBeier commented on modules/13_tc/endo_jan22/presolve.gms
> +	vm_tau.up(h,tautype) =  3 * pcm_tau(h,tautype);
The new realization differentiates managed pastures and rangelands. Tau does not apply to rangelands.
There is a strong decline of yields because of climate change impacts that leads to a high need to intensify or expand the small pasture areas. Given the strict Half Earth protection scenario, this is difficult and requires huge investments that require relaxing the upper limit for tau here.

2022-08-16 15:08 UTC, FelicitasBeier commented on config/default.cfg
> +cfg$magicc_emis_scen <- "NULL"
Back to SSP2 default because NULL not allowed

2022-08-17 07:53 UTC, merged