Develop
magpiemodel/magpie pull request #442
Opened 2022-08-29 04:55 UTC by bodirsky

## :bird: Purpose of this PR :bird:

- New MACCs realization

## :wrench: Checklist for PR creator :wrench:

- [X ] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [X ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

![grafik](https://user-images.githubusercontent.com/14294086/184792127-6c878f90-71d8-4647-b563-8943f0fcf703.png)

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The new code doesn't contain declared but unused parameters or variables.
- [ ] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] In case of updated cellular input tgz file in default.cfg: scenario_config.csv has been updated accordingly (rcp1p9, rcp2p6 etc)
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2022-08-30 14:12 UTC, flohump requested changes
Thanks for these improvements!
As far as I can judge, your suggestions make sense content-wise.
Please add a summary of changes to the changelog file.
There seem to be left-over files from deleted module realizations. Please clean up.

2022-09-01 13:29 UTC, tscheypidi requested changes
Looks good overall. Just see the few requests for changes I made and in addition update CHANGELOG.md as also requested by Florian

2022-09-01 13:29 UTC, tscheypidi commented on config/default.cfg
> +cfg$input <- c(regional    = "rev4.76blb2_h12_magpie.tgz",
this should be a regular revision not one with a developer suffix.....can you create the data again without it?

2022-09-01 13:29 UTC, tscheypidi commented on config/default.cfg
> -# * (off_jul16): maccs for non-CO2 emission mitigation deactivated
why did you also delete the off realization? Couldn't this one still be useful when a lightweight model run is required?

2022-09-01 13:29 UTC, tscheypidi commented on modules/42_water_demand/agr_sector_aug13/input.gms
> +s42_multiplier_startyear           Year from which pumping costs multiplier will be implemented (1) / 0 /
what happened here?

2022-09-01 13:29 UTC, tscheypidi commented on modules/50_nr_soil_budget/macceff_aug22/presolve.gms
> +*' (1) E_1 = I_1 * EF * (1-MACCs1)
have you checked how this looks in the final HTML document and PDF? I think this is a novelty to have equations as part of the hand-written documentation and I suspect that you might need to format it differently to have it shown correctly in the final documentations.
Are these equations really needed here or could you just verbally explain what you are doing?

2022-09-01 13:43 UTC, flohump commented
We also need to adjust this function in the magpie4 R library. The output is used by REMIND.
https://github.com/pik-piam/magpie4/blob/master/R/EmissionsBeforeTechnicalMitigation.R
I will coordinate with @bodirsky .

2022-09-02 14:47 UTC, flohump commented
> We also need to adjust this function in the magpie4 R library. The output is used by REMIND.
> https://github.com/pik-piam/magpie4/blob/master/R/EmissionsBeforeTechnicalMitigation.R
> I will coordinate with @bodirsky .

I updated the function such that it works with the model version in this PR as well as with the current develop.
https://github.com/pik-piam/magpie4/blob/master/R/EmissionsBeforeTechnicalMitigation.R

2022-09-07 04:37 UTC, bodirsky commented on config/default.cfg
> +cfg$input <- c(regional    = "rev4.76blb2_h12_magpie.tgz",
i must do that shortly before the PR is ready, right? or when is the time to switch from developer to official suffix?

2022-09-13 01:28 UTC, bodirsky commented on modules/50_nr_soil_budget/macceff_aug22/presolve.gms
> +*' (1) E_1 = I_1 * EF * (1-MACCs1)
now documented

2022-09-13 01:28 UTC, bodirsky commented on modules/50_nr_soil_budget/macceff_aug22/presolve.gms
> +*' (4) (1-NUE2) = (1-NUEb)*(1-MaccsT)
now documented

2022-09-13 01:31 UTC, bodirsky commented on modules/57_maccs/on_aug22/equations.gms
> +*' MACC costs are calculated based on emissions BEFORE technical mitigation.
no, its correct, just check the next sentence.
the reason is the data format the maccs are given to us, they apply on maccs before technical mitigation, so we divided by (1-maccs) to get the emissions btm

2022-09-13 01:33 UTC, bodirsky commented on modules/57_maccs/on_aug22/preloop.gms
> +In this realization, the IPCC AR4 global warming potential factor for N2O (298) and CH4 (25) are used because
can you check?

2022-09-13 01:34 UTC, bodirsky commented on config/default.cfg
> -# * (off_jul16): maccs for non-CO2 emission mitigation deactivated
can be done by setting s57_maxmac_n_soil and the other ones to 0

2022-09-13 01:36 UTC, bodirsky commented on modules/42_water_demand/agr_sector_aug13/input.gms
> +s42_multiplier_startyear           Year from which pumping costs multiplier will be implemented (1) / 0 /
i have no idea, not something i indendently changed... now changed it back

2022-09-13 01:36 UTC, bodirsky commented on modules/50_nr_soil_budget/macceff_aug22/presolve.gms
> +*' (1) E_1 = I_1 * EF * (1-MACCs1)
checked it, seems ok, it just copies it in as is. Had to add a few spaced, though.

2022-09-13 06:11 UTC, bodirsky commented on modules/57_maccs/on_aug22/preloop.gms
> +In this realization, the IPCC AR4 global warming potential factor for N2O (298) and CH4 (25) are used because
ok, florian checked and it should be ok, no changes needed

2022-09-14 02:51 UTC, bodirsky commented on config/scenario_config.csv
> +input['cellular'];;;;;;;;;;;;;;;;;;;;;;;;;;;;;rev4.75_h12_0bd54110_cellularmagpie_c200_MRI-ESM2-0-ssp119_lpjml-8e6c5eb1.tgz;rev4.75_h12_6819938d_cellularmagpie_c200_MRI-ESM2-0-ssp126_lpjml-8e6c5eb1.t
updated; eventually general.R in preprocessing should not comment out these scenarios then?

2022-09-14 02:52 UTC, bodirsky commented on config/default.cfg
> +cfg$input <- c(regional    = "rev4.76blb2_h12_magpie.tgz",
now updated to rev4.77

2022-09-15 12:48 UTC, flohump approved these changes
Looks good!
I added some minor suggestions, mostly spelling corrections.

2022-09-15 12:48 UTC, flohump commented on config/default.cfg
> +# /p/projects/landuse/data/input/archive
```suggestion
# /p/projects/magpie/data/input/archive
```

2022-09-15 12:48 UTC, flohump commented on config/default.cfg
> +# /p/projects/landuse/data/input/calibration
```suggestion
# /p/projects/magpie/data/input/calibration
```

2022-09-15 12:48 UTC, flohump commented on modules/42_water_demand/agr_sector_aug13/input.gms
> +s42_multiplier_startyear           Year from which pumping costs multiplier will be implemented (1) / 0 /
```suggestion
s42_multiplier_startyear           Year from which pumping costs multiplier will be implemented (1) / 1995 /
```

2022-09-15 12:48 UTC, flohump commented on modules/57_maccs/on_aug22/preloop.gms
> +Note that the emissions before mtigation, which need to be part of the integral calculation but is not available in preloop,
```suggestion
Note that the emissions before mitigation, which need to be part of the integral calculation but are not available in preloop,
```

2022-09-16 07:54 UTC, tscheypidi requested changes
please remove the PIK specific descriptions and check whether the RCP change in inputs is intended. Otherwise, looks good to me

2022-09-16 07:54 UTC, tscheypidi commented on config/default.cfg
> +               cellular    = "rev4.77_h12_0bd54110_cellularmagpie_c200_MRI-ESM2-0-ssp119_lpjml-8e6c5eb1.tgz",
why did you change the rcp from 7.0 to 1.9?

2022-09-16 07:54 UTC, tscheypidi commented on config/default.cfg
> +# /p/projects/landuse/data/input/archive
please don't put cluster/PIK specific descriptions into the config

2022-09-23 02:18 UTC, bodirsky commented on config/default.cfg
> +# /p/projects/landuse/data/input/archive
It is clearly stated that this is only for PIK users.
As most users are PIK I think this is very helpful. 
I'm not aware of any other way of documenting it, and I and others have constant trouble remembering where the files are. If there is another userfriendly way, i'm fine. But otherwise, non-PIK users can just skip two lines of comments.

2022-09-23 02:24 UTC, bodirsky commented on modules/42_water_demand/agr_sector_aug13/input.gms
> +s42_multiplier_startyear           Year from which pumping costs multiplier will be implemented (1) / 0 /
what changes these constantly back? i am sure i didnt touch it!

2022-09-23 02:34 UTC, bodirsky commented on config/default.cfg
> +               cellular    = "rev4.77_h12_0bd54110_cellularmagpie_c200_MRI-ESM2-0-ssp119_lpjml-8e6c5eb1.tgz",
ups. thanks that was a copying mistake

2022-09-23 07:05 UTC, tscheypidi approved these changes

2022-09-23 07:08 UTC, merged