Bilateral trade Under Construction
magpiemodel/magpie pull request #449
Opened 2022-09-08 11:37 UTC by caviddhen

## :bird: Purpose of this PR :bird:

- Briefly explain the purpose of this pull request

## :wrench: Checklist for PR creator :wrench:

- [ ] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : 0.45 hours
  * This PR's default :  0.44 hours

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The new code doesn't contain declared but unused parameters or variables.
- [ ] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] In case of updated cellular input tgz file in default.cfg: scenario_config.csv has been updated accordingly (rcp1p9, rcp2p6 etc)
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau. Not high risk, but interesting to see. 

![Resources_Land_Cover_Cropland (7)](https://user-images.githubusercontent.com/37618991/189112552-4bd5af5d-7c10-4789-a09d-86aaefa2a6d5.png)
![Trade_Net_Trade_Crops](https://user-images.githubusercontent.com/37618991/189112558-f971f22b-422a-4703-bb14-59e3676647f1.png)
![Trade_Net_Trade_Livestock_products](https://user-images.githubusercontent.com/37618991/189112560-82a1c08e-467f-4277-85e0-4b13682bad1d.png)
![Resources_Land_Cover_Pastures_and_Rangelands (4)](https://user-images.githubusercontent.com/37618991/189112562-47fbb0f8-d65b-4bd9-b7b2-0f8ce949c8ff.png)
![Resources_Land_Cover_Forest (4)](https://user-images.githubusercontent.com/37618991/189112566-d4456623-fc0b-41c8-b673-1017f45447b6.png)
![Emissions_CO2_Land_Land_use_Change (5)](https://user-images.githubusercontent.com/37618991/189112567-dae93960-a89a-4baf-9602-09f13585a57e.png)
![Productivity_Landuse_Intensity_Indicator_Tau (7)](https://user-images.githubusercontent.com/37618991/189112568-4e7294d6-a89d-4448-beeb-39d677e31e9b.png)
![Emissions_CO2_Land_Land_use_Change (6)](https://user-images.githubusercontent.com/37618991/189112569-7f3a9091-782d-4ccb-b115-5bd26fb6cb4a.png)
![Productivity_Landuse_Intensity_Indicator_Tau (8)](https://user-images.githubusercontent.com/37618991/189112570-50dcc113-4374-4834-8cd1-8f60a779ad2b.png)
![Resources_Land_Cover_Pastures_and_Rangelands (5)](https://user-images.githubusercontent.com/37618991/189112571-e29be656-1752-4f4d-820f-9ab12df52d4b.png)
![Resources_Land_Cover_Forest (5)](https://user-images.githubusercontent.com/37618991/189112573-cbfd40a9-04f6-4c04-9fef-d1c96546ccec.png)

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2022-09-14 03:41 UTC, bodirsky commented
you have a packaging and local trade plot included above, i guess this should not be part of this PR?

2022-09-14 06:05 UTC, bodirsky requested changes

2022-09-14 06:05 UTC, bodirsky commented on modules/21_trade/selfsuff_reduced_bilateral22/realization.gms
> +*** |  (C) 2008-2021 Potsdam Institute for Climate Impact Research (PIK)
documentation doesnt mention bilateral trade except for in the limitations

2022-09-14 06:05 UTC, bodirsky commented on modules/42_water_demand/agr_sector_aug13/input.gms
> +s42_multiplier_startyear           Year from which pumping costs multiplier will be implemented (1) / 0 /
this happened in my case, too...
where does this come from?
guess should be reverwed..

2022-09-14 06:05 UTC, bodirsky commented on modules/42_water_demand/all_sectors_aug13/input.gms
> +s42_multiplier_startyear           Year from which pumping costs multiplier will be implemented (1) / 0 /
also here, why is this changed? seems to be some automatic script that does that

2022-12-20 15:41 UTC, caviddhen commented on modules/21_trade/selfsuff_reduced_bilateral22/equations.gms
> +* Regional trade costs are the costs for each region aggregated over all the tradable commodities.
do you mean to have costs and tariffs at iso level? so not aggregated?

2022-12-20 17:01 UTC, caviddhen commented on modules/21_trade/input/files
>  f21_trade_balance.cs3
done

2022-12-20 17:02 UTC, caviddhen commented on modules/21_trade/selfsuff_reduced_bilateral22/declarations.gms
> +*** |  (C) 2008-2021 Potsdam Institute for Climate Impact Research (PIK)
I did this but it seems like git is already tracking anything named the same. 

The main additions are q21_trade_bilat, q21_costs_tariffs, q21_costs_margins

2022-12-20 17:02 UTC, caviddhen commented on modules/21_trade/selfsuff_reduced_bilateral22/declarations.gms
> + i21_trade_margin(i_ex,i_im,k_trade)            Trade margins (USD05MER per tDM)
done

2022-12-20 17:50 UTC, caviddhen commented on modules/21_trade/selfsuff_reduced_bilateral22/equations.gms
> +*' The following equation indicates the regional trade constraint for the self-sufficiency pool.
yes correct

2023-02-14 17:36 UTC, caviddhen commented on modules/21_trade/selfsuff_reduced_bilateral22/equations.gms
> + q21_trade_glo(k_trade)..
still required for the balance flow

2023-02-15 08:41 UTC, bodirsky approved these changes

2023-02-15 08:44 UTC, bodirsky reviewed
At the moment, the s21_trade_tariff is a pure sensitivity analysis.

It would be nice to also have the option of fading out tariffs, as a trade-lib scenario.

2023-02-15 08:46 UTC, bodirsky requested changes
the timing of the trade-tariff switch (2010) is against our convention that makes scenario switches only active after 2020

2023-02-15 19:52 UTC, caviddhen commented
> the timing of the trade-tariff switch (2010) is against our convention that makes scenario switches only active after 2020

where did you see this? trade tariffs used to not have a time dimension, so it was either completely off or on for all timesteps

2023-02-17 12:09 UTC, bodirsky approved these changes

2023-02-17 20:45 UTC, tscheypidi requested changes
Looks mostly ready. Just some things to be considered/changed:

* Please check all copyright statements and make sure that they range till 2023
* please check the goxygen documentation. Code looks a bit like some simple comments should actually be goxygen comments. Apart from that it would be important to check whether the documentation for the realization looks good.
* 169kB is quite a lot for such a simple figure. As it is now already part of the git history a change would only further increase the repository size but please try to avoid such file sizes in the future if possible

2023-02-17 20:45 UTC, tscheypidi commented on main.gms
> +$setglobal trade  selfsuff_reduced_bilateral22
please do not commit changes in main.gms

2023-02-17 20:45 UTC, tscheypidi commented on modules/21_trade/selfsuff_reduced_bilateral22/declarations.gms
> +*** |  (C) 2008-2021 Potsdam Institute for Climate Impact Research (PIK)
Please check that copyright is updated in all files to 2008-2023

```suggestion
*** |  (C) 2008-2023 Potsdam Institute for Climate Impact Research (PIK)
```

2023-02-17 20:45 UTC, tscheypidi commented on modules/21_trade/selfsuff_reduced_bilateral22/equations.gms
> +* Trade tariffs are associated with exporting regions. They are dependent on net exports and tariff levels.
Shouldn't this be part of the goxygen documentation as well?
```suggestion
*' Trade tariffs are associated with exporting regions. They are dependent on net exports and tariff levels.
```
Same question/suggestion for the following comments.

2023-02-18 16:39 UTC, caviddhen commented
> Looks mostly ready. Just some things to be considered/changed:
> 
> * Please check all copyright statements and make sure that they range till 2023
> * please check the goxygen documentation. Code looks a bit like some simple comments should actually be goxygen comments. Apart from that it would be important to check whether the documentation for the realization looks good.
> * 169kB is quite a lot for such a simple figure. As it is now already part of the git history a change would only further increase the repository size but please try to avoid such file sizes in the future if possible

Thanks Jan! adjusted now! and the documentation looks ok too. (and sorry, the image had copied over from the last realization, as this one builds on it, noted for the future).

2023-02-18 20:06 UTC, tscheypidi approved these changes

2023-02-20 07:15 UTC, merged