minimum wage scneario
magpiemodel/magpie pull request #454
Opened 2022-09-21 13:15 UTC by deleip

## :bird: Purpose of this PR :bird:

This PR introduces the option to include a global minimum wage set by `s36_minimum_wage`, which can either lead to total labor costs being scaled accordingly (`s36_scale_labor_costs <- 1`), or it is assumed that productivity increases such that total labor costs stay the same (`s36_scale_labor_costs <- 0`). 
The 38_factor_costs realization "mixed_reg_feb17" was removed as it is not used anymore. In the realization `sticky_labor` the calibration of the share parameter was fixed, and the option to fix the capital need (i.e. not allowing for substitution between labor and capital) until a given year `s38_fix_capital_need` was introduced.

## :wrench: Checklist for PR creator :wrench:

- [x] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [x] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : 22 mins
  * This PR's default :  22 mins

- [ ] Added changes to `CHANGELOG.md`
- [x] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [x] No hard coded numbers and cluster/country/region names.
- [x] The new code doesn't contain declared but unused parameters or variables.
- [x] Where relevant, In-code comments added including documentation comments.
- [x] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [x] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [x] Self-review of my own code.
- [x] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%
- old default vs. new default
![default_cropland](https://user-images.githubusercontent.com/17687509/191502625-71060fd8-2a59-4477-a8ff-11d2f1da4fe5.png)
![dafault_tau](https://user-images.githubusercontent.com/17687509/191502637-96738178-28f2-4473-9d6e-c8292bf0f574.png)
![deafult_foodExpenditureIndex](https://user-images.githubusercontent.com/17687509/191502646-0500fbf4-226b-42c1-a9e2-b748a33aeab7.png)
- results of wage scenario (red: no minimum wage, blue: minimum wage but no labor/capital substitution, green: minimum wage with labor/capital substitution)
![wageScenario_laborCostShare](https://user-images.githubusercontent.com/17687509/191503564-b16b49fa-28a9-47e2-9ef2-fb9e7fa1be9b.png)
![wageScenario_cropProduction](https://user-images.githubusercontent.com/17687509/191503579-4dfd2344-acc4-41a9-b049-6704ed49f292.png)
![wageScenario_agEmployment](https://user-images.githubusercontent.com/17687509/191503590-065fd923-672c-4d8e-b239-00dd1313cdda.png)
![wageScenario_foodExpenditureIndex](https://user-images.githubusercontent.com/17687509/191503602-52cab737-ecc4-4925-9d93-59c11e9d20c2.png)

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2022-09-27 07:27 UTC, bodirsky requested changes
All in all reads already well and nicely docuemnted.
I suggest to replace s_wage by the actual labor_costs_per_unit that you have in your other module. Is that possible?

2022-09-27 07:27 UTC, bodirsky commented on modules/38_factor_costs/per_ton_fao_may22/declarations.gms
> +q38_cost_prod_crop_labor(i)      Regional labor costs for plant production (mio. USD05MER per yr)
crop production

2022-09-27 07:27 UTC, bodirsky commented on modules/38_factor_costs/per_ton_fao_may22/declarations.gms
> +q38_cost_prod_crop_capital(i)    Regional capital costs for plant production (mio. USD05MER per yr)
crop production

2022-09-27 07:27 UTC, bodirsky commented on modules/38_factor_costs/sticky_feb18/equations.gms
> +                              =e= sum(kcr,vm_prod_reg(i2,kcr) * sum(ct,p38_variable_costs(ct,i2,kcr) * pm_labor_cost_scaling(ct,i2)))
why is this called variable costs if it is labor costs?

2022-09-27 07:27 UTC, bodirsky commented on modules/38_factor_costs/sticky_labor/equations.gms
> +                              =e= sum(kcr,sum(cell(i2,j2), vm_prod(j2,kcr) * v38_labor_need(j2,kcr) * s38_wage * sum(ct, pm_labor_cost_scaling(ct,i2))))
here it is called labor need, that makes more sense, no?

2022-09-27 07:27 UTC, bodirsky commented on modules/38_factor_costs/sticky_feb18/equations.gms
> +                              =e= sum(kcr,vm_prod_reg(i2,kcr) * sum(ct,p38_variable_costs(ct,i2,kcr) * pm_labor_cost_scaling(ct,i2)))
also this is more something like a cost intensity, as it is multiplied with a production

2022-09-27 07:27 UTC, bodirsky commented on modules/38_factor_costs/sticky_labor/equations.gms
> +                              =e= sum(kcr,sum(cell(i2,j2), vm_prod(j2,kcr) * v38_labor_need(j2,kcr) * s38_wage * sum(ct, pm_labor_cost_scaling(ct,i2))))
I think a more elegant implementation would be to have the baseline and actual wage as interfaces, and then the actual wage would replace s38_wage, and the baseline wage woudl be used to replace s38_wage in the preprocessing calibration

2022-09-27 07:27 UTC, bodirsky commented on modules/38_factor_costs/sticky_labor/presolve.gms
> +i38_ces_shr(j,kcr) = sum(cell(i,j), (p38_intr_depr(t,i) * sum(mobil38, v38_capital_need.l(j,kcr,mobil38))**(1 + s38_ces_elast_par)) / (p38_intr_depr(t,i) * sum(mobil38, v38_capital_need.l(j,kcr,mobil
basically here, your wage shoudl replace s38_wage. then the ces_shr would be calibrated to your wages

2022-09-27 07:27 UTC, bodirsky commented on modules/38_factor_costs/sticky_labor/presolve.gms
> +i38_ces_shr(j,kcr) = sum(cell(i,j), (p38_intr_depr(t,i) * sum(mobil38, v38_capital_need.l(j,kcr,mobil38))**(1 + s38_ces_elast_par)) / (p38_intr_depr(t,i) * sum(mobil38, v38_capital_need.l(j,kcr,mobil
result is the same, but reduces the number of parameters and makes code clearer.

2022-09-27 07:27 UTC, bodirsky commented on modules/70_livestock/fbask_jan16/declarations.gms
> + i70_foddr_scp_fadeout(t_all,i)                   Fooder fadeout (share 0-1) to be replaced by SCP (1)
fooder = fodder, right?

2022-09-27 07:29 UTC, bodirsky commented on modules/38_factor_costs/sticky_labor/presolve.gms
> +i38_ces_shr(j,kcr) = sum(cell(i,j), (p38_intr_depr(t,i) * sum(mobil38, v38_capital_need.l(j,kcr,mobil38))**(1 + s38_ces_elast_par)) / (p38_intr_depr(t,i) * sum(mobil38, v38_capital_need.l(j,kcr,mobil
then v38_labor_need should also become the total hours worked, right?

2022-09-27 18:31 UTC, deleip commented on modules/38_factor_costs/sticky_feb18/equations.gms
> +                              =e= sum(kcr,vm_prod_reg(i2,kcr) * sum(ct,p38_variable_costs(ct,i2,kcr) * pm_labor_cost_scaling(ct,i2)))
I changed it to p38_labor_need (and also updated the description)

2022-09-27 18:31 UTC, deleip commented on modules/38_factor_costs/sticky_labor/equations.gms
> +                              =e= sum(kcr,sum(cell(i2,j2), vm_prod(j2,kcr) * v38_labor_need(j2,kcr) * s38_wage * sum(ct, pm_labor_cost_scaling(ct,i2))))
done (see below)

2022-09-28 09:46 UTC, deleip commented on modules/38_factor_costs/sticky_labor/presolve.gms
> +i38_ces_shr(j,kcr) = sum(cell(i,j), (p38_intr_depr(t,i) * sum(mobil38, v38_capital_need.l(j,kcr,mobil38))**(1 + s38_ces_elast_par)) / (p38_intr_depr(t,i) * sum(mobil38, v38_capital_need.l(j,kcr,mobil
I found another problem with that (but think I fixed it): with the cost scaling parameter, I had the option to not scale costs despite higher wages. In that case we assume that labor productivity increases proportional to wages. When using the actual wages and v38_laborhours_need (instead of a monetary labor need) in sticky_labor, if we assume that total labor costs do not increase despite higher waged, the v38_laborhours_need needs to be reduced accordingly. I introduced a new parameter p38_labor_prod_wage that will only be != 1 in a wage scenario without total cost scaling, and enters the CES function. This then gives lower v38_laborhours_need, which cancels out with the higher wages in the cost equation (apart from some labor/capital substitution)

2022-09-29 13:12 UTC, flohump requested changes
Looks fine in general!
I have some minor requests for changes.

2022-09-29 13:12 UTC, flohump commented on modules/36_employment/exo_may22/declarations.gms
> + pm_hourly_costs(t,i)                   Hourly labor costs in agriculture on regional level after including minimum wage (USDMER05 per hour)
These two new interfaces are very similar and also have the same unit.
Therefore, you could merge these into one interface with a set for distinction between baseline and minimum wage scenario.
@tscheypidi What do you suggest?

2022-09-30 10:22 UTC, deleip commented on modules/36_employment/exo_may22/declarations.gms
> + p36_nonmagpie_labor_costs(t,i)         Labor costs from subsidies and VoP not covered by MAgPIE (mio. USDMER05)
VoP means Value of Production (the part not covered by MAgPIE comes from wool, beeswax, honey, silk-worms)

2022-09-30 12:41 UTC, tscheypidi requested changes

2022-09-30 12:41 UTC, tscheypidi commented on CHANGELOG.md
> +- **38_factor_costs** and **70_livestock** included labor cost scaling in case of minimum wage scenario
please put this entry separate for both modules so that the changes can be sorted by module before the next release

2022-09-30 12:41 UTC, tscheypidi commented on config/default.cfg
> +cfg$gms$s36_minimum_wage <- 0            # default = 0 (no minimum wage)
is that a binary 1/0 switch or does it have a unit?

2022-09-30 12:41 UTC, tscheypidi commented on modules/36_employment/exo_may22/declarations.gms
> + pm_hourly_costs(t,i)                   Hourly labor costs in agriculture on regional level after including minimum wage (USDMER05 per hour)
I agree, that should be merged into one parameter

2022-09-30 12:41 UTC, tscheypidi commented on modules/36_employment/exo_may22/declarations.gms
> + pm_labor_cost_scaling(t,i)             Multiplicative factor describing increase in hourly labor costs to match minimum wage (1)
why is that interface needed? I would have thought that if you provide the hourly costs to the modules they should be able to compute the respective labor costs? Isn't it possible that the modules compute the required working hours and then base their calculations on `pm_hourly_costs` (diving the given labor costs by hourly costs should give the hours one should start with)

2022-09-30 12:41 UTC, tscheypidi commented on modules/36_employment/exo_may22/equations.gms
> -*' which are not covered by MAgPIE.
Github is complaining here and in some other spots about missing newlines. Perhaps you can check why this is happening (might be coming from the text editor you use)

2022-09-30 12:41 UTC, tscheypidi commented on modules/36_employment/exo_may22/input.gms
>  ;
please specify units for the scalars and use (1) if it does not have a unit

2022-09-30 12:41 UTC, tscheypidi commented on modules/38_factor_costs/sticky_labor/preloop.gms
> +p38_labor_prod_wage(t,i)$(pm_labor_cost_scaling(t,i) <> 1) = 1;
Why is that 1 if `pm_labor_cost_scaling` is different to 1?

2022-10-01 20:38 UTC, deleip commented on config/default.cfg
> +cfg$gms$s36_minimum_wage <- 0            # default = 0 (no minimum wage)
it's a USD/h value, I added the unit in the description

2022-10-04 08:13 UTC, deleip commented on modules/36_employment/exo_may22/declarations.gms
> + pm_hourly_costs(t,i)                   Hourly labor costs in agriculture on regional level after including minimum wage (USDMER05 per hour)
done (also for p36_hourly_costs_iso)

2022-10-04 08:13 UTC, deleip commented on modules/36_employment/exo_may22/declarations.gms
> + pm_labor_cost_scaling(t,i)             Multiplicative factor describing increase in hourly labor costs to match minimum wage (1)
the switch `s36_scale_productivity_with_wage` can now take any positive value which defines how strongly labor productivity should be affected by higher wages (instead of being a binary switch). The new interface is `pm_productivity_gain_from_wages` which replaces the interface `pm_labor_cost_scaling`

2022-10-04 08:14 UTC, deleip commented on modules/36_employment/exo_may22/equations.gms
> -*' which are not covered by MAgPIE.
I don't see any complains in the updated files, either I'm not looking for the right thing, or I already fixed them unknowingly with the other changes...

2022-10-04 08:38 UTC, tscheypidi approved these changes
looks good

2022-10-04 15:01 UTC, flohump approved these changes

2022-10-04 15:32 UTC, merged