Inclusion of AQUASTAT calibration factors for yields
magpiemodel/magpie pull request #457
Opened 2022-10-03 05:00 UTC by vartika271987

## :bird: Purpose of this PR :bird: 
Inclusion of AQUASTAT rainfed vs irrigation calibration factors as a switch to improve yield ratios

- Briefly explain the purpose of this pull request

## :wrench: Checklist for PR creator :wrench:

- [X] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* * High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label
![image](https://user-images.githubusercontent.com/51452385/193501971-3c204303-0624-463f-8938-35cd4084fd6e.png)
![image](https://user-images.githubusercontent.com/51452385/193502552-fb8e2605-27a3-441d-9560-c47c5f8a3871.png)
![image](https://user-images.githubusercontent.com/51452385/193502634-65b206da-efff-4db1-b2ec-1316f474d395.png)
![image](https://user-images.githubusercontent.com/51452385/193502057-6b503a76-674f-47df-befd-67e797162f92.png)
![image](https://user-images.githubusercontent.com/51452385/193502714-c7de0464-8784-4c4f-b652-5f54fc1e6ddf.png)

* High risk
  * Default run from the current develop branch (2909_nocalib)
  * Default run based on the current version of the fork from which PR is made (2909_yescalib)

- [X] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : 58 mins
  * This PR's default :  60 mins

- [X] Added changes to `CHANGELOG.md`
- [X] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [X] No hard coded numbers and cluster/country/region names.
- [X] The new code doesn't contain declared but unused parameters or variables.
- [X] Where relevant, In-code comments added including documentation comments.
- [X] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [X] Self-review of my own code.
- [ ] In case of updated cellular input tgz file in default.cfg: scenario_config.csv has been updated accordingly (rcp1p9, rcp2p6 etc)
- [X] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly addressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

2022-10-06 11:05 UTC, tscheypidi requested changes

2022-10-06 14:08 UTC, xwangatpik reviewed
The test results in general look reasonable, also for China. Just a remark that the ir-rf calibration makes the rainfed yields higher and the irrigated yields lower for India. How can this give a larger amount of agricultural water use in the run with ir-rf calibration?

2022-10-06 18:00 UTC, mishkos approved these changes
From the calculation aspect all looks fine from my side.

2022-10-06 18:00 UTC, mishkos commented on config/default.cfg
> +#       as well as for certain regional or global settings (e.g. NPIs).
A bit more precise recommendation would be: "... as well as for any other setting that would affect initial values in the model, e.g. changes in costs structure, NPI policies, etc."

2022-10-06 18:00 UTC, mishkos commented on modules/18_residues/off/not_used.txt
> +fm_multicropping,input,questionnaire
So, `fm_multicropping` should better be defined in the `water_demand` module, where it's not ignored in all realizations. Is this correct? I'd like to understand this better ;)

2022-10-06 18:04 UTC, tscheypidi commented on modules/18_residues/off/not_used.txt
> +fm_multicropping,input,questionnaire
No, the solution is to declare it in all realizations of that module. The decision where to declare an interface should solely be a content-based decision. In case of multicropping the residues modules is in my opinion the slightly more natural choice.

2022-10-07 08:40 UTC, k4rst3ns commented
> The test results in general look reasonable, also for China. Just a remark that the ir-rf calibration makes the rainfed yields higher and the irrigated yields lower for India. How can this give a larger amount of agricultural water use in the run with ir-rf calibration?

Hey @Xiaoxi: I am unsure with the actual irrgitaed yields will tell us something on regional scales as they are always weighted by the actual crop pattern which can lead to different results. E.g. imagine MAgPIE is now doing more irrigation at places with not so high yield than before. If so irrigated yield of IND will be dropping.
Maybe look on Yields (after calibration) - this is weighted with always the same weights and therefor is a more stable variable to look at if we want to compare yields across runs maybe?

2022-10-07 09:25 UTC, FelicitasBeier commented
> The test results in general look reasonable, also for China. Just a remark that the ir-rf calibration makes the rainfed yields higher and the irrigated yields lower for India. How can this give a larger amount of agricultural water use in the run with ir-rf calibration?

I have added the indicator "Yields after calibraiton" for both rainfed and irrigated yields. I think this explains why there is an incentive to irrigate (i.e. higher withdrawals and higher irrigated area in India). Please confirm.

2022-10-09 06:26 UTC, xwangatpik commented
> 

All good. Thanks for the clarification, Feli and Kristine  :)

2022-10-13 09:50 UTC, FelicitasBeier reviewed
My comments have been resolved.

2022-10-13 09:57 UTC, tscheypidi approved these changes
I just found one line where the goxygen comment prefix is missing (see my suggested change and please incorporate it). Other than that it looks ready to go for me.

2022-10-13 09:57 UTC, tscheypidi commented on modules/14_yields/managementcalib_aug19/preloop.gms
> +* `s14_limit_calib` can be used to switch limited calibration on (1) and off (0).
```suggestion
*' `s14_limit_calib` can be used to switch limited calibration on (1) and off (0).
```

2022-10-13 09:59 UTC, FelicitasBeier commented on modules/14_yields/managementcalib_aug19/preloop.gms
> +* `s14_limit_calib` can be used to switch limited calibration on (1) and off (0).
Thanks! Sharp eyes! Fixed now.

2022-10-13 10:06 UTC, mishkos approved these changes
just a very tiny edit in the description requested.

2022-10-13 10:06 UTC, mishkos commented on modules/14_yields/module.gms
> +*' Irrigated yields can optionally be calibrated to meet irrigated-rainfed
by default this is now a standard. One can opt not to do it.

2022-10-13 10:30 UTC, FelicitasBeier commented on modules/14_yields/module.gms
> +*' Irrigated yields can optionally be calibrated to meet irrigated-rainfed
I thought about adding that as well, but wasn't sure whether that should be in the description because I think it should be rather general?

2022-10-13 10:38 UTC, emolinab commented on config/default.cfg
> +# NOTE: It is recommended to use best_calib only for sticky factor cost realizations!
where exactly?

2022-10-13 11:05 UTC, FelicitasBeier commented on config/default.cfg
> +# NOTE: It is recommended to use best_calib only for sticky factor cost realizations!
It refers to this chunk:
```
# ***---------------------    38_factor_costs    -------------------------------
# * Make sure you use the corresponding calibration file to the selected realization
# * Please, check details in input settings.
# * (per_ton_fao_may22)    factor costs fixed per ton
# * (sticky_feb18)         factor costs including investments in capital
# * (sticky_labor)         based on sticky_feb18 + labor productivity factor included
# NOTE: It is recommended to recalibrate the model when changing this setting!
# NOTE: It is recommended to use best_calib only for sticky factor cost realizations!
cfg$gms$factor_costs <- "per_ton_fao_may22"        # default = per_ton_fao_may22
```

And the question is whether we leave the line: "# NOTE: It is recommended to use best_calib only for sticky factor cost realizations!". Jan was not sure if this still applies or not. Kristine and I understood that this was the case.

2022-10-13 14:21 UTC, emolinab commented on config/default.cfg
> +# NOTE: It is recommended to use best_calib only for sticky factor cost realizations!
Please change it to: "In case the maximum number of iterations is reached without convergence,  please consider to use the best_calib setting"

2022-10-13 14:46 UTC, merged