Bugfix SOM realization
magpiemodel/magpie pull request #477
Opened 2022-11-11 18:09 UTC by k4rst3ns

## :bird: Description of this PR :bird:

- This PR will correct the buggy version of the cellpool som realization, that did not track correctly the noncropland land transitions.
- 
## :wrench: Checklist for PR creator :wrench:

- [x] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
- [x] Self-review own code
- [x] Document changes 
  - [x] Add changes to `CHANGELOG.md`
  - [x] Where relevant, put In-code documentation comments
  - [x] Properly address updates in interfaces in the module documentations
  - [ ] [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
    - Still running: Run test runs via `Rscript start.R --> "test runs"`

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  *0.37* mins
  - This PR's with cellpool :  *0.41* mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate

2022-11-15 12:28 UTC, tscheypidi requested changes
looks good...just two minor requests

2022-11-15 12:28 UTC, tscheypidi commented on modules/10_land/landmatrix_dec18/presolve.gms
> +*vm_lu_transitions.fx(j,"secdforest","forestry") = 0;
can these commented lines and the following ones be removed? I know they were there before, but in general we should not have commented lines of code in there

2022-11-15 12:28 UTC, tscheypidi commented on modules/10_land/module.gms
the module description should now also mention that the transition information is shared as well.

2022-11-22 13:07 UTC, flohump requested changes
Thanks for fixing this bug.
I have only some minor commetns , on top of @tscheypidi comments.

2022-11-22 13:07 UTC, flohump commented on modules/10_land/landmatrix_dec18/presolve.gms
> +*vm_lu_transitions.fx(j,"secdforest","forestry") = 0;
removing these lines is fine with me

2022-11-22 13:07 UTC, flohump commented on modules/42_water_demand/agr_sector_aug13/input.gms
> +s42_multiplier_startyear           Year from which pumping costs multiplier will be implemented (1) / 1995 /
I thought that we had sorted out this problem @tscheypidi what do you think?

2022-11-22 13:07 UTC, flohump commented on modules/42_water_demand/agr_sector_aug13/input.gms
> +s42_multiplier_startyear           Year from which pumping costs multiplier will be implemented (1) / 1995 /
1995 is the correct value from the default.cfg. All fine here.

2022-11-25 14:30 UTC, k4rst3ns commented on modules/10_land/landmatrix_dec18/presolve.gms
> +*vm_lu_transitions.fx(j,"secdforest","forestry") = 0;
removed all commented lines:

*v10_lu_transitions.fx(j,"secdforest","forestry") = 0;
*v10_lu_transitions.fx(j,"other","forestry") = 0;

*' Forestry can only increase
*v10_lu_transitions.fx(j,"forestry",land_to10) = 0;
*v10_lu_transitions.up(j,"forestry","forestry") = Inf;

*' Secdforest can only decrease (during optimization)
*v10_lu_transitions.fx(j,land_from10,"secdforest") = 0;
*v10_lu_transitions.up(j,"secdforest","secdforest") = Inf;

2022-11-25 14:34 UTC, k4rst3ns commented on modules/10_land/module.gms
the realization description has this info. Is it needed to move the information also here?

and speaking of the realization.gms, should I add the only net LU transitions per cluster issue to the limitations there?

2022-11-25 14:39 UTC, k4rst3ns commented on modules/10_land/landmatrix_dec18/equations.gms
> -               vm_croplandexpansion(j2,land_from10) =e=
fixed. Also added that vm_lu_transitions is now an interface.

2022-11-25 14:52 UTC, tscheypidi commented on modules/10_land/module.gms
interfaces must be documented in module.gms are valid for all realizations. Adding the warning that it is only net transitions to limitations is a good idea.

2022-11-25 19:26 UTC, tscheypidi approved these changes

2022-11-28 13:57 UTC, flohump approved these changes
Looks good.

2022-11-28 14:03 UTC, merged