Rework of land conversion cost calibration approach
magpiemodel/magpie pull request #480
Opened 2022-11-23 15:01 UTC by pvjeetze

## :bird: Description of this PR :bird:

- The previous approach for calibrating the land conversion costs led to sometimes funny behaviour depending on the choice of the crop realisation or other settings. This PR is meant to fix that. This PR draws on the former approach of using both land conversion costs and rewards for cropland contraction in order to match historical cropland patterns. However, both the costs and the rewards are now calibrated freely. Moreover, the calibration factors are only applied in the year 2015 (before they were applied in all time steps from 1995 to 2015). In the time steps before 2015, the calibration factor now converge linearly from 1 to the 2015 calibrated land conversion cost factors. Similarly, the rewards linearly increase until 2015 to the calibrated level and fade to zero until 2050. 

## :wrench: Checklist for PR creator :wrench:

- [x] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [x] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [x] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `gams main.gms action=c`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Default run based on the current version of the fork from which PR is made
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate

2022-11-23 15:14 UTC, tscheypidi requested changes
Hi @pvjeetze your PR points to the master branch, but it must point to the develop branch instead. Please fix that first before the reviewer proceed

2022-11-23 15:17 UTC, pvjeetze commented
> Hi @pvjeetze your PR points to the master branch, but it must point to the develop branch instead. Please fix that first before the reviewer proceed

fixed

2022-11-23 15:22 UTC, tscheypidi approved these changes

2022-11-24 07:27 UTC, pvjeetze commented
The test runs were in preparation. They have now finished. "v14_EndoPerTon" in the Figures above corresponds to this PR's default.

2022-11-24 11:44 UTC, tscheypidi approved these changes
looks good

2022-11-24 13:00 UTC, mishkos commented on config/default.cfg
> +cfg$cost_calib_min_landconversion_cost <- 0.05            # def= 0.05
Are all the calibration condition relaxed because of runtime savings, basically a quicker convergence? I suppose this doesn't affect much the quality of calibration factors?

2022-11-24 16:51 UTC, weindl approved these changes
Looks good to me.

2022-11-24 16:51 UTC, weindl commented on scripts/calibration/landconversion_cost.R
> +    # only reward only if share of cropland lost between 1995 and 2015 exceeds a certain threshold. Otherwise set to 0.
remove the duplicate use of "only"

2022-11-24 16:51 UTC, weindl commented on scripts/start_functions.R
> +                     cost_min = cfg$cost_calib_min_landconversion_cost,
I found the definition of the function calibrate_magpie in landconversion_cost.R. My above comment is therefore not relevant anymore. There seems to be 2 places where a function with the name "calibrate_magpie" is defined...

2022-11-24 16:57 UTC, mishkos approved these changes
All good then

2022-11-24 17:08 UTC, pvjeetze commented on CHANGELOG.md
> +- **39_landconversion** scalar `s39_reward_crop_reduction` provides a crop reduction reward
fixed

2022-11-24 17:08 UTC, pvjeetze commented on scripts/calibration/landconversion_cost.R
> +    # only reward only if share of cropland lost between 1995 and 2015 exceeds a certain threshold. Otherwise set to 0.
removed duplicate

2022-11-24 18:59 UTC, flohump commented on scripts/start/extra/recalibrate_all.R
> +
description: calculate and store new calibration factors for yields AND land conversion costs; for default setup.

2022-11-24 19:25 UTC, pvjeetze commented on scripts/start/extra/recalibrate_all.R
> +
done :)

2022-11-24 19:34 UTC, merged