semi-natural vegetation in cropland areas rework
magpiemodel/magpie pull request #487
Opened 2022-12-01 15:51 UTC by pvjeetze

## :bird: Description of this PR :bird:

- Semi-natural vegetation (SNV) conservation in cropland areas is now provided by the module `22_land_conservation`. This makes is easier to specifiy, which land types shall be conserved as SNV. I also added an option (`s22_snv_natveg_only`) to the `default.cfg` for deciding whether all non-cropland land types qualify as SNV or only primforest, secdforest and otherland (i.e. 'natveg'). 

## :wrench: Checklist for PR creator :wrench:

- [ ] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [ ] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [ ] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `gams main.gms action=c`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Default run based on the current version of the fork from which PR is made
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate

2022-12-02 07:55 UTC, pfuehrlich-pik reviewed
Looks good, just some formatting/alignment comments. Seems like a lot of code duplication is introduced, is this required by GAMS/the way MAgPIE is structured, or is there a way to reduce the duplication?

2022-12-02 07:55 UTC, pfuehrlich-pik commented on config/default.cfg
> +cfg$gms$c30_marginal_land <- "q33_marginal"   # def = "all_marginal"
Should the default in the comment also be changed?
```suggestion
cfg$gms$c30_marginal_land <- "q33_marginal"   # def = "q33_marginal"
```

2022-12-02 07:55 UTC, pfuehrlich-pik commented on modules/30_crop/endo_apr21/input.gms
> +s30_snv_shr   		    Share of available cropland that is witheld for other land cover types (1) / 0 /
Why did the indentation change here?

2022-12-02 07:55 UTC, pfuehrlich-pik commented on modules/30_crop/endo_apr21/declarations.gms
> + p30_snv_shr(t,j)                   Share of semi-natural vegetation in cropland areas (1)
The alignment of the parameter explanations seems off here.

2022-12-02 07:55 UTC, pfuehrlich-pik commented on modules/30_crop/penalty_apr22/declarations.gms
> + p30_snv_shr(t,j)                   Share of semi-natural vegetation in cropland areas (1)
The explanation alignment seems off here.

2022-12-02 07:55 UTC, pfuehrlich-pik commented on modules/30_crop/penalty_apr22/declarations.gms
> + q30_natveg_snv(j)               Natural vegetation cover in cropland areas (mio. ha)
```suggestion
 q30_bv_per(j,potnatveg)              Biodiversity value of perennial cropland (mio. ha)
 q30_natveg_snv(j)                    Natural vegetation cover in cropland areas (mio. ha)
```

2022-12-02 07:55 UTC, pfuehrlich-pik commented on modules/30_crop/penalty_apr22/input.gms
> +s30_snv_shr   		    Share of available cropland that is witheld for other land cover types (1) / 0 /
alignment

2022-12-02 07:55 UTC, pfuehrlich-pik commented on modules/30_crop/rotation_apr22/declarations.gms
> + p30_snv_shr(t,j)                   Share of semi-natural vegetation in cropland areas (1)
alignment

2022-12-02 07:55 UTC, pfuehrlich-pik commented on modules/30_crop/rotation_apr22/declarations.gms
> + q30_natveg_snv(j)               Natural vegetation cover in cropland areas (mio. ha)
alignment

2022-12-02 07:55 UTC, pfuehrlich-pik commented on modules/30_crop/rotation_apr22/input.gms
> +s30_snv_natveg_only   Whether only forest and other land are allowed as semi-natural vegetation in cropland areas (1) / 0 /
alignments

2022-12-02 10:30 UTC, pvjeetze commented on modules/30_crop/endo_apr21/declarations.gms
> + p30_snv_shr(t,j)                   Share of semi-natural vegetation in cropland areas (1)
Not sure what's going on there. Tried to fix it, but it looks fine in my VS Code

2022-12-02 10:31 UTC, pvjeetze commented on config/default.cfg
> +cfg$gms$c30_marginal_land <- "q33_marginal"   # def = "all_marginal"
fixed

2022-12-02 10:32 UTC, pvjeetze commented on modules/30_crop/endo_apr21/input.gms
> +s30_snv_shr   		    Share of available cropland that is witheld for other land cover types (1) / 0 /
tried to fix that, but the indentation is sometimes printed differently here than in vs code

2022-12-02 10:35 UTC, pvjeetze commented
Many thanks @pfuehrlich-pik! I tried to fix the alignments but it also seems to be a visualisation issue between vs code and github. Regarding the code duplication, this is because the changes had to be made across all three crop realisations, which are independent of each other.

2022-12-02 10:56 UTC, pvjeetze commented on CHANGELOG.md
> +- **10_land** added interface `fm_land_iso` realization for consistency
```suggestion
- **10_land** added interface `fm_land_iso` for consistency
```

2022-12-02 11:22 UTC, pfuehrlich-pik commented on modules/30_crop/endo_apr21/input.gms
> +s30_snv_shr   		    Share of available cropland that is witheld for other land cover types (1) / 0 /
Maybe tabs are used for indentation? I'd much prefer to just use spaces, they are always printed the same way (if a monospace font is used)

2022-12-02 11:26 UTC, pfuehrlich-pik commented
Seems like tabs and spaces are used in a mix in lots of files :grimacing: I guess we should decide for one or (hopefully not) the other in a magpie meeting and establish a policy.

2022-12-02 11:44 UTC, pvjeetze commented
@pfuehrlich-pik fixed the alignment with spaces here

2022-12-02 12:55 UTC, pfuehrlich-pik approved these changes
Thanks, alignment looks good now :+1:

2022-12-06 11:42 UTC, weindl requested changes

2022-12-06 11:42 UTC, weindl commented on modules/30_crop/endo_apr21/equations.gms
> +          + sum((ct,land_natveg,consv_type), pm_land_conservation(ct,j2,land_natveg,consv_type));
I have two comments here:
1. From the equation I take that the semi-natural land policy should come on top of other land conservation layers. How is this assumption conceptually supported (= why can't the areas included in the conservation masks fulfill the purpose of having natural land in the mosaic)? 
2. How to deal with forestry? The previous implementation used  "past, forestry, primforest, secdforest, other" as possible candidates for semi-natural land, right?
With the new option, there is now the possibility to only allow for "primforest, secdforest, other" as candidates for semi-natural land. If forestry is left out by intention in the new option, I would add this in the comment, e.g. "(not grassland and forestry)".

2022-12-06 11:42 UTC, weindl commented on modules/30_crop/endo_apr21/input.gms
> +s30_snv_natveg_only             Whether only forest and other land are allowed as semi-natural vegetation in cropland areas (0=no 1=yes) / 0 /
see comment above about forestry:  If forestry is left out by intention in the new option, I would add this in the description.

2022-12-06 11:45 UTC, emolinab reviewed
It looks good to me. Although it is not a change in default settings, I think there are many changes, and it would be important to report the time it takes to solve magpie when the switch is on and how do the LU patterns (at least cropland) look like.

2022-12-06 16:38 UTC, pvjeetze commented on modules/30_crop/endo_apr21/equations.gms
> +          + sum((ct,land_natveg,consv_type), pm_land_conservation(ct,j2,land_natveg,consv_type));
But just as a comment: I think this does not crucially change the results...

2022-12-06 16:44 UTC, pvjeetze commented on CHANGELOG.md
> +- **30_crop/config** added switch `s30_snv_natveg_only`for including only natveg in semi-natural vegetation in cropland scenarios
fixed

2022-12-06 16:44 UTC, pvjeetze commented on CHANGELOG.md
>  ### added
fixed

2022-12-06 16:45 UTC, pvjeetze commented on config/scenario_config.csv
> +gms$s30_snv_shr;;;;;;;;;;;;0.2;;;;;;;;;0.2;0.2;0.2;0.2;0.2;;;;;;;;;;;;;;;;;;
I reverted back the changes. I actually ran in the opposite use case in my test runs, where the SSP setting unwantedly overwrote my earlier setting, but probably that's the less common use case. So I stuck to your suggestion.

2022-12-06 16:46 UTC, pvjeetze commented on config/scenario_config.csv
> +gms$s30_snv_scenario_target;;;;;;;;;;;;2030;;;;;;;;;2030;2030;2030;2030;2030;;;;;;;;;;;;;;;;;;
For this switch the specified year is actually irrelevant, as `s30_snv_shr` is zero. So it only really matters in years, where the share is >0.

2022-12-06 16:49 UTC, pvjeetze commented on config/default.cfg
> +cfg$gms$c30_marginal_land <- "q33_marginal"   # def = "q33_marginal"
Not as comprehensively as with your method. I'm still happy to do that. My assumption here was that the tests would again reconfirm this choice and that it was worthwile to include in the new release, to get it done with. But happy as well to wait and include it later

2022-12-06 16:49 UTC, pvjeetze commented on modules/30_crop/endo_apr21/input.gms
> +s30_snv_natveg_only             Whether only forest and other land are allowed as semi-natural vegetation in cropland areas (0=no 1=yes) / 0 /
fixed

2022-12-06 17:16 UTC, pvjeetze commented on modules/30_crop/endo_apr21/equations.gms
> +          + sum((ct,land_natveg,consv_type), pm_land_conservation(ct,j2,land_natveg,consv_type));
ok, but without the proposed `q30_land_snv` equation above we would actually assume that with `s30_snv_natveg_only = 0` protected areas would contribute to SNV in cropland area, which would be inconsistent with `s30_snv_natveg_only = 1`. Are you sure this is fine?

2022-12-07 13:12 UTC, weindl commented on config/default.cfg
> +cfg$gms$c30_marginal_land <- "q33_marginal"   # def = "q33_marginal"
Thank you for the new plots, which are helpful to evaluate the effects.

2022-12-07 13:12 UTC, weindl commented on config/scenario_config.csv
> +gms$s30_snv_shr;;;;;;;;;;;;0.2;;;;;;;;;0.2;0.2;0.2;0.2;0.2;;;;;;;;;;;;;;;;;;
Thank you

2022-12-07 17:08 UTC, pvjeetze commented on modules/30_crop/endo_apr21/equations.gms
> +          + sum((ct,land_natveg,consv_type), pm_land_conservation(ct,j2,land_natveg,consv_type));
Many thanks for the very valuable comments! I fixed the approach based on our bilateral discussion on this. Please see whether this is fine. 
I also think that it is actually that including primary forest does not make sense strictly. By definition any vegetation in ag. landscapes cannot be primary because of the surrounding influence. From the model perspective it also makes sense, because primary forest can only be found in remote areas in the boreal zone or in the Amazon or Congo basins (with minor exceptions maybe).

2022-12-08 20:33 UTC, weindl approved these changes

2022-12-09 06:03 UTC, merged