Efp
magpiemodel/magpie pull request #492
Opened 2022-12-13 12:02 UTC by FelicitasBeier

## :bird: Description of this PR :bird:

- This PR flexibilizes the selection of the start year and target year of the fading in of the Environmental Flow Policy
- Previously, it faded in "linearly" through the file f42_env_flow_policy.csv and alternative scenarios (e.g. the India country case studies used extra files to set different start and target years (f42_env_flow_policy_india.csv))
- Now the start and target year can be set through s42_efp_startyear and s42_efp_targetyear. The policy then fades in truly linearly using a macro

## :wrench: Checklist for PR creator :wrench:

- [x] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - Fading is now linear (before it was nearly linear), minor changes as can be seen in the results shown below

- [x] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [x] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [x] Perform test runs
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
 

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

Some results: 
Tau unchanged
<img width="591" alt="EFP_tau" src="https://user-images.githubusercontent.com/39262100/207312318-ec631682-425f-4744-9f46-389b56e51473.PNG">

Area actually irrigated 
<img width="607" alt="EFP_AAI" src="https://user-images.githubusercontent.com/39262100/207312387-b34db864-de53-4cf1-93b6-a8bae6609c3e.PNG">

Withdrawal comparing EFP off with EFP on (old and new)
<img width="604" alt="EFPwithdrawal" src="https://user-images.githubusercontent.com/39262100/207312444-51781b25-9e80-4840-9046-bd1bd8e012bb.PNG">

Withdrawal with example of different start and end year compared to previous default
<img width="600" alt="withdrawalNEWSCEN" src="https://user-images.githubusercontent.com/39262100/207312518-32cd841c-e63f-423b-afc3-b2507a58ec4f.PNG">

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate

2022-12-13 12:38 UTC, tscheypidi approved these changes

2022-12-14 03:44 UTC, bodirsky requested changes

2022-12-14 03:44 UTC, bodirsky commented on core/macros.gms
>  $macro m_linear_interpol(input,start_year,target_year,start_value,target_value) \
The macro is also used in 44_biodiversity. 
changing >= to = is a content-wise change that needs to be coordinated with them. Did you?

2022-12-14 03:44 UTC, bodirsky commented on core/macros.gms
>  $macro m_linear_interpol(input,start_year,target_year,start_value,target_value) \
i also think it makes more sense as you do it , but it will change the behaviour in their case.
so you should adapt 
 s44_start_year			Start year of biodiversity price (1) 							/ 2025 /
 s44_target_year		Target year of biodiversity price  (1)							/ 2100 /
 i think only the first one needs changing (to 2020).
 the second one is probably a flaw by them

2022-12-14 03:44 UTC, bodirsky commented on core/macros.gms
>  $macro m_linear_interpol(input,start_year,target_year,start_value,target_value) \
I also wonder whether its the intended behaviour that they overwrite all past timesteps with start_year, so that the history gets eliminated.

2022-12-14 03:44 UTC, bodirsky commented on core/macros.gms
>  $macro m_linear_interpol(input,start_year,target_year,start_value,target_value) \
actually, im unsere whether your <= to = change has an effect at all?
in any case, i think some things are weird in this function

2022-12-14 03:44 UTC, bodirsky commented on modules/42_water_demand/agr_sector_aug13/presolve.gms
> +* Agricultural water demand
i assume this is just moved without changes?

2022-12-14 03:44 UTC, bodirsky commented on modules/42_water_demand/agr_sector_aug13/presolve.gms
> +  i42_env_flow_policy(t,i) = (im_development_state(t,i) * p42_efp(t,"on")) * p42_EFP_region_shr(t,i)
if you want to save a parameter, included new calcs from preloop in here

2022-12-14 03:44 UTC, bodirsky commented on modules/42_water_demand/agr_sector_aug13/preloop.gms
> +* Trajectory for environmental flow policy
instead of "on" "of" setting, i would define the target value (can also be 0.5, or stay at 0).
That would allow us later also to say SSP1 has an EFP of 50% (at the moment, i dont like the 100% setting for SSP1 which is part of the trunk)

2022-12-14 03:44 UTC, bodirsky commented on modules/42_water_demand/agr_sector_aug13/preloop.gms
> +* Trajectory for environmental flow policy
would also reduce dimensionality

2022-12-14 03:44 UTC, bodirsky commented on modules/42_water_demand/agr_sector_aug13/preloop.gms
> +* Trajectory for environmental flow policy
one coudl have one target value for activated countries, and one for discactivated countries. so even more differentiation would be possible, and calculations would be largely simplified

2022-12-14 08:18 UTC, tscheypidi commented on core/macros.gms
>  $macro m_linear_interpol(input,start_year,target_year,start_value,target_value) \
I had some discussions with Feli about it and to our understanding it does not affect behavior in currently used cases but allows to set start_year = target_year, which currently does not work due to a division by zero

2022-12-14 08:21 UTC, FelicitasBeier commented on modules/42_water_demand/agr_sector_aug13/presolve.gms
> +* Agricultural water demand
Yes. The equations are now ordered by content rather than mixed. No effect on the results.

2022-12-14 08:24 UTC, FelicitasBeier commented on modules/42_water_demand/agr_sector_aug13/preloop.gms
> +* Trajectory for environmental flow policy
You can define different EFPs already in the model. 
The change here is just about the fading in of the policy.
For the setting you want, you would change s42_env_flow_scenario.

If you want further settings this would be for a future PR and I would even advise to wait until the mrwater preprocessing is included as we have even more flexibility there to make it SSP-specific

2022-12-15 10:35 UTC, bodirsky approved these changes

2022-12-15 12:49 UTC, FelicitasBeier commented on core/macros.gms
>  $macro m_linear_interpol(input,start_year,target_year,start_value,target_value) \
This is not the case because the start_value is set to 0

2022-12-15 12:50 UTC, FelicitasBeier commented on modules/42_water_demand/agr_sector_aug13/presolve.gms
> +  i42_env_flow_policy(t,i) = (im_development_state(t,i) * p42_efp(t,"on")) * p42_EFP_region_shr(t,i)
This is not possible because the macro expects an object with only one dimension, but p42_efp has two.

2022-12-15 12:51 UTC, merged