employment from maccs
magpiemodel/magpie pull request #496
Opened 2022-12-23 09:54 UTC by deleip

## :bird: Description of this PR :bird:

- This PR includes labor cost from maccs in the employment calculation (and splits costs from maccs into labor and capital to do so)

## :wrench: Checklist for PR creator :wrench:

- [x] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [x] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [x] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : 21 mins
  - This PR's default :  22 mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2022-12-23 14:17 UTC, bodirsky requested changes

2022-12-23 14:17 UTC, bodirsky commented on modules/36_employment/exo_may22/equations.gms
> +*' the same way in a separate equation, using the labor costs coming from the
the same way = assuming the same capital share

2022-12-23 14:17 UTC, bodirsky commented on modules/36_employment/exo_may22/input.gms
> +s36_minimum_wage global minimum wage (USDMER05 per hour) / 5 /
why is 5 the new default?

2022-12-23 14:17 UTC, bodirsky commented on modules/36_employment/module.gms
>  *' The calculation of employment then uses labor costs for crop and livestock production
one "and" could be removed

2022-12-23 14:17 UTC, bodirsky commented on modules/38_factor_costs/sticky_feb18/input.gms
> +$setglobal c38_fac_req  reg
documetnation missing what this switch is doing

2022-12-23 14:17 UTC, bodirsky commented on modules/38_factor_costs/sticky_labor/input.gms
> +$setglobal c38_fac_req  reg
same as above

2022-12-23 14:17 UTC, bodirsky commented on modules/57_maccs/on_aug22/declarations.gms
> + vm_maccs_costs(i,req)   Costs of technical mitigation of GHG emissions (mio. USD95MER per yr)
req is not an intuitive dimension name to me. requirements?

2022-12-23 14:17 UTC, bodirsky commented on modules/57_maccs/on_aug22/equations.gms
> +  * sum(ct, pm_cost_share_crops(ct ,i2,"labor") * (1/pm_productivity_gain_from_wages(ct,i2)) *
not sure whether "productivtiy_gain_from_wages" is the right causality; isnt it more wage_gain_from_productivtiy?
a higher wage doesnt cause a higher productivity, but vice versa, i guess

2022-12-23 14:17 UTC, bodirsky commented on modules/57_maccs/on_aug22/equations.gms
> +*' productivity change.
this part im not fully sure i understand.
Do you assume that labor costs fall with increasing labor productivity? should it just be the labor quantity which is falling (because the labour requriements can be satisfied by fewer people)?
or is this only for the scenario where wages are increased without productivity increasing?

2022-12-23 14:27 UTC, tscheypidi approved these changes
overall looks good to me. There are just some settings which changed in the GAMS code but I did not see any changes in default.cfg. Under the assumption that the defaults did **not** change it would be good to revert the setting changes in the gms files. If there are actually changes in default settings I would like to understand better why these changed.

2022-12-23 14:27 UTC, tscheypidi commented on modules/38_factor_costs/sticky_feb18/input.gms
> +$setglobal c38_fac_req  reg
and did the default change here?

2022-12-23 14:27 UTC, tscheypidi commented on modules/57_maccs/on_aug22/equations.gms
> +  * sum(ct, pm_cost_share_crops(ct ,i2,"labor") * (1/pm_productivity_gain_from_wages(ct,i2)) *
what about a neutral formulation such as `producitivity_wages_relationship`?

2022-12-23 14:27 UTC, tscheypidi commented on modules/57_maccs/on_aug22/input.gms
> +  s57_maxmac_n_soil    activate soil N mitigation independent of pollutant price (step of MACC and -1 is inactive) / 201 /
some other changes in default settings?

2022-12-23 14:49 UTC, deleip commented on modules/57_maccs/on_aug22/equations.gms
> +*' productivity change.
labor costs are first scaled according to the change in wages (so same number of people employed but earning more). But if we also have a productivity increase it should actually be less people that earn the higher wage, so we divide again by a factor describing the productivity gain.
Would "The labor share is scaled according to the changes in wages, taking into account the corresponding productivity change." be clearer?

2022-12-23 14:49 UTC, deleip commented on modules/57_maccs/on_aug22/equations.gms
> +  * sum(ct, pm_cost_share_crops(ct ,i2,"labor") * (1/pm_productivity_gain_from_wages(ct,i2)) *
in real life, yes. But the logic in magpie is the other way round: we have external wage scenarios, and then a switch to decide whether (and how much) productivity should also change. So I actually think it would be good to keep it this way, also to keep in mind that this is not implemented the way it would in reality happen

2022-12-23 14:53 UTC, deleip commented on modules/36_employment/exo_may22/equations.gms
> +*' the same way in a separate equation, using the labor costs coming from the
the capital share is already applied in the 57_maccs module, here I only mean how employment is calculated from labor cost (i.e. dividing by hourly labor costs and weekly hours). I changed the description to make it clearer

2022-12-23 14:53 UTC, deleip commented on modules/36_employment/exo_may22/input.gms
> +s36_minimum_wage global minimum wage (USDMER05 per hour) / 5 /
it's not, it just changed due a test run I made, I reverted it

2022-12-23 14:53 UTC, deleip commented on modules/38_factor_costs/sticky_labor/input.gms
> +$setglobal c38_fac_req  reg
same as above ;)

2022-12-23 14:59 UTC, deleip commented on modules/57_maccs/on_aug22/input.gms
> +  s57_maxmac_n_soil    activate soil N mitigation independent of pollutant price (step of MACC and -1 is inactive) / 201 /
none of the default settings changed, I just messed up and pushed some changes from a test run I made. I reverted it

2022-12-23 15:03 UTC, deleip commented on modules/57_maccs/on_aug22/declarations.gms
> + vm_maccs_costs(i,req)   Costs of technical mitigation of GHG emissions (mio. USD95MER per yr)
this is not a new set, but what we also use in the factor_costs module. And we also use req as abbreviation for requirement in many variable names... But I can change if you really think it is unclear

2023-01-04 08:59 UTC, bodirsky approved these changes

2023-01-04 08:59 UTC, bodirsky commented on modules/57_maccs/on_aug22/declarations.gms
> + vm_maccs_costs(i,req)   Costs of technical mitigation of GHG emissions (mio. USD95MER per yr)
hmm, still dont know what it means ;)
A change woudl be good, but not obligatory for me accepting the PR :)

2023-01-04 08:59 UTC, bodirsky commented on modules/57_maccs/on_aug22/equations.gms
> +*' productivity change.
no its ok, i read it once more, now its clearer to me.

2023-01-04 12:59 UTC, merged