labor share target in crop production
magpiemodel/magpie pull request #499
Opened 2023-01-09 14:25 UTC by deleip

## :bird: Description of this PR :bird:

- This PR allows to set a target labor share (out of labor + capital costs for crop production) to be met by 2050. To allow for regional differences, an adjustment factor (`s38_target_labor_share_adjustment`) is applied to the difference between baseline labor cost share in 2050 and the global target (`s38_target_labor_share`) to define an regionally adjusted target. 

## :wrench: Checklist for PR creator :wrench:

- [x] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [x] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [x] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2023-01-11 09:49 UTC, bodirsky requested changes
naming changes request, content looks fine!

2023-01-11 09:49 UTC, bodirsky commented on modules/38_factor_costs/sticky_labor/presolve.gms
> +if (m_year(t) < s38_fix_capital_need,
s38_fix_capital need again doesnt sound like the parameter where a minimum labor share kicks in
how about s38_startyear_min_labor?

2023-01-11 09:49 UTC, bodirsky commented on modules/38_factor_costs/sticky_labor/presolve.gms
> +if (m_year(t) < s38_fix_capital_need,
and why is the min year with a parameter, but the target year 2050 is hardcoded? the other way round would seem more logical, or even better both parameters.

2023-01-11 09:49 UTC, bodirsky commented on modules/56_ghg_policy/price_aug22/input.gms
> +  s56_limit_ch4_n2o_price upper limit for CH4 and N2O GHG prices (USD05MER per tC) / 4000 /
i guess this change is not by you?

2023-01-11 13:28 UTC, deleip commented on modules/38_factor_costs/sticky_labor/presolve.gms
> +if (m_year(t) < s38_fix_capital_need,
s38_fix_capital was already introduced earlier, to allow comparison between sticky_labor and sticky_feb16. So it's not only about the start year for min_labor scenarios but more general. How about s38_startyear_labor_substitution? But that might be still confusing, as 2020 is not the first year with substitution, but the last year where it's still fixed...

2023-01-11 13:30 UTC, deleip commented on modules/38_factor_costs/sticky_labor/presolve.gms
> +if (m_year(t) < s38_fix_capital_need,
That s38_fix_capital was already there before is also the reason why this is a parameter in the target labor share calculation (for consistency), while 2050 is fixed. I can make the target year a parameter as well...

2023-01-11 13:33 UTC, deleip commented on modules/56_ghg_policy/price_aug22/input.gms
> +  s56_limit_ch4_n2o_price upper limit for CH4 and N2O GHG prices (USD05MER per tC) / 4000 /
no, Florian changed the default a few weeks back

2023-01-12 10:51 UTC, bodirsky approved these changes

2023-01-12 15:25 UTC, tscheypidi approved these changes

2023-01-12 15:48 UTC, merged