added sub-national validation output script for India
magpiemodel/magpie pull request #500
Opened 2023-01-10 13:01 UTC by PrantikaDas

## :bird: Description of this PR :bird:

- The output script generates subnational spatial validation for India in comparison to India's national agriculture database

## :wrench: Checklist for PR creator :wrench:

- [X] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts

- [X] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
 
- [X] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments

- [X] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : NA
  - This PR's default :  NA

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2023-01-10 13:12 UTC, pfuehrlich-pik commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +ind_apy_mapping <- read.csv(system.file("extdata", "regional/mappingIndiaAPY.csv", package = "mrfable"))
Does `madrat::toolGetMapping` not work here?

2023-01-10 13:12 UTC, pfuehrlich-pik commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +# hist     <- "runs/validation.mif"
```suggestion
```

2023-01-10 13:12 UTC, pfuehrlich-pik commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +  outputdir <- "output//v4p77/h12_2022-12-15_22.09.46"
```suggestion
  outputdir <- "output/v4p77/h12_2022-12-15_22.09.46"
```

2023-01-10 13:12 UTC, pfuehrlich-pik commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +ind_states <- read.csv(system.file("extdata", "regional/india_state_code.csv", package = "mrfable"))
I'd suggest that we stick to camelCase in magpiemodel as well, so it is consistent with our variable naming style in R packages.
```suggestion
indStates <- read.csv(system.file("extdata", "regional/india_state_code.csv", package = "mrfable"))
```

2023-01-10 13:25 UTC, pfuehrlich-pik commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +ind_states <- read.csv(system.file("extdata", "regional/india_state_code.csv", package = "mrfable"))
No, both functions and variables should follow camelCase

2023-01-10 13:39 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +ind_apy_mapping <- read.csv(system.file("extdata", "regional/mappingIndiaAPY.csv", package = "mrfable"))
it does. will change

2023-01-11 10:41 UTC, mishkos requested changes

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +ind_states <- read.csv(system.file("extdata", "regional/india_state_code.csv", package = "mrfable"))
```suggestion
indStates <- toolGetMapping(system.file("extdata", "regional/india_state_code.csv", package = "mrfable"))
```

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +ind_cells <- which(mapping$ind %in% ind_states$State_code)
```suggestion
indCells <- which(mapping$ind %in% indStates$State_code)
```

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +land_hr <- read.magpie(file.path(outputdir,"cell.land_0.5.mz"))[ind_cells,,]
```suggestion
landHr <- read.magpie(file.path(outputdir,"cell.land_0.5.mz"))[indCells,,]
```

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +croparea_hr_share <- read.magpie(file.path(outputdir,"cell.croparea_0.5_share.mz"))[ind_cells,,]
```suggestion
cropareaHrShare <- read.magpie(file.path(outputdir,"cell.croparea_0.5_share.mz"))[indCells,,]
```

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +cell_hr <- dimSums(land_hr, dim=3)
```suggestion
cellHr <- dimSums(landHr, dim=3)
```

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +croparea_hr <- croparea_hr_share[,,]*setItems(cell_hr[,1,], dim=2, NULL)
```suggestion
cropareaHr <- cropareaHrShare[,,]*setItems(cell_hr[,1,], dim=2, NULL)
```

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +croparea_hr <- dimSums(croparea_hr, dim=3.2)
```suggestion
cropareaHr <- dimSums(cropareaHr, dim=3.2)
```

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +mapping_ind <- mapping[ind_cells,]
```suggestion
mappingInd <- mapping[indCells,]
```

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +croparea_state <- toolAggregate(croparea_hr, rel=mapping_ind, from="iso_mag", to="ind")
```suggestion
cropareaState <- toolAggregate(cropareaHr, rel=mappingInd, from="iso_mag", to="ind")
```

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +ind_apy_mapping <- read.csv(system.file("extdata", "regional/mappingIndiaAPY.csv", package = "mrfable"))
```suggestion
indApyMapping <- toolGetMapping(system.file("extdata", "regional/mappingIndiaAPY.csv", package = "mrfable"))
```

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +h <- h[ind_states$State_code,,]
```suggestion
h <- h[indStates$State_code,,]
```

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +croparea_state <- croparea_state[,,unique(mappingCropsAPY[,"k"])]
```suggestion
cropareaState <- cropareaState[,,unique(mappingCropsAPY[,"k"])]
```

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +names(dimnames(croparea_state)) <- c("state","year","crop")
```suggestion
names(dimnames(cropareaState)) <- c("state","year","crop")
```

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +croparea_state <- add_dimension(croparea_state, dim=3.1, add="scenario", nm="")
```suggestion
cropareaState <- add_dimension(cropareaState, dim=3.1, add="scenario", nm="")
```

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +croparea_state <- add_dimension(croparea_state, dim=3.2, add="model", nm="MAgPIE")
```suggestion
cropareaState <- add_dimension(cropareaState, dim=3.2, add="model", nm="MAgPIE")
```

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +croparea_state <- setItems(croparea_state, dim=3.3, reportingnames(getItems(croparea_state,dim=3.3)))
```suggestion
cropareaState <- setItems(cropareaState, dim=3.3, reportingnames(getItems(cropareaState,dim=3.3)))
```

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +    swlatex(sw,paste0("\\section{Croparea ",k," in ",ind_states[which(ind_states$State_code==state),"State_name"],"}"))
```suggestion
    swlatex(sw,paste0("\\section{Croparea ",k," in ",indStates[which(indStates$State_code==state),"State_name"],"}"))
```

2023-01-11 10:41 UTC, mishkos commented on scripts/output/projects/FABLE_India_subnational_validation.R
> +    swfigure(sw, print, mipLineHistorical(croparea_state[state,,k],h[state,,k],ylab="Mha"))
```suggestion
    swfigure(sw, print, mipLineHistorical(cropareaState[state,,k],h[state,,k],ylab="Mha"))
```

2023-01-11 12:28 UTC, mishkos approved these changes
The script is running after adopted styling changes. Looks good.

2023-01-11 13:34 UTC, pfuehrlich-pik approved these changes

2023-01-11 13:36 UTC, merged