Disaggregation to 0.5° takes land conservation into account
magpiemodel/magpie pull request #536
Opened 2023-03-01 08:53 UTC by pvjeetze

## :bird: Description of this PR :bird:

- So far, land conservation (current WDPA or future land conservation) was irgnored during disaggregation. This PR changes that. Now, cropland expansion at the 0.5° level does not happen in areas subject to land conservation.
- This is important for all indicators that are derived from the 0.5°  land use map, e.g. the BII in the FSEC context. 

## :wrench: Checklist for PR creator :wrench:

- [ ] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [ ] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [ ] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2023-03-01 18:34 UTC, tscheypidi requested changes

2023-03-01 18:34 UTC, tscheypidi commented on scripts/output/extra/disaggregation.R
> +library(mrcommons)
there should not be any dependencies on madrat-based packages in the postprocessing. the madrat-package itself is an exception and can be loaded for `toolAggregate`. What are you using here from `mrcommons`?

2023-03-01 18:34 UTC, tscheypidi commented on config/default.cfg
> +                            "modules/22_land_conservation/input/consv_prio_areas_0.5.mz",
is that required to have these files copied into every output folder?

2023-03-02 08:04 UTC, pvjeetze commented on scripts/output/extra/disaggregation.R
> +library(mrcommons)
This was simply adopted from the previous `extra/disaggregation_BII.R` script, which used the function `mrcommons::toolCell2isoCell()`. However, I just had a look at it and found that it could actually be removed.

2023-03-02 08:08 UTC, pvjeetze commented on config/default.cfg
> +                            "modules/22_land_conservation/input/consv_prio_areas_0.5.mz",
Yes, in particular `consv_prio_areas_0.5.mz` is used in other instances during postprocessing. This has also been discussed with @flohump. According to @flohump this also prevents errors in high-resolution run batches.

2023-03-02 08:35 UTC, flohump approved these changes
thanks for these improvements

2023-03-02 08:35 UTC, flohump commented on config/default.cfg
> +                            "modules/22_land_conservation/input/consv_prio_areas_0.5.mz",
Yes. If you start multiple runs at the same time or do highres runs, there can be cases when where the requested file for the output script is not in `input` or `modules/xxx/input` because at the same time new input data is downloaded for preparing another run.
Moreover, we can also have cases where 0.5 degree files differ between RCPs. This think this not the case here.

2023-03-02 10:15 UTC, tscheypidi approved these changes

2023-03-02 10:22 UTC, merged