Introducing exogenous diets for India
magpiemodel/magpie pull request #541
Opened 2023-03-07 08:22 UTC by vartika271987

## :bird: Description of this PR :bird:

- This PR introduces exogenous diet scenario for India as prescribed by the National Institute of Nutrition(NIN) in India. The scalar `s15_exo_nin` alongwith the `scen_countries15` allow the possibility to set exogenous diets for India with or without exogenous diets for other regions. 

## :wrench: Checklist for PR creator :wrench:

- [X] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)

- [X] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [X] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [X] Perform test runs
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    
1. Calorie Intake - default versus NIN India endo other regions 
![image](https://user-images.githubusercontent.com/51452385/223360316-c193d1da-1495-4b06-9a52-0740d6da7091.png)
2. Calorie Intake - default versus NIN India EAT other regions 
![image](https://user-images.githubusercontent.com/51452385/223360448-23e87caf-be1f-43b7-9aee-3eca1836f500.png)
3. Calorie Intake only for India - default, EAT all regions, NIN India EAT other regions 
![image](https://user-images.githubusercontent.com/51452385/223361108-eaa87436-e919-4fb1-ac93-fe17b5408e4a.png)
4. Cropland 
![image](https://user-images.githubusercontent.com/51452385/223362741-559d19d1-25f8-4995-9b56-6ae72b54e867.png)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default :35.06 mins
  - This PR's default :  33:49 mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2023-03-09 13:00 UTC, weindl requested changes

2023-03-09 13:00 UTC, weindl commented on modules/15_food/input/files
> +f15_intake_NIN.cs3
I did not find a new input file "f15_intake_NIN.cs3" and think it can be deleted here.

2023-03-13 10:20 UTC, vartika271987 commented on config/default.cfg
> +# * Also need to set cfg$gms$scen_countries15  <- "IND" for this switch to work
Done

2023-03-13 10:20 UTC, vartika271987 commented on modules/15_food/anthro_iso_jun22/input.gms
> +$offdelim;
Yes. I have updated the description now

2023-03-13 10:21 UTC, vartika271987 commented on config/default.cfg
> +cfg$gms$s15_exo_nin <- 0               # def = 0
Done

2023-03-13 10:21 UTC, vartika271987 commented on modules/15_food/input/files
> +f15_intake_NIN.cs3
Done.

2023-03-13 11:07 UTC, weindl commented on modules/15_food/anthro_iso_jun22/input.gms
> +>>>>>>> e9d2797ef4bebb36c9509f069c6bd65e31bbb3b5
Please remove these remaining lines from a merge conflict.

2023-03-13 11:11 UTC, weindl commented on modules/15_food/anthro_iso_jun22/input.gms
> +**Different set elements for sets "t_scen15", "kcal_scen15" and "EAT_scen15" result in the identical target diet as per f15_intake_EATLancet
I think there is still the info missing that this file contains the NIN data for India, and the EAT-Lancet diet for all other countries.

2023-03-13 11:23 UTC, vartika271987 commented on modules/15_food/anthro_iso_jun22/input.gms
> +* Only one option applicable for India
Added description in defau;t.cfg and updated changelog

2023-03-13 11:23 UTC, vartika271987 commented on modules/15_food/anthro_iso_jun22/input.gms
> +>>>>>>> e9d2797ef4bebb36c9509f069c6bd65e31bbb3b5
Done

2023-03-13 11:24 UTC, vartika271987 commented on modules/15_food/anthro_iso_jun22/input.gms
> +$offdelim;
Have expanded on this now.

2023-03-13 14:04 UTC, weindl commented on modules/15_food/anthropometrics_jan18/presolve.gms
> +        i15_intake_EATLancet_all(i,"2100kcal","%c15_NIN_scen%",kfo);
This line should not be modified, since it determines the configuration of the EAT-Lancet diet (not the NIN diet which is determined in the line below).
Please revert "%c15_NIN_scen%" --> "%c15_EAT_scen%"

2023-03-13 14:05 UTC, weindl commented on modules/15_food/anthropometrics_jan18/presolve.gms
> +        i15_intake_EATLancet_all(i,"%c15_kcal_scen%","%c15_NIN_scen%",kfo);
This line should not be modified, since it determines the configuration of the EAT-Lancet diet (not the NIN diet which is determined in the line below).
Please revert "%c15_NIN_scen%" --> "%c15_EAT_scen%"

2023-03-14 03:26 UTC, vartika271987 commented on modules/15_food/anthropometrics_jan18/presolve.gms
> +        i15_intake_EATLancet_all(i,"2100kcal","%c15_NIN_scen%",kfo);
This creeped in erroneously from a merge conflict. Has been removed. The old anthropometrics realization does not contain any reference to NIN anymore.

2023-03-14 03:26 UTC, vartika271987 commented on modules/15_food/anthropometrics_jan18/presolve.gms
> +        i15_intake_EATLancet_all(i,"%c15_kcal_scen%","%c15_NIN_scen%",kfo);
This creeped in erroneously from a merge conflict. Has been removed.

2023-03-15 12:10 UTC, weindl commented on CHANGELOG.md
> +  provide dietary scenarios within NIN for India. At present contains only one option
Please remove the comments regarding the India diet changes here (under section [4.6.4]). You have already correctly included them in line 19.

2023-03-15 12:14 UTC, weindl commented on modules/15_food/anthropometrics_jan18/presolve.gms
> +        i15_intake_EATLancet_all(i,"2100kcal","%c15_NIN_scen%",kfo);
Thanks for fixing this. Looks good now. However, the switch c15_NIN_scen is now not used anymore, and should therefore be deleted from all files (i.e. from the default.cfg and modules/15_food/anthro_iso_jun22/input.gms)

2023-03-15 12:16 UTC, weindl requested changes
Thanks for the modifications. Some small issues still need to be addressed.

2023-03-16 05:29 UTC, vartika271987 commented on modules/15_food/anthropometrics_jan18/presolve.gms
> +        i15_intake_EATLancet_all(i,"2100kcal","%c15_NIN_scen%",kfo);
The c15_NIN_scen was created to reflect the only possible scenario for India under `FLX_hmilk` option. I have now added this information in the description of the switch which includes all settings needed to correctly activate the NIN India settings.

2023-03-16 05:29 UTC, vartika271987 commented on CHANGELOG.md
> +  provide dietary scenarios within NIN for India. At present contains only one option
Done

2023-04-05 14:15 UTC, vartika271987 commented on config/default.cfg
> +cfg$gms$s15_exo_nin <- 0               # def = 0
I have now replaced the setting by removing the extra switch and adding a third options for `s15_exo_diet` where exogenous diet scenario for India can be selected.

2023-04-05 14:15 UTC, vartika271987 commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +   if((s15_exo_diet = 1 or s15_exo_nin = 1),
Replaced by adding a third scenario in `s15_exo_diet`. Works fine.

2023-04-05 14:16 UTC, vartika271987 commented on CHANGELOG.md
> +- **15_food** added `s15_exo_nin` scalar, input data and other configuration for inclusion of India's exogenous diet recommendations by National Institute of Nutrition (NIN)
Done now.

2023-04-05 14:16 UTC, vartika271987 commented on CHANGELOG.md
> +- **config** added options for afforestation assumptions and updated additional data to 4.38
This occured because of several merge conflicts. It should be fine now.

2023-04-05 14:24 UTC, tscheypidi approved these changes

2023-04-05 15:11 UTC, merged