magpie release 4.6.6
magpiemodel/magpie pull request #556
Opened 2023-05-05 09:56 UTC by pfuehrlich-pik

2023-05-05 09:59 UTC, FelicitasBeier approved these changes
Thanks

2023-05-05 10:14 UTC, tscheypidi approved these changes

2023-05-05 15:19 UTC, FelicitasBeier requested changes
still wait until next week for the release

2023-05-10 14:09 UTC, FelicitasBeier approved these changes
Looks good. Thank you!

2023-05-10 14:55 UTC, merged