Update pasture management factor
magpiemodel/magpie pull request #578
Opened 2023-07-17 13:58 UTC by weindl

## :bird: Description of this PR :bird:

-  The temporal development of milk demand is integrated as additional driver in the calculation of the pasture management factor. Additional changes are due to minor clean-up and re-calibration.

## :wrench: Checklist for PR creator :wrench:

- [x] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [x] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)
    

![Emissions_CO2_Land_Land_use_Change](https://github.com/magpiemodel/magpie/assets/39915455/e7d7bb23-1c36-4f15-a710-f065a40c408c)

![Resources_Land_Cover_Cropland](https://github.com/magpiemodel/magpie/assets/39915455/f031a470-6418-4e66-97e2-af432d38e7c1)

![Resources_Land_Cover_Pastures_and_Rangelands](https://github.com/magpiemodel/magpie/assets/39915455/b5b01bf0-f978-48ed-a882-ad46241a16af)

![Productivity_Landuse_Intensity_Indicator_Tau](https://github.com/magpiemodel/magpie/assets/39915455/d221bca7-411e-4012-babd-c709512565e0)

![Prices_Index2020_Agriculture_Food_products](https://github.com/magpiemodel/magpie/assets/39915455/3575c535-0f25-49ad-b2e8-0531f2fd8b07)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2023-07-18 07:38 UTC, tscheypidi requested changes
solution looks good to me but I would update the formulation in the code slightly

2023-07-18 07:38 UTC, tscheypidi commented on modules/15_food/anthro_iso_jun22/input.gms
> +$setglobal c15_rumdairy_scp_scen  sigmoid_20pc_20_50
`default.cfg` says the setting should be constant. Did you run the tests with sigmoid_20pc_20_50?

```suggestion
$setglobal c15_rumdairy_scp_scen  constant
```

2023-07-18 07:38 UTC, tscheypidi commented on modules/15_food/anthropometrics_jan18/input.gms
> +$setglobal c15_rumdairy_scp_scen  sigmoid_20pc_20_50
again deviation from settings in default.cfg
```suggestion
$setglobal c15_rumdairy_scp_scen  constant
```

2023-07-18 07:38 UTC, tscheypidi commented on modules/31_past/grasslands_apr22/input.gms
> +$setglobal c31_past_suit_scen  ssp245
deviation from default.cfg
```suggestion
$setglobal c31_past_suit_scen  ssp370
```

2023-07-18 07:38 UTC, tscheypidi commented on modules/70_livestock/fbask_jan16/presolve.gms
> +       )$(ord(t)>1);
This equation is a bit hard to read if you do not know what it does. I would suggest to split it into two and check again whether there might be a workaround not to have to use the mapping `kap_to_kfo_ap`. The revised code could be something along the lines of:

```
p70_cattle_pc(t,i,kli_rd) = pm_kcal_pc_initial(t,i,kli_rd))*im_feed_baskets(t,i,kli_rd,"pasture")/fm_nutrition_attributes(t,kli_rd,"kcal");

p70_incr_cattle(t,i)  =  1$(ord(t)=1) + (p70_cattle_pc(t,i,"livst_rum")* p70_cattle_stock_proxy(t,i)/p70_cattle_stock_proxy(t-1,i) + p70_cattle_pc(t,i,"livst_milk")* p70_milk_cow_proxy(t,i)/p70_milk_cow_proxy(t-1,i))/sum(kli_rd, p70_cattle_pc(t,i,kli_rd));

2023-07-19 08:39 UTC, weindl commented on modules/15_food/anthro_iso_jun22/input.gms
> +$setglobal c15_rumdairy_scp_scen  sigmoid_20pc_20_50
Thanks for noting the inconsistency. Yes, I did test runs with sigmoid_20pc_20_50 and did not revert this setting back to default.

2023-07-19 11:41 UTC, weindl commented on modules/31_past/grasslands_apr22/input.gms
> +$setglobal c31_past_suit_scen  ssp245
The reason for this inconsistency with the default.cfg is that the SSP2 settings in the scenario_config.csv in this case deviates from the default setting. However, since another PR will remove the switch c31_past_suit_scen in the near future, the inconsistency will also be removed. I nonetheless reverted my change as proposed.

2023-07-19 20:56 UTC, weindl commented on modules/16_demand/sector_may15/sets.gms
> +   kap_to_kfo_ap(kap,kfo_ap) Mapping between animal products and animal food products
A solution was found without the need to introduce this additional mapping.

2023-07-19 21:05 UTC, tscheypidi approved these changes

2023-07-20 07:15 UTC, bodirsky commented on modules/70_livestock/fbask_jan16/declarations.gms
> + p70_cattle_stock_proxy(t,i)                      Proxy for cattle stocks needed to fullfil food demand for ruminant meat (mio. animals per yr)
why proxy and why not just stocks?
Would be great to have animal numbers in the model, its a very good output indicator.

2023-07-20 07:15 UTC, bodirsky commented on modules/70_livestock/fbask_jan16/declarations.gms
>   i70_livestock_productivity(t_all,i,sys)          Productivity indicator for livestock production (t FM per animal per yr)
is it really per animal? what about chicken?

2023-07-20 07:15 UTC, bodirsky commented on modules/70_livestock/fbask_jan16/presolve.gms
> +p70_milk_cow_proxy(t,i)$(p70_milk_cow_proxy(t,i) < 0.2*p70_milk_cow_proxy("y1995",i)) = 0.2*p70_milk_cow_proxy("y1995",i);
so the animals cannot be less than 20% of initial stocks? or is this just for the grassland calculations?

2023-07-20 07:15 UTC, bodirsky commented on modules/70_livestock/fbask_jan16/presolve.gms
> +p70_milk_cow_proxy(t,i)$(p70_milk_cow_proxy(t,i) < 0.2*p70_milk_cow_proxy("y1995",i)) = 0.2*p70_milk_cow_proxy("y1995",i);
maybe make clearer that this is a special case calculation, and not about stocks in general?

2023-07-20 07:15 UTC, bodirsky commented on modules/70_livestock/fbask_jan16/presolve.gms
> +p70_milk_cow_proxy(t,i)$(p70_milk_cow_proxy(t,i) < 0.2*p70_milk_cow_proxy("y1995",i)) = 0.2*p70_milk_cow_proxy("y1995",i);
something like "grazing_intensity_stock_proxy"

2023-07-20 07:15 UTC, bodirsky commented on modules/70_livestock/fbask_jan16/presolve.gms
> +*' that links changes in pasture management with changes in the number of cattle:
I am missing here some information how this linear relationship was derived

2023-07-20 11:43 UTC, bodirsky approved these changes

2023-07-20 13:44 UTC, merged