Cluster-level Residues Realization
magpiemodel/magpie pull request #585
Opened 2023-08-08 16:20 UTC by caviddhen

## :bird: Description of this PR :bird:

Add a cluster-level residues realization of reduced complexity. This realization allows for tracking the cluster-level production of agricultural residues via the new variable v18_prod_res. Other fates of residues (i.e. recycling and burning), as well as below-ground production, still happen at regional level, in order to reduce runtime.

## :wrench: Checklist for PR creator :wrench:

- [ ] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [ ] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [ ] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2023-08-09 12:46 UTC, pfuehrlich-pik reviewed
Thanks a lot for this impressive work and major contribution! The code is well documented, so even though I don't know much at all about how magpie's gams code works I could follow rather well! The one bigger thing I'd suggest though is not using the word "cell" or "cellular" anymore, as it means cluster in some cases and gridcell in others. In magpie's gams code, cell always means cluster (as Patrick told me), so I'd suggest always using the words "cluster" or "cluster-level" (as you already do in some cases) instead.

2023-08-18 09:24 UTC, k4rst3ns commented on modules/18_residues/flexcell_july23/declarations.gms
> + v18_res_biomass_ag_cell(j,kcr)             Production of aboveground residues in each cluster (mio. tDM)
Maybe that means that the whole realization name than should be changed?
According to that it might make sense to be a bit more specific as only the removals are on cluster/cell level?
Sorry I know renaming always costs some efforts ^^'

2023-08-18 09:45 UTC, k4rst3ns approved these changes
Equation look good to me. Realization despription highlights that residue production/removal is on cluster level, but changelog as well as naming might be changed to a clearer name, as it might be that upcoming realizations might be as well on cluster level having other features (e.g. recycling on cluster level).

2023-08-18 09:45 UTC, k4rst3ns commented on CHANGELOG.md
> +- **18_residues** Included cluster-level residue realization
maybe more specific what variables are on cluster level?

2023-08-18 09:45 UTC, k4rst3ns commented on modules/18_residues/flexcell_july23/declarations.gms
> + v18_res_ag_removal(j,kcr,attributes)       Removal of crop residues in respective attribute units DM GJ Nr P K WM C (mio. tX)
Will that be an interface soon?
If so maybe already now make it an interface and think about how to fill it for the reg module realization?

2023-09-21 15:47 UTC, caviddhen commented on modules/18_residues/flexcell_july23/declarations.gms
> + v18_res_ag_removal(j,kcr,attributes)       Removal of crop residues in respective attribute units DM GJ Nr P K WM C (mio. tX)
v18_prod_res will be the interface, and this one already has an equation distributing it felxibly added to the reg module realization.

2023-09-22 08:25 UTC, pfuehrlich-pik requested changes
Looks good, just some typos and one important thing: Please double check that the correct realization name is used everywhere. While you're at it I think it would be a good idea also rename once again to flexcluster_jul23 to be consistent with the 3-letter-month used for all other realizations.

2023-09-22 08:25 UTC, pfuehrlich-pik commented on main.gms
> +$setglobal residues  flexcell_july23
```suggestion
$setglobal residues  flexcluster_july23
```

2023-09-22 08:25 UTC, pfuehrlich-pik commented on modules/18_residues/flexcluster_july23/declarations.gms
> + v18_res_biomass_ag_clust(j,kcr)             Production of aboveground residues in each cluster (mio. tDM)
```suggestion
 v18_res_biomass_ag_clust(j,kcr)            Production of aboveground residues in each cluster (mio. tDM)
```

2023-09-22 08:25 UTC, pfuehrlich-pik commented on modules/18_residues/flexcluster_july23/declarations.gms
> + i18_res_use_burn(t_all,dev18,kcr)         Share of residues burned on field (1)
```suggestion
 i18_res_use_burn(t_all,dev18,kcr)          Share of residues burned on field (1)
```

2023-09-22 08:25 UTC, pfuehrlich-pik commented on modules/18_residues/flexcluster_july23/declarations.gms
> + oq18_cell_field_constraint(t,j,kres,type)       Make sure the amount removed in any cell does not exceet the amoutn available
It probably makes sense, but this is the only parameter without a unit in the description.

2023-09-22 08:25 UTC, pfuehrlich-pik commented on modules/18_residues/flexcluster_july23/declarations.gms
> + oq18_cell_field_constraint(t,j,kres,type)       Make sure the amount removed in any cell does not exceet the amoutn available
```suggestion
 oq18_cell_field_constraint(t,j,kres,type)       Make sure the amount removed in any cell does not exceed the amount available
```

2023-09-22 08:25 UTC, pfuehrlich-pik commented on modules/18_residues/flexcluster_july23/equations.gms
> +*' While the residue biomass is estiamted with a crop-specific nutrient
```suggestion
*' While the residue biomass is estimated with a crop-specific nutrient
```

2023-09-22 08:25 UTC, pfuehrlich-pik commented on modules/18_residues/flexcluster_july23/realization.gms
> +$Ifi "%phase%" == "sets" $include "./modules/18_residues/flexcell_july23/sets.gms"
Please have another look that "flexcell_july23" is renamed everywhere

2023-09-22 08:25 UTC, pfuehrlich-pik commented on modules/18_residues/flexcluster_july23/sets.gms
> +dev18 country develoment indicator
```suggestion
dev18 country development indicator
```
It might make sense to install a plugin into your editor that checks for typos :wink:

2023-09-22 21:10 UTC, pfuehrlich-pik approved these changes

2023-09-23 17:32 UTC, merged