area-based bioenergy policy
magpiemodel/magpie pull request #605
Opened 2023-11-02 13:03 UTC by flohump

## :bird: Description of this PR :bird:

- Briefly explain the purpose of this pull request

## :wrench: Checklist for PR creator :wrench:

- [ ] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [ ] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [ ] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2023-11-02 14:19 UTC, tscheypidi requested changes
looks overall good to me. I just did some suggestions for reducing the footprint of the implementation. 

Please don't forget to adjust the other realizations accordingly and to add a corresponding setting in default.cfg

2023-11-02 14:19 UTC, tscheypidi commented on modules/30_crop/endo_apr21/declarations.gms
> + p30_bioen_pol                      Area-based 2nd gen bioenergy policy (1)
```suggestion
```
not needed

2023-11-02 14:19 UTC, tscheypidi commented on modules/30_crop/endo_apr21/equations.gms
> + q30_land_bioen(j2)$(s30_bioen_pol = 1) ..
```suggestion
 q30_land_bioen(j2)$(sum(ct, m_year(ct)) > s30_bioen_pol_ref_year) ..
```
The constraint should become active in the years after the reference year, right?

2023-11-02 14:19 UTC, tscheypidi commented on modules/30_crop/endo_apr21/equations.gms
> +*' Available area for the cultivation of begr and betr can be limited to the cropland area of the time step given by `s30_bioen_pol_ref_year`.
```suggestion

*' Area-based constraint for 2nd gen. bioenergy, limiting the cultivation of begr and betr to the cropland area of the time step given by `s30_bioen_pol_ref_year`.
```

2023-11-02 14:19 UTC, tscheypidi commented on modules/30_crop/endo_apr21/input.gms
> +s30_bioen_pol                   Area-based 2nd gen bioenergy policy (0 = off 1 = on)  / 1 /
```suggestion
```

2023-11-02 14:19 UTC, tscheypidi commented on modules/30_crop/endo_apr21/input.gms
> +s30_bioen_pol_ref_year          Reference year for bioenergy policy   / 2020 /
```suggestion
s30_bioen_pol_ref_year          Reference year for bioenergy area constraint   / 2200 /
```

2023-11-02 14:19 UTC, tscheypidi commented on modules/30_crop/endo_apr21/postsolve.gms
> +p30_bioen_pol_ref_area(j)$(sum(ct, m_year(ct)) = s30_bioen_pol_ref_year) = pcm_land(j,"crop");
Doesn't that need to be in presolve? What happens if the start year should be 1995?

2023-11-02 14:19 UTC, tscheypidi commented on modules/30_crop/endo_apr21/presolve.gms
> +);
```suggestion
```

not needed

2023-11-03 08:29 UTC, flohump commented on modules/30_crop/endo_apr21/equations.gms
> + q30_land_bioen(j2)$(s30_bioen_pol = 1) ..
Yes, therefore we need to set the reference area in postsolve.

2023-11-03 08:32 UTC, flohump commented on modules/30_crop/endo_apr21/postsolve.gms
> +p30_bioen_pol_ref_area(j)$(sum(ct, m_year(ct)) = s30_bioen_pol_ref_year) = pcm_land(j,"crop");
No, postsolve is the right place for this. In case of 1995, cropland after optimization will be used as reference area for 2000, 2005 etc.

2023-11-07 13:06 UTC, closed without merging