Revision peatland module v2 realisation
magpiemodel/magpie pull request #611
Opened 2023-11-10 20:12 UTC by flohump

## :bird: Description of this PR :bird:

- Improved initialization of managed peatland 
- Removed constraint for rewetted / intact peatland in favour of emission factors for intact peatland. The previous constraint did not work as expected under all cirumstances. Emission factors for intact peatland are considered in the internal GHG emission pricing. The magpie4 library has been adjusted accordingly. 
- added dissagg. of peatland outputs to disagg. script.

## :wrench: Checklist for PR creator :wrench:

- [ ] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [ ] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [ ] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2023-11-16 14:54 UTC, tscheypidi requested changes

2023-11-16 14:54 UTC, tscheypidi commented on modules/58_peatland/v2/equations.gms
> +    + ((vm_land_forestry(j2,"plant")-pcm_land_forestry(j2,"plant"))*p58_scaling_factor(j2,"forestry"));
can these three equations now be merged into one? They are now identical for crop, past and forestry, right?

2023-11-16 15:15 UTC, flohump commented on modules/58_peatland/v2/equations.gms
> +    + ((vm_land_forestry(j2,"plant")-pcm_land_forestry(j2,"plant"))*p58_scaling_factor(j2,"forestry"));
Two different interfaces are used in these equations: `vm_land` and `vm_land_forestry`. Therefore, it is not possible to merge these 3 equations into one using a set.

2023-11-20 08:21 UTC, deleip requested changes

2023-11-20 08:21 UTC, deleip commented on modules/58_peatland/v2/equations.gms
> +    + ((vm_land(j2,"crop")-pcm_land(j2,"crop"))*p58_scaling_factor(j2,"crop"));
The example above still uses the old logic for scaling factors, would be good to update that. 
But thinking about a new example I'm actually wondering whether the new method works in all cases: what if a cell has 100ha, out of which 30ha are cropland, 50ha are peatland, and of those 10ha are peatland used for crops. Then we get `p58_scaling_factor(j2,"crop") = 1/3`. If now in the next timestep cropland would expand to the full area of the cell, we would get `v58_peatland(j2,"crop") = 10 + (100 - 30) * 1/3 = 33.33 ha`. But if the full cell area is cropland, also the full peatland area would need to be used for cropland... Are such cases somehow taken care of?

2023-11-28 10:32 UTC, flohump commented on modules/58_peatland/v2/equations.gms
> +    + ((vm_land(j2,"crop")-pcm_land(j2,"crop"))*p58_scaling_factor(j2,"crop"));
With the new approach such cases are taken care for.

2023-12-04 15:24 UTC, deleip approved these changes
Looks good to me. Just some smaller comments on readability/code simplification left :)

2023-12-05 07:27 UTC, flohump commented on modules/58_peatland/v2/realization.gms
> +*' @limitations Peatland area and GHG emissions are fixed to 2020 levels for the historic period,
yes. changed.

2023-12-05 07:30 UTC, flohump commented on modules/58_peatland/v2/equations.gms
>    vm_peatland_cost(j2) =e= v58_peatland_cost(j2);
I removed `v58_peatland_cost` and took care of adjustments in the magpie4 R library.
In this context, I reintroduced `v58_peatland_cost_annuity` with a new set `cost58`, which replaces the 3 individual constraints and variables. This simplifies the code and avoids further adjustments in the magpie4 R library.

2023-12-05 07:31 UTC, flohump commented on modules/58_peatland/v2/sets.gms
> +  manLand58(land) Managed main land categories
removed

2023-12-05 07:37 UTC, flohump commented
> Looks good to me. Just some smaller comments on readability/code simplification left :)

Thanks for the detailed review!
I added you as co-author of the peatland module. 
After the update of the cost variables, I sucessfully produced new test runs.

2023-12-05 07:37 UTC, flohump commented on core/macros.gms
> +$macro m_peatLandLeft(pclandFull,setFull,vland,pcland) \
renamed to `m58_LandLeft`

2023-12-05 13:44 UTC, merged