New EAT Lancet Diet Implementation
magpiemodel/magpie pull request #625
Opened 2024-01-18 14:34 UTC by FelicitasBeier

## :bird: Description of this PR :bird:

- New EATLancet diet implementation (required as part of the EAT2.0 project)
- The previous EATLancet (EAT 1.0) implementation was not a direct implementation of EAT targets, but based on scenario runs from IMPACT which in turn used the EAT Lancet targets. Now, the EAT targets (transformed to kcal) constrain p15_intake_detail directly in MAgPIE
- Currently, this new implementation can be selected via `cfg$gms$s15_exo_diet <- 3`, but the goal is to replace the old implementation by this one, i.e. delete code of  `cfg$gms$s15_exo_diet <- 1` to have no parallel implementations. Note is included in default.cfg for the switch
- Changes in the old diet implementation / default:
1. alcohol is reduced to zero by default when EATLancet diet is activated. This is in line with the EATLancet definition. If for a project, you would like to divert from this recommendation, you have to set the switch s15_exo_alcohol to 1.
2. brans does not have a target in EATLancet. It stays at its current level by default. If a reduction to 0 is wanted, s15_exo_brans has to be activated (set to 1) now.
- Differences between EAT1.0 and EAT2.0 (beyond technical implementation differences):
1. Starchy fruit didn’t have max. target
2. Roots didn’t have separate target (were parts of staples)
3. Soybean does not have separate target anymore. It’s combined with the legumes target
4. Peanuts does not have separate target anymore. It’s combined with nuts & seeds.
- Special treatment of EAT2.0 recommendation within MAgPIE:
1. We do not use gram targets, but kcal targets because MAgPIE calculates with kcal and treats the food products as homogenous good. We used the conversion from the Willet et al. paper
2. We do not scale up nuts in others following the EAT nut target, but they are scaled together with the fruits and vegetables because “other” is a homogenous good. “Fruits and Vegetables” together with “Bananas & plantains” have to meet EAT Fruit + Veggie target (with bananas & plantains having a maximum for EAT starchy fruit). The “nuts in other” then count towards the nut target and rapeseed and sunflower are scaled accordingly. The respective shares (of nuts in other and of bananas in cassav_sp) are country-specific because especially the bananas in cassav_sp vary by country. This is in line with EAT2.0 idea of regionalized diets and is consistent with iso-level food intake calculations

## :wrench: Checklist for PR creator :wrench:

- [x] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [x] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [x] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [x] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

![Nutrition_Calorie_Intake (1)](https://github.com/magpiemodel/magpie/assets/39262100/fb566ac0-3e00-4c76-a8d6-30fe18be5824)

![Nutrition_Calorie_Intake_Crops_Other_crops_Fruits_Vegetables_Nuts](https://github.com/magpiemodel/magpie/assets/39262100/903627ee-9009-4b08-8dd6-d180c1044909)
![Nutrition_Calorie_Intake_Crops_Oil_crops_Other_oil_crops_incl_rapeseed](https://github.com/magpiemodel/magpie/assets/39262100/fb8055a1-40d6-450c-8a11-ff04fdb17dc4)
![Nutrition_Calorie_Intake_Crops_Oil_crops_Groundnuts](https://github.com/magpiemodel/magpie/assets/39262100/e8c6aa26-7c35-421c-b02a-bac1189c023e)

![Nutrition_Calorie_Intake_Fish](https://github.com/magpiemodel/magpie/assets/39262100/b6135721-dade-4b55-85ef-38d1d68ee58b)

![Nutrition_Calorie_Intake_Livestock_products_Poultry_meat](https://github.com/magpiemodel/magpie/assets/39262100/a4b6a602-0c2a-443a-a66d-c7b73c97f21d)
![Nutrition_Calorie_Intake_Livestock_products_Ruminant_meat](https://github.com/magpiemodel/magpie/assets/39262100/564a40f9-35ed-4121-a0e2-970d51a02709)

![Labor_Employment_Agricultural_employment](https://github.com/magpiemodel/magpie/assets/39262100/4d6273f3-1fc9-41b1-868b-c46c84c2104b)
![Biodiversity_Shannon_crop_area_diversity_index](https://github.com/magpiemodel/magpie/assets/39262100/8480bb82-6e77-4ca2-be9b-fd2115f36a2d)
![Emissions_CH4_Land_Agriculture](https://github.com/magpiemodel/magpie/assets/39262100/02007492-21bd-4bf2-bff7-57b3bfd139f1)
![Emissions_CO2_Land_Land_use_Change](https://github.com/magpiemodel/magpie/assets/39262100/3adb4642-7ca5-41c6-805d-082c98600524)
![Productivity_Landuse_Intensity_Indicator_Tau](https://github.com/magpiemodel/magpie/assets/39262100/ceecc346-38f3-48e5-8bfe-6efcb3e27f9f)
![Resources_Land_Cover_Cropland](https://github.com/magpiemodel/magpie/assets/39262100/3c7eec69-058c-4396-951d-5c9adfc6e785)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [x] content review done (at least 1)
- [x] RSE review done (at least 1)

2024-02-07 13:06 UTC, tscheypidi requested changes
looks good to me overall...just some smaller requests.

2024-02-07 13:06 UTC, tscheypidi commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +display i15_intake_detailed_scen_target;
why is that displayed?

2024-02-07 13:06 UTC, tscheypidi commented on modules/15_food/anthro_iso_jun22/realization.gms
> +*' @authors Benjamin Leon Bodirsky, Isabelle Weindl, Jan Philipp Dietrich, Felicitas Beier
last place is not appropriate here. I am not sure about Bennis and Isabelles contributions here, but you definitely contributed more than I did.

2024-02-07 13:55 UTC, pfuehrlich-pik commented on renv/activate.R
> +  attr(version, "sha") <- "0e3aab27a928eb261819a3fc45a3ee2b4ba902a5"
Apparantly there are two variants of renv 0.16.0, and this PR switches between the two. To get rid of this problem I suggest to switch to the newest version 1.0.3 which should be more stable, and where I hope there are no two variants. To do this it should suffice to put `renvVersion <- "1.0.3"` into the [.Rprofile](https://github.com/magpiemodel/magpie/blob/fee7e6a916eb5861f4f406b1886fd28430b34de0/.Rprofile#L11C1-L11C24), and then restart R.

2024-02-07 14:42 UTC, FelicitasBeier commented on config/default.cfg
> +               additional  = "additional_data_rev4.46.tgz",
That was a mistake. Probably happened through a merge conflict. Changed it back to 4.47 now.

2024-02-07 14:44 UTC, FelicitasBeier commented on modules/15_food/anthro_iso_jun22/realization.gms
> +*' @authors Benjamin Leon Bodirsky, Isabelle Weindl, Jan Philipp Dietrich, Felicitas Beier
Ah, I thought that goes by timeline of contribution.

2024-02-07 14:49 UTC, FelicitasBeier commented on renv/activate.R
> +  attr(version, "sha") <- "0e3aab27a928eb261819a3fc45a3ee2b4ba902a5"
Ah, thanks. Done

2024-02-07 15:46 UTC, FelicitasBeier commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +display i15_intake_detailed_scen_target;
Thanks for noticing. This was for testing only. Removed it now.

2024-02-07 15:46 UTC, FelicitasBeier commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +display i15_intake_detailed_scen_target;
Thanks for noticing. This was for testing only. Removed it now.

2024-02-07 15:47 UTC, FelicitasBeier commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*** ISABELLE: Please double-check whether I can remove the if condition from the nuts target equations
@weindl Could you double-check?

2024-02-09 10:52 UTC, bodirsky requested changes
Mostly minor changes. Please separate fruitvegnuts and roots switch

2024-02-09 10:52 UTC, bodirsky commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*' Split the 'others' category into fruits plus vegetables and nuts
parameter names dont help to understand the differences

2024-02-09 10:52 UTC, bodirsky commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*' Extract fruits and vegetables that are part of others categroy
category

2024-02-09 10:52 UTC, bodirsky commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +
in the revised code snippet you sent me there is a mistake

* Assign starchy fruit and cassava roots back to cassava_sp scenario target
    i15_intake_detailed_scen_target(t,iso,"cassav_sp") =
      i15_intake_detailed_scen_roots(t,iso) / p15_intake_detail_roots(t,iso) * p15_intake_detail_roots(t,iso) -
      i15_intake_detailed_scen_target(t,iso,"potato") +
      i15_intake_detailed_scen_starchyfruit(t,iso);
      
      you divide and multipley by the same parameter. i guess this should just be cassav_sp?

2024-02-09 10:52 UTC, bodirsky commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*' in step 1.) selected total calorie intake is met.
the X in step

2024-02-09 10:52 UTC, bodirsky commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*' in step 1.) selected total calorie intake is met.
i guess the "the" is too much

2024-02-09 10:52 UTC, bodirsky commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*' original level.
does this need to be noted here again?

2024-02-09 12:04 UTC, FelicitasBeier commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*' Bananas and plantains are included in the 'cassav_sp' category.
Done

2024-02-09 12:10 UTC, FelicitasBeier commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*' original level.
No. I removed it now.

2024-02-09 12:17 UTC, FelicitasBeier commented on modules/15_food/anthro_iso_jun22/preloop.gms
> +* Initialisation of the recommendations for healthy food intake:
Thanks! Will do.

2024-02-09 12:17 UTC, FelicitasBeier commented on config/default.cfg
> +cfg$gms$s15_exo_fruitvegnutroots  <- 1   # def = 1, options: 0,1
Alright. Will do.

2024-02-09 12:19 UTC, FelicitasBeier commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*' Split the 'others' category into fruits plus vegetables and nuts
You mean i15_intake_detailed_scen_target(t,iso,"potato") and i15_intake_detailed_scen_starchyfruit(t,iso)? One is the target of potato, the other the one for starchyfruit.
What would you suggest?

2024-02-09 13:10 UTC, tscheypidi approved these changes

2024-02-09 13:54 UTC, FelicitasBeier commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*' Split the 'others' category into fruits plus vegetables and nuts
Ah, or you mean the fruitveg2others_kcal_ratio? 
That is actually the ratio of fruits&veggies in other and the ratio of bananas&plantains in cassav_sp.

Couldn't think of a better name. Maybe fruits2other_kcal_ratio?

2024-02-12 22:45 UTC, weindl requested changes
Looks good in general. For more details, see comments.

2024-02-12 22:45 UTC, weindl commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*      p15_intake_detailed_scen_target(t,iso,"oils") = i15_intake_EATLancet(iso,"oils")
I think this line "p15_intake_detailed_scen_target(t,iso,"oils") = i15_intake_EATLancet(iso,"oils")" should be deleted. 
That was the approach of the old implementation.

2024-02-12 22:45 UTC, weindl commented on modules/15_food/anthro_iso_jun22/input.gms
>  scalar s15_exo_oils Exogenous oils (1) / 1 /;
default for s15_exo_brans is 0

2024-02-15 08:36 UTC, FelicitasBeier commented on CHANGELOG.md
> +- **default.cfg** update input data to rev 4.96
I now removed this line because the update to 4.99 is already included further up in the changelog, including a description of what has changed

2024-02-15 08:55 UTC, FelicitasBeier commented on config/default.cfg
> +# *       (Willett et al., 2019). This EATLancet implementation is deprecated.
Done. Both here and in bibliography file

2024-02-15 13:52 UTC, FelicitasBeier commented on config/default.cfg
> +cfg$gms$s15_exo_brans        <- 0   # def = 0 (as no target defined in EATLancet, they are kept at their historical value, unless switch activated (1), then brans are set to 0), options: 0,1
done

2024-02-19 08:44 UTC, FelicitasBeier commented on config/default.cfg
> +# * Only activated if s15_exo_diet is set to 1
Actually only when 1 or 3. Not active for India-specific diet (exo_diet = 2)

2024-02-19 08:50 UTC, FelicitasBeier commented on config/scenario_fsec.csv
>  gms$s15_exo_fish;;;;;;;;0;0;0;0;0;0;0;1;0;;;;;;;;;;;;;;;;;0;0;;;;;;;;;;;;;;;
Yes, this was intended. We cannot model the negative consequences of fish production in MAgPIE and therefore only included a switch to fruit&veg, monogastrics, ruminants etc. targets, but not fish in the FSEC study.

2024-02-19 09:12 UTC, FelicitasBeier commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*' Split the 'others' category into fruits plus vegetables and nuts
replaced with i15_fruit_ratio now

2024-02-19 09:44 UTC, FelicitasBeier commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*      p15_intake_detailed_scen_target(t,iso,"oils") = i15_intake_EATLancet(iso,"oils")
That was commented out. It's removed now.

2024-02-19 13:15 UTC, FelicitasBeier commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*  and their amount has been added to cassav_sp already.
It is part of p15_intake_detail_fruitveg and p15_intake_detailed_scen_fruitveg already

2024-02-19 13:19 UTC, FelicitasBeier commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +            = p15_intake_detail_nuts(t,iso) * i15_intake_detailed_scen_fruitveg(t,iso) / (p15_intake_detail_fruitveg(t,iso) - i15_intake_detailed_scen_starchyfruit(t,iso))
Good catch! Thank you! Corrected it now.

2024-02-23 16:08 UTC, bodirsky approved these changes
super feli!

2024-02-24 11:10 UTC, FelicitasBeier commented on config/default.cfg
> -# * only activated if s15_exo_diet is set to 1
Thanks. Done.

2024-02-24 11:13 UTC, FelicitasBeier commented
Thank you, @bodirsky and @weindl for this extensive review and discussions!

2024-02-24 11:13 UTC, merged