Updated EAT Lancet 2.0 start script
magpiemodel/magpie pull request #636
Opened 2024-02-29 10:12 UTC by FelicitasBeier

## :bird: Description of this PR :bird:

- updated run script for EAT 2p0

## :wrench: Checklist for PR creator :wrench:

- [x] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [x] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [x] Document changes 
  not necessary. only updated start script

- [x] Perform test runs
  - runs are made for EAT 2p0 submission

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2024-02-29 12:53 UTC, pfuehrlich-pik approved these changes

2024-03-07 09:48 UTC, pvjeetze requested changes
Looks good to me. I would, however, as suggested earlier change the conservation template from `BH_IFL` to `30by30`

2024-03-07 09:48 UTC, pvjeetze commented on config/scenario_fsec.csv
> +gms$c22_protect_scenario;;;;;;;;;;;;;;;;;;;;;;;;;;;;;BH_IFL;;;;;;;;;;;;;;;;;;;;;;
I would suggest switching this to 30by30

2024-03-07 09:48 UTC, pvjeetze commented on config/scenario_fsec.csv
> +gms$c22_protect_scenario;;;;;;;;;;;;;;;;;;;;;;;;;;;;;BH_IFL;;;;;;;;;;;;;;;;;;;;;;
```suggestion
gms$c22_protect_scenario;;;;;;;;;;;;;;;;;;;;;;;;;;;;;30by30;;;;;;;;;;;;;;;;;;;;;;
```

2024-03-07 09:48 UTC, pvjeetze commented on config/scenario_fsec.csv
> +gms$c22_protect_scenario;;;;;;;;;;;;;;;;;;;;;;;;;;;;;BH_IFL;;;;;;;;;;;;;;;;;;;;;;
@bodirsky?

2024-03-07 10:27 UTC, bodirsky approved these changes

2024-03-07 11:09 UTC, FelicitasBeier commented on config/scenario_fsec.csv
> +gms$c22_protect_scenario;;;;;;;;;;;;;;;;;;;;;;;;;;;;;BH_IFL;;;;;;;;;;;;;;;;;;;;;;
alright. I changed it now. Thanks!

2024-03-07 12:25 UTC, pvjeetze approved these changes

2024-03-07 12:26 UTC, pvjeetze commented
Thanks, looks good to me!

2024-03-08 08:06 UTC, FelicitasBeier reviewed
PLEASE DO NOT MERGE, YET.
We want to include new input data.

2024-03-18 09:40 UTC, merged