AgroForestry: treecover on cropland and betr
magpiemodel/magpie pull request #644
Opened 2024-03-11 12:57 UTC by flohump

## :bird: Description of this PR :bird:

This PR adds tree cover on cropland and bioenergy trees as two different AgroForestry systems to MAgPIE 
To intergrate cropland tree cover properly into the existing model, the following changes are applied:

- new module `29_cropland`, accouting for crop area, fallow cropland and tree cover on cropland 
- module `30_crop` renamed to `30_croparea`, which now only accounts for crop area.
- module `29_ageclass` has been renamed to `28_ageclass`
- SNV has been moved from `30_crop` to `29_cropland`
- `30_crop/penalty` and `30_crop/rotation` realizations have been merged into a singe `30_croparea/detail_apr24` realization
- the previous `30_crop/endo_apr21` crop realization has been renamed to `30_croparea/simple_apr24`
- The new module `29_cropland` has two realizations: `detail_apr24` and `simple_apr24` (default)
- 29_cropland/detail_apr24 includes all tree cover (includign age-classes) and fallow land calculations
- 29_cropland/simple_apr24 assumes zero tree cover and fallow land.

todo: include input files for 30_croparea in additional_data.tgz.

todo: emisCO2 in magpie4 reporting

Changelog
### changed
- **29_ageclass** module 29_ageclass has been renamed to 28_ageclass to make space for `29_cropland` just before `30_croparea`
- **30_crop** module `30_crop` renamed to `30_croparea`, which now only accounts for crop area.
- **30_crop** SNV implementation has been moved from `30_crop` to `29_cropland/detail_apr24` 
- **30_crop** the two realizations `penalty_apr22` and `rotation_apr22` have been merged into a single `30_croparea/detail_apr24` realization
- **30_crop** the previous `30_crop/endo_apr21` realization has been moved to `30_croparea/simple_apr24`

### added
- **29_cropland** new module `29_cropland` accounting for crop area, fallow cropland and tree cover on cropland with two realizations: `detail_apr24` and `simple_apr24` (default) .
- **10_land** added interface `pm_land_hist` with historic land use patterns
- **32_forestry** added technical balance term `v32_land_missing_ndc`

### fixed
- **80_optimization** bugfix in nlp_par. Double solve statement was not working

## :wrench: Checklist for PR creator :wrench:

- [x] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [ ] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [x] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [x] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

![Resources_Land_Cover_Cropland-100](https://github.com/magpiemodel/magpie/assets/16921122/bf9dd1c7-ad61-4001-957e-8c9a77ed7e9b)
![Resources_Land_Cover_Cropland_Tree_Cover](https://github.com/magpiemodel/magpie/assets/16921122/0fef39ae-e2fa-4951-9217-241128e0e5a7)
![Productivity_Landuse_Intensity_Indicator_Tau-87](https://github.com/magpiemodel/magpie/assets/16921122/e51bacb8-3272-479e-bea3-bd27a13ff32a)
![Emissions_CO2_Land_Land_use_Change-86](https://github.com/magpiemodel/magpie/assets/16921122/b4b887b4-97fa-4bf9-a0c4-e0e93caaee10)
![Prices_Index2020_Agriculture_Food_products-2](https://github.com/magpiemodel/magpie/assets/16921122/251dfa57-d94a-4ccf-9279-520a4ccc426a)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : 27 mins
  - This PR's default :  27 mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2024-03-12 07:16 UTC, bodirsky reviewed
A few documentation changes.
Seems good to me, but should be done analogous for all 3 realizations.
Please let me know if you need help with understanding the penalty implementation!

2024-03-12 07:16 UTC, bodirsky commented on modules/30_crop/endo_apr21/equations.gms
> +   sum((kcr,w), vm_area(j2,kcr,w)) + vm_fallow(j2) + sum(ac, v30_treecover(j2,ac)) =e= vm_land(j2,"crop");
now you introduced fallow into the endo_apr realization. Was that on purpose?
As long as it is fixed to 0, probably doesnt matter...

2024-03-12 07:16 UTC, bodirsky commented on modules/30_crop/endo_apr21/equations.gms
> +   sum((kcr,w), vm_area(j2,kcr,w)) + vm_fallow(j2) + sum(ac, v30_treecover(j2,ac)) =e= vm_land(j2,"crop");
now you introduced fallow into the endo_apr realization. Was that on purpose?
As long as it is fixed to 0, probably doesnt matter...

2024-03-12 07:16 UTC, bodirsky commented on modules/30_crop/endo_apr21/preloop.gms
> +if(s30_treecover_bii_coeff = 0,
ah, now i see, this is just a switch!

2024-03-12 07:16 UTC, bodirsky commented on modules/30_crop/endo_apr21/equations.gms
> + q30_bv_treecover(j2,potnatveg) .. vm_bv(j2,"crop_tree",potnatveg)
what is the set potnatveg doing?

2024-03-12 07:16 UTC, bodirsky commented on modules/30_crop/endo_apr21/presolve.gms
> +
i guess this is copy paste from a previous implementation, right? only reviewing it shortly

2024-03-12 07:16 UTC, bodirsky commented on modules/30_crop/endo_apr21/declarations.gms
> + p30_treecover_shr(t,j)                 Share of treecover on cropland (1)
rename to treecover_min_shr
its not the actual share, but the min target

2024-03-12 10:59 UTC, pvjeetze commented on modules/30_crop/endo_apr21/presolve.gms
> +pc30_treecover(j,ac) = p30_treecover(t,j,ac);
Just double checking. Here we go from 3 dimensions (t,j,ac) to 2 dimensions (j,ac). Is this right?

2024-03-15 14:59 UTC, tscheypidi requested changes
Looks overall good to me. Please have a look at the specific comments to see my requests for modifications

2024-03-15 14:59 UTC, tscheypidi commented on modules/30_crop/endo_apr21/equations.gms
> +   sum((kcr,w), vm_area(j2,kcr,w)) + vm_fallow(j2) + vm_treecover_area(j2) =e= vm_land(j2,"crop");
why is now fallow coming in here? this will change the default behavior of the realization, right? If so, it should be also labelled differently I think

2024-03-15 14:59 UTC, tscheypidi commented on modules/61_agroforestry/endo/equations.gms
> +*' Cost for bioenergy trees are accounted for in the [30_crop] module.
Please have a look at the resulting documenation. I would at least use full sentences to describe the methodology. The documentation page should read as a real documentation of the realization

2024-05-15 15:06 UTC, k4rst3ns requested changes
Thanks, Florian for this major effort.

I added some comments and I also spotted some things that have to be fixed (see comments on the som module). I think in general it looks very good. I guess I normally would comment the code more excessively and added some comments there I would find it really helpful to have more guidance through the code ^^'

2024-05-21 13:05 UTC, tscheypidi approved these changes
added some comments, but looks good to me overall

2024-05-22 14:57 UTC, pvjeetze approved these changes
Just some minor questions, looks otherwise good to me!

2024-05-29 16:54 UTC, flohump reviewed
Thanks for your helpful and constructive feedback. I revised the code accordingly.

2024-05-29 16:54 UTC, flohump commented on modules/29_cropland/detail_apr24/presolve.gms
> +m_boundfix(vm_fallow,(j),l,1e-6);
done

2024-05-29 16:54 UTC, flohump commented on modules/29_cropland/input/files
> +CroplandTreecover_0.5.mz
done

2024-05-29 16:54 UTC, flohump commented on modules/29_cropland/module.gms
> +*' Area and carbon stocks for fallow land and tree cover are defined in this module.
Thanks. Done.

2024-05-29 16:54 UTC, flohump commented on modules/29_cropland/simple_apr24/realization.gms
> +*' Costs are fixed to zero.
thanks for spotting. done.

2024-05-29 16:54 UTC, flohump commented on scripts/start/test_runs.R
> +### NatureSparing
yes. as discussed internally.

2024-05-29 16:54 UTC, flohump commented on CHANGELOG.md
> +- **80_optimization** bugfix in nlp_par. Double solve statement was not working
Yes, moved to another PR.

2024-05-29 16:54 UTC, flohump commented on CHANGELOG.md
> +- **30_crop** SNV implementation has been moved from `30_crop` to `29_cropland`
Done.

2024-05-29 16:54 UTC, flohump commented on modules/59_som/cellpool_jan23/equations.gms
>  q59_som_target_noncropland(j2,noncropland59) ..
thanks for spotting. fixed.

2024-05-29 16:54 UTC, flohump commented on modules/32_forestry/dynamic_feb21/presolve.gms
> +   p32_aff_pot(t,j) = sum((kcr,w),vm_area.l(j,kcr,w) - vm_area.lo(j,kcr,w)) + (vm_land.l(j,"past") - vm_land.lo(j,"past")) - pm_land_conservation(t,j,"other","restore");
thanks for spotting. changed.

2024-05-29 16:54 UTC, flohump commented on modules/30_croparea/detail_apr24/equations.gms
> +  q30_rotation_max(j2,rotamax_red30)$(i30_implementation = 1) ..
done.

2024-05-29 16:54 UTC, flohump commented on modules/30_croparea/detail_apr24/preloop.gms
> +
done

2024-05-29 16:54 UTC, flohump commented on modules/30_croparea/detail_apr24/sets.gms
>  ;
This has been merged carefully.

2024-05-29 16:54 UTC, flohump commented on modules/30_croparea/detail_apr24/presolve.gms
> +  i30_implementation = 1;
There was no default before because we had two different realizations. But now the default is rule-based, i.e. i30_implementation = 1. This is needed for identical results in the historical period.

2024-05-29 16:54 UTC, flohump commented on modules/50_nr_soil_budget/macceff_aug22/equations.gms
> +*                 Commented out for consistency with q50_nr_surplus_nonagland
Done

2024-05-29 16:54 UTC, flohump commented on config/default.cfg
> +cfg$gms$s29_snv_scenario_target <- 2029       # def = 2029
thanks for spotting. was a mistake. reverted back

2024-06-10 09:54 UTC, k4rst3ns approved these changes
Looks good.
More comments not always full sentences :sweat_smile: but I guess this might be a matter of preference.
The only thing I again thought of was the alignment of fallow in bii and som regards. The difference might be not big, but it might be still good to align these? But this could be also done when I do the changes to the dynamic realization to align them to the new carbon stocks in a couple of weeks.

2024-06-10 09:54 UTC, k4rst3ns commented on modules/29_cropland/detail_apr24/equations.gms
> +*' Fallow land biodiversity value is based on perennial crops.
Ok, but still than we shoudl adress this similarly in the SOM realization:
https://github.com/flohump/magpie/blob/1774fcfba8467d6695b50af1c395efc77672beb1/modules/59_som/cellpool_jan23/preloop.gms#L71

Here we use maize as reference. Maybe we can switch it to "oilpalm" (which is the only perenial we have in som module.

if we change it, for both dynamic realizations it has to be changed ^^'

2024-06-18 09:23 UTC, merged