bugfix solve statement
magpiemodel/magpie pull request #646
Opened 2024-03-22 12:42 UTC by flohump

## :bird: Description of this PR :bird:

- Briefly explain the purpose of this pull request

## :wrench: Checklist for PR creator :wrench:

- [ ] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [ ] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [ ] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2024-03-22 14:42 UTC, FelicitasBeier approved these changes
Thanks for fixing these!

2024-03-24 12:26 UTC, bodirsky requested changes
please change landSparing setting

2024-03-24 12:26 UTC, bodirsky commented on scripts/calibration/landconversion_cost.R
> +  y <- readGDX(gdx_file,"t")
how do you make sure that t is not a longer vector than f10_land? f10_land only has 1995:2015 included. is this because the runs for the land conversion calibration also only have these timesteps?

2024-03-24 12:26 UTC, bodirsky commented on scripts/calibration/landconversion_cost.R
>    out2[, seq(2050, 2150, by = 5), ] <- out2050
not clear whats happening here. if the calibration factor is below 1 (implying that magpie is expanding less than the real data?), then its set to 1 (so magpie is becoming more likely to expand in in the future after the calibration? why?). So something is fading out, but only in one direction

2024-03-24 12:26 UTC, bodirsky commented on scripts/calibration/landconversion_cost.R
> +    # set value for CAZ to cost_max for better convergence
same for runs where canada and australia are not one region (FSEC)?

2024-03-24 12:26 UTC, bodirsky commented on scripts/calibration/landconversion_cost.R
> +    # set value for CAZ to cost_max for better convergence
![image](https://github.com/magpiemodel/magpie/assets/14294086/379670b0-2b6e-44c3-95d4-51ea018cd460)

2024-03-24 12:26 UTC, bodirsky commented on scripts/calibration/landconversion_cost.R
> +    # set value for CAZ to cost_max for better convergence
quite large difference in validation data between our data and FAO, btw

2024-03-24 18:06 UTC, flohump commented on modules/80_optimization/lp_nlp_apr17/solve.gms
> +  solve magpie USING nlp MINIMIZING vm_cost_glo;
I added a single comment at first appearance in each realization.

2024-03-24 18:08 UTC, flohump commented on config/scenario_fsec.csv
> +input['calibration'];calibration_FSEC_23Mar24.tgz;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Done. Increased version to v39d_FSEC

2024-03-24 18:09 UTC, flohump commented on scripts/calibration/landconversion_cost.R
>    shrLost <- (setYears(hist[getRegions(magpie), 2015, ], NULL) - setYears(hist[getRegions(magpie), 1995, ], NULL)) / setYears(hist[getRegions(magpie), 1995, ], NULL)
Yes, this is on purpose. Here, the difference of cropland between 2015 and 1995 is calculated. This information is used  for the reward calcuation.

2024-03-24 18:10 UTC, flohump commented on scripts/calibration/landconversion_cost.R
> +  y <- readGDX(gdx_file,"t")
Yes, the calibration runs use the time step set `calib`, which is defined from 1995 to 2015 in 5 year time steps.
`$If "%c_timesteps%"== "calib" /y1995,y2000,y2005,y2010,y2015/;`

2024-03-24 18:12 UTC, flohump commented on scripts/calibration/landconversion_cost.R
>    out2[, seq(2050, 2150, by = 5), ] <- out2050
Here, the time series is constructed:
The lowpass filter is applied on 1995-2015.
Betwen 2015 and 2050, all calibration factors below 1 are raised to 1 and all calibration factors above 1 are kept constant. After 2050 all factors are kept constant.

2024-03-24 18:16 UTC, flohump commented on scripts/calibration/landconversion_cost.R
> +    # set value for CAZ to cost_max for better convergence
> same for runs where canada and australia are not one region (FSEC)?

No, CAZ is a special case. We have obseved jumping behaviour of cropland in CAZ in several PRs, where minor things have been changed. Setting cost_max for CAZ is brute-force to mute this effect. It indicates that it would be good to split the region. It does not happen with the FSEC regions.

2024-03-25 06:41 UTC, bodirsky approved these changes

2024-03-25 10:37 UTC, tscheypidi approved these changes

2024-04-03 09:26 UTC, bodirsky requested changes
Jan says double solve statement makes no sense for nlp_par solve in HR runs

2024-04-07 08:30 UTC, flohump commented on config/default.cfg
> +cfg$gms$s14_minimum_wood_yield <- 0   #def = 0
@bodirsky Why set to zero? Why not use FSEC setting as new default?

2024-04-08 09:48 UTC, bodirsky approved these changes

2024-04-08 10:01 UTC, tscheypidi approved these changes

2024-04-09 04:47 UTC, merged