Update PB scripts and bugfix in new EATLancet diet
magpiemodel/magpie pull request #656
Opened 2024-04-09 16:08 UTC by FelicitasBeier

## :bird: Description of this PR :bird:

- condition in new diet implementation set to small number rather than 0 due to rounding issues
- added EL2_Diet;EL2_default;EL2_lessSus to scenario_config for coupled REMIND-MAgPIE runs of EAT2p0 project
- updates in EAT2p0 AgMIP comparison start script
- added start script for EAT2p0 deep dive

## :wrench: Checklist for PR creator :wrench:

- [x] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [x] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [x] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [x] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2024-04-09 18:30 UTC, tscheypidi approved these changes
looks good to me, but I am not able to spot the difference in scenario_config.csv. What is the difference here?

2024-04-09 19:27 UTC, flohump requested changes

2024-04-09 19:27 UTC, flohump commented on config/scenario_config.csv
> +;cc;nocc;nocc_hist;SSP1;SSP2;SSP2EU;SSP3;SSP4;SSP5;SDP;SDP-EI;SDP-RC;SDP-MC;BASE;NPI;NDC;coupling;emulator;input;Tland;eat_lancet_diet;EL2_Diet;EL2_default;EL2_lessSus;LAMA_Inequal;LAMA_Inequal-SustD
New columns: EL2_default;EL2_lessSus
New rows: magicc_emis_scen

2024-04-09 19:27 UTC, flohump commented on config/scenario_config.csv
> +magicc_emis_scen;;;;;;;;;;;;;;;;;;;;;;;SSP2EU-DSPkB500-DS_betax;SSP2EU-DSPkB500-DS_betax;;;;;;;;;;;;;;;;;;;;;;;;
I think for `magicc_emis_scen` a mif/csv file is needed.
Please revise

2024-04-10 07:33 UTC, FelicitasBeier commented on config/scenario_config.csv
> +;cc;nocc;nocc_hist;SSP1;SSP2;SSP2EU;SSP3;SSP4;SSP5;SDP;SDP-EI;SDP-RC;SDP-MC;BASE;NPI;NDC;coupling;emulator;input;Tland;eat_lancet_diet;EL2_Diet;EL2_default;EL2_lessSus;LAMA_Inequal;LAMA_Inequal-SustD
Exactly

2024-04-10 07:34 UTC, FelicitasBeier commented on config/scenario_config.csv
> +magicc_emis_scen;;;;;;;;;;;;;;;;;;;;;;;SSP2EU-DSPkB500-DS_betax;SSP2EU-DSPkB500-DS_betax;;;;;;;;;;;;;;;;;;;;;;;;
Thanks for spotting this. It's fixed now.

2024-04-11 12:44 UTC, merged