Added options for baseline protection
magpiemodel/magpie pull request #662
Opened 2024-04-12 15:48 UTC by pvjeetze

## :bird: Description of this PR :bird:

- This PR adds options for choosing the baseline protection. This means that not only the full WDPA protection can be selected but also subsets of protected area categories (IUCN categories I, II & II and IUCN catergories IV, V & VI). In addition, no baseline protection at all can be chosen, which might be useful for certain test cases. 

## :wrench: Checklist for PR creator :wrench:

- [ ] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [ ] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [ ] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2024-04-15 10:37 UTC, pascal-sauer approved these changes

2024-04-23 09:48 UTC, pvjeetze commented
Dear @all here's a brief reminder to please review this PR :)

2024-04-23 20:52 UTC, flohump requested changes
Looks good. Thanks for adding the additional protection layers. 
Please also update scenario_fsec.csv accordingly, i.e. input files and maybe protection layers.

2024-04-24 07:31 UTC, pascal-sauer reviewed
Some clarifying questions, looks fine otherwise :)

2024-04-24 07:31 UTC, pascal-sauer commented on scripts/output/extra/disaggregation.R
> +  if (!all(c(cfg$gms$c22_base_protect, cfg$gms$c22_base_protect_noselect) %in% "none")) {
```suggestion
  if (cfg$gms$c22_base_protect != "none" || cfg$gms$c22_base_protect_noselect != "none") {
```

2024-04-24 07:31 UTC, pascal-sauer commented on scripts/output/extra/disaggregation.R
> +  if (!all(c(cfg$gms$c22_base_protect, cfg$gms$c22_base_protect_noselect) %in% "none")) {
On second thought, this if statement does not actually do anything, does it? The same variables are checked individually afterwards.

2024-04-24 07:31 UTC, pascal-sauer commented on scripts/output/extra/disaggregation.R
> +    } else if (base_protect_select == "none") {
This `if` is redundant, isn't it?
```suggestion
    } else {
```

2024-04-24 07:31 UTC, pascal-sauer commented on scripts/output/extra/disaggregation.R
> +    } else if (base_protect_select == "none") {
This `else` would not be reached if the check in line 107 is FALSE, so that check actually can change things. Is that intended?

2024-04-24 07:31 UTC, pascal-sauer commented on scripts/output/extra/disaggregation.R
> +)
Did you use an auto-formatter? The way it was formatted before is compliant with the linter rules we have in the R packages, the new formatting is not.

2024-04-24 11:15 UTC, weindl approved these changes
Looks good.

2024-04-24 11:15 UTC, weindl commented on modules/22_land_conservation/area_based_apr22/declarations.gms
> + p22_add_consv(t,j,consv22_all,land)                Addtional land conservation in conservation priority areas (mio. ha)
small typo "Addtional"

2024-04-25 14:03 UTC, pvjeetze commented on scripts/output/extra/disaggregation.R
> +)
lucode2::autoFormat() does not work with scripts. I used a different auto formatter.

2024-04-25 14:12 UTC, pvjeetze commented
> Looks good. Thanks for adding the additional protection layers. Please also update scenario_fsec.csv accordingly, i.e. input files and maybe protection layers.

@flohump I added the FSEC files. No changes are needed wrt to the used switches.

2024-05-06 07:48 UTC, pascal-sauer approved these changes

2024-05-14 16:42 UTC, pvjeetze commented
@flohump I've addressed the comments, please see whether this PR can be approved and then merged.

2024-05-17 09:13 UTC, flohump approved these changes
Looks good.

2024-05-17 09:36 UTC, merged