grassland_apr22 preloop calibration
magpiemodel/magpie pull request #663
Opened 2024-04-14 09:41 UTC by mppalves

## :bird: Description of this PR :bird:

In this pull request, I've streamlined the code by removing redundant sets and added a calibration step for managed pasture areas to the preloop file after eliminating a similar step from calcPastureSuit.R's preprocessing. I've introduced a technical solution to prevent unrealistic grassland exchanges in the initial timestep by applying a conversion cost between rangelands and managed pastures only at the start. Additionally, I enhanced the module's description.

## :wrench: Checklist for PR creator :wrench:

- [ ] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [ ] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [ ] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2024-04-15 11:49 UTC, tscheypidi requested changes

2024-04-15 11:49 UTC, tscheypidi commented on modules/31_past/grasslands_apr22/declarations.gms
> +pc31_grasslands_conversion_cost(t,j)                         Adjusted expansion costs to avoid unrealistic exchange between pastr and range in the first time step (USD05MER per ha)
the prefix "c" stands for current which means that it only contains the value of the current time step, but this parameter has time as a dimension. 
Looking further down in the code I saw that you use this only to set a value in 1995 but have 0s for all other years. That does not look sensible to me. Lets have a discussion about what it does and why

2024-04-15 11:49 UTC, tscheypidi commented on modules/31_past/grasslands_apr22/input.gms
> +  s31_cost_expansion   Grasslands expansion costs (USD05MER per hectare)          / 1000 /
why does this scalar not show up in the default.cfg?

2024-04-15 11:49 UTC, tscheypidi commented on modules/31_past/grasslands_apr22/preloop.gms
> +pc31_grasslands_conversion_cost(t,j) = 0;
why are there costs in 1995 but not in any other year?

2024-04-15 11:49 UTC, tscheypidi commented on modules/31_past/grasslands_apr22/preloop.gms
> +i31_manpast_suit(t_past,j) = f31_LUH2v2(t_past,j,"pastr");
I do not understand this part

2024-04-27 11:14 UTC, mppalves commented on modules/31_past/grasslands_apr22/declarations.gms
> +pc31_grasslands_conversion_cost(t,j)                         Adjusted expansion costs to avoid unrealistic exchange between pastr and range in the first time step (USD05MER per ha)
Hi Jan. This was a way I found to have a parameter that I could add a cost only to the first time step. 
I could not think about another solution to apply this idea to the following equation.
Do you have any suggestion?
q31_expansion_cost(j2,grassland) ..
  v31_cost_grass_expansion(j2, grassland) =g= 
    (v31_grass_area(j2, grassland) - pc31_grass(j2,grassland)) * sum(ct, pc31_grasslands_conversion_cost(ct,j2));

2024-04-27 11:15 UTC, mppalves commented on modules/31_past/grasslands_apr22/input.gms
> +  s31_cost_expansion   Grasslands expansion costs (USD05MER per hectare)          / 1000 /
If we agree on adding a cost for land expansion I will add it the config in the next commit.

2024-04-27 13:16 UTC, mppalves commented on modules/31_past/grasslands_apr22/preloop.gms
> +pc31_grasslands_conversion_cost(t,j) = 0;
This is the way I found to add cost just on the first time step.

As we have discussed, cost information on the conversion between managed pastures and rangelands on a global scale is not available. I also believe that based on our current definition of managed pastures and rangelands, they should be very small and heterogeneous across the globe. Therefore, I would prefer to have zero cost for land conversion costs and let the model decide the type of pastures to use based on the productivity needed, constrained by the "max managed pasture." The expansion costs for total pasture are already defined for the expansion of grasslands in general in the land module.

The need for this variable is only to assign a cost for the first time step, where for some inexplicable reason, even when managed pasture has a clear advantage in terms of productivity and no extra costs associated with it, CONOPT decides to revert the areas of managed pastures and rangelands, especially in Latin America and Africa, but to a lesser extent on other continents

2024-04-27 13:40 UTC, mppalves commented on modules/31_past/grasslands_apr22/preloop.gms
> +i31_manpast_suit(t_past,j) = f31_LUH2v2(t_past,j,"pastr");
i31_manpast_suit(t_all,j)$(i31_manpast_suit(t_all,j) = 0) = f31_LUH2v2("y1995",j,"pastr");

This replaces areas with 0 in the predicted i31_manpast_suit (managed pasture max) with the values from 1995. This is necessary because if a cluster has 0 managed pasture in the estimated (managed pasture max), it will always be 0. This 0 can appear as a result of applying the LUH method on a larger cell size, but this might not be the case from our historical reference dataset. To allow these areas with 0 to support pasture expansion, I allow them to have at least the same value they had in 1995, the beginning of our simulation period.

p31_pastr_suit_sf(j) = (f31_LUH2v2("y1995",j,"pastr") / i31_manpast_suit("y1995",j))$(i31_manpast_suit("y1995",j) <> 0);
Calculate a calibration factor to harmonize the i31_manpast_suit (managed pasture max) estimated to match LUH data in the year 1995.

i31_manpast_suit(t_all,j) = i31_manpast_suit(t_all,j) * p31_pastr_suit_sf(j); 
Apply the calibration factor over the whole dataset.

i31_manpast_suit(t_past,j) = f31_LUH2v2(t_past,j,"pastr");
This last line ensures that the areas where we already have a pasture suitability calculated by LUH (t_past) use that instead of our estimates.

2024-11-21 13:31 UTC, closed without merging