New fader implementation in modules 15_food and 70_livestock
magpiemodel/magpie pull request #674
Opened 2024-05-13 10:32 UTC by pvjeetze

## :bird: Description of this PR :bird:

- New fader implementation the 15_food and 70_livestock modules

## :wrench: Checklist for PR creator :wrench:

- [ ] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [ ] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [ ] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2024-05-13 13:58 UTC, weindl requested changes
Looks good! Only very minor things to be fixed.

2024-05-13 13:58 UTC, weindl commented on modules/15_food/anthro_iso_jun22/input.gms
> +s15_kcal_pc_livestock_intake_target Target for livestock intake (kcal per cap per day) / 430 /
please correct "intake" --> "food calorie supply"

2024-05-13 13:58 UTC, weindl commented on modules/15_food/anthro_iso_jun22/input.gms
> +s15_exo_food_scenario_start         Food substitution start year        / 2025 /
instead of "s15_exo_food_scenario_start" --> "s15_exo_foodscen_start" (as in the default.cfg);
the same for target

2024-05-13 13:58 UTC, weindl commented on modules/15_food/anthropometrics_jan18/input.gms
> +s15_exo_foodscen_convergence               Convergence to exogenous food scenario (1) / 1 /
see comment for other realization

2024-05-13 13:58 UTC, weindl commented on modules/15_food/anthropometrics_jan18/input.gms
> +s15_subst_functional_form                  Switch for functional form of substitution fader (1) / 1 /
"s15_subst_functional_form": see comment for other realization

2024-05-13 15:44 UTC, flohump commented on config/default.cfg
>  # * kfo_rd is used in the food substitution scenarios c15_rumdairy_scp_scen and c15_rumdairyscen (see above)
please adjust. c15_rumdairy_scp_scen does no longer exist.

2024-05-15 08:29 UTC, weindl approved these changes
All comments are solved, except some instances where the correction ""intake" --> "food calorie supply" still has to be done.

2024-05-15 08:29 UTC, weindl commented on modules/15_food/anthro_iso_jun22/input.gms
> +s15_livescen_target                 Switch for livestock intake target (1) / 0 /
please correct "intake" --> "food calorie supply"

2024-05-15 08:29 UTC, weindl commented on modules/15_food/anthropometrics_jan18/input.gms
> +s15_kcal_pc_livestock_supply_target        Target for livestock intake (kcal per cap per day) / 430 /
please correct "intake" --> "food calorie supply"

2024-05-15 08:29 UTC, weindl commented on modules/15_food/anthropometrics_jan18/input.gms
> +s15_livescen_target                        Switch for livestock intake target (1) / 0 /
please correct "intake" --> "food calorie supply"

2024-05-15 08:52 UTC, tscheypidi approved these changes

2024-05-17 08:34 UTC, pvjeetze commented on modules/15_food/anthro_iso_jun22/input.gms
> +s15_livescen_target                 Switch for livestock intake target (1) / 0 /
thanks for spotting this, addressed it :)

2024-05-17 08:36 UTC, flohump approved these changes
Looks good. Thanks for addressing the comments.

2024-05-17 09:29 UTC, merged