New forest recovery based on potential forest areaF p forest
magpiemodel/magpie pull request #676
Opened 2024-05-17 12:42 UTC by pvjeetze

## :bird: Description of this PR :bird:

- Briefly explain the purpose of this pull request

## :wrench: Checklist for PR creator :wrench:

- [ ] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [ ] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [ ] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2024-05-22 21:21 UTC, tscheypidi approved these changes
changes look good to me and a quick check in shinyresults suggested to me that the new implementation might be even slightly faster. Nice work!

2024-05-23 06:23 UTC, flohump requested changes
Looks very good overall. Thanks for these improvements. 
I left some minor comments, mostly for clarification.
Do your test runs including the forestry sector?
It would be important to check if the new constraint for forest/forestry area expansion has major implications on plantation establishment.

2024-05-23 06:23 UTC, flohump commented on modules/80_optimization/nlp_apr17/solve.gms
> +      magpie.optfile = 0;
This file seems content-wise unchanged. Only formatting has changed. Consider reverting. 
For future work it would be good to find out why this happens and if it can be avoided. 
It might be an inconsistency between editors used by different users
maybe @tscheypidi can help to sort this out for future work

2024-05-23 06:23 UTC, flohump commented on modules/35_natveg/pot_forest_may24/equations.gms
> +q35_max_forest_establishment(j2)..
This is the core constraint of the new imlementation, which also includes "forestry", i.e. plant, aff and npi.
Consider adding this detail in the above comment to make it clear that not only land in 35_natveg but also land in 32_forestry is affected by this constraint.

2024-05-23 08:52 UTC, flohump commented on modules/35_natveg/pot_forest_may24/declarations.gms
>   p35_recovered_forest(t,j,ac)                     Recovered forest (mio. ha)
Please remove if no longer needed.

2024-05-23 10:11 UTC, pvjeetze commented on modules/35_natveg/pot_forest_may24/equations.gms
> +q35_max_forest_establishment(j2)..
done

2024-05-23 10:11 UTC, pvjeetze commented on modules/80_optimization/nlp_apr17/solve.gms
> +      magpie.optfile = 0;
My editor seems to remove trailing white spaces by default.

2024-05-23 10:12 UTC, pvjeetze commented on modules/35_natveg/pot_forest_may24/equations.gms
thanks for spotting this. Changes the equation accordingly!

2024-05-24 21:17 UTC, flohump approved these changes
GAMS code looks good. 
magpie4 R library still needs to be updated.

2024-05-27 08:34 UTC, pvjeetze commented on modules/35_natveg/pot_forest_may24/declarations.gms
>   p35_recovered_forest(t,j,ac)                     Recovered forest (mio. ha)
tom remove any ambiguity in the reporting ,`p35_recovered_forest ` is now renamed to `p35_forest_recovery_area`.

2024-05-28 07:27 UTC, merged