revision of SCP implementation for milk
magpiemodel/magpie pull request #698
Opened 2024-07-12 08:04 UTC by flohump

## :bird: Description of this PR :bird:

- **15_food** revision of SCP implementation for milk. Added demand for plant oil and sugar as ingredients for milk production using single cell protein.

## :wrench: Checklist for PR creator :wrench:

- [ ] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [ ] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [ ] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2024-07-12 08:18 UTC, slovat commented on modules/15_food/anthro_iso_jun22/declarations.gms
> + s15_scp_protein_to_kcal conversion factor (kcal per gram of protein) / 4.27 /
s15_scp_fat_to_kcal , s15_scp_sugar_to_kcal, s15_scp_protein_to_kcal  these are the specific conversion factors for milk. It would be worth clarifying this in the scalar name. If demand for sugar and oil is also implemented for meat, then this too would have a specific caloric conversion factors that are different from milk.

2024-07-12 08:20 UTC, tscheypidi approved these changes
Just one comment concerning the used units where a different unit and/or a better unit description could be helpful

2024-07-12 08:20 UTC, tscheypidi commented on modules/15_food/anthro_iso_jun22/declarations.gms
> + s15_scp_fat_per_milk fat needed as ingredient for scp milk (mass per 100g milk) / 3.3 /
I don't understand the unit. Is it g/100g ?! Why not just a mass ratio (1:1)?

2024-07-12 08:28 UTC, slovat approved these changes
Just one small comment regarding the naming of s15_scp_fat_to_kcal , s15_scp_sugar_to_kcal and s15_scp_protein_to_kcal, these are specific to milk, it would be worth clarifying this in their names

2024-07-15 11:37 UTC, weindl requested changes

2024-07-15 11:37 UTC, weindl commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*'
I think '1/s15_scp_protein_to_kcal_milk' has to be replaced by 'i15_protein_to_kcal_ratio(t,"scp")' (the same for line 138 below).
The reference unit for replacement of milk with scp-milk is protein. Based on the estimation of how much scp-protein is needed to replace cow milk, we can calculate here, how much additional sugar and oil is required to create an "scp milk" with similar properties like cow milk. 

Furthermore, I don't understand why the conversion factors for kcal per gram of fat and sugar should be specific for milk.

2024-07-15 11:49 UTC, flohump commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*'
Thanks for your review!
If I understand correctly, we could do the following: 
Instead of 
`p15_kcal_pc_calibrated_scp(t,i,kfo_rd) = p15_kcal_pc_calibrated(t,i,kfo_rd) * (1-i15_rumdairy_scp_fadeout(t,i)) * i15_protein_to_kcal_ratio(t,kfo_rd) / `i15_protein_to_kcal_ratio(t,"scp");`
we could do
`p15_protein_pc_calibrated_scp(t,i,kfo_rd) = p15_kcal_pc_calibrated(t,i,kfo_rd) * (1-i15_rumdairy_scp_fadeout(t,i)) * i15_protein_to_kcal_ratio(t,kfo_rd);`
Thus keeping the unit in protein. 
`p15_kcal_pc_calibrated(t,i,"scp") = p15_kcal_pc_calibrated(t,i,"scp") + sum(kfo_rd, p15_protein_pc_calibrated_scp(t,i,kfo_rd))/i15_protein_to_kcal_ratio(t,"scp");`

This would simplify the addition of oil to:
`p15_kcal_pc_calibrated(t,i,"oils") = p15_kcal_pc_calibrated(t,i,"oils") 
   + sum(kfo_rd$sameas(kfo_rd,"livst_milk"), p15_protein_pc_calibrated_scp(t,i,kfo_rd)) / s15_scp_protein_per_milk * s15_scp_fat_per_milk;`
For sugar: 
`p15_kcal_pc_calibrated(t,i,"sugar") = p15_kcal_pc_calibrated(t,i,"sugar") 
   + sum(kfo_rd$sameas(kfo_rd,"livst_milk"), p15_protein_pc_calibrated_scp(t,i,kfo_rd)) / s15_scp_protein_per_milk * s15_scp_sugar_per_milk;`

2024-07-15 11:53 UTC, flohump commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*'
@slovat Do you follow here?

2024-07-15 13:03 UTC, slovat commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*'
Not sure I completely understand. If I get it right, you are saying rather than going through kcal, work with mass of protein. Based on the mass of SCP milk protein produced, calculate the amount of fat and sugar demand then based on their mass ratio with protein in milk? I.e. if I produce 20 Mt milk protein and the mass ratio of protein to fat is 1:1, I would also need 20 Mt fat?

2024-07-15 13:07 UTC, slovat commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*'
@weindl I'm not sure what's best to use for the conversion factors for kcal per gram of fat and sugar and what level of detail is usually used in MAgPIE. We could use a generic factor of 4 kcal/g protein or sugar and 9 kcal/g fat. But if I'm not mistaken, caloric densities reflect energy available for humans and this includes something about digestability. Because different food products have different digestabilities, a gram of sugar in say milk is different than in wheat and so there is different amounts available depending on the food product. This means there are specific caloric conversion factors for differnet food products (they don't vary hugely between different products), but if this is not normally done in MAgPIE, we can just use generic factors too.

2024-07-15 14:27 UTC, weindl commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*'
Thanks @flohump Your suggestion looks good. The only thing I noticed: as long as the meaning of the scalars does not chnage, we still need 's15_scp_fat_to_kcal_milk' and 's15_scp_sugar_to_kcal_milk' to convert mass to kcal, as required by e.g. 'p15_kcal_pc_calibrated(t,i,"oils")'.

2024-07-15 14:58 UTC, jansteinhauser commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*'
@flohump In general, your approach makes sense to me, but the sugar and fat equations need an additional factor at the end translating g sugar / fat to kcal.  Right now, equation units would be 
`kcal = kcal + g protein / (g protein / 100 g milk) * g fat / 100 g milk = kcal + g fat (or g sugar, respectively)`


`p15_kcal_pc_calibrated(t,i,"oils") = p15_kcal_pc_calibrated(t,i,"oils") + sum(kfo_rd$sameas(kfo_rd,"livst_milk"), p15_protein_pc_calibrated_scp(t,i,kfo_rd)) / s15_scp_protein_per_milk * s15_scp_fat_per_milk * fm_nutrition_attributes(t,"oils", "kcal");`

`p15_kcal_pc_calibrated(t,i,"sugar") = p15_kcal_pc_calibrated(t,i,"sugar") + sum(kfo_rd$sameas(kfo_rd,"livst_milk"), p15_protein_pc_calibrated_scp(t,i,kfo_rd)) / s15_scp_protein_per_milk * s15_scp_sugar_per_milk * fm_nutrition_attributes(t, "sugar" ,"kcal");`

Few fine-tuning question: Are these sugar and fat amounts / 100g the one that are consumed at the end or the amount that goes into the SCP production process, with different amounts actually consumed? 

And is it important for reporting of food profiles that we're splitting a single category (milk) into three distinct ones (SCP, sugar, oils) instead of summing these values to a single SCP kcal value?

2024-07-15 15:00 UTC, jansteinhauser commented on modules/15_food/anthropometrics_jan18/presolve.gms
> +*'
Same changes necessary as in the other module.

2024-07-15 15:05 UTC, jansteinhauser requested changes
See comment in exodietmacro.gms. Process makes sense to me, but the suggested equations seem to need unit checking.

2024-07-16 13:47 UTC, weindl approved these changes
Thank you for this version. Looks good!

2024-07-16 13:47 UTC, weindl commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +*'
Looks good now

2024-07-16 14:12 UTC, jansteinhauser approved these changes
Looks great, just one tiny description suggestion.

2024-07-19 07:07 UTC, jansteinhauser requested changes
Please double check units

2024-07-19 07:07 UTC, jansteinhauser commented on modules/15_food/anthro_iso_jun22/exodietmacro.gms
> +     s15_scp_fat_protein_ratio_meat - s15_scp_fat_per_meat) * fm_nutrition_attributes(t,"oils", "kcal");
Should be `s15_scp_fat_per_meat / 100` since it's `g / 100 g` while everything else is `X / g`

2024-07-19 07:07 UTC, jansteinhauser commented on modules/15_food/anthro_iso_jun22/input.gms
> +s15_scp_supplement_fat_meat         Switch for supplemental fat needed as ingredient for scp-based meat alternatives (1) / 0 /
Since this is  a switch, shouldn't this be c15 instead of s15?

2024-07-19 07:07 UTC, jansteinhauser commented on modules/15_food/anthropometrics_jan18/input.gms
> +s15_scp_supplement_fat_meat                Switch for supplemental fat needed as ingredient for scp-based meat alternatives (1) / 0 /
as above:  this is a switch, shouldn't this be c15 instead of s15?

2024-07-19 07:07 UTC, jansteinhauser commented on modules/15_food/anthropometrics_jan18/intersolve.gms
> +     s15_scp_fat_protein_ratio_meat - s15_scp_fat_per_meat) * fm_nutrition_attributes(t,"oils", "kcal");
As above: Should be s15_scp_fat_per_meat / 100 since it's g / 100 g while everything else is X / g

2024-07-19 07:07 UTC, jansteinhauser commented on modules/15_food/anthropometrics_jan18/presolve.gms
> +     s15_scp_fat_protein_ratio_meat - s15_scp_fat_per_meat) * fm_nutrition_attributes(t,"oils", "kcal");
As above: Should be s15_scp_fat_per_meat / 100 since it's g / 100 g while everything else is X / g

2024-07-19 08:29 UTC, flohump commented on config/default.cfg
> +cfg$gms$s15_scp_supplement_fat_meat <- 0    # def = 0
No this is fine because it is a scalar. We use `c15` for character-based switches.

2024-07-19 08:30 UTC, flohump commented on modules/15_food/anthro_iso_jun22/input.gms
> +s15_scp_supplement_fat_meat         Switch for supplemental fat needed as ingredient for scp-based meat alternatives (1) / 0 /
same as above

2024-07-19 08:30 UTC, flohump commented on modules/15_food/anthropometrics_jan18/input.gms
> +s15_scp_supplement_fat_meat                Switch for supplemental fat needed as ingredient for scp-based meat alternatives (1) / 0 /
same as above

2024-07-19 08:30 UTC, flohump commented on modules/15_food/anthropometrics_jan18/intersolve.gms
> +     s15_scp_fat_protein_ratio_meat - s15_scp_fat_per_meat) * fm_nutrition_attributes(t,"oils", "kcal");
same as above

2024-07-19 08:30 UTC, flohump commented on modules/15_food/anthropometrics_jan18/presolve.gms
> +     s15_scp_fat_protein_ratio_meat - s15_scp_fat_per_meat) * fm_nutrition_attributes(t,"oils", "kcal");
same as above

2024-07-19 08:36 UTC, jansteinhauser approved these changes

2024-07-22 09:52 UTC, weindl requested changes
The addition to the code looks good in general. I have only one comment to the naming of a new scalar.

2024-07-22 09:52 UTC, weindl commented on modules/15_food/anthro_iso_jun22/declarations.gms
> + s15_scp_fat_per_meat               Fat content of microbial biomass based on Solein from Solar foods (t fat per t DM) / 0.05 /
I suggest to rename the scalar 's15_scp_fat_per_meat' to better reflect its meaning ( ="fat content of microbial biomass). 
For me 's15_scp_fat_per_meat' sounds like a scalar indicating how much fat is needed to produce a unit of final scp-meat product in wet matter, which is not the case.

Maybe 's15_scp_fat_content' or similar?

2024-07-22 10:04 UTC, weindl commented on modules/15_food/anthro_iso_jun22/declarations.gms
> + s15_scp_fat_per_meat               Fat content of microbial biomass based on Solein from Solar foods (t fat per t DM) / 0.05 /
The renaming would also require changes in the magpie4.

2024-07-22 10:32 UTC, flohump commented on modules/15_food/anthro_iso_jun22/declarations.gms
> + s15_scp_fat_per_meat               Fat content of microbial biomass based on Solein from Solar foods (t fat per t DM) / 0.05 /
Thanks for the suggestion. I revised the scalar name in the GAMS code and the `magpie4` R library.

2024-07-22 11:45 UTC, weindl approved these changes

2024-07-23 08:00 UTC, merged