Update GDP to 2017 base year
magpiemodel/magpie pull request #717
Opened 2024-09-10 11:11 UTC by caviddhen

## :bird: Description of this PR :bird:

- Update documentation, scalar values, and module code (deflating food demand and livestock regression inputs) to be consistent with 2017 GDP base year.
 
## :wrench: Checklist for PR creator :wrench:

- [ ] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [ ] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [ ] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

![Resources_Land_Cover_Cropland (54)](https://github.com/user-attachments/assets/984115ab-c5cb-4643-b184-9b630d2c8830)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : 0.250 hours
  - This PR's default :  0.255 hours

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2024-09-25 13:27 UTC, tscheypidi approved these changes
just three smaller comments

2024-09-25 13:27 UTC, tscheypidi commented on modules/32_forestry/dynamic_may24/input.gms
> +  s32_est_cost_plant              Establishment cost for plantations (USD per ha) / 2460 /
should it be here and in the following lines also USD17MER?

2024-09-25 13:27 UTC, tscheypidi commented on modules/73_timber/default/input.gms
> +  s73_free_prod_cost                   Very high cost for settling demand without production (USD per tDM) / 24600 /
also USD17MER?

2024-09-25 15:08 UTC, pascal-sauer commented
There are still quite a few places left where we have just USD and not USD17, you can find those on the cluster with `rg '\bUSD\b'`

2024-09-25 15:10 UTC, pascal-sauer commented
Thanks for going through the whole magpie codebase to adapt it!

2024-09-26 12:05 UTC, flohump commented on modules/41_area_equipped_for_irrigation/endo_apr13/declarations.gms
> + pc41_unitcost_AEI(i)            Unit cost of AEI expansion (USD17MER per ha)
It was USD04MER before. @caviddhen took care of this in mrland. Direct conversion of USD1995MER to US17MER in calcIrrigationInvCosts

2024-09-26 14:04 UTC, deleip reviewed
some more things I noticed while going through the files, but couldn't directly comment on as they had no changes:

- ~in the food demand model we still have regression factors in USD05PPP, maybe adding a note about that inconsistency would be good? (same for the livestock regression that is in USD04)~

- ~in the declaration files of the urban module quite a lot of units are missing. as we changing so much anyway it might be a good moment to add those now?~ (I'll ask David to fix this once he's back)

- ~in pot_forest_may24/declarations line 85 the unit is just USD. Probably also MER?~

- ~the declaration file of the employment module has not been updated (lots of USDMER05 still there)~

- in the maccs module, values are in USD95MER, is this on purpose?

2024-09-26 16:46 UTC, flohump commented on config/default.cfg
>  cfg$gms$s31_fac_req_past  <- 1             # def = 1
Not converted because of technical cost term

2024-09-26 16:47 UTC, flohump commented on config/default.cfg
> -s73_free_prod_cost <- 1000000           # def = 1000000
good catch. I reverted it.

2024-09-26 16:49 UTC, flohump commented on modules/13_tc/exo/declarations.gms
> + i13_tc_factor(t)            Regression factor (USD17MER per ha)
I added a comment about the conversion in the f13_tc_factor file.

2024-09-27 08:05 UTC, deleip commented on config/projects/scenario_config_fsec.csv
>  input['additional'];additional_data_rev4.51.tgz;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
```suggestion
input['additional'];additional_data_rev4.56.tgz;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
```

2024-09-27 08:12 UTC, flohump commented
> some more things I noticed while going through the files, but couldn't directly comment on as they had no changes:
> 
> * ~in the food demand model we still have regression factors in USD05PPP, maybe adding a note about that inconsistency would be good? (same for the livestock regression that is in USD04)~
> * ~in the declaration files of the urban module quite a lot of units are missing. as we changing so much anyway it might be a good moment to add those now?~ (I'll ask David to fix this once he's back)
> * ~in pot_forest_may24/declarations line 85 the unit is just USD. Probably also MER?~
> * ~the declaration file of the employment module has not been updated (lots of USDMER05 still there)~
> * in the maccs module, values are in USD95MER, is this on purpose? <- DONE. It's now USD17MER

2024-09-27 09:37 UTC, deleip approved these changes

2024-09-28 08:08 UTC, bodirsky requested changes
food demand module seems fine.
In residues module, the link to the datasource is broken, I suggested a new one.
Cost calculations seem a bit off.
More generally, its unclear how the switch from 05 to 17 was done for values in additional data or hardcoded values. In my opinion, they should be inflated.

2024-09-28 08:08 UTC, bodirsky commented on modules/18_residues/flexcluster_jul23/equations.gms
>  *' for developing prices see [here](citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.557.5823&rep=rep1&type=pdf).
The links are dead.
I would switch to 

Budynski, Stephanie. 2020. “Straw Manufacturing in Alberta.”
https://open.alberta.ca/dataset/690317b0-1d07-4f9e-ae71-6340e16f6493/resource/89789096-1c7a-47ab-beb2-94d55606c922/download/af-straw-manufacturing-in-alberta-2020-01.pdf

the correct conversion of lb to ton is *2,205
the resulting costs are therfore 27.5 for baling, hauling and stacking, and range up to 50 for large bales. Small bales are substantially more expensive, which is a good argument that the US costs are not too high for other countries

2024-09-28 08:08 UTC, bodirsky commented on modules/18_residues/flexcluster_jul23/input.gms
> -parameter f18_fac_req_kres(kres) Factor requirements (USD05MER per tDM)
please check these values based on my comment above.

2024-09-28 08:08 UTC, bodirsky commented on modules/18_residues/flexreg_apr16/equations.gms
> -*' 1 large round bale is approximately 500 kg, resulting in 24USD per ton,
see comment above

2024-10-02 08:16 UTC, flohump commented on modules/18_residues/flexreg_apr16/equations.gms
> -*' 1 large round bale is approximately 500 kg, resulting in 24USD per ton,
revised

2024-10-02 08:16 UTC, flohump commented on modules/18_residues/flexcluster_jul23/input.gms
> -parameter f18_fac_req_kres(kres) Factor requirements (USD05MER per tDM)
revised

2024-10-02 08:17 UTC, flohump commented on modules/18_residues/flexcluster_jul23/equations.gms
>  *' for developing prices see [here](citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.557.5823&rep=rep1&type=pdf).
revised

2024-10-03 08:06 UTC, merged