Start script 'healthy landscapes paper' and output script for automatic submission of SEALS runs
magpiemodel/magpie pull request #721
Opened 2024-09-18 14:10 UTC by pvjeetze

## :bird: Description of this PR :bird:

- Added start script for 'healthy landscapes paper'
- Added script for automatic submission of SEALS allocation runs
- `.nc` files are no longer exported by default after disaggregation of MAgPIE outputs
- updated `magpie4` dependency to `2.12.0` to [adjust lowpass filter based on sm_fix_SSP2 in emisCO2](https://github.com/pik-piam/magpie4/commit/2bfb4ccb4ebfb371e1944fccc20b67417d663b37)
- This PR should go into the next release 4.8.2 @pascal-sauer 

## :wrench: Checklist for PR creator :wrench:

- [ ] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [ ] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [ ] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2024-09-18 14:39 UTC, flohump approved these changes
Looks good. Thanks for these improvements.

2024-09-18 18:49 UTC, weindl approved these changes
Looks good, thank you!

2024-09-18 18:49 UTC, weindl commented on config/default.cfg
> +cfg$gms$land_snv <- "secdforest, other"    #def = "secdforest, other"
Maybe add to the changelog that the default setting for the SVN policy has changed.

2024-09-19 08:50 UTC, pvjeetze commented on config/default.cfg
> +cfg$gms$land_snv <- "secdforest, other"    #def = "secdforest, other"
I updated the changelog. Thanks for spotting this

2024-09-19 09:30 UTC, pascal-sauer requested changes
Looks good to me, just need to deal with the paths to your personal folders

2024-09-19 09:38 UTC, pvjeetze commented on config/projects/scenario_config_year_fix.csv
> +﻿;fix_2020;fix_2025
This simply conforms to the structure a the scenario configs with the settings in columns and the switches in rows.

2024-09-19 09:45 UTC, pvjeetze commented on scripts/output/extra/runSEALSallocation.R
> +miniforgePath <- "/home/vjeetze/miniforge3/bin/activate"
This goes back to the whole discussion whether miniforge should be available to all (e.g. via the piam module or else). At the moment I could only install it into my home directory. This may be fine for the time being and if any users want to use the script they can install it in their home directory and change the path. 

I don't expect this script to be used by anyone besides me at the moment. I want this to be part of the release in the current form mainly for reasons of documentation for a paper. However, the script is also fully functional, if the user settings are modified based on user specific installations of miniforge and SEALS.

2024-09-19 09:47 UTC, pvjeetze commented on scripts/output/extra/runSEALSallocation.R
> +dirSEALS <- "/p/projects/magpie/users/vjeetze/seals/files/seals/seals_dev"
Again, only think of these paths as simple placeholders, that should be adapted by different users (thus "User settings")

2024-09-19 12:24 UTC, pvjeetze commented on scripts/output/extra/runSEALSallocation.R
> +miniforgePath <- "/home/vjeetze/miniforge3/bin/activate"
I've adapted the script based on our bilateral discussion. Please have a look whether you are fine with these changes.

2024-09-19 12:49 UTC, pascal-sauer approved these changes

2024-09-19 12:49 UTC, pascal-sauer commented on scripts/output/extra/runSEALSallocation.R
> +dirProject <- "./output/seals"
```suggestion
dirProject <- "./output/seals"
message("seals outputs are written to output/seals/...TODO")
```

2024-09-20 10:12 UTC, pascal-sauer approved these changes

2024-09-20 10:14 UTC, merged