follow-up fix for PR744
magpiemodel/magpie pull request #745
Opened 2024-11-12 08:13 UTC by flohump

## :bird: Description of this PR :bird:

this PR resolves the following issue: land area is not constant over time

## :wrench: Checklist for PR creator :wrench:

- [ ] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [ ] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [ ] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [ ] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [ ] content review done (at least 1)
- [ ] RSE review done (at least 1)

2024-11-12 10:01 UTC, k4rst3ns commented on modules/10_land/landmatrix_dec18/equations.gms
> +  pcm_land(j2,land_from);
why not `vm_land.l`? I thought this was one of the points of PR before to have here same accuracy.

2024-11-13 10:00 UTC, flohump commented on modules/10_land/landmatrix_dec18/equations.gms
> +  pcm_land(j2,land_from);
It turned out that vm_land.l and pcm_land differ considerably. 
It seems that vm_land.l is not updated in all realizations.

2024-11-13 12:47 UTC, pascal-sauer commented on config/default.cfg
> +               cellular    = "rev4.116_h12_fd712c0b_cellularmagpie_c200_MRI-ESM2-0-ssp370_lpjml-8e6c5eb1.tgz",
We change from ssp119 to ssp370, just double checking this is intended?

2024-11-13 12:51 UTC, pascal-sauer commented on modules/44_biodiversity/bii_target/sets.gms
> +alias(biome44,biome44_2);
Why is this alias needed?

2024-11-13 13:07 UTC, flohump commented on modules/44_biodiversity/bii_target/sets.gms
> +alias(biome44,biome44_2);
This is needed for the calculation of `i44_biome_share(j,biome44)`
```
i44_biome_share(j,biome44) = 
   (f44_biome_area(j,biome44) + 1e-10) / sum(biome44_2, f44_biome_area(j,biome44_2) + 1e-10);
```

2024-11-13 13:17 UTC, deleip commented on config/default.cfg
> +               cellular    = "rev4.116_h12_fd712c0b_cellularmagpie_c200_MRI-ESM2-0-ssp370_lpjml-8e6c5eb1.tgz",
oops, yes, this was a mistake on my side then, sorry!

2024-11-13 16:42 UTC, pascal-sauer commented on modules/44_biodiversity/bii_target/sets.gms
> +alias(biome44,biome44_2);
Out of curiosity, why does it not work to just use biome44 instead of biome44_2 everywhere?

2024-11-13 17:20 UTC, pascal-sauer commented on modules/44_biodiversity/bii_target/sets.gms
> +alias(biome44,biome44_2);
Ah, under control means it appears on the left hand size of the equation (or is it an assignment?)?

2024-11-14 07:45 UTC, flohump commented on modules/44_biodiversity/bii_target/sets.gms
> +alias(biome44,biome44_2);
Under control in GAMS means that all calculations are done for each set element.

2024-11-14 08:28 UTC, pvjeetze requested changes
Thanks a lot for these extensive and fast updates! 

I requested some minor changes.

In addition we should have again a discussion and a decision in the MAgPIE meeting on how to deal with project-specific scenario configs.

2024-11-14 08:28 UTC, pvjeetze commented on modules/44_biodiversity/bii_target/equations.gms
> +          sum((cell(i2,j2),potnatveg,landcover44), vm_bv(j2,landcover44,potnatveg) * f44_biome(j2,biome44))
Here's a bug

```suggestion
          sum((cell(i2,j2),potnatveg,landcover44), vm_bv(j2,landcover44,potnatveg) * i44_biome_share(j2,biome44))
```

2024-11-14 08:28 UTC, pvjeetze commented on modules/44_biodiversity/bii_target/preloop.gms
> +* Update i44_biome_area_reg
```suggestion
* Set i44_biome_area_reg
```

2024-11-14 08:28 UTC, pvjeetze commented on modules/44_biodiversity/bii_target/presolve.gms
> +* Update i44_biome_area_reg
The biome area is constant, so setting it once in the preloop should be fine, right?
(unless there's a but that total land area is not constant over time)

2024-11-14 08:28 UTC, pvjeetze commented on modules/44_biodiversity/bii_target_apr24/preloop.gms
> +* Update i44_biome_area_reg
```suggestion
* Set i44_biome_area_reg
```

2024-11-14 08:28 UTC, pvjeetze commented on modules/44_biodiversity/bii_target_apr24/presolve.gms
> +* Update i44_biome_area_reg
See comment above

2024-11-14 08:33 UTC, flohump commented on config/projects/scenario_config_el2.csv
> +input['cellular'];rev4.116EL2_h12_c6a7458f_cellularmagpie_c200_IPSL-CM6A-LR-ssp370_lpjml-8e6c5eb1.tgz;;
Thanks for bringing this up. Let's discuss about this in the MAgPIE meeting.

2024-11-14 08:34 UTC, flohump commented on config/projects/scenario_config_fsec.csv
Since we use FSEC in our default test runs, it should be updated from my view.

2024-11-14 08:35 UTC, flohump commented on modules/44_biodiversity/bii_target/equations.gms
> +          sum((cell(i2,j2),potnatveg,landcover44), vm_bv(j2,landcover44,potnatveg) * f44_biome(j2,biome44))
Thanks for spotting!

2024-11-14 08:39 UTC, flohump commented on modules/44_biodiversity/bii_target/presolve.gms
> +* Update i44_biome_area_reg
Fair point. I will remove this from both realisations.

2024-11-14 08:52 UTC, pvjeetze approved these changes
Thanks for the updates. Looks good for me now.

I only have a minor addtional comment regarding the placement of code in the preloop.

2024-11-14 08:52 UTC, pvjeetze commented on modules/44_biodiversity/bii_target/preloop.gms
> +* Update v44_bii.l based on vm_bv.l
On a second thought, are lines 16-28 actually needed here in the preloop, if we also have it in the presolve?

2024-11-14 08:52 UTC, pvjeetze commented on modules/44_biodiversity/bii_target_apr24/preloop.gms
> +* Update v44_bii.l based on vm_bv.l
See comment above.

2024-11-14 08:56 UTC, flohump commented on modules/44_biodiversity/bii_target/preloop.gms
> +* Update v44_bii.l based on vm_bv.l
Yes, of course it can be removed from preloop. Thanks.
I first added it only in preloop. But then understood we need it in in particular in presolve for updates between time steps.

2024-11-14 08:57 UTC, flohump commented on modules/44_biodiversity/bii_target_apr24/preloop.gms
> +* Update v44_bii.l based on vm_bv.l
removed

2024-11-15 08:18 UTC, merged